import type { DeckDef } from '../types'

// Quran Vocabulary, level 9. See GitHub issue #8.
//
// Scaffolded by scripts/generateVocab.ts: the headword, root, occurrence count,
// ayah and citation come from the corpus and the canonical text. The meanings,
// principal parts and ayah translations were authored on top of that scaffold.
//
// Where the corpus lemmatizes a word to a passive, an imperative or a mudari
// that nobody looks up, the note id is the dictionary form while the headword
// stays as the corpus has it, since that is what the ayah shows.
//
// DRAFT: verify every English meaning before memorizing it. Turkish is
// convenience text and stays draft - correct it on sight while studying.
//
// Locked until the previous level is mostly graduated; see quranVocabTrack.ts.

export const quranVocab9: DeckDef = {
  id: 'quran-vocab-9',
  name: { english: 'Quran Vocabulary 9', turkish: 'Kur’an Kelimeleri 9' },
  nameArabic: 'مُفْرَدَاتُ الْقُرْآنِ ٩',
  description: {
    english:
      'Frequency band 9 of the Quran vocabulary track, each word with an ayah where it occurs.',
    turkish:
      'Kur’an kelime yolunun 9. sıklık kuşağı; her kelime geçtiği bir ayetle.',
  },
  directions: ['ar-to-meaning'],
  newPerDay: 10,
  burySiblings: true,
  notes: [
    {
      id: 'baiyd',
      arabic: 'بَعِيد',
      english: 'far, distant',
      turkish: 'uzak',
      example: {
        arabic: 'إِنَّهُمْ يَرَوْنَهُۥ بَعِيدًۭا',
        english: 'Indeed, they see it as far off,',
        turkish: 'Şüphesiz onlar onu uzak görüyorlar,',
        source: 'Qur\'an 70:6',
        highlight: { english: 'far off', turkish: 'uzak' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بعد',
        forms: [
          { label: 'plural', arabic: 'بُعَدَاء' },
        ],
        occurrences: 25,
        occurringForm: 'بَعِيدًا',
      },
    },
    {
      id: 'baghaa',
      arabic: 'بَغَى',
      english: 'to seek, to desire',
      turkish: 'aramak, istemek',
      example: {
        arabic: 'قَالَ ذَٰلِكَ مَا كُنَّا نَبْغِ ۚ فَٱرْتَدَّا عَلَىٰٓ ءَاثَارِهِمَا قَصَصًۭا',
        english: 'He said: That is what we were seeking. So they returned, retracing their footsteps.',
        turkish: 'Dedi ki: İşte aradığımız buydu. Böylece izlerini takip ederek geri döndüler.',
        source: 'Qur\'an 18:64',
        highlight: { english: 'seeking', turkish: 'aradığımız' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بغي',
        forms: [
          { label: 'mudari', arabic: 'يَبْغِي' },
        ],
        occurrences: 25,
        occurringForm: 'نَبْغِ',
      },
    },
    {
      id: 'jadala',
      arabic: 'جادَلُ',
      english: 'to dispute, to argue',
      turkish: 'mücadele etmek, tartışmak',
      example: {
        arabic: 'وَمِنَ ٱلنَّاسِ مَن يُجَٰدِلُ فِى ٱللَّهِ بِغَيْرِ عِلْمٍۢ وَيَتَّبِعُ كُلَّ شَيْطَٰنٍۢ مَّرِيدٍۢ',
        english: 'And among the people is he who disputes about Allah without knowledge and follows every rebellious devil.',
        turkish: 'İnsanlardan kimi, bilgisizce Allah hakkında tartışır ve her azgın şeytanın ardına düşer.',
        source: 'Qur\'an 22:3',
        highlight: { english: 'disputes', turkish: 'tartışır' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'جدل',
        forms: [
          { label: 'mudari', arabic: 'يُجَادِلُ' },
          { label: 'masdar', arabic: 'مُجَادَلَة' },
        ],
        occurrences: 25,
        occurringForm: 'يُجَٰدِلُ',
      },
    },
    {
      id: 'junah',
      arabic: 'جُناح',
      english: 'blame, fault, sin',
      turkish: 'günah, vebal, sakınca',
      example: {
        arabic: 'لَّيْسَ عَلَيْكُمْ جُنَاحٌ أَن تَدْخُلُوا۟ بُيُوتًا غَيْرَ مَسْكُونَةٍۢ فِيهَا مَتَٰعٌۭ لَّكُمْ ۚ وَٱللَّهُ يَعْلَمُ مَا تُبْدُونَ وَمَا تَكْتُمُونَ',
        english: 'There is no blame upon you for entering uninhabited houses in which there is some benefit for you. And Allah knows what you reveal and what you conceal.',
        turkish: 'İçinde sizin için bir yarar bulunan, oturulmayan evlere girmenizde size bir günah yoktur. Allah açığa vurduğunuzu da gizlediğinizi de bilir.',
        source: 'Qur\'an 24:29',
        highlight: { english: 'blame', turkish: 'günah' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'جنح',
        occurrences: 25,
        occurringForm: 'جُنَاحٌ',
      },
    },
    {
      id: 'khala',
      arabic: 'خَلا',
      english: 'to pass, to be gone by; to be empty',
      turkish: 'geçip gitmek; boş olmak',
      example: {
        arabic: 'لَا يُؤْمِنُونَ بِهِۦ ۖ وَقَدْ خَلَتْ سُنَّةُ ٱلْأَوَّلِينَ',
        english: 'They do not believe in it, though the way of the former peoples has already passed.',
        turkish: 'Ona inanmazlar; oysa öncekilerin sünneti geçip gitmiştir.',
        source: 'Qur\'an 15:13',
        highlight: { english: 'has already passed', turkish: 'geçip gitmiştir' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'خلو',
        forms: [
          { label: 'mudari', arabic: 'يَخْلُو' },
        ],
        occurrences: 25,
        occurringForm: 'خَلَتْ',
      },
    },
    {
      id: 'iysaa',
      arabic: 'عِيسَى',
      english: 'Jesus',
      turkish: 'İsa',
      example: {
        arabic: 'ذَٰلِكَ عِيسَى ٱبْنُ مَرْيَمَ ۚ قَوْلَ ٱلْحَقِّ ٱلَّذِى فِيهِ يَمْتَرُونَ',
        english: 'That is Jesus, the son of Mary — the word of truth about which they are in doubt.',
        turkish: 'İşte, hakkında şüpheye düştükleri Meryem oğlu İsa; bu, gerçek sözdür.',
        source: 'Qur\'an 19:34',
        highlight: { english: 'Jesus', turkish: 'İsa' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 25,
        occurringForm: 'عِيسَى',
      },
    },
    {
      id: 'qadara',
      arabic: 'قَدَرَ',
      english: 'to have power over, to be able; to decree, to measure out',
      turkish: 'güç yetirmek; takdir etmek, ölçmek',
      example: {
        arabic: 'أَيَحْسَبُ أَن لَّن يَقْدِرَ عَلَيْهِ أَحَدٌۭ',
        english: 'Does he think that no one has power over him?',
        turkish: 'Kendisine hiç kimsenin güç yetiremeyeceğini mi sanıyor?',
        source: 'Qur\'an 90:5',
        highlight: { english: 'has power', turkish: 'güç yetiremeyeceğini' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'قدر',
        forms: [
          { label: 'mudari', arabic: 'يَقْدِرُ' },
          { label: 'masdar', arabic: 'قُدْرَة' },
        ],
        occurrences: 25,
        occurringForm: 'يَقْدِرَ',
      },
    },
    {
      id: 'lisan',
      arabic: 'لِسان',
      english: 'tongue, language',
      turkish: 'dil',
      example: {
        arabic: 'وَٱجْعَل لِّى لِسَانَ صِدْقٍۢ فِى ٱلْءَاخِرِينَ',
        english: 'And grant me a tongue of truth among later generations,',
        turkish: 'Ve sonra geleceklerin içinde bana doğruluk dili nasip et,',
        source: 'Qur\'an 26:84',
        highlight: { english: 'tongue', turkish: 'dili' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'لسن',
        forms: [
          { label: 'plural', arabic: 'أَلْسِنَة' },
        ],
        occurrences: 25,
        occurringForm: 'لِسَانَ',
      },
    },
    {
      id: 'miythaq',
      arabic: 'مِيثاق',
      english: 'covenant, solemn pledge',
      turkish: 'misak, sağlam söz, ahit',
      example: {
        arabic: 'وَكَيْفَ تَأْخُذُونَهُۥ وَقَدْ أَفْضَىٰ بَعْضُكُمْ إِلَىٰ بَعْضٍۢ وَأَخَذْنَ مِنكُم مِّيثَٰقًا غَلِيظًۭا',
        english: 'And how could you take it back when you have gone in unto one another and they have taken from you a solemn covenant?',
        turkish: 'Birbirinizle kaynaşmış ve onlar sizden sağlam bir söz almışken onu nasıl geri alırsınız?',
        source: 'Qur\'an 4:21',
        highlight: { english: 'solemn covenant', turkish: 'sağlam bir söz' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'وثق',
        forms: [
          { label: 'plural', arabic: 'مَوَاثِيق' },
        ],
        occurrences: 25,
        occurringForm: 'مِّيثَٰقًا',
      },
    },
    {
      id: 'shaara',
      arabic: 'يَشْعُرُ',
      english: 'to perceive, to be aware',
      turkish: 'farkına varmak, sezmek',
      example: {
        arabic: 'فَيَأْتِيَهُم بَغْتَةًۭ وَهُمْ لَا يَشْعُرُونَ',
        english: 'so that it comes to them suddenly, while they do not perceive.',
        turkish: 'Böylece o, onlar farkında değilken ansızın kendilerine gelir.',
        source: 'Qur\'an 26:202',
        highlight: { english: 'perceive', turkish: 'farkında değilken' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'شعر',
        forms: [
          { label: 'mudari', arabic: 'يَشْعُرُ' },
          { label: 'masdar', arabic: 'شُعُور' },
        ],
        occurrences: 25,
        occurringForm: 'يَشْعُرُونَ',
      },
    },
    {
      id: 'akbar',
      arabic: 'أَكْبَر',
      english: 'greater, greatest',
      turkish: 'daha büyük, en büyük',
      example: {
        arabic: 'كَذَٰلِكَ ٱلْعَذَابُ ۖ وَلَعَذَابُ ٱلْءَاخِرَةِ أَكْبَرُ ۚ لَوْ كَانُوا۟ يَعْلَمُونَ',
        english: 'Such is the punishment, and the punishment of the Hereafter is greater, if only they knew.',
        turkish: 'Azap işte böyledir; ahiret azabı ise daha büyüktür. Keşke bilselerdi.',
        source: 'Qur\'an 68:33',
        highlight: { english: 'greater', turkish: 'daha büyüktür' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كبر',
        occurrences: 24,
        occurringForm: 'أَكْبَرُ',
      },
    },
    {
      id: 'unthaa',
      arabic: 'أُنثَى',
      english: 'female',
      turkish: 'dişi, kadın',
      example: {
        arabic: 'أَمْ خَلَقْنَا ٱلْمَلَٰٓئِكَةَ إِنَٰثًۭا وَهُمْ شَٰهِدُونَ',
        english: 'Or did We create the angels female while they were witnesses?',
        turkish: 'Yoksa biz melekleri dişi olarak yarattık da onlar buna şahit mi oldular?',
        source: 'Qur\'an 37:150',
        highlight: { english: 'female', turkish: 'dişi' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أنث',
        forms: [
          { label: 'plural', arabic: 'إِنَاث' },
        ],
        occurrences: 24,
        occurringForm: 'إِنَٰثًا',
      },
    },
    {
      id: 'iyya',
      arabic: 'إِيّا',
      english: 'you, him, them (base of a fronted object pronoun)',
      turkish: 'seni, onu (öne alınan nesne zamiri tabanı)',
      example: {
        arabic: 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
        english: 'You alone we worship, and You alone we ask for help.',
        turkish: 'Yalnız sana kulluk eder, yalnız senden yardım dileriz.',
        source: 'Qur\'an 1:5',
        highlight: { english: 'You alone we worship', turkish: 'sana' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 24,
        occurringForm: 'إِيَّاكَ',
      },
    },
    {
      id: 'tawaffaa',
      arabic: 'تَوَفَّى',
      english: 'to take in full; to take the soul, to cause to die',
      turkish: 'tastamam almak; canını almak, vefat ettirmek',
      example: {
        arabic: 'فَكَيْفَ إِذَا تَوَفَّتْهُمُ ٱلْمَلَٰٓئِكَةُ يَضْرِبُونَ وُجُوهَهُمْ وَأَدْبَٰرَهُمْ',
        english: 'Then how will it be when the angels take them in death, striking their faces and their backs?',
        turkish: 'Melekler yüzlerine ve sırtlarına vurarak canlarını alırken halleri nice olacak?',
        source: 'Qur\'an 47:27',
        highlight: { english: 'take them in death', turkish: 'canlarını alırken' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'وفي',
        forms: [
          { label: 'mudari', arabic: 'يَتَوَفَّى' },
        ],
        occurrences: 24,
        occurringForm: 'تَوَفَّتْهُمُ',
      },
    },
    {
      id: 'hayy',
      arabic: 'حَيّ',
      english: 'living, alive',
      turkish: 'diri, canlı',
      example: {
        arabic: 'أَحْيَآءًۭ وَأَمْوَٰتًۭا',
        english: 'for the living and the dead,',
        turkish: 'dirilere de ölülere de,',
        source: 'Qur\'an 77:26',
        highlight: { english: 'the living', turkish: 'dirilere' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حيي',
        forms: [
          { label: 'plural', arabic: 'أَحْيَاء' },
        ],
        occurrences: 24,
        occurringForm: 'أَحْيَآءً',
      },
    },
    {
      id: 'taifa',
      arabic: 'طائِفَة',
      english: 'group, party, band',
      turkish: 'taife, grup, bölük',
      example: {
        arabic: 'إِذْ هَمَّت طَّآئِفَتَانِ مِنكُمْ أَن تَفْشَلَا وَٱللَّهُ وَلِيُّهُمَا ۗ وَعَلَى ٱللَّهِ فَلْيَتَوَكَّلِ ٱلْمُؤْمِنُونَ',
        english: 'When two parties among you were about to lose heart, though Allah was their protector. And upon Allah let the believers rely.',
        turkish: 'Hani sizden iki grup bozulmaya yüz tutmuştu; oysa Allah onların dostuydu. Müminler yalnız Allah\'a güvensinler.',
        source: 'Qur\'an 3:122',
        highlight: { english: 'two parties', turkish: 'iki grup' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'طوف',
        forms: [
          { label: 'plural', arabic: 'طَوَائِف' },
        ],
        occurrences: 24,
        occurringForm: 'طَّآئِفَتَانِ',
      },
    },
    {
      id: 'taam',
      arabic: 'طَعام',
      english: 'food',
      turkish: 'yemek, yiyecek',
      example: {
        arabic: 'طَعَامُ ٱلْأَثِيمِ',
        english: 'the food of the sinful.',
        turkish: 'Günahkârın yemeğidir.',
        source: 'Qur\'an 44:44',
        highlight: { english: 'food', turkish: 'yemeğidir' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'طعم',
        forms: [
          { label: 'plural', arabic: 'أَطْعِمَة' },
        ],
        occurrences: 24,
        occurringForm: 'طَعَامُ',
      },
    },
    {
      id: 'ghaniyy',
      arabic: 'غَنِيّ',
      english: 'rich, free of need, self-sufficient',
      turkish: 'zengin, hiçbir şeye muhtaç olmayan',
      example: {
        arabic: '۞ قَوْلٌۭ مَّعْرُوفٌۭ وَمَغْفِرَةٌ خَيْرٌۭ مِّن صَدَقَةٍۢ يَتْبَعُهَآ أَذًۭى ۗ وَٱللَّهُ غَنِىٌّ حَلِيمٌۭ',
        english: 'A kind word and forgiveness are better than a charity followed by injury. And Allah is Free of need, Forbearing.',
        turkish: 'Güzel bir söz ve bağışlama, ardından eziyet gelen bir sadakadan hayırlıdır. Allah hiçbir şeye muhtaç değildir, halimdir.',
        source: 'Qur\'an 2:263',
        highlight: { english: 'Free of need', turkish: 'muhtaç değildir' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'غني',
        forms: [
          { label: 'plural', arabic: 'أَغْنِيَاء' },
        ],
        occurrences: 24,
        occurringForm: 'غَنِىٌّ',
      },
    },
    {
      id: 'kada',
      arabic: 'كادَ',
      english: 'to be about to, to almost do',
      turkish: 'neredeyse yapmak, az kalsın etmek',
      example: {
        arabic: 'تَكَادُ ٱلسَّمَٰوَٰتُ يَتَفَطَّرْنَ مِنْهُ وَتَنشَقُّ ٱلْأَرْضُ وَتَخِرُّ ٱلْجِبَالُ هَدًّا',
        english: 'The heavens almost rupture from it, and the earth splits open, and the mountains collapse in ruin.',
        turkish: 'Bundan dolayı neredeyse gökler çatlayacak, yer yarılacak ve dağlar yıkılıp çökecek.',
        source: 'Qur\'an 19:90',
        highlight: { english: 'almost', turkish: 'neredeyse' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'كود',
        forms: [
          { label: 'mudari', arabic: 'يَكَادُ' },
        ],
        occurrences: 24,
        occurringForm: 'تَكَادُ',
      },
    },
    {
      id: 'liqa',
      arabic: 'لِقاء',
      english: 'meeting, encounter',
      turkish: 'kavuşma, karşılaşma',
      example: {
        arabic: 'مَن كَانَ يَرْجُوا۟ لِقَآءَ ٱللَّهِ فَإِنَّ أَجَلَ ٱللَّهِ لَءَاتٍۢ ۚ وَهُوَ ٱلسَّمِيعُ ٱلْعَلِيمُ',
        english: 'Whoever hopes for the meeting with Allah, then indeed the term set by Allah is coming. And He is the Hearing, the Knowing.',
        turkish: 'Kim Allah\'a kavuşmayı umuyorsa, şüphesiz Allah\'ın belirlediği vakit gelecektir. O işitendir, bilendir.',
        source: 'Qur\'an 29:5',
        highlight: { english: 'the meeting', turkish: 'kavuşmayı' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'لقي',
        occurrences: 24,
        occurringForm: 'لِقَآءَ',
      },
    },
    {
      id: 'wara',
      arabic: 'وَراء',
      english: 'behind, beyond',
      turkish: 'arka, arkasında, ötesinde',
      example: {
        arabic: 'وَأَمَّا مَنْ أُوتِىَ كِتَٰبَهُۥ وَرَآءَ ظَهْرِهِۦ',
        english: 'But as for the one who is given his record behind his back,',
        turkish: 'Kitabı arkasından verilen kimseye gelince,',
        source: 'Qur\'an 84:10',
        highlight: { english: 'behind', turkish: 'arkasından' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'وري',
        occurrences: 24,
        occurringForm: 'وَرَآءَ',
      },
    },
    {
      id: 'wakiyl',
      arabic: 'وَكِيل',
      english: 'trustee, guardian, disposer of affairs',
      turkish: 'vekil, işleri üstlenen koruyucu',
      example: {
        arabic: 'وَتَوَكَّلْ عَلَى ٱللَّهِ ۚ وَكَفَىٰ بِٱللَّهِ وَكِيلًۭا',
        english: 'And rely upon Allah; and Allah is sufficient as a trustee.',
        turkish: 'Allah\'a güven; vekil olarak Allah yeter.',
        source: 'Qur\'an 33:3',
        highlight: { english: 'trustee', turkish: 'vekil' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'وكل',
        forms: [
          { label: 'plural', arabic: 'وُكَلَاء' },
        ],
        occurrences: 24,
        occurringForm: 'وَكِيلًا',
      },
    },
    {
      id: 'adhina',
      arabic: 'أَذِنَ',
      english: 'to permit, to give leave',
      turkish: 'izin vermek',
      example: {
        arabic: 'وَلَا يُؤْذَنُ لَهُمْ فَيَعْتَذِرُونَ',
        english: 'Nor will they be permitted, so that they might offer excuses.',
        turkish: 'Onlara izin de verilmez ki özür dilesinler.',
        source: 'Qur\'an 77:36',
        highlight: { english: 'be permitted', turkish: 'izin de verilmez' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'أذن',
        forms: [
          { label: 'mudari', arabic: 'يَأْذَنُ' },
          { label: 'masdar', arabic: 'إِذْن' },
        ],
        occurrences: 23,
        occurringForm: 'يُؤْذَنُ',
      },
    },
    {
      id: 'anjaa',
      arabic: 'أَنجَى',
      english: 'to save, to rescue, to deliver',
      turkish: 'kurtarmak',
      example: {
        arabic: 'فَٱسْتَجَبْنَا لَهُۥ وَنَجَّيْنَٰهُ مِنَ ٱلْغَمِّ ۚ وَكَذَٰلِكَ نُۨجِى ٱلْمُؤْمِنِينَ',
        english: 'So We responded to him and saved him from the distress. And thus do We save the believers.',
        turkish: 'Onun duasını kabul ettik ve onu kederden kurtardık. İşte müminleri böyle kurtarırız.',
        source: 'Qur\'an 21:88',
        highlight: { english: 'saved', turkish: 'kurtardık' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نجو',
        forms: [
          { label: 'mudari', arabic: 'يُنْجِي' },
          { label: 'masdar', arabic: 'إِنْجَاء' },
        ],
        occurrences: 23,
        occurringForm: 'نُۨجِى',
      },
    },
    {
      id: 'imma',
      arabic: 'إِمّا',
      english: 'if (emphatic); either... or',
      turkish: 'eğer; ya... ya da',
      example: {
        arabic: 'قُل رَّبِّ إِمَّا تُرِيَنِّى مَا يُوعَدُونَ',
        english: 'Say: My Lord, if You should show me what they are promised,',
        turkish: 'De ki: Rabbim, onlara vaat edileni bana gösterecek olursan,',
        source: 'Qur\'an 23:93',
        highlight: { english: 'if', turkish: 'olursan' },
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 23,
        occurringForm: 'إِمَّا',
      },
    },
    {
      id: 'baddala',
      arabic: 'بَدَّلَ',
      english: 'to change, to alter, to substitute',
      turkish: 'değiştirmek, yerine başkasını koymak',
      example: {
        arabic: 'مَا يُبَدَّلُ ٱلْقَوْلُ لَدَىَّ وَمَآ أَنَا۠ بِظَلَّٰمٍۢ لِّلْعَبِيدِ',
        english: 'The word is not changed with Me, and I am not unjust to the servants.',
        turkish: 'Benim katımda söz değiştirilmez ve ben kullara asla zulmedici değilim.',
        source: 'Qur\'an 50:29',
        highlight: { english: 'is not changed', turkish: 'değiştirilmez' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بدل',
        forms: [
          { label: 'mudari', arabic: 'يُبَدِّلُ' },
          { label: 'masdar', arabic: 'تَبْدِيل' },
        ],
        occurrences: 23,
        occurringForm: 'يُبَدَّلُ',
      },
    },
    {
      id: 'dhikraa',
      arabic: 'ذِكْرَى',
      english: 'reminder, remembrance',
      turkish: 'hatırlatma, öğüt',
      example: {
        arabic: 'ذِكْرَىٰ وَمَا كُنَّا ظَٰلِمِينَ',
        english: 'as a reminder; and We were never unjust.',
        turkish: 'Bir öğüt olarak; ve biz zalimler değildik.',
        source: 'Qur\'an 26:209',
        highlight: { english: 'reminder', turkish: 'öğüt' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ذكر',
        occurrences: 23,
        occurringForm: 'ذِكْرَىٰ',
      },
    },
    {
      id: 'sajid',
      arabic: 'ساجِد',
      english: 'prostrating, one who prostrates',
      turkish: 'secde eden',
      example: {
        arabic: 'وَأُلْقِىَ ٱلسَّحَرَةُ سَٰجِدِينَ',
        english: 'And the magicians fell down prostrating.',
        turkish: 'Sihirbazlar secdeye kapandılar.',
        source: 'Qur\'an 7:120',
        highlight: { english: 'prostrating', turkish: 'secdeye kapandılar' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سجد',
        forms: [
          { label: 'plural', arabic: 'سَاجِدُون' },
        ],
        occurrences: 23,
        occurringForm: 'سَٰجِدِينَ',
      },
    },
    {
      id: 'sab',
      arabic: 'سَبْع',
      english: 'seven',
      turkish: 'yedi',
      example: {
        arabic: 'وَبَنَيْنَا فَوْقَكُمْ سَبْعًۭا شِدَادًۭا',
        english: 'And We built above you seven strong ones,',
        turkish: 'Ve üstünüzde yedi sağlam gök bina ettik,',
        source: 'Qur\'an 78:12',
        highlight: { english: 'seven', turkish: 'yedi' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سبع',
        occurrences: 23,
        occurringForm: 'سَبْعًا',
      },
    },
    {
      id: 'zuluma',
      arabic: 'ظُلُمَة',
      english: 'darkness',
      turkish: 'zulmet, karanlık',
      example: {
        arabic: 'وَلَا ٱلظُّلُمَٰتُ وَلَا ٱلنُّورُ',
        english: 'nor are the darknesses and the light,',
        turkish: 'ne karanlıklar ne de aydınlık,',
        source: 'Qur\'an 35:20',
        highlight: { english: 'darknesses', turkish: 'karanlıklar' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ظلم',
        forms: [
          { label: 'plural', arabic: 'ظُلُمَات' },
        ],
        occurrences: 23,
        occurringForm: 'ٱلظُّلُمَٰتُ',
      },
    },
    {
      id: 'fatana',
      arabic: 'فَتَنُ',
      english: 'to try, to put to trial; to tempt',
      turkish: 'imtihan etmek, denemek; fitneye düşürmek',
      example: {
        arabic: 'يَوْمَ هُمْ عَلَى ٱلنَّارِ يُفْتَنُونَ',
        english: 'The Day they will be tried over the Fire.',
        turkish: 'O gün onlar ateş üzerinde denenirler.',
        source: 'Qur\'an 51:13',
        highlight: { english: 'tried', turkish: 'denenirler' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'فتن',
        forms: [
          { label: 'mudari', arabic: 'يَفْتِنُ' },
          { label: 'masdar', arabic: 'فِتْنَة' },
        ],
        occurrences: 23,
        occurringForm: 'يُفْتَنُونَ',
      },
    },
    {
      id: 'fulk',
      arabic: 'فُلْك',
      english: 'ship, ark',
      turkish: 'gemi',
      example: {
        arabic: 'وَعَلَيْهَا وَعَلَى ٱلْفُلْكِ تُحْمَلُونَ',
        english: 'And upon them and upon ships you are carried.',
        turkish: 'Onların üzerinde ve gemilerde taşınırsınız.',
        source: 'Qur\'an 23:22',
        highlight: { english: 'ships', turkish: 'gemilerde' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'فلك',
        occurrences: 23,
        occurringForm: 'ٱلْفُلْكِ',
      },
    },
    {
      id: 'qarn',
      arabic: 'قَرْن',
      english: 'generation, age',
      turkish: 'nesil, çağ',
      example: {
        arabic: 'ثُمَّ أَنشَأْنَا مِنۢ بَعْدِهِمْ قَرْنًا ءَاخَرِينَ',
        english: 'Then We produced after them another generation.',
        turkish: 'Sonra onların ardından başka bir nesil var ettik.',
        source: 'Qur\'an 23:31',
        highlight: { english: 'generation', turkish: 'nesil' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قرن',
        forms: [
          { label: 'plural', arabic: 'قُرُون' },
        ],
        occurrences: 23,
        occurringForm: 'قَرْنًا',
      },
    },
    {
      id: 'laana',
      arabic: 'لَعَنَ',
      english: 'to curse',
      turkish: 'lanetlemek',
      example: {
        arabic: 'إِنَّ ٱللَّهَ لَعَنَ ٱلْكَٰفِرِينَ وَأَعَدَّ لَهُمْ سَعِيرًا',
        english: 'Indeed, Allah has cursed the disbelievers and prepared for them a blaze.',
        turkish: 'Şüphesiz Allah kâfirleri lanetlemiş ve onlara çılgın bir ateş hazırlamıştır.',
        source: 'Qur\'an 33:64',
        highlight: { english: 'cursed', turkish: 'lanetlemiş' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'لعن',
        forms: [
          { label: 'mudari', arabic: 'يَلْعَنُ' },
          { label: 'masdar', arabic: 'لَعْن' },
        ],
        occurrences: 23,
        occurringForm: 'لَعَنَ',
      },
    },
    {
      id: 'miskiyn',
      arabic: 'مِسْكِين',
      english: 'poor person, needy one',
      turkish: 'yoksul, miskin',
      example: {
        arabic: 'أَوْ مِسْكِينًۭا ذَا مَتْرَبَةٍۢ',
        english: 'or a needy person in the dust,',
        turkish: 'ya da toprağa bulanmış bir yoksulu,',
        source: 'Qur\'an 90:16',
        highlight: { english: 'needy person', turkish: 'yoksulu' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سكن',
        forms: [
          { label: 'plural', arabic: 'مَسَاكِين' },
        ],
        occurrences: 23,
        occurringForm: 'مِسْكِينًا',
      },
    },
    {
      id: 'yatiym',
      arabic: 'يَتِيم',
      english: 'orphan',
      turkish: 'yetim',
      example: {
        arabic: 'يَتِيمًۭا ذَا مَقْرَبَةٍ',
        english: 'an orphan of near kinship,',
        turkish: 'akrabalığı olan bir yetimi,',
        source: 'Qur\'an 90:15',
        highlight: { english: 'orphan', turkish: 'yetimi' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'يتم',
        forms: [
          { label: 'plural', arabic: 'يَتَامَى' },
        ],
        occurrences: 23,
        occurringForm: 'يَتِيمًا',
      },
    },
    {
      id: 'adhaqa',
      arabic: 'أَذاقَ',
      english: 'to make taste, to give a taste of',
      turkish: 'tattırmak',
      example: {
        arabic: 'وَلَئِنْ أَذَقْنَا ٱلْإِنسَٰنَ مِنَّا رَحْمَةًۭ ثُمَّ نَزَعْنَٰهَا مِنْهُ إِنَّهُۥ لَيَـُٔوسٌۭ كَفُورٌۭ',
        english: 'And if We give man a taste of mercy from Us and then take it away from him, indeed he is despairing and ungrateful.',
        turkish: 'İnsana tarafımızdan bir rahmet tattırıp sonra onu kendisinden çekip alsak, o mutlaka umutsuz ve nankör olur.',
        source: 'Qur\'an 11:9',
        highlight: { english: 'give man a taste', turkish: 'tattırıp' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ذوق',
        forms: [
          { label: 'mudari', arabic: 'يُذِيقُ' },
          { label: 'masdar', arabic: 'إِذَاقَة' },
        ],
        occurrences: 22,
        occurringForm: 'أَذَقْنَا',
      },
    },
    {
      id: 'aslama',
      arabic: 'أَسْلَمَ',
      english: 'to submit, to surrender oneself',
      turkish: 'teslim olmak, boyun eğmek',
      example: {
        arabic: 'إِذْ قَالَ لَهُۥ رَبُّهُۥٓ أَسْلِمْ ۖ قَالَ أَسْلَمْتُ لِرَبِّ ٱلْعَٰلَمِينَ',
        english: 'When his Lord said to him: Submit. He said: I have submitted to the Lord of the worlds.',
        turkish: 'Hani Rabbi ona: Teslim ol, demişti. O da: Âlemlerin Rabbine teslim oldum, demişti.',
        source: 'Qur\'an 2:131',
        highlight: { english: 'Submit', turkish: 'Teslim ol' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سلم',
        forms: [
          { label: 'mudari', arabic: 'يُسْلِمُ' },
          { label: 'masdar', arabic: 'إِسْلَام' },
        ],
        occurrences: 22,
        occurringForm: 'أَسْلِمْ',
      },
    },
    {
      id: 'barr',
      arabic: 'بَرّ',
      english: 'righteous, dutiful',
      turkish: 'iyi, itaatkâr, erdemli',
      example: {
        arabic: 'كِرَامٍۭ بَرَرَةٍۢ',
        english: 'noble and dutiful.',
        turkish: 'değerli ve iyi olanların.',
        source: 'Qur\'an 80:16',
        highlight: { english: 'dutiful', turkish: 'iyi' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'برر',
        forms: [
          { label: 'plural', arabic: 'أَبْرَار' },
        ],
        occurrences: 22,
        occurringForm: 'بَرَرَةٍ',
      },
    },
    {
      id: 'balaa',
      arabic: 'بَلَى',
      english: 'yes indeed, on the contrary (answering a negative)',
      turkish: 'elbette, aksine (olumsuz soruya cevap)',
      example: {
        arabic: 'بَلَىٰٓ إِنَّ رَبَّهُۥ كَانَ بِهِۦ بَصِيرًۭا',
        english: 'Yes indeed! His Lord was ever seeing of him.',
        turkish: 'Elbette! Şüphesiz Rabbi onu görmekteydi.',
        source: 'Qur\'an 84:15',
        highlight: { english: 'Yes indeed', turkish: 'Elbette' },
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 22,
        occurringForm: 'بَلَىٰٓ',
      },
    },
    {
      id: 'jamaa',
      arabic: 'جَمَعَ',
      english: 'to gather, to collect',
      turkish: 'toplamak, biriktirmek',
      example: {
        arabic: 'ٱلَّذِى جَمَعَ مَالًۭا وَعَدَّدَهُۥ',
        english: 'who gathers wealth and counts it over.',
        turkish: 'O ki mal biriktirdi ve onu tekrar tekrar saydı.',
        source: 'Qur\'an 104:2',
        highlight: { english: 'gathers', turkish: 'biriktirdi' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'جمع',
        forms: [
          { label: 'mudari', arabic: 'يَجْمَعُ' },
          { label: 'masdar', arabic: 'جَمْع' },
        ],
        occurrences: 22,
        occurringForm: 'جَمَعَ',
      },
    },
    {
      id: 'jinn',
      arabic: 'جِنّ',
      english: 'jinn',
      turkish: 'cinler',
      example: {
        arabic: 'وَمَا خَلَقْتُ ٱلْجِنَّ وَٱلْإِنسَ إِلَّا لِيَعْبُدُونِ',
        english: 'And I did not create the jinn and mankind except to worship Me.',
        turkish: 'Ben cinleri ve insanları ancak bana kulluk etsinler diye yarattım.',
        source: 'Qur\'an 51:56',
        highlight: { english: 'jinn', turkish: 'cinleri' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'جنن',
        occurrences: 22,
        occurringForm: 'ٱلْجِنَّ',
      },
    },
    {
      id: 'khalf',
      arabic: 'خَلْف',
      english: 'behind; a succeeding generation, successors',
      turkish: 'arka, arkasında; sonradan gelen nesil',
      example: {
        arabic: '۞ فَخَلَفَ مِنۢ بَعْدِهِمْ خَلْفٌ أَضَاعُوا۟ ٱلصَّلَوٰةَ وَٱتَّبَعُوا۟ ٱلشَّهَوَٰتِ ۖ فَسَوْفَ يَلْقَوْنَ غَيًّا',
        english: 'Then there came after them a generation who neglected the prayer and followed desires; so they will meet perdition,',
        turkish: 'Onların ardından, namazı bırakan ve şehvetlerine uyan bir nesil geldi; onlar azgınlıklarının cezasını görecekler,',
        source: 'Qur\'an 19:59',
        highlight: { english: 'a generation', turkish: 'bir nesil' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'خلف',
        occurrences: 22,
        occurringForm: 'خَلْفٌ',
      },
    },
    {
      id: 'dua',
      arabic: 'دُعاء',
      english: 'supplication, call, prayer',
      turkish: 'dua, çağrı, yakarış',
      example: {
        arabic: 'لَّا يَسْـَٔمُ ٱلْإِنسَٰنُ مِن دُعَآءِ ٱلْخَيْرِ وَإِن مَّسَّهُ ٱلشَّرُّ فَيَـُٔوسٌۭ قَنُوطٌۭ',
        english: 'Man does not weary of praying for good, but if evil touches him, he is despairing and hopeless.',
        turkish: 'İnsan hayır istemekten usanmaz; ama kendisine bir kötülük dokunursa umutsuzluğa düşer, karamsar olur.',
        source: 'Qur\'an 41:49',
        highlight: { english: 'praying', turkish: 'istemekten' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'دعو',
        forms: [
          { label: 'plural', arabic: 'أَدْعِيَة' },
        ],
        occurrences: 22,
        occurringForm: 'دُعَآءِ',
      },
    },
    {
      id: 'rafaa',
      arabic: 'رَفَعَ',
      english: 'to raise, to lift up',
      turkish: 'yükseltmek, kaldırmak',
      example: {
        arabic: 'رَفَعَ سَمْكَهَا فَسَوَّىٰهَا',
        english: 'He raised its vault and proportioned it,',
        turkish: 'Onun kubbesini yükseltti ve düzene koydu,',
        source: 'Qur\'an 79:28',
        highlight: { english: 'raised', turkish: 'yükseltti' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'رفع',
        forms: [
          { label: 'mudari', arabic: 'يَرْفَعُ' },
          { label: 'masdar', arabic: 'رَفْع' },
        ],
        occurrences: 22,
        occurringForm: 'رَفَعَ',
      },
    },
    {
      id: 'sahir',
      arabic: 'ساحِر',
      english: 'magician, sorcerer',
      turkish: 'sihirbaz, büyücü',
      example: {
        arabic: 'يَأْتُوكَ بِكُلِّ سَٰحِرٍ عَلِيمٍۢ',
        english: 'that they bring you every learned magician.',
        turkish: 'Sana bütün bilgili sihirbazları getirsinler.',
        source: 'Qur\'an 7:112',
        highlight: { english: 'magician', turkish: 'sihirbazları' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سحر',
        forms: [
          { label: 'plural', arabic: 'سَحَرَة' },
        ],
        occurrences: 22,
        occurringForm: 'سَٰحِرٍ',
      },
    },
    {
      id: 'sakhkhara',
      arabic: 'سَخَّرَ',
      english: 'to subject, to make serve, to subdue',
      turkish: 'boyun eğdirmek, emrine vermek',
      example: {
        arabic: 'إِنَّا سَخَّرْنَا ٱلْجِبَالَ مَعَهُۥ يُسَبِّحْنَ بِٱلْعَشِىِّ وَٱلْإِشْرَاقِ',
        english: 'Indeed, We subjected the mountains with him, glorifying in the evening and at sunrise,',
        turkish: 'Biz dağları onunla birlikte, akşam ve gün doğarken tespih etsinler diye boyun eğdirdik,',
        source: 'Qur\'an 38:18',
        highlight: { english: 'subjected', turkish: 'boyun eğdirdik' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سخر',
        forms: [
          { label: 'mudari', arabic: 'يُسَخِّرُ' },
          { label: 'masdar', arabic: 'تَسْخِير' },
        ],
        occurrences: 22,
        occurringForm: 'سَخَّرْنَا',
      },
    },
    {
      id: 'sam',
      arabic: 'سَمْع',
      english: 'hearing',
      turkish: 'işitme, kulak',
      example: {
        arabic: 'ٱلَّذِينَ كَانَتْ أَعْيُنُهُمْ فِى غِطَآءٍ عَن ذِكْرِى وَكَانُوا۟ لَا يَسْتَطِيعُونَ سَمْعًا',
        english: 'those whose eyes were under a cover from My remembrance, and who were not able to hear.',
        turkish: 'Onlar, gözleri beni anmaya karşı perdeli olan ve işitmeye de güç yetiremeyenlerdir.',
        source: 'Qur\'an 18:101',
        highlight: { english: 'to hear', turkish: 'işitmeye' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سمع',
        forms: [
          { label: 'plural', arabic: 'أَسْمَاع' },
        ],
        occurrences: 22,
        occurringForm: 'سَمْعًا',
      },
    },
    {
      id: 'ladaa',
      arabic: 'لَدَى',
      english: 'at, with, in the presence of',
      turkish: 'yanında, katında',
      example: {
        arabic: 'إِنَّ لَدَيْنَآ أَنكَالًۭا وَجَحِيمًۭا',
        english: 'Indeed, with Us are shackles and a blazing fire,',
        turkish: 'Şüphesiz katımızda bukağılar ve alevli bir ateş vardır,',
        source: 'Qur\'an 73:12',
        highlight: { english: 'with Us', turkish: 'katımızda' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 22,
        occurringForm: 'لَدَيْنَآ',
      },
    },
    {
      id: 'mawaa',
      arabic: 'مَأْوَى',
      english: 'refuge, shelter, abode',
      turkish: 'sığınak, barınak, varılacak yer',
      example: {
        arabic: 'عِندَهَا جَنَّةُ ٱلْمَأْوَىٰٓ',
        english: 'Near it is the Garden of Refuge.',
        turkish: 'Onun yanında Me\'vâ cenneti vardır.',
        source: 'Qur\'an 53:15',
        highlight: { english: 'Refuge', turkish: 'Me\'vâ' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أوي',
        occurrences: 22,
        occurringForm: 'ٱلْمَأْوَىٰٓ',
      },
    },
  ],
}
