import type { DeckDef } from '../types'

// Quran Vocabulary, level 2. See GitHub issue #8.
//
// Scaffolded by scripts/generateVocab.ts: the headword, root, occurrence count,
// ayah and citation come from the corpus and the canonical text. The meanings,
// principal parts and ayah translations were authored on top of that scaffold.
//
// Where the corpus lemmatizes a word to a passive, an imperative or a mudari
// that nobody looks up, the note id is the dictionary form while the headword
// stays as the corpus has it, since that is what the ayah shows.
//
// DRAFT: verify every English meaning before memorizing it. Turkish is
// convenience text and stays draft - correct it on sight while studying.
//
// Locked until the previous level is mostly graduated; see quranVocabTrack.ts.

export const quranVocab2: DeckDef = {
  id: 'quran-vocab-2',
  name: { english: 'Quran Vocabulary 2', turkish: 'Kur’an Kelimeleri 2' },
  nameArabic: 'مُفْرَدَاتُ الْقُرْآنِ ٢',
  description: {
    english:
      'Frequency band 2 of the Quran vocabulary track, each word with an ayah where it occurs.',
    turkish:
      'Kur’an kelime yolunun 2. sıklık kuşağı; her kelime geçtiği bir ayetle.',
  },
  directions: ['ar-to-meaning'],
  newPerDay: 10,
  burySiblings: true,
  notes: [
    {
      id: 'khayr',
      arabic: 'خَيْر',
      english: 'good, goodness; better',
      turkish: 'hayır, iyilik; daha iyi',
      example: {
        arabic: 'وَٱلْءَاخِرَةُ خَيْرٌۭ وَأَبْقَىٰٓ',
        english: 'while the Hereafter is better and more lasting.',
        turkish: 'Oysa ahiret daha hayırlı ve daha kalıcıdır.',
        source: 'Qur\'an 87:17',
        highlight: { english: 'better', turkish: 'hayırlı' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'خير',
        occurrences: 178,
        occurringForm: 'خَيْرٌ',
      },
    },
    {
      id: 'sabiyl',
      arabic: 'سَبِيل',
      english: 'way, path',
      turkish: 'yol',
      example: {
        arabic: 'لِّتَسْلُكُوا۟ مِنْهَا سُبُلًۭا فِجَاجًۭا',
        english: 'that you may travel along its broad ways.',
        turkish: 'onda geniş yollarda gidesiniz diye.',
        source: 'Qur\'an 71:20',
        highlight: { english: 'ways', turkish: 'yollarda' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سبل',
        forms: [
          { label: 'plural', arabic: 'سُبُل' },
        ],
        occurrences: 176,
        occurringForm: 'سُبُلًا',
      },
    },
    {
      id: 'kadhdhaba',
      arabic: 'كَذَّبَ',
      english: 'to deny, to call a lie',
      turkish: 'yalanlamak',
      example: {
        arabic: 'كَذَّبَتْ ثَمُودُ بِطَغْوَىٰهَآ',
        english: 'Thamud denied through their transgression,',
        turkish: 'Semûd, azgınlığı yüzünden yalanladı,',
        source: 'Qur\'an 91:11',
        highlight: { english: 'denied', turkish: 'yalanladı' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'كذب',
        forms: [
          { label: 'mudari', arabic: 'يُكَذِّبُ' },
          { label: 'masdar', arabic: 'تَكْذِيب' },
        ],
        occurrences: 176,
        occurringForm: 'كَذَّبَتْ',
      },
    },
    {
      id: 'daa',
      arabic: 'دَعا',
      english: 'to call, to supplicate',
      turkish: 'çağırmak, dua etmek',
      example: {
        arabic: 'فَسَوْفَ يَدْعُوا۟ ثُبُورًۭا',
        english: 'he will soon call out for destruction,',
        turkish: 'yakında yok olmayı çağıracak,',
        source: 'Qur\'an 84:11',
        highlight: { english: 'call out', turkish: 'çağıracak' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'دعو',
        forms: [
          { label: 'mudari', arabic: 'يَدْعُو' },
          { label: 'masdar', arabic: 'دُعَاء' },
        ],
        occurrences: 170,
        occurringForm: 'يَدْعُوا۟',
      },
    },
    {
      id: 'amr',
      arabic: 'أَمْر',
      english: 'command, matter, affair',
      turkish: 'emir, iş, buyruk',
      example: {
        arabic: 'فَٱلْمُدَبِّرَٰتِ أَمْرًۭا',
        english: 'and those who arrange each matter,',
        turkish: 'derken işi düzenleyenlere,',
        source: 'Qur\'an 79:5',
        highlight: { english: 'matter', turkish: 'işi' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أمر',
        forms: [
          { label: 'plural', arabic: 'أُمُور' },
        ],
        occurrences: 166,
        occurringForm: 'أَمْرًا',
      },
    },
    {
      id: 'attaqaa',
      arabic: 'اتَّقَى',
      english: 'to fear God, to guard oneself',
      turkish: 'sakınmak, Allah’tan korkmak',
      example: {
        arabic: 'وَإِذَا قِيلَ لَهُ ٱتَّقِ ٱللَّهَ أَخَذَتْهُ ٱلْعِزَّةُ بِٱلْإِثْمِ ۚ فَحَسْبُهُۥ جَهَنَّمُ ۚ وَلَبِئْسَ ٱلْمِهَادُ',
        english: 'And when it is said to him: Fear Allah, pride carries him off into sin. Hell is enough for him, and what a wretched resting place.',
        turkish: 'Ona: Allah’tan kork, denildiğinde, gururu onu günaha sürükler. Ona cehennem yeter; o ne kötü bir yataktır.',
        source: 'Qur\'an 2:206',
        highlight: { english: 'Fear', turkish: 'kork' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'وقي',
        forms: [
          { label: 'mudari', arabic: 'يَتَّقِي' },
          { label: 'masdar', arabic: 'اِتِّقَاء' },
        ],
        occurrences: 166,
        occurringForm: 'ٱتَّقِ',
      },
    },
    {
      id: 'lamma',
      arabic: 'لَمّا',
      english: 'not yet; when',
      turkish: 'henüz -medi; -dığı zaman',
      example: {
        arabic: 'كَلَّا لَمَّا يَقْضِ مَآ أَمَرَهُۥ',
        english: 'No! He has not yet fulfilled what He commanded him.',
        turkish: 'Hayır! O, kendisine emredileni henüz yerine getirmedi.',
        source: 'Qur\'an 80:23',
        highlight: { english: 'not yet', turkish: 'henüz' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 165,
        occurringForm: 'لَمَّا',
      },
    },
    {
      id: 'ma-2',
      arabic: 'مَع',
      english: 'with',
      turkish: 'ile, beraber',
      example: {
        arabic: 'فَإِنَّ مَعَ ٱلْعُسْرِ يُسْرًا',
        english: 'So indeed, with hardship is ease.',
        turkish: 'Şüphesiz güçlükle beraber bir kolaylık vardır.',
        source: 'Qur\'an 94:5',
        highlight: { english: 'with', turkish: 'beraber' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 164,
        occurringForm: 'مَعَ',
      },
    },
    {
      id: 'aliym',
      arabic: 'عَلِيم',
      english: 'knowing, learned',
      turkish: 'alîm, bilen',
      example: {
        arabic: 'يَأْتُوكَ بِكُلِّ سَٰحِرٍ عَلِيمٍۢ',
        english: 'that they bring you every learned magician.',
        turkish: 'sana her bilgili sihirbazı getirsinler.',
        source: 'Qur\'an 7:112',
        highlight: { english: 'learned', turkish: 'bilgili' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'علم',
        forms: [
          { label: 'plural', arabic: 'عُلَمَاء' },
        ],
        occurrences: 163,
        occurringForm: 'عَلِيمٍ',
      },
    },
    {
      id: 'bad',
      arabic: 'بَعْض',
      english: 'some, part of',
      turkish: 'bazı, bir kısmı',
      example: {
        arabic: 'وَلَوْ نَزَّلْنَٰهُ عَلَىٰ بَعْضِ ٱلْأَعْجَمِينَ',
        english: 'And if We had sent it down upon one of the non-Arabs,',
        turkish: 'Onu Arapça bilmeyenlerden birine indirseydik,',
        source: 'Qur\'an 26:198',
        highlight: { english: 'one of', turkish: 'birine' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بعض',
        occurrences: 157,
        occurringForm: 'بَعْضِ',
      },
    },
    {
      id: 'dhuw',
      arabic: 'ذُو',
      english: 'possessor of, owner of',
      turkish: 'sahip, sahibi',
      example: {
        arabic: 'ذَوَاتَآ أَفْنَانٍۢ',
        english: 'Both of them having spreading branches.',
        turkish: 'İkisi de çeşit çeşit dallara sahiptir.',
        source: 'Qur\'an 55:48',
        highlight: { english: 'having', turkish: 'sahiptir' },
      },
      vocab: {
        partOfSpeech: 'ism',
        forms: [
          { label: 'plural', arabic: 'ذَوُو' },
        ],
        occurrences: 156,
        occurringForm: 'ذَوَاتَآ',
      },
    },
    {
      id: 'kafir',
      arabic: 'كافِر',
      english: 'disbeliever',
      turkish: 'kâfir, inkârcı',
      example: {
        arabic: 'قَالَ ٱلَّذِينَ ٱسْتَكْبَرُوٓا۟ إِنَّا بِٱلَّذِىٓ ءَامَنتُم بِهِۦ كَٰفِرُونَ',
        english: 'Those who were arrogant said: Indeed, we are disbelievers in that which you have believed.',
        turkish: 'Büyüklük taslayanlar dedi ki: Doğrusu biz, sizin inandığınızı inkâr ediyoruz.',
        source: 'Qur\'an 7:76',
        highlight: { english: 'disbelievers', turkish: 'inkâr ediyoruz' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كفر',
        forms: [
          { label: 'plural', arabic: 'كُفَّار' },
        ],
        occurrences: 156,
        occurringForm: 'كَٰفِرُونَ',
      },
    },
    {
      id: 'akhir',
      arabic: 'آخِر',
      english: 'last, final; hereafter',
      turkish: 'son, sonuncu; ahiret',
      example: {
        arabic: 'وَتَذَرُونَ ٱلْءَاخِرَةَ',
        english: 'and leave the Hereafter behind.',
        turkish: 've ahireti bırakıyorsunuz.',
        source: 'Qur\'an 75:21',
        highlight: { english: 'Hereafter', turkish: 'ahiret' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أخر',
        forms: [
          { label: 'plural', arabic: 'أَوَاخِر' },
        ],
        occurrences: 155,
        occurringForm: 'ٱلْءَاخِرَةَ',
      },
    },
    {
      id: 'ilah',
      arabic: 'إِلٰه',
      english: 'god, deity',
      turkish: 'ilah, tanrı',
      example: {
        arabic: 'إِلَٰهِ ٱلنَّاسِ',
        english: 'the God of mankind,',
        turkish: 'insanların ilahının,',
        source: 'Qur\'an 114:3',
        highlight: { english: 'God', turkish: 'ilah' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أله',
        forms: [
          { label: 'plural', arabic: 'آلِهَة' },
        ],
        occurrences: 147,
        occurringForm: 'إِلَٰهِ',
      },
    },
    {
      id: 'janna',
      arabic: 'جَنَّة',
      english: 'garden, paradise',
      turkish: 'cennet, bahçe',
      example: {
        arabic: 'فِى جَنَّةٍ عَالِيَةٍۢ',
        english: 'in an elevated garden,',
        turkish: 'yüce bir cennette,',
        source: 'Qur\'an 88:10',
        highlight: { english: 'garden', turkish: 'cennet' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'جنن',
        forms: [
          { label: 'plural', arabic: 'جَنَّات' },
        ],
        occurrences: 147,
        occurringForm: 'جَنَّةٍ',
      },
    },
    {
      id: 'ghayr',
      arabic: 'غَيْر',
      english: 'other than, not',
      turkish: 'başka, gayrı, değil',
      example: {
        arabic: 'عَلَى ٱلْكَٰفِرِينَ غَيْرُ يَسِيرٍۢ',
        english: 'for the disbelievers, not easy.',
        turkish: 'kâfirler için kolay değildir.',
        source: 'Qur\'an 74:10',
        highlight: { english: 'not', turkish: 'değil' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'غير',
        occurrences: 147,
        occurringForm: 'غَيْرُ',
      },
    },
    {
      id: 'nar',
      arabic: 'نار',
      english: 'fire',
      turkish: 'ateş',
      example: {
        arabic: 'نَارٌ حَامِيَةٌۢ',
        english: 'A blazing fire.',
        turkish: 'Kızgın bir ateştir.',
        source: 'Qur\'an 101:11',
        highlight: { english: 'fire', turkish: 'ateş' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نور',
        forms: [
          { label: 'plural', arabic: 'نِيرَان' },
        ],
        occurrences: 145,
        occurringForm: 'نَارٌ',
      },
    },
    {
      id: 'duwn',
      arabic: 'دُون',
      english: 'besides, other than, below',
      turkish: 'başka, dışında, aşağısında',
      example: {
        arabic: 'أَئِفْكًا ءَالِهَةًۭ دُونَ ٱللَّهِ تُرِيدُونَ',
        english: 'Is it falsehood, gods other than Allah, that you desire?',
        turkish: 'Allah’tan başka uydurma ilahlar mı istiyorsunuz?',
        source: 'Qur\'an 37:86',
        highlight: { english: 'other than', turkish: 'başka' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'دون',
        occurrences: 144,
        occurringForm: 'دُونَ',
      },
    },
    {
      id: 'hadaa',
      arabic: 'هَدَى',
      english: 'to guide',
      turkish: 'hidayet etmek, doğru yola iletmek',
      example: {
        arabic: 'وَأَضَلَّ فِرْعَوْنُ قَوْمَهُۥ وَمَا هَدَىٰ',
        english: 'And Pharaoh led his people astray and did not guide them.',
        turkish: 'Firavun kavmini saptırdı, doğru yola iletmedi.',
        source: 'Qur\'an 20:79',
        highlight: { english: 'guide', turkish: 'doğru yola iletmedi' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'هدي',
        forms: [
          { label: 'mudari', arabic: 'يَهْدِي' },
          { label: 'masdar', arabic: 'هِدَايَة' },
        ],
        occurrences: 144,
        occurringForm: 'هَدَىٰ',
      },
    },
    {
      id: 'hattaa',
      arabic: 'حَتَّى',
      english: 'until, so that',
      turkish: '-e kadar, ta ki',
      example: {
        arabic: 'حَتَّىٰ زُرْتُمُ ٱلْمَقَابِرَ',
        english: 'until you visited the graves.',
        turkish: 'ta ki kabirleri ziyaret ettiniz.',
        source: 'Qur\'an 102:2',
        highlight: { english: 'until', turkish: 'ta ki' },
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 142,
        occurringForm: 'حَتَّىٰ',
      },
    },
    {
      id: 'arada',
      arabic: 'أَرادَ',
      english: 'to want, to intend',
      turkish: 'istemek, dilemek',
      example: {
        arabic: 'فَعَّالٌۭ لِّمَا يُرِيدُ',
        english: 'Doer of whatever He intends.',
        turkish: 'Dilediğini mutlaka yapandır.',
        source: 'Qur\'an 85:16',
        highlight: { english: 'intends', turkish: 'Dilediğini' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'رود',
        forms: [
          { label: 'mudari', arabic: 'يُرِيدُ' },
          { label: 'masdar', arabic: 'إِرَادَة' },
        ],
        occurrences: 139,
        occurringForm: 'يُرِيدُ',
      },
    },
    {
      id: 'am',
      arabic: 'أَم',
      english: 'or (in questions)',
      turkish: 'yoksa, veya',
      example: {
        arabic: 'أَمْ لَكُمْ سُلْطَٰنٌۭ مُّبِينٌۭ',
        english: 'Or do you have a clear authority?',
        turkish: 'Yoksa sizin apaçık bir deliliniz mi var?',
        source: 'Qur\'an 37:156',
        highlight: { english: 'Or', turkish: 'Yoksa' },
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 137,
        occurringForm: 'أَمْ',
      },
    },
    {
      id: 'attabaa',
      arabic: 'اتَّبَعَ',
      english: 'to follow',
      turkish: 'tabi olmak, uymak',
      example: {
        arabic: 'لَعَلَّنَا نَتَّبِعُ ٱلسَّحَرَةَ إِن كَانُوا۟ هُمُ ٱلْغَٰلِبِينَ',
        english: 'so that we may follow the magicians if they are the victors.',
        turkish: 'umarız, galip gelirlerse sihirbazlara uyarız.',
        source: 'Qur\'an 26:40',
        highlight: { english: 'follow', turkish: 'uyarız' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'تبع',
        forms: [
          { label: 'mudari', arabic: 'يَتَّبِعُ' },
          { label: 'masdar', arabic: 'اِتِّبَاع' },
        ],
        occurrences: 136,
        occurringForm: 'نَتَّبِعُ',
      },
    },
    {
      id: 'muwsaa',
      arabic: 'مُوسَى',
      english: 'Moses',
      turkish: 'Musa',
      example: {
        arabic: 'رَبِّ مُوسَىٰ وَهَٰرُونَ',
        english: 'the Lord of Moses and Aaron.',
        turkish: 'Musa ve Harun’un Rabbine.',
        source: 'Qur\'an 7:122',
        highlight: { english: 'Moses', turkish: 'Musa' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 136,
        occurringForm: 'مُوسَىٰ',
      },
    },
    {
      id: 'qalb',
      arabic: 'قَلْب',
      english: 'heart',
      turkish: 'kalp, gönül',
      example: {
        arabic: 'قُلُوبٌۭ يَوْمَئِذٍۢ وَاجِفَةٌ',
        english: 'Hearts, that Day, will tremble,',
        turkish: 'O gün kalpler titrer,',
        source: 'Qur\'an 79:8',
        highlight: { english: 'Hearts', turkish: 'kalpler' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قلب',
        forms: [
          { label: 'plural', arabic: 'قُلُوب' },
        ],
        occurrences: 132,
        occurringForm: 'قُلُوبٌ',
      },
    },
    {
      id: 'abd',
      arabic: 'عَبْد',
      english: 'servant, slave',
      turkish: 'kul, köle',
      example: {
        arabic: 'عَبْدًا إِذَا صَلَّىٰٓ',
        english: 'a servant when he prays?',
        turkish: 'namaz kıldığı zaman bir kulu?',
        source: 'Qur\'an 96:10',
        highlight: { english: 'servant', turkish: 'kulu' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عبد',
        forms: [
          { label: 'plural', arabic: 'عِبَاد' },
        ],
        occurrences: 131,
        occurringForm: 'عَبْدًا',
      },
    },
    {
      id: 'arsala',
      arabic: 'أَرْسَلَ',
      english: 'to send',
      turkish: 'göndermek',
      example: {
        arabic: 'يُرْسِلِ ٱلسَّمَآءَ عَلَيْكُم مِّدْرَارًۭا',
        english: 'He will send the sky upon you in abundant rain,',
        turkish: 'Gökten üzerinize bol bol yağmur göndersin,',
        source: 'Qur\'an 71:11',
        highlight: { english: 'send', turkish: 'göndersin' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'رسل',
        forms: [
          { label: 'mudari', arabic: 'يُرْسِلُ' },
          { label: 'masdar', arabic: 'إِرْسَال' },
        ],
        occurrences: 130,
        occurringForm: 'يُرْسِلِ',
      },
    },
    {
      id: 'zalim',
      arabic: 'ظالِم',
      english: 'wrongdoer, unjust',
      turkish: 'zalim, haksızlık eden',
      example: {
        arabic: 'ذِكْرَىٰ وَمَا كُنَّا ظَٰلِمِينَ',
        english: 'as a reminder; and We were never unjust.',
        turkish: 'bir hatırlatma olarak; biz zalimler değildik.',
        source: 'Qur\'an 26:209',
        highlight: { english: 'unjust', turkish: 'zalimler' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ظلم',
        forms: [
          { label: 'plural', arabic: 'ظَالِمُون' },
        ],
        occurrences: 129,
        occurringForm: 'ظَٰلِمِينَ',
      },
    },
    {
      id: 'laall',
      arabic: 'لَعَلّ',
      english: 'perhaps, so that',
      turkish: 'belki, umulur ki',
      example: {
        arabic: 'ٱللَّهُ ٱلَّذِىٓ أَنزَلَ ٱلْكِتَٰبَ بِٱلْحَقِّ وَٱلْمِيزَانَ ۗ وَمَا يُدْرِيكَ لَعَلَّ ٱلسَّاعَةَ قَرِيبٌۭ',
        english: 'It is Allah who sent down the Book in truth, and the balance. And what will make you know? Perhaps the Hour is near.',
        turkish: 'Kitabı hak ile ve ölçüyü indiren Allah’tır. Ne bilirsin, belki de o saat yakındır.',
        source: 'Qur\'an 42:17',
        highlight: { english: 'Perhaps', turkish: 'belki' },
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 129,
        occurringForm: 'لَعَلَّ',
      },
    },
    {
      id: 'akhadha',
      arabic: 'أَخَذَ',
      english: 'to take, to seize',
      turkish: 'almak, yakalamak',
      example: {
        arabic: 'خُذِ ٱلْعَفْوَ وَأْمُرْ بِٱلْعُرْفِ وَأَعْرِضْ عَنِ ٱلْجَٰهِلِينَ',
        english: 'Take what is easily forgiven, enjoin what is right, and turn away from the ignorant.',
        turkish: 'Affı benimse, iyiliği emret, cahillerden yüz çevir.',
        source: 'Qur\'an 7:199',
        highlight: { english: 'Take', turkish: 'benimse' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'أخذ',
        forms: [
          { label: 'mudari', arabic: 'يَأْخُذُ' },
          { label: 'masdar', arabic: 'أَخْذ' },
        ],
        occurrences: 127,
        occurringForm: 'خُذِ',
      },
    },
    {
      id: 'ahl',
      arabic: 'أَهْل',
      english: 'family, people of',
      turkish: 'aile, ehli, halkı',
      example: {
        arabic: 'وَجَآءَ أَهْلُ ٱلْمَدِينَةِ يَسْتَبْشِرُونَ',
        english: 'And the people of the city came rejoicing.',
        turkish: 'Şehir halkı sevinerek geldi.',
        source: 'Qur\'an 15:67',
        highlight: { english: 'people of', turkish: 'halkı' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أهل',
        forms: [
          { label: 'plural', arabic: 'أَهْلُون' },
        ],
        occurrences: 127,
        occurringForm: 'أَهْلُ',
      },
    },
    {
      id: 'bal',
      arabic: 'بَل',
      english: 'rather, nay',
      turkish: 'aksine, bilakis, hayır',
      example: {
        arabic: 'بَلْ عَجِبْتَ وَيَسْخَرُونَ',
        english: 'Rather, you marvel, while they mock.',
        turkish: 'Aksine sen hayret ettin, onlar ise alay ediyorlar.',
        source: 'Qur\'an 37:12',
        highlight: { english: 'Rather', turkish: 'Aksine' },
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 127,
        occurringForm: 'بَلْ',
      },
    },
    {
      id: 'attakhadha',
      arabic: 'اتَّخَذَ',
      english: 'to take for oneself, to adopt',
      turkish: 'edinmek',
      example: {
        arabic: 'وَقَالُوا۟ ٱتَّخَذَ ٱلرَّحْمَٰنُ وَلَدًۭا',
        english: 'And they say: The Most Merciful has taken a son.',
        turkish: 'Dediler ki: Rahman bir çocuk edindi.',
        source: 'Qur\'an 19:88',
        highlight: { english: 'taken', turkish: 'edindi' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'أخذ',
        forms: [
          { label: 'mudari', arabic: 'يَتَّخِذُ' },
          { label: 'masdar', arabic: 'اِتِّخَاذ' },
        ],
        occurrences: 124,
        occurringForm: 'ٱتَّخَذَ',
      },
    },
    {
      id: 'abada',
      arabic: 'عَبَدَ',
      english: 'to worship, to serve',
      turkish: 'ibadet etmek, kulluk etmek',
      example: {
        arabic: 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
        english: 'You alone we worship, and You alone we ask for help.',
        turkish: 'Yalnız sana kulluk eder, yalnız senden yardım dileriz.',
        source: 'Qur\'an 1:5',
        highlight: { english: 'worship', turkish: 'kulluk eder' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عبد',
        forms: [
          { label: 'mudari', arabic: 'يَعْبُدُ' },
          { label: 'masdar', arabic: 'عِبَادَة' },
        ],
        occurrences: 122,
        occurringForm: 'نَعْبُدُ',
      },
    },
    {
      id: 'yad',
      arabic: 'يَد',
      english: 'hand',
      turkish: 'el',
      example: {
        arabic: 'تَبَّتْ يَدَآ أَبِى لَهَبٍۢ وَتَبَّ',
        english: 'May the hands of Abu Lahab perish, and may he perish.',
        turkish: 'Ebu Leheb’in elleri kurusun, kendisi de kurusun.',
        source: 'Qur\'an 111:1',
        highlight: { english: 'hands', turkish: 'elleri' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'يدي',
        forms: [
          { label: 'plural', arabic: 'أَيْدِي' },
        ],
        occurrences: 120,
        occurringForm: 'يَدَآ',
      },
    },
    {
      id: 'mubiyn',
      arabic: 'مُبِين',
      english: 'clear, manifest',
      turkish: 'apaçık, açık',
      example: {
        arabic: 'بِلِسَانٍ عَرَبِىٍّۢ مُّبِينٍۢ',
        english: 'in a clear Arabic tongue.',
        turkish: 'apaçık bir Arap diliyle.',
        source: 'Qur\'an 26:195',
        highlight: { english: 'clear', turkish: 'apaçık' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بين',
        occurrences: 119,
        occurringForm: 'مُّبِينٍ',
      },
    },
    {
      id: 'rahiym',
      arabic: 'رَحِيم',
      english: 'merciful',
      turkish: 'merhametli, esirgeyen',
      example: {
        arabic: 'نُزُلًۭا مِّنْ غَفُورٍۢ رَّحِيمٍۢ',
        english: 'as accommodation from a Forgiving, Merciful one.',
        turkish: 'çok bağışlayan, çok merhametli olandan bir ikram olarak.',
        source: 'Qur\'an 41:32',
        highlight: { english: 'Merciful', turkish: 'merhametli' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'رحم',
        forms: [
          { label: 'plural', arabic: 'رُحَمَاء' },
        ],
        occurrences: 116,
        occurringForm: 'رَّحِيمٍ',
      },
    },
    {
      id: 'dunya',
      arabic: 'دُنْيا',
      english: 'world, this life',
      turkish: 'dünya',
      example: {
        arabic: 'وَءَاثَرَ ٱلْحَيَوٰةَ ٱلدُّنْيَا',
        english: 'and preferred the life of this world,',
        turkish: 've dünya hayatını tercih ettiyse,',
        source: 'Qur\'an 79:38',
        highlight: { english: 'this world', turkish: 'dünya' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'دنو',
        occurrences: 115,
        occurringForm: 'ٱلدُّنْيَا',
      },
    },
    {
      id: 'rahma',
      arabic: 'رَحْمَة',
      english: 'mercy, compassion',
      turkish: 'rahmet, merhamet',
      example: {
        arabic: 'ذِكْرُ رَحْمَتِ رَبِّكَ عَبْدَهُۥ زَكَرِيَّآ',
        english: 'A mention of the mercy of your Lord to His servant Zechariah.',
        turkish: 'Rabbinin, kulu Zekeriya’ya olan rahmetinin anılışıdır.',
        source: 'Qur\'an 19:2',
        highlight: { english: 'mercy', turkish: 'rahmet' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'رحم',
        occurrences: 114,
        occurringForm: 'رَحْمَتِ',
      },
    },
    {
      id: 'zalama',
      arabic: 'ظَلَمَ',
      english: 'to wrong, to do injustice',
      turkish: 'zulmetmek, haksızlık etmek',
      example: {
        arabic: 'إِنَّ ٱللَّهَ لَا يَظْلِمُ ٱلنَّاسَ شَيْـًۭٔا وَلَٰكِنَّ ٱلنَّاسَ أَنفُسَهُمْ يَظْلِمُونَ',
        english: 'Indeed, Allah does not wrong people at all, but the people wrong themselves.',
        turkish: 'Şüphesiz Allah insanlara hiçbir şekilde zulmetmez, fakat insanlar kendilerine zulmederler.',
        source: 'Qur\'an 10:44',
        highlight: { english: 'does not wrong', turkish: 'zulmetmez' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ظلم',
        forms: [
          { label: 'mudari', arabic: 'يَظْلِمُ' },
          { label: 'masdar', arabic: 'ظُلْم' },
        ],
        occurrences: 110,
        occurringForm: 'يَظْلِمُ',
      },
    },
    {
      id: 'aziym',
      arabic: 'عَظِيم',
      english: 'great, mighty',
      turkish: 'büyük, yüce',
      example: {
        arabic: 'لِيَوْمٍ عَظِيمٍۢ',
        english: 'for a great Day,',
        turkish: 'büyük bir gün için,',
        source: 'Qur\'an 83:5',
        highlight: { english: 'great', turkish: 'büyük' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عظم',
        forms: [
          { label: 'plural', arabic: 'عِظَام' },
        ],
        occurrences: 107,
        occurringForm: 'عَظِيمٍ',
      },
    },
    {
      id: 'saala',
      arabic: 'سَأَلَ',
      english: 'to ask',
      turkish: 'sormak, istemek',
      example: {
        arabic: 'وَإِذَا ٱلْمَوْءُۥدَةُ سُئِلَتْ',
        english: 'And when the girl buried alive is asked,',
        turkish: 'Diri diri gömülen kıza sorulduğu zaman,',
        source: 'Qur\'an 81:8',
        highlight: { english: 'asked', turkish: 'sorulduğu' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سأل',
        forms: [
          { label: 'mudari', arabic: 'يَسْأَلُ' },
          { label: 'masdar', arabic: 'سُؤَال' },
        ],
        occurrences: 106,
        occurringForm: 'سُئِلَتْ',
      },
    },
    {
      id: 'lan',
      arabic: 'لَن',
      english: 'never (with the subjunctive)',
      turkish: 'asla -meyecek',
      example: {
        arabic: 'إِنَّهُۥ ظَنَّ أَن لَّن يَحُورَ',
        english: 'Indeed, he thought he would never return.',
        turkish: 'Şüphesiz o, asla dönmeyeceğini sanmıştı.',
        source: 'Qur\'an 84:14',
        highlight: { english: 'never', turkish: 'asla' },
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 106,
        occurringForm: 'لَّن',
      },
    },
    {
      id: 'wajada',
      arabic: 'وَجَدَ',
      english: 'to find',
      turkish: 'bulmak',
      example: {
        arabic: 'أُو۟لَٰٓئِكَ ٱلَّذِينَ لَعَنَهُمُ ٱللَّهُ ۖ وَمَن يَلْعَنِ ٱللَّهُ فَلَن تَجِدَ لَهُۥ نَصِيرًا',
        english: 'Those are the ones whom Allah has cursed; and whoever Allah curses, you will never find for him a helper.',
        turkish: 'İşte onlar, Allah’ın lanetlediği kimselerdir; Allah kimi lanetlerse, ona asla bir yardımcı bulamazsın.',
        source: 'Qur\'an 4:52',
        highlight: { english: 'find', turkish: 'bulamazsın' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'وجد',
        forms: [
          { label: 'mudari', arabic: 'يَجِدُ' },
        ],
        occurrences: 106,
        occurringForm: 'تَجِدَ',
      },
    },
    {
      id: 'ajr',
      arabic: 'أَجْر',
      english: 'reward, wage',
      turkish: 'ecir, ödül, ücret',
      example: {
        arabic: 'وَإِذًۭا لَّءَاتَيْنَٰهُم مِّن لَّدُنَّآ أَجْرًا عَظِيمًۭا',
        english: 'and then We would have given them from Us a great reward.',
        turkish: 'o zaman onlara katımızdan büyük bir ödül verirdik.',
        source: 'Qur\'an 4:67',
        highlight: { english: 'reward', turkish: 'ödül' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أجر',
        forms: [
          { label: 'plural', arabic: 'أُجُور' },
        ],
        occurrences: 105,
        occurringForm: 'أَجْرًا',
      },
    },
    {
      id: 'ilm',
      arabic: 'عِلْم',
      english: 'knowledge',
      turkish: 'ilim, bilgi',
      example: {
        arabic: 'كَلَّا لَوْ تَعْلَمُونَ عِلْمَ ٱلْيَقِينِ',
        english: 'No! If you only knew with the knowledge of certainty.',
        turkish: 'Hayır! Kesin bir bilgiyle bilseydiniz.',
        source: 'Qur\'an 102:5',
        highlight: { english: 'knowledge', turkish: 'bilgi' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'علم',
        forms: [
          { label: 'plural', arabic: 'عُلُوم' },
        ],
        occurrences: 105,
        occurringForm: 'عِلْمَ',
      },
    },
    {
      id: 'aziyz',
      arabic: 'عَزِيز',
      english: 'mighty, almighty; precious',
      turkish: 'aziz, güçlü; değerli',
      example: {
        arabic: 'وَيَنصُرَكَ ٱللَّهُ نَصْرًا عَزِيزًا',
        english: 'and that Allah may help you with a mighty help.',
        turkish: 've Allah sana güçlü bir yardımla yardım etsin.',
        source: 'Qur\'an 48:3',
        highlight: { english: 'mighty', turkish: 'güçlü' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عزز',
        forms: [
          { label: 'plural', arabic: 'أَعِزَّة' },
        ],
        occurrences: 101,
        occurringForm: 'عَزِيزًا',
      },
    },
    {
      id: 'akhraja',
      arabic: 'أَخْرَجَ',
      english: 'to bring out, to expel',
      turkish: 'çıkarmak',
      example: {
        arabic: 'وَٱلَّذِىٓ أَخْرَجَ ٱلْمَرْعَىٰ',
        english: 'and who brought out the pasture,',
        turkish: 've otlağı çıkaran,',
        source: 'Qur\'an 87:4',
        highlight: { english: 'brought out', turkish: 'çıkaran' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'خرج',
        forms: [
          { label: 'mudari', arabic: 'يُخْرِجُ' },
          { label: 'masdar', arabic: 'إِخْرَاج' },
        ],
        occurrences: 99,
        occurringForm: 'أَخْرَجَ',
      },
    },
    {
      id: 'hakiym',
      arabic: 'حَكِيم',
      english: 'wise',
      turkish: 'hakîm, hikmet sahibi',
      example: {
        arabic: 'فِيهَا يُفْرَقُ كُلُّ أَمْرٍ حَكِيمٍ',
        english: 'In it every wise matter is made distinct,',
        turkish: 'O gecede her hikmetli iş ayırt edilir,',
        source: 'Qur\'an 44:4',
        highlight: { english: 'wise', turkish: 'hikmetli' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حكم',
        forms: [
          { label: 'plural', arabic: 'حُكَمَاء' },
        ],
        occurrences: 97,
        occurringForm: 'حَكِيمٍ',
      },
    },
    {
      id: 'akala',
      arabic: 'أَكَلَ',
      english: 'to eat',
      turkish: 'yemek',
      example: {
        arabic: 'لَّا يَأْكُلُهُۥٓ إِلَّا ٱلْخَٰطِـُٔونَ',
        english: 'None will eat it except the sinners.',
        turkish: 'Onu ancak günahkârlar yer.',
        source: 'Qur\'an 69:37',
        highlight: { english: 'eat', turkish: 'yer' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'أكل',
        forms: [
          { label: 'mudari', arabic: 'يَأْكُلُ' },
          { label: 'masdar', arabic: 'أَكْل' },
        ],
        occurrences: 93,
        occurringForm: 'يَأْكُلُهُۥٓ',
      },
    },
  ],
}
