import type { DeckDef } from '../types'

// Quran Vocabulary, level 5. See GitHub issue #8.
//
// Scaffolded by scripts/generateVocab.ts: the headword, root, occurrence count,
// ayah and citation come from the corpus and the canonical text. The meanings,
// principal parts and ayah translations were authored on top of that scaffold.
//
// Where the corpus lemmatizes a word to a passive, an imperative or a mudari
// that nobody looks up, the note id is the dictionary form while the headword
// stays as the corpus has it, since that is what the ayah shows.
//
// DRAFT: verify every English meaning before memorizing it. Turkish is
// convenience text and stays draft - correct it on sight while studying.
//
// Locked until the previous level is mostly graduated; see quranVocabTrack.ts.

export const quranVocab5: DeckDef = {
  id: 'quran-vocab-5',
  name: { english: 'Quran Vocabulary 5', turkish: 'Kur’an Kelimeleri 5' },
  nameArabic: 'مُفْرَدَاتُ الْقُرْآنِ ٥',
  description: {
    english:
      'Frequency band 5 of the Quran vocabulary track, each word with an ayah where it occurs.',
    turkish:
      'Kur’an kelime yolunun 5. sıklık kuşağı; her kelime geçtiği bir ayetle.',
  },
  directions: ['ar-to-meaning'],
  newPerDay: 10,
  burySiblings: true,
  notes: [
    {
      id: 'jamiy',
      arabic: 'جَمِيع',
      english: 'all together, whole; assembly',
      turkish: 'hep birlikte, topluluk',
      example: {
        arabic: 'أَمْ يَقُولُونَ نَحْنُ جَمِيعٌۭ مُّنتَصِرٌۭ',
        english: 'Or do they say: We are an assembly that will prevail?',
        turkish: 'Yoksa, Biz galip gelecek bir topluluğuz mu diyorlar?',
        source: 'Qur\'an 54:44',
        highlight: { english: 'assembly', turkish: 'topluluğuz' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'جمع',
        occurrences: 53,
        occurringForm: 'جَمِيعٌ',
      },
    },
    {
      id: 'kharaja',
      arabic: 'خَرَجَ',
      english: 'to go out, to come forth',
      turkish: 'çıkmak',
      example: {
        arabic: 'يَخْرُجُ مِنْهُمَا ٱللُّؤْلُؤُ وَٱلْمَرْجَانُ',
        english: 'From both of them come forth pearl and coral.',
        turkish: 'İkisinden de inci ve mercan çıkar.',
        source: 'Qur\'an 55:22',
        highlight: { english: 'come forth', turkish: 'çıkar' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'خرج',
        forms: [
          { label: 'mudari', arabic: 'يَخْرُجُ' },
          { label: 'masdar', arabic: 'خُرُوج' },
        ],
        occurrences: 53,
        occurringForm: 'يَخْرُجُ',
      },
    },
    {
      id: 'dalla',
      arabic: 'ضَلَّ',
      english: 'to go astray, to err',
      turkish: 'sapmak, yolunu şaşırmak',
      example: {
        arabic: 'وَلَقَدْ ضَلَّ قَبْلَهُمْ أَكْثَرُ ٱلْأَوَّلِينَ',
        english: 'And certainly most of the former peoples went astray before them.',
        turkish: 'Andolsun ki onlardan önce evvelkilerin çoğu sapmıştı.',
        source: 'Qur\'an 37:71',
        highlight: { english: 'went astray', turkish: 'sapmıştı' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ضلل',
        forms: [
          { label: 'mudari', arabic: 'يَضِلُّ' },
          { label: 'masdar', arabic: 'ضَلَال' },
        ],
        occurrences: 53,
        occurringForm: 'ضَلَّ',
      },
    },
    {
      id: 'ajal',
      arabic: 'أَجَل',
      english: 'term, appointed time',
      turkish: 'ecel, belirlenmiş süre',
      example: {
        arabic: 'وَلِكُلِّ أُمَّةٍ أَجَلٌۭ ۖ فَإِذَا جَآءَ أَجَلُهُمْ لَا يَسْتَأْخِرُونَ سَاعَةًۭ ۖ وَلَا يَسْتَقْدِمُونَ',
        english: 'And for every community there is a term. So when their term comes, they cannot delay it an hour, nor can they bring it forward.',
        turkish: 'Her ümmetin bir eceli vardır. Ecelleri geldiğinde ne bir saat geri kalabilirler ne de öne geçebilirler.',
        source: 'Qur\'an 7:34',
        highlight: { english: 'a term', turkish: 'eceli' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أجل',
        forms: [
          { label: 'plural', arabic: 'آجَال' },
        ],
        occurrences: 52,
        occurringForm: 'أَجَلٌ',
      },
    },
    {
      id: 'baatha',
      arabic: 'بَعَثَ',
      english: 'to send, to raise up',
      turkish: 'göndermek, diriltmek',
      example: {
        arabic: 'وَسَلَٰمٌ عَلَيْهِ يَوْمَ وُلِدَ وَيَوْمَ يَمُوتُ وَيَوْمَ يُبْعَثُ حَيًّۭا',
        english: 'And peace be upon him the day he was born, the day he dies, and the day he is raised alive.',
        turkish: 'Doğduğu gün, öleceği gün ve diri olarak diriltileceği gün ona selam olsun.',
        source: 'Qur\'an 19:15',
        highlight: { english: 'raised alive', turkish: 'diriltileceği' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بعث',
        forms: [
          { label: 'mudari', arabic: 'يَبْعَثُ' },
          { label: 'masdar', arabic: 'بَعْث' },
        ],
        occurrences: 52,
        occurringForm: 'يُبْعَثُ',
      },
    },
    {
      id: 'khalq',
      arabic: 'خَلْق',
      english: 'creation, creating',
      turkish: 'yaratma, yaratılış',
      example: {
        arabic: 'ءَأَنتُمْ أَشَدُّ خَلْقًا أَمِ ٱلسَّمَآءُ ۚ بَنَىٰهَا',
        english: 'Are you harder to create, or the heaven? He built it.',
        turkish: 'Sizi yaratmak mı daha güçtür, yoksa göğü mü? Onu O bina etti.',
        source: 'Qur\'an 79:27',
        highlight: { english: 'to create', turkish: 'yaratmak' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'خلق',
        occurrences: 52,
        occurringForm: 'خَلْقًا',
      },
    },
    {
      id: 'mujrim',
      arabic: 'مُجْرِم',
      english: 'criminal, guilty one',
      turkish: 'mücrim, suçlu',
      example: {
        arabic: 'كُلُوا۟ وَتَمَتَّعُوا۟ قَلِيلًا إِنَّكُم مُّجْرِمُونَ',
        english: 'Eat and enjoy yourselves a little; indeed, you are criminals.',
        turkish: 'Yiyin ve biraz faydalanın; şüphesiz siz mücrimlersiniz.',
        source: 'Qur\'an 77:46',
        highlight: { english: 'criminals', turkish: 'mücrim' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'جرم',
        forms: [
          { label: 'plural', arabic: 'مُجْرِمُون' },
        ],
        occurrences: 52,
        occurringForm: 'مُّجْرِمُونَ',
      },
    },
    {
      id: 'ahya',
      arabic: 'أَحْيا',
      english: 'to give life, to revive',
      turkish: 'diriltmek, hayat vermek',
      example: {
        arabic: 'هُوَ يُحْىِۦ وَيُمِيتُ وَإِلَيْهِ تُرْجَعُونَ',
        english: 'He gives life and causes death, and to Him you will be returned.',
        turkish: 'O diriltir ve öldürür; O\'na döndürüleceksiniz.',
        source: 'Qur\'an 10:56',
        highlight: { english: 'gives life', turkish: 'diriltir' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حيي',
        forms: [
          { label: 'mudari', arabic: 'يُحْيِي' },
          { label: 'masdar', arabic: 'إِحْيَاء' },
        ],
        occurrences: 51,
        occurringForm: 'يُحْىِۦ',
      },
    },
    {
      id: 'ahlaka',
      arabic: 'أَهْلَكَ',
      english: 'to destroy, to ruin',
      turkish: 'helak etmek, yok etmek',
      example: {
        arabic: 'أَلَمْ نُهْلِكِ ٱلْأَوَّلِينَ',
        english: 'Did We not destroy the former peoples?',
        turkish: 'Biz öncekileri helak etmedik mi?',
        source: 'Qur\'an 77:16',
        highlight: { english: 'destroy', turkish: 'helak etmedik' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'هلك',
        forms: [
          { label: 'mudari', arabic: 'يُهْلِكُ' },
          { label: 'masdar', arabic: 'إِهْلَاك' },
        ],
        occurrences: 51,
        occurringForm: 'نُهْلِكِ',
      },
    },
    {
      id: 'basiyr',
      arabic: 'بَصِير',
      english: 'seeing, all-seeing',
      turkish: 'basîr, gören',
      example: {
        arabic: 'إِنَّكَ كُنتَ بِنَا بَصِيرًۭا',
        english: 'Indeed, You have always been Seeing of us.',
        turkish: 'Şüphesiz Sen bizi görmektesin.',
        source: 'Qur\'an 20:35',
        highlight: { english: 'Seeing', turkish: 'görmektesin' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بصر',
        occurrences: 51,
        occurringForm: 'بَصِيرًا',
      },
    },
    {
      id: 'taht',
      arabic: 'تَحْت',
      english: 'under, beneath',
      turkish: 'altında',
      example: {
        arabic: 'لَهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ وَمَا بَيْنَهُمَا وَمَا تَحْتَ ٱلثَّرَىٰ',
        english: 'To Him belongs whatever is in the heavens, whatever is on the earth, whatever is between them, and whatever is under the soil.',
        turkish: 'Göklerde, yerde, ikisinin arasında ve toprağın altında ne varsa O\'nundur.',
        source: 'Qur\'an 20:6',
        highlight: { english: 'under', turkish: 'altında' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'تحت',
        occurrences: 51,
        occurringForm: 'تَحْتَ',
      },
    },
    {
      id: 'tadhakkara',
      arabic: 'تَذَكَّرَ',
      english: 'to remember, to take heed',
      turkish: 'hatırlamak, öğüt almak',
      example: {
        arabic: 'أَوْ يَذَّكَّرُ فَتَنفَعَهُ ٱلذِّكْرَىٰٓ',
        english: 'or he would take heed, so the reminder would benefit him.',
        turkish: 'yahut öğüt alır da öğüt kendisine fayda verir.',
        source: 'Qur\'an 80:4',
        highlight: { english: 'take heed', turkish: 'öğüt alır' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ذكر',
        forms: [
          { label: 'mudari', arabic: 'يَتَذَكَّرُ' },
          { label: 'masdar', arabic: 'تَذَكُّر' },
        ],
        occurrences: 51,
        occurringForm: 'يَذَّكَّرُ',
      },
    },
    {
      id: 'aftaraa',
      arabic: 'افْتَرَى',
      english: 'to fabricate, to invent a lie',
      turkish: 'uydurmak, iftira etmek',
      example: {
        arabic: 'فَمَنِ ٱفْتَرَىٰ عَلَى ٱللَّهِ ٱلْكَذِبَ مِنۢ بَعْدِ ذَٰلِكَ فَأُو۟لَٰٓئِكَ هُمُ ٱلظَّٰلِمُونَ',
        english: 'So whoever invents a lie about Allah after that, those are the wrongdoers.',
        turkish: 'Kim bundan sonra Allah\'a karşı yalan uydurursa, işte onlar zalimlerdir.',
        source: 'Qur\'an 3:94',
        highlight: { english: 'invents a lie', turkish: 'yalan uydurursa' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'فري',
        forms: [
          { label: 'mudari', arabic: 'يَفْتَرِي' },
          { label: 'masdar', arabic: 'اِفْتِرَاء' },
        ],
        occurrences: 50,
        occurringForm: 'ٱفْتَرَىٰ',
      },
    },
    {
      id: 'suw',
      arabic: 'سُوء',
      english: 'evil, badness, harm',
      turkish: 'kötülük, fenalık',
      example: {
        arabic: 'أُو۟لَٰٓئِكَ ٱلَّذِينَ لَهُمْ سُوٓءُ ٱلْعَذَابِ وَهُمْ فِى ٱلْءَاخِرَةِ هُمُ ٱلْأَخْسَرُونَ',
        english: 'Those are the ones for whom is the evil of punishment, and in the Hereafter they are the greatest losers.',
        turkish: 'İşte azabın kötüsü onlar içindir ve ahirette de en çok ziyana uğrayanlar onlardır.',
        source: 'Qur\'an 27:5',
        highlight: { english: 'the evil of', turkish: 'kötüsü' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سوأ',
        occurrences: 50,
        occurringForm: 'سُوٓءُ',
      },
    },
    {
      id: 'aduww',
      arabic: 'عَدُوّ',
      english: 'enemy',
      turkish: 'düşman',
      example: {
        arabic: 'فَإِنَّهُمْ عَدُوٌّۭ لِّىٓ إِلَّا رَبَّ ٱلْعَٰلَمِينَ',
        english: 'Indeed, they are an enemy to me, except the Lord of the worlds,',
        turkish: 'Şüphesiz onlar benim düşmanımdır; ancak âlemlerin Rabbi hariç,',
        source: 'Qur\'an 26:77',
        highlight: { english: 'enemy', turkish: 'düşmanımdır' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عدو',
        forms: [
          { label: 'plural', arabic: 'أَعْدَاء' },
        ],
        occurrences: 50,
        occurringForm: 'عَدُوٌّ',
      },
    },
    {
      id: 'mawt',
      arabic: 'مَوْت',
      english: 'death',
      turkish: 'ölüm',
      example: {
        arabic: 'ثُمَّ بَعَثْنَٰكُم مِّنۢ بَعْدِ مَوْتِكُمْ لَعَلَّكُمْ تَشْكُرُونَ',
        english: 'Then We raised you up after your death, so that you might be grateful.',
        turkish: 'Sonra, şükredesiniz diye ölümünüzün ardından sizi dirilttik.',
        source: 'Qur\'an 2:56',
        highlight: { english: 'death', turkish: 'ölümünüzün' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'موت',
        occurrences: 50,
        occurringForm: 'مَوْتِكُمْ',
      },
    },
    {
      id: 'nima',
      arabic: 'نِعْمَة',
      english: 'blessing, favor',
      turkish: 'nimet, lütuf',
      example: {
        arabic: 'وَمَا لِأَحَدٍ عِندَهُۥ مِن نِّعْمَةٍۢ تُجْزَىٰٓ',
        english: 'And no one has with him a favor to be repaid,',
        turkish: 'Onun yanında hiç kimsenin karşılığı verilecek bir nimeti yoktur,',
        source: 'Qur\'an 92:19',
        highlight: { english: 'favor', turkish: 'nimeti' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نعم',
        forms: [
          { label: 'plural', arabic: 'نِعَم' },
        ],
        occurrences: 50,
        occurringForm: 'نِّعْمَةٍ',
      },
    },
    {
      id: 'alam-2',
      arabic: 'أَعْلَم',
      english: 'most knowing, best aware',
      turkish: 'en iyi bilen',
      example: {
        arabic: 'وَٱللَّهُ أَعْلَمُ بِمَا يُوعُونَ',
        english: 'And Allah is most knowing of what they keep within.',
        turkish: 'Allah, onların içlerinde sakladıklarını en iyi bilendir.',
        source: 'Qur\'an 84:23',
        highlight: { english: 'most knowing', turkish: 'en iyi bilendir' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'علم',
        occurrences: 49,
        occurringForm: 'أَعْلَمُ',
      },
    },
    {
      id: 'zada',
      arabic: 'زادَ',
      english: 'to increase, to add',
      turkish: 'artırmak, çoğaltmak',
      example: {
        arabic: 'ثُمَّ يَطْمَعُ أَنْ أَزِيدَ',
        english: 'Then he desires that I should add more.',
        turkish: 'Sonra daha da artırmamı umuyor.',
        source: 'Qur\'an 74:15',
        highlight: { english: 'add more', turkish: 'artırmamı' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'زيد',
        forms: [
          { label: 'mudari', arabic: 'يَزِيدُ' },
          { label: 'masdar', arabic: 'زِيَادَة' },
        ],
        occurrences: 49,
        occurringForm: 'أَزِيدَ',
      },
    },
    {
      id: 'aqala',
      arabic: 'عَقَلُ',
      english: 'to reason, to understand',
      turkish: 'akletmek, anlamak',
      example: {
        arabic: 'وَقَالُوا۟ لَوْ كُنَّا نَسْمَعُ أَوْ نَعْقِلُ مَا كُنَّا فِىٓ أَصْحَٰبِ ٱلسَّعِيرِ',
        english: 'And they will say: Had we listened or reasoned, we would not be among the companions of the Blaze.',
        turkish: 'Derler ki: Eğer dinleseydik yahut akletseydik, çılgın ateşin halkı arasında olmazdık.',
        source: 'Qur\'an 67:10',
        highlight: { english: 'reasoned', turkish: 'akletseydik' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عقل',
        forms: [
          { label: 'mudari', arabic: 'يَعْقِلُ' },
          { label: 'masdar', arabic: 'عَقْل' },
        ],
        occurrences: 49,
        occurringForm: 'نَعْقِلُ',
      },
    },
    {
      id: 'ghayb',
      arabic: 'غَيْب',
      english: 'the unseen, hidden',
      turkish: 'gayb, görünmeyen',
      example: {
        arabic: 'إِنَّ ٱللَّهَ عَٰلِمُ غَيْبِ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ ۚ إِنَّهُۥ عَلِيمٌۢ بِذَاتِ ٱلصُّدُورِ',
        english: 'Indeed, Allah is the Knower of the unseen of the heavens and the earth. Indeed, He knows what is within the breasts.',
        turkish: 'Şüphesiz Allah göklerin ve yerin gaybını bilendir. O, sinelerin özünü bilir.',
        source: 'Qur\'an 35:38',
        highlight: { english: 'the unseen', turkish: 'gaybını' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'غيب',
        forms: [
          { label: 'plural', arabic: 'غُيُوب' },
        ],
        occurrences: 49,
        occurringForm: 'غَيْبِ',
      },
    },
    {
      id: 'kataba',
      arabic: 'كَتَبَ',
      english: 'to write; to decree',
      turkish: 'yazmak; takdir etmek',
      example: {
        arabic: 'كَتَبَ ٱللَّهُ لَأَغْلِبَنَّ أَنَا۠ وَرُسُلِىٓ ۚ إِنَّ ٱللَّهَ قَوِىٌّ عَزِيزٌۭ',
        english: 'Allah has decreed: I and My messengers will surely prevail. Indeed, Allah is Strong and Mighty.',
        turkish: 'Allah yazdı: Elbette ben ve elçilerim galip geleceğiz. Şüphesiz Allah güçlüdür, üstündür.',
        source: 'Qur\'an 58:21',
        highlight: { english: 'has decreed', turkish: 'yazdı' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'كتب',
        forms: [
          { label: 'mudari', arabic: 'يَكْتُبُ' },
          { label: 'masdar', arabic: 'كِتَابَة' },
        ],
        occurrences: 49,
        occurringForm: 'كَتَبَ',
      },
    },
    {
      id: 'muttaqy',
      arabic: 'مُتَّقي',
      english: 'God-fearing one, righteous one',
      turkish: 'takva sahibi, sakınan',
      example: {
        arabic: 'إِنَّ ٱلْمُتَّقِينَ فِى جَنَّٰتٍۢ وَعُيُونٍ',
        english: 'Indeed, the righteous will be amid gardens and springs,',
        turkish: 'Şüphesiz takva sahipleri cennetlerde ve pınar başlarındadır,',
        source: 'Qur\'an 15:45',
        highlight: { english: 'the righteous', turkish: 'takva sahipleri' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'وقي',
        forms: [
          { label: 'plural', arabic: 'مُتَّقُون' },
        ],
        occurrences: 49,
        occurringForm: 'ٱلْمُتَّقِينَ',
      },
    },
    {
      id: 'wad',
      arabic: 'وَعْد',
      english: 'promise',
      turkish: 'vaat, söz',
      example: {
        arabic: 'وَيَقُولُونَ سُبْحَٰنَ رَبِّنَآ إِن كَانَ وَعْدُ رَبِّنَا لَمَفْعُولًۭا',
        english: 'And they say: Glory to our Lord! Indeed, the promise of our Lord is surely fulfilled.',
        turkish: 'Ve derler ki: Rabbimiz yücedir; Rabbimizin vaadi mutlaka gerçekleşir.',
        source: 'Qur\'an 17:108',
        highlight: { english: 'promise', turkish: 'vaadi' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'وعد',
        forms: [
          { label: 'plural', arabic: 'وُعُود' },
        ],
        occurrences: 49,
        occurringForm: 'وَعْدُ',
      },
    },
    {
      id: 'basar',
      arabic: 'بَصَر',
      english: 'sight, vision; eye',
      turkish: 'basar, görme; göz',
      example: {
        arabic: 'أَبْصَٰرُهَا خَٰشِعَةٌۭ',
        english: 'their eyes humbled.',
        turkish: 'gözleri korkuyla eğilmiştir.',
        source: 'Qur\'an 79:9',
        highlight: { english: 'eyes', turkish: 'gözleri' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بصر',
        forms: [
          { label: 'plural', arabic: 'أَبْصَار' },
        ],
        occurrences: 48,
        occurringForm: 'أَبْصَٰرُهَا',
      },
    },
    {
      id: 'dar',
      arabic: 'دار',
      english: 'house, abode, dwelling',
      turkish: 'ev, yurt, diyar',
      example: {
        arabic: '۞ لَهُمْ دَارُ ٱلسَّلَٰمِ عِندَ رَبِّهِمْ ۖ وَهُوَ وَلِيُّهُم بِمَا كَانُوا۟ يَعْمَلُونَ',
        english: 'For them is the abode of peace with their Lord, and He is their protector because of what they used to do.',
        turkish: 'Rableri katında onlar için esenlik yurdu vardır ve yaptıkları işler sebebiyle O, onların dostudur.',
        source: 'Qur\'an 6:127',
        highlight: { english: 'abode', turkish: 'yurdu' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'دور',
        forms: [
          { label: 'plural', arabic: 'دِيَار' },
        ],
        occurrences: 48,
        occurringForm: 'دَارُ',
      },
    },
    {
      id: 'saa',
      arabic: 'ساعَة',
      english: 'hour, moment; the Hour',
      turkish: 'saat, an; kıyamet',
      example: {
        arabic: 'قُل لَّكُم مِّيعَادُ يَوْمٍۢ لَّا تَسْتَـْٔخِرُونَ عَنْهُ سَاعَةًۭ وَلَا تَسْتَقْدِمُونَ',
        english: 'Say: You have an appointment of a Day which you cannot delay by an hour, nor bring forward.',
        turkish: 'De ki: Sizin için belirlenmiş bir gün vardır; ondan ne bir saat geri kalırsınız ne de öne geçersiniz.',
        source: 'Qur\'an 34:30',
        highlight: { english: 'an hour', turkish: 'saat' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سوع',
        forms: [
          { label: 'plural', arabic: 'سَاعَات' },
        ],
        occurrences: 48,
        occurringForm: 'سَاعَةً',
      },
    },
    {
      id: 'mulk',
      arabic: 'مُلْك',
      english: 'dominion, sovereignty, kingdom',
      turkish: 'mülk, egemenlik',
      example: {
        arabic: 'وَلِلَّهِ مُلْكُ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ ۖ وَإِلَى ٱللَّهِ ٱلْمَصِيرُ',
        english: 'And to Allah belongs the dominion of the heavens and the earth, and to Allah is the destination.',
        turkish: 'Göklerin ve yerin mülkü Allah\'ındır; dönüş de Allah\'adır.',
        source: 'Qur\'an 24:42',
        highlight: { english: 'dominion', turkish: 'mülkü' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ملك',
        occurrences: 48,
        occurringForm: 'مُلْكُ',
      },
    },
    {
      id: 'samiy',
      arabic: 'سَمِيع',
      english: 'hearing, all-hearing',
      turkish: 'semî, işiten',
      example: {
        arabic: 'وَإِنْ عَزَمُوا۟ ٱلطَّلَٰقَ فَإِنَّ ٱللَّهَ سَمِيعٌ عَلِيمٌۭ',
        english: 'And if they resolve on divorce, then indeed Allah is Hearing and Knowing.',
        turkish: 'Eğer boşanmaya karar verirlerse, şüphesiz Allah semîdir, alîmdir.',
        source: 'Qur\'an 2:227',
        highlight: { english: 'Hearing', turkish: 'semî' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سمع',
        occurrences: 47,
        occurringForm: 'سَمِيعٌ',
      },
    },
    {
      id: 'zanna',
      arabic: 'ظَنَّ',
      english: 'to think, to suppose',
      turkish: 'sanmak, zannetmek',
      example: {
        arabic: 'أَلَا يَظُنُّ أُو۟لَٰٓئِكَ أَنَّهُم مَّبْعُوثُونَ',
        english: 'Do those not think that they will be resurrected',
        turkish: 'Onlar diriltileceklerini sanmıyorlar mı',
        source: 'Qur\'an 83:4',
        highlight: { english: 'think', turkish: 'sanmıyorlar' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ظنن',
        forms: [
          { label: 'mudari', arabic: 'يَظُنُّ' },
          { label: 'masdar', arabic: 'ظَنّ' },
        ],
        occurrences: 47,
        occurringForm: 'يَظُنُّ',
      },
    },
    {
      id: 'ab',
      arabic: 'أَب',
      english: 'father',
      turkish: 'baba',
      example: {
        arabic: 'تَبَّتْ يَدَآ أَبِى لَهَبٍۢ وَتَبَّ',
        english: 'May the hands of Abu Lahab perish, and may he perish.',
        turkish: 'Ebu Leheb\'in iki eli kurusun; kurudu da.',
        source: 'Qur\'an 111:1',
        highlight: { english: 'Abu', turkish: 'Ebu' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أبو',
        forms: [
          { label: 'plural', arabic: 'آبَاء' },
        ],
        occurrences: 46,
        occurringForm: 'أَبِى',
      },
    },
    {
      id: 'shakara',
      arabic: 'شَكَرَ',
      english: 'to thank, to be grateful',
      turkish: 'şükretmek',
      example: {
        arabic: 'نِّعْمَةًۭ مِّنْ عِندِنَا ۚ كَذَٰلِكَ نَجْزِى مَن شَكَرَ',
        english: 'as a favor from Us. Thus do We reward whoever is grateful.',
        turkish: 'Katımızdan bir nimet olarak. Şükredeni işte böyle ödüllendiririz.',
        source: 'Qur\'an 54:35',
        highlight: { english: 'is grateful', turkish: 'Şükredeni' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'شكر',
        forms: [
          { label: 'mudari', arabic: 'يَشْكُرُ' },
          { label: 'masdar', arabic: 'شُكْر' },
        ],
        occurrences: 46,
        occurringForm: 'شَكَرَ',
      },
    },
    {
      id: 'nabbaa',
      arabic: 'نَبَّأَ',
      english: 'to inform, to tell',
      turkish: 'haber vermek, bildirmek',
      example: {
        arabic: '۞ نَبِّئْ عِبَادِىٓ أَنِّىٓ أَنَا ٱلْغَفُورُ ٱلرَّحِيمُ',
        english: 'Inform My servants that I am the Forgiving, the Merciful,',
        turkish: 'Kullarıma haber ver ki, ben çok bağışlayanım, çok merhamet edenim,',
        source: 'Qur\'an 15:49',
        highlight: { english: 'Inform', turkish: 'haber ver' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نبأ',
        forms: [
          { label: 'mudari', arabic: 'يُنَبِّئُ' },
        ],
        occurrences: 46,
        occurringForm: 'نَبِّئْ',
      },
    },
    {
      id: 'iyman',
      arabic: 'إِيمان',
      english: 'faith, belief',
      turkish: 'iman, inanç',
      example: {
        arabic: 'ٱلَّذِينَ ءَامَنُوا۟ وَلَمْ يَلْبِسُوٓا۟ إِيمَٰنَهُم بِظُلْمٍ أُو۟لَٰٓئِكَ لَهُمُ ٱلْأَمْنُ وَهُم مُّهْتَدُونَ',
        english: 'Those who believed and did not mix their faith with wrongdoing, for them is security, and they are the rightly guided.',
        turkish: 'İman edip imanlarına zulüm karıştırmayanlar var ya, güven onlarındır ve doğru yolu bulanlar da onlardır.',
        source: 'Qur\'an 6:82',
        highlight: { english: 'faith', turkish: 'imanlarına' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أمن',
        occurrences: 45,
        occurringForm: 'إِيمَٰنَهُم',
      },
    },
    {
      id: 'hakama',
      arabic: 'حَكَمَ',
      english: 'to judge, to rule',
      turkish: 'hükmetmek, karar vermek',
      example: {
        arabic: 'ٱللَّهُ يَحْكُمُ بَيْنَكُمْ يَوْمَ ٱلْقِيَٰمَةِ فِيمَا كُنتُمْ فِيهِ تَخْتَلِفُونَ',
        english: 'Allah will judge between you on the Day of Resurrection concerning that over which you used to differ.',
        turkish: 'Ayrılığa düştüğünüz konularda Allah, kıyamet günü aranızda hüküm verecektir.',
        source: 'Qur\'an 22:69',
        highlight: { english: 'judge', turkish: 'hüküm verecektir' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حكم',
        forms: [
          { label: 'mudari', arabic: 'يَحْكُمُ' },
          { label: 'masdar', arabic: 'حُكْم' },
        ],
        occurrences: 45,
        occurringForm: 'يَحْكُمُ',
      },
    },
    {
      id: 'khabiyr',
      arabic: 'خَبِير',
      english: 'aware, well-informed',
      turkish: 'haberdar, her şeyden haberi olan',
      example: {
        arabic: 'الٓر ۚ كِتَٰبٌ أُحْكِمَتْ ءَايَٰتُهُۥ ثُمَّ فُصِّلَتْ مِن لَّدُنْ حَكِيمٍ خَبِيرٍ',
        english: 'Alif Lam Ra. A Book whose verses were made firm and then explained in detail, from One Wise and Aware.',
        turkish: 'Elif Lâm Râ. Ayetleri sağlamlaştırılmış, sonra hikmet sahibi ve her şeyden haberdar olan tarafından açıklanmış bir kitaptır.',
        source: 'Qur\'an 11:1',
        highlight: { english: 'Aware', turkish: 'haberdar' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'خبر',
        occurrences: 45,
        occurringForm: 'خَبِيرٍ',
      },
    },
    {
      id: 'sirat',
      arabic: 'صِراط',
      english: 'path, way',
      turkish: 'sırat, yol',
      example: {
        arabic: 'وَلَهَدَيْنَٰهُمْ صِرَٰطًۭا مُّسْتَقِيمًۭا',
        english: 'And We would have guided them to a straight path.',
        turkish: 'Ve onları elbette dosdoğru bir sırata iletirdik.',
        source: 'Qur\'an 4:68',
        highlight: { english: 'path', turkish: 'sırat' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صرط',
        occurrences: 45,
        occurringForm: 'صِرَٰطًا',
      },
    },
    {
      id: 'qadiyr',
      arabic: 'قَدِير',
      english: 'powerful, able',
      turkish: 'kadir, güç yetiren',
      example: {
        arabic: 'إِلَى ٱللَّهِ مَرْجِعُكُمْ ۖ وَهُوَ عَلَىٰ كُلِّ شَىْءٍۢ قَدِيرٌ',
        english: 'To Allah is your return, and He is over all things competent.',
        turkish: 'Dönüşünüz Allah\'adır; O her şeye kadirdir.',
        source: 'Qur\'an 11:4',
        highlight: { english: 'competent', turkish: 'kadirdir' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قدر',
        occurrences: 45,
        occurringForm: 'قَدِيرٌ',
      },
    },
    {
      id: 'yadhara',
      arabic: 'يَذَرَ',
      english: 'to leave, to leave behind',
      turkish: 'bırakmak, terk etmek',
      example: {
        arabic: 'لَا تُبْقِى وَلَا تَذَرُ',
        english: 'It spares nothing and leaves nothing.',
        turkish: 'Ne geriye bir şey komaz ne de bırakır.',
        source: 'Qur\'an 74:28',
        highlight: { english: 'leaves', turkish: 'bırakır' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'وذر',
        forms: [
          { label: 'mudari', arabic: 'يَذَرُ' },
        ],
        occurrences: 45,
        occurringForm: 'تَذَرُ',
      },
    },
    {
      id: 'andhara',
      arabic: 'أَنذَرَ',
      english: 'to warn',
      turkish: 'uyarmak',
      example: {
        arabic: 'لِتُنذِرَ قَوْمًۭا مَّآ أُنذِرَ ءَابَآؤُهُمْ فَهُمْ غَٰفِلُونَ',
        english: 'so that you may warn a people whose fathers were not warned, so they are heedless.',
        turkish: 'Babaları uyarılmamış bir kavmi uyarasın diye; onlar gafildirler.',
        source: 'Qur\'an 36:6',
        highlight: { english: 'may warn', turkish: 'uyarasın' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نذر',
        forms: [
          { label: 'mudari', arabic: 'يُنْذِرُ' },
          { label: 'masdar', arabic: 'إِنْذَار' },
        ],
        occurrences: 44,
        occurringForm: 'أُنذِرَ',
      },
    },
    {
      id: 'hasiba',
      arabic: 'حَسِبَ',
      english: 'to think, to reckon',
      turkish: 'sanmak, hesap etmek',
      example: {
        arabic: 'يَحْسَبُ أَنَّ مَالَهُۥٓ أَخْلَدَهُۥ',
        english: 'He thinks that his wealth will make him immortal.',
        turkish: 'Malının kendisini ebedi kılacağını sanır.',
        source: 'Qur\'an 104:3',
        highlight: { english: 'thinks', turkish: 'sanır' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حسب',
        forms: [
          { label: 'mudari', arabic: 'يَحْسَبُ' },
        ],
        occurrences: 44,
        occurringForm: 'يَحْسَبُ',
      },
    },
    {
      id: 'shahida',
      arabic: 'شَهِدَ',
      english: 'to witness, to testify',
      turkish: 'şahitlik etmek, tanık olmak',
      example: {
        arabic: 'يَوْمَ تَشْهَدُ عَلَيْهِمْ أَلْسِنَتُهُمْ وَأَيْدِيهِمْ وَأَرْجُلُهُم بِمَا كَانُوا۟ يَعْمَلُونَ',
        english: 'On the Day when their tongues, their hands and their feet will testify against them about what they used to do.',
        turkish: 'O gün dilleri, elleri ve ayakları yaptıkları şeyler hakkında aleyhlerine şahitlik eder.',
        source: 'Qur\'an 24:24',
        highlight: { english: 'testify', turkish: 'şahitlik eder' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'شهد',
        forms: [
          { label: 'mudari', arabic: 'يَشْهَدُ' },
          { label: 'masdar', arabic: 'شَهَادَة' },
        ],
        occurrences: 44,
        occurringForm: 'تَشْهَدُ',
      },
    },
    {
      id: 'sadr',
      arabic: 'صَدْر',
      english: 'chest, breast',
      turkish: 'göğüs, sine',
      example: {
        arabic: 'ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ',
        english: 'who whispers in the breasts of mankind,',
        turkish: 'o ki insanların göğüslerine vesvese verir,',
        source: 'Qur\'an 114:5',
        highlight: { english: 'breasts', turkish: 'göğüslerine' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صدر',
        forms: [
          { label: 'plural', arabic: 'صُدُور' },
        ],
        occurrences: 44,
        occurringForm: 'صُدُورِ',
      },
    },
    {
      id: 'mushrik',
      arabic: 'مُشْرِك',
      english: 'polytheist, one who associates partners with God',
      turkish: 'müşrik, ortak koşan',
      example: {
        arabic: 'وَمَا يُؤْمِنُ أَكْثَرُهُم بِٱللَّهِ إِلَّا وَهُم مُّشْرِكُونَ',
        english: 'And most of them do not believe in Allah except while they associate others with Him.',
        turkish: 'Onların çoğu, ancak ortak koşarak Allah\'a inanır.',
        source: 'Qur\'an 12:106',
        highlight: { english: 'associate others', turkish: 'ortak koşarak' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شرك',
        forms: [
          { label: 'plural', arabic: 'مُشْرِكُون' },
        ],
        occurrences: 44,
        occurringForm: 'مُّشْرِكُونَ',
      },
    },
    {
      id: 'malaka',
      arabic: 'مَلَكَتْ',
      english: 'to own, to possess; to have power over',
      turkish: 'sahip olmak, malik olmak',
      example: {
        arabic: 'قُلْ إِنِّى لَآ أَمْلِكُ لَكُمْ ضَرًّۭا وَلَا رَشَدًۭا',
        english: 'Say: Indeed, I hold no power over harm or right guidance for you.',
        turkish: 'De ki: Ben size ne bir zarar verebilirim ne de bir doğruluk.',
        source: 'Qur\'an 72:21',
        highlight: { english: 'hold no power', turkish: 'verebilirim' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ملك',
        forms: [
          { label: 'mudari', arabic: 'يَمْلِكُ' },
          { label: 'masdar', arabic: 'مِلْك' },
        ],
        occurrences: 44,
        occurringForm: 'أَمْلِكُ',
      },
    },
    {
      id: 'nadaa',
      arabic: 'نادَى',
      english: 'to call, to call out',
      turkish: 'seslenmek, çağırmak',
      example: {
        arabic: 'فَلَمَّآ أَتَىٰهَا نُودِىَ يَٰمُوسَىٰٓ',
        english: 'And when he came to it, he was called: O Musa!',
        turkish: 'Oraya geldiğinde kendisine seslenildi: Ey Musa!',
        source: 'Qur\'an 20:11',
        highlight: { english: 'was called', turkish: 'seslenildi' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ندي',
        forms: [
          { label: 'mudari', arabic: 'يُنَادِي' },
          { label: 'masdar', arabic: 'نِدَاء' },
        ],
        occurrences: 44,
        occurringForm: 'نُودِىَ',
      },
    },
    {
      id: 'israiyl',
      arabic: 'إِسْرائِيل',
      english: 'Israel (Jacob)',
      turkish: 'İsrail (Yakup)',
      example: {
        arabic: 'كَذَٰلِكَ وَأَوْرَثْنَٰهَا بَنِىٓ إِسْرَٰٓءِيلَ',
        english: 'Thus it was. And We made the Children of Israel inherit it.',
        turkish: 'İşte böyle. Ve onu İsrailoğullarına miras kıldık.',
        source: 'Qur\'an 26:59',
        highlight: { english: 'Israel', turkish: 'İsrail' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 43,
        occurringForm: 'إِسْرَٰٓءِيلَ',
      },
    },
    {
      id: 'hamd',
      arabic: 'حَمْد',
      english: 'praise',
      turkish: 'hamd, övgü',
      example: {
        arabic: 'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ',
        english: 'All praise is for Allah, Lord of the worlds.',
        turkish: 'Hamd, âlemlerin Rabbi olan Allah\'a mahsustur.',
        source: 'Qur\'an 1:2',
        highlight: { english: 'praise', turkish: 'Hamd' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حمد',
        occurrences: 43,
        occurringForm: 'ٱلْحَمْدُ',
      },
    },
    {
      id: 'nuwh',
      arabic: 'نُوح',
      english: 'Noah',
      turkish: 'Nuh',
      example: {
        arabic: 'كَذَّبَتْ قَوْمُ نُوحٍ ٱلْمُرْسَلِينَ',
        english: 'The people of Noah denied the messengers.',
        turkish: 'Nuh kavmi, gönderilen elçileri yalanladı.',
        source: 'Qur\'an 26:105',
        highlight: { english: 'Noah', turkish: 'Nuh' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 43,
        occurringForm: 'نُوحٍ',
      },
    },
    {
      id: 'nuwr',
      arabic: 'نُور',
      english: 'light',
      turkish: 'nur, ışık',
      example: {
        arabic: 'وَجَعَلَ ٱلْقَمَرَ فِيهِنَّ نُورًۭا وَجَعَلَ ٱلشَّمْسَ سِرَاجًۭا',
        english: 'And He made the moon in them a light and made the sun a lamp.',
        turkish: 'Ve orada ayı bir nur, güneşi de bir kandil yaptı.',
        source: 'Qur\'an 71:16',
        highlight: { english: 'a light', turkish: 'nur' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نور',
        forms: [
          { label: 'plural', arabic: 'أَنْوَار' },
        ],
        occurrences: 43,
        occurringForm: 'نُورًا',
      },
    },
  ],
}
