import type { DeckDef } from '../types'

// Quran Vocabulary, level 3. See GitHub issue #8.
//
// Scaffolded by scripts/generateVocab.ts and then authored by hand, as the
// earlier levels were.
//
// Several corpus lemmas here are a passive, an imperative or a mudari form
// rather than the dictionary headword; their note ids are renamed to the form
// a learner would look up (aqala, malaka, muttaqiy).
//
// DRAFT: verify every English meaning before memorizing it. Turkish is
// generated convenience text and stays draft - correct it on sight while
// studying.
//
// Locked until the previous level is mostly graduated; see quranVocabTrack.ts.

export const quranVocab3: DeckDef = {
  id: 'quran-vocab-3',
  name: 'Quran Vocabulary 3',
  nameArabic: 'مُفْرَدَاتُ الْقُرْآنِ ٣',
  description:
    'Frequency band 3 of the Quran vocabulary track, each word with an ayah where it occurs.',
  directions: ['ar-to-meaning'],
  newPerDay: 10,
  burySiblings: true,
  notes: [
    {
      id: 'baatha',
      arabic: 'بَعَثَ',
      english: 'to raise up, to send forth',
      turkish: 'diriltmek, göndermek',
      example: {
        arabic: 'وَسَلَٰمٌ عَلَيْهِ يَوْمَ وُلِدَ وَيَوْمَ يَمُوتُ وَيَوْمَ يُبْعَثُ حَيًّۭا',
        english: 'And peace be upon him the day he was born, the day he dies, and the day he is raised alive.',
        turkish: 'Doğduğu gün, öleceği gün ve diri olarak kaldırılacağı gün ona selam olsun.',
        source: 'Qur\'an 19:15',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بعث',
        forms: [
          { label: 'mudari', arabic: 'يَبْعَثُ' },
          { label: 'masdar', arabic: 'بَعْث' },
        ],
        occurrences: 52,
        occurringForm: 'يُبْعَثُ',
      },
    },
    {
      id: 'mujrim',
      arabic: 'مُجْرِم',
      english: 'criminal, guilty one',
      turkish: 'suçlu, günahkâr',
      example: {
        arabic: 'كُلُوا۟ وَتَمَتَّعُوا۟ قَلِيلًا إِنَّكُم مُّجْرِمُونَ',
        english: 'Eat and enjoy yourselves a little; indeed, you are criminals.',
        turkish: 'Yiyin, biraz faydalanın; şüphesiz siz suçlularsınız.',
        source: 'Qur\'an 77:46',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'جرم',
        forms: [
          { label: 'plural', arabic: 'مُجْرِمُون' },
        ],
        occurrences: 52,
        occurringForm: 'مُّجْرِمُونَ',
      },
    },
    {
      id: 'ahya',
      arabic: 'أَحْيا',
      english: 'to give life, to revive',
      turkish: 'diriltmek, hayat vermek',
      example: {
        arabic: 'هُوَ يُحْىِۦ وَيُمِيتُ وَإِلَيْهِ تُرْجَعُونَ',
        english: 'He gives life and causes death, and to Him you will be returned.',
        turkish: 'O diriltir ve öldürür; O’na döndürüleceksiniz.',
        source: 'Qur\'an 10:56',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حيي',
        forms: [
          { label: 'mudari', arabic: 'يُحْيِي' },
          { label: 'masdar', arabic: 'إِحْيَاء' },
        ],
        occurrences: 51,
        occurringForm: 'يُحْىِۦ',
      },
    },
    {
      id: 'ahlaka',
      arabic: 'أَهْلَكَ',
      english: 'to destroy',
      turkish: 'helâk etmek, yok etmek',
      example: {
        arabic: 'أَلَمْ نُهْلِكِ ٱلْأَوَّلِينَ',
        english: 'Did We not destroy the former peoples?',
        turkish: 'Biz öncekileri helâk etmedik mi?',
        source: 'Qur\'an 77:16',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'هلك',
        forms: [
          { label: 'mudari', arabic: 'يُهْلِكُ' },
          { label: 'masdar', arabic: 'إِهْلَاك' },
        ],
        occurrences: 51,
        occurringForm: 'نُهْلِكِ',
      },
    },
    {
      id: 'basiyr',
      arabic: 'بَصِير',
      english: 'all-seeing',
      turkish: 'her şeyi gören, basîr',
      example: {
        arabic: 'إِنَّكَ كُنتَ بِنَا بَصِيرًۭا',
        english: 'Indeed, You are of us ever seeing.',
        turkish: 'Şüphesiz sen bizi görmektesin.',
        source: 'Qur\'an 20:35',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بصر',
        occurrences: 51,
        occurringForm: 'بَصِيرًا',
      },
    },
    {
      id: 'taht',
      arabic: 'تَحْت',
      english: 'under, beneath',
      turkish: 'altında',
      example: {
        arabic: 'لَهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ وَمَا بَيْنَهُمَا وَمَا تَحْتَ ٱلثَّرَىٰ',
        english: 'To Him belongs what is in the heavens and what is on the earth and what is between them and what is under the soil.',
        turkish: 'Göklerdekiler, yerdekiler, ikisi arasındakiler ve toprağın altındakiler O’nundur.',
        source: 'Qur\'an 20:6',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'تحت',
        occurrences: 51,
        occurringForm: 'تَحْتَ',
      },
    },
    {
      id: 'tadhakkara',
      arabic: 'تَذَكَّرَ',
      english: 'to take heed, to be reminded',
      turkish: 'öğüt almak, düşünüp anlamak',
      example: {
        arabic: 'أَوْ يَذَّكَّرُ فَتَنفَعَهُ ٱلذِّكْرَىٰٓ',
        english: 'or be reminded, so the reminder would benefit him?',
        turkish: 'yahut öğüt alacak da o öğüt kendisine fayda verecekti?',
        source: 'Qur\'an 80:4',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ذكر',
        forms: [
          { label: 'mudari', arabic: 'يَتَذَكَّرُ' },
        ],
        occurrences: 51,
        occurringForm: 'يَذَّكَّرُ',
      },
    },
    {
      id: 'aftaraa',
      arabic: 'افْتَرَى',
      english: 'to fabricate, to invent a lie',
      turkish: 'iftira etmek, uydurmak',
      example: {
        arabic: 'فَمَنِ ٱفْتَرَىٰ عَلَى ٱللَّهِ ٱلْكَذِبَ مِنۢ بَعْدِ ذَٰلِكَ فَأُو۟لَٰٓئِكَ هُمُ ٱلظَّٰلِمُونَ',
        english: 'And whoever invents a lie about Allah after that — those are the wrongdoers.',
        turkish: 'Bundan sonra kim Allah’a karşı yalan uydurursa, işte onlar zalimlerdir.',
        source: 'Qur\'an 3:94',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'فري',
        forms: [
          { label: 'mudari', arabic: 'يَفْتَرِي' },
          { label: 'masdar', arabic: 'اِفْتِرَاء' },
        ],
        occurrences: 50,
        occurringForm: 'ٱفْتَرَىٰ',
      },
    },
    {
      id: 'suw',
      arabic: 'سُوء',
      english: 'evil, badness',
      turkish: 'kötülük, fenalık',
      example: {
        arabic: 'أُو۟لَٰٓئِكَ ٱلَّذِينَ لَهُمْ سُوٓءُ ٱلْعَذَابِ وَهُمْ فِى ٱلْءَاخِرَةِ هُمُ ٱلْأَخْسَرُونَ',
        english: 'Those are the ones for whom is the worst punishment, and in the Hereafter they are the greatest losers.',
        turkish: 'Azabın kötüsü onlaradır; ahirette de en çok ziyana uğrayanlar onlardır.',
        source: 'Qur\'an 27:5',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سوأ',
        occurrences: 50,
        occurringForm: 'سُوٓءُ',
      },
    },
    {
      id: 'aduww',
      arabic: 'عَدُوّ',
      english: 'enemy',
      turkish: 'düşman',
      example: {
        arabic: 'فَإِنَّهُمْ عَدُوٌّۭ لِّىٓ إِلَّا رَبَّ ٱلْعَٰلَمِينَ',
        english: 'Indeed, they are enemies to me, except the Lord of the worlds,',
        turkish: 'Şüphesiz onlar benim düşmanımdır; ancak âlemlerin Rabbi başka,',
        source: 'Qur\'an 26:77',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عدو',
        forms: [
          { label: 'plural', arabic: 'أَعْدَاء' },
        ],
        occurrences: 50,
        occurringForm: 'عَدُوٌّ',
      },
    },
    {
      id: 'mawt',
      arabic: 'مَوْت',
      english: 'death',
      turkish: 'ölüm',
      example: {
        arabic: 'ثُمَّ بَعَثْنَٰكُم مِّنۢ بَعْدِ مَوْتِكُمْ لَعَلَّكُمْ تَشْكُرُونَ',
        english: 'Then We revived you after your death that perhaps you would be grateful.',
        turkish: 'Sonra, şükredesiniz diye ölümünüzün ardından sizi dirilttik.',
        source: 'Qur\'an 2:56',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'موت',
        occurrences: 50,
        occurringForm: 'مَوْتِكُمْ',
      },
    },
    {
      id: 'nima',
      arabic: 'نِعْمَة',
      english: 'blessing, favour',
      turkish: 'nimet, lütuf',
      example: {
        arabic: 'وَمَا لِأَحَدٍ عِندَهُۥ مِن نِّعْمَةٍۢ تُجْزَىٰٓ',
        english: 'And not for anyone who has with him a favour to be repaid,',
        turkish: 'Onun yanında, karşılığı verilecek bir nimet de yoktur,',
        source: 'Qur\'an 92:19',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نعم',
        forms: [
          { label: 'plural', arabic: 'نِعَم' },
        ],
        occurrences: 50,
        occurringForm: 'نِّعْمَةٍ',
      },
    },
    {
      id: 'alam-2',
      arabic: 'أَعْلَم',
      english: 'most knowing, knows best',
      turkish: 'en iyi bilen',
      example: {
        arabic: 'وَٱللَّهُ أَعْلَمُ بِمَا يُوعُونَ',
        english: 'And Allah is most knowing of what they keep within themselves.',
        turkish: 'Allah, içlerinde sakladıklarını en iyi bilendir.',
        source: 'Qur\'an 84:23',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'علم',
        occurrences: 49,
        occurringForm: 'أَعْلَمُ',
      },
    },
    {
      id: 'zada',
      arabic: 'زادَ',
      english: 'to increase, to add',
      turkish: 'artırmak, çoğaltmak',
      example: {
        arabic: 'ثُمَّ يَطْمَعُ أَنْ أَزِيدَ',
        english: 'Then he wants that I should add more.',
        turkish: 'Sonra daha da artırmamı umuyor.',
        source: 'Qur\'an 74:15',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'زيد',
        forms: [
          { label: 'mudari', arabic: 'يَزِيدُ' },
          { label: 'masdar', arabic: 'زِيَادَة' },
        ],
        occurrences: 49,
        occurringForm: 'أَزِيدَ',
      },
    },
    {
      id: 'aqala',
      arabic: 'عَقَلُ',
      english: 'to reason, to use one’s mind',
      turkish: 'akletmek, aklını kullanmak',
      example: {
        arabic: 'وَقَالُوا۟ لَوْ كُنَّا نَسْمَعُ أَوْ نَعْقِلُ مَا كُنَّا فِىٓ أَصْحَٰبِ ٱلسَّعِيرِ',
        english: 'And they will say: If only we had listened or reasoned, we would not be among the companions of the Blaze.',
        turkish: 'Derler ki: Keşke dinleseydik yahut akletseydik, çılgın ateşin halkı arasında olmazdık.',
        source: 'Qur\'an 67:10',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عقل',
        forms: [
          { label: 'mudari', arabic: 'يَعْقِلُ' },
          { label: 'masdar', arabic: 'عَقْل' },
        ],
        occurrences: 49,
        occurringForm: 'نَعْقِلُ',
      },
    },
    {
      id: 'ghayb',
      arabic: 'غَيْب',
      english: 'the unseen',
      turkish: 'gayb, görünmeyen',
      example: {
        arabic: 'إِنَّ ٱللَّهَ عَٰلِمُ غَيْبِ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ ۚ إِنَّهُۥ عَلِيمٌۢ بِذَاتِ ٱلصُّدُورِ',
        english: 'Indeed, Allah is Knower of the unseen of the heavens and the earth. Indeed, He is Knowing of what is within the breasts.',
        turkish: 'Şüphesiz Allah göklerin ve yerin gaybını bilir. O, göğüslerin özünü bilendir.',
        source: 'Qur\'an 35:38',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'غيب',
        occurrences: 49,
        occurringForm: 'غَيْبِ',
      },
    },
    {
      id: 'kataba',
      arabic: 'كَتَبَ',
      english: 'to write; to decree',
      turkish: 'yazmak; farz kılmak',
      example: {
        arabic: 'كَتَبَ ٱللَّهُ لَأَغْلِبَنَّ أَنَا۠ وَرُسُلِىٓ ۚ إِنَّ ٱللَّهَ قَوِىٌّ عَزِيزٌۭ',
        english: 'Allah has decreed: I will surely prevail, I and My messengers. Indeed, Allah is Strong and Mighty.',
        turkish: 'Allah yazmıştır: Andolsun ben ve elçilerim galip geleceğiz. Şüphesiz Allah güçlüdür, üstündür.',
        source: 'Qur\'an 58:21',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'كتب',
        forms: [
          { label: 'mudari', arabic: 'يَكْتُبُ' },
          { label: 'masdar', arabic: 'كِتَابَة' },
        ],
        occurrences: 49,
        occurringForm: 'كَتَبَ',
      },
    },
    {
      id: 'muttaqiy',
      arabic: 'مُتَّقي',
      english: 'one who fears Allah, godfearing',
      turkish: 'takva sahibi, müttaki',
      example: {
        arabic: 'إِنَّ ٱلْمُتَّقِينَ فِى جَنَّٰتٍۢ وَعُيُونٍ',
        english: 'Indeed, the righteous will be within gardens and springs,',
        turkish: 'Şüphesiz takva sahipleri cennetlerde ve pınarlardadır,',
        source: 'Qur\'an 15:45',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'وقي',
        forms: [
          { label: 'plural', arabic: 'مُتَّقُون' },
        ],
        occurrences: 49,
        occurringForm: 'ٱلْمُتَّقِينَ',
      },
    },
    {
      id: 'wad',
      arabic: 'وَعْد',
      english: 'promise',
      turkish: 'vaat, söz',
      example: {
        arabic: 'وَيَقُولُونَ سُبْحَٰنَ رَبِّنَآ إِن كَانَ وَعْدُ رَبِّنَا لَمَفْعُولًۭا',
        english: 'and they say: Exalted is our Lord; the promise of our Lord has surely been fulfilled.',
        turkish: 'Derler ki: Rabbimizi tenzih ederiz; Rabbimizin vaadi mutlaka yerine gelir.',
        source: 'Qur\'an 17:108',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'وعد',
        occurrences: 49,
        occurringForm: 'وَعْدُ',
      },
    },
    {
      id: 'basar',
      arabic: 'بَصَر',
      english: 'sight, vision',
      turkish: 'göz, görme',
      example: {
        arabic: 'أَبْصَٰرُهَا خَٰشِعَةٌۭ',
        english: 'Their eyes humbled,',
        turkish: 'Gözleri korkudan eğilmiştir,',
        source: 'Qur\'an 79:9',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بصر',
        forms: [
          { label: 'plural', arabic: 'أَبْصَار' },
        ],
        occurrences: 48,
        occurringForm: 'أَبْصَٰرُهَا',
      },
    },
    {
      id: 'dar',
      arabic: 'دار',
      english: 'abode, home',
      turkish: 'yurt, ev',
      example: {
        arabic: '۞ لَهُمْ دَارُ ٱلسَّلَٰمِ عِندَ رَبِّهِمْ ۖ وَهُوَ وَلِيُّهُم بِمَا كَانُوا۟ يَعْمَلُونَ',
        english: 'For them will be the Home of Peace with their Lord, and He is their protector because of what they used to do.',
        turkish: 'Rableri katında selâm yurdu onlarındır; yaptıkları sebebiyle O, onların dostudur.',
        source: 'Qur\'an 6:127',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'دور',
        forms: [
          { label: 'plural', arabic: 'دِيَار' },
        ],
        occurrences: 48,
        occurringForm: 'دَارُ',
      },
    },
    {
      id: 'saa',
      arabic: 'ساعَة',
      english: 'hour; the Hour',
      turkish: 'saat; kıyamet saati',
      example: {
        arabic: 'قُل لَّكُم مِّيعَادُ يَوْمٍۢ لَّا تَسْتَـْٔخِرُونَ عَنْهُ سَاعَةًۭ وَلَا تَسْتَقْدِمُونَ',
        english: 'Say: For you is the appointment of a Day which you cannot delay by an hour, nor advance.',
        turkish: 'De ki: Sizin için bir gün belirlenmiştir; ondan bir saat geri de kalamazsınız, ileri de geçemezsiniz.',
        source: 'Qur\'an 34:30',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سوع',
        occurrences: 48,
        occurringForm: 'سَاعَةً',
      },
    },
    {
      id: 'samiy',
      arabic: 'سَمِيع',
      english: 'all-hearing',
      turkish: 'her şeyi işiten, semî',
      example: {
        arabic: 'وَإِنْ عَزَمُوا۟ ٱلطَّلَٰقَ فَإِنَّ ٱللَّهَ سَمِيعٌ عَلِيمٌۭ',
        english: 'And if they decide upon divorce, then indeed Allah is Hearing and Knowing.',
        turkish: 'Boşamaya karar verirlerse, şüphesiz Allah işitendir, bilendir.',
        source: 'Qur\'an 2:227',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سمع',
        occurrences: 47,
        occurringForm: 'سَمِيعٌ',
      },
    },
    {
      id: 'zanna',
      arabic: 'ظَنَّ',
      english: 'to think, to suppose',
      turkish: 'zannetmek, sanmak',
      example: {
        arabic: 'أَلَا يَظُنُّ أُو۟لَٰٓئِكَ أَنَّهُم مَّبْعُوثُونَ',
        english: 'Do they not think that they will be resurrected?',
        turkish: 'Onlar diriltileceklerini sanmıyorlar mı?',
        source: 'Qur\'an 83:4',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ظنن',
        forms: [
          { label: 'mudari', arabic: 'يَظُنُّ' },
          { label: 'masdar', arabic: 'ظَنّ' },
        ],
        occurrences: 47,
        occurringForm: 'يَظُنُّ',
      },
    },
    {
      id: 'ab',
      arabic: 'أَب',
      english: 'father',
      turkish: 'baba',
      example: {
        arabic: 'تَبَّتْ يَدَآ أَبِى لَهَبٍۢ وَتَبَّ',
        english: 'May the hands of Abu Lahab be ruined, and ruined is he.',
        turkish: 'Ebu Leheb’in elleri kurusun, kurudu da.',
        source: 'Qur\'an 111:1',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أبو',
        forms: [
          { label: 'plural', arabic: 'آبَاء' },
        ],
        occurrences: 46,
        occurringForm: 'أَبِى',
      },
    },
    {
      id: 'shakara',
      arabic: 'شَكَرَ',
      english: 'to give thanks',
      turkish: 'şükretmek',
      example: {
        arabic: 'نِّعْمَةًۭ مِّنْ عِندِنَا ۚ كَذَٰلِكَ نَجْزِى مَن شَكَرَ',
        english: 'as a favour from Us. Thus do We reward whoever is grateful.',
        turkish: 'Katımızdan bir nimet olarak. Şükredeni işte böyle mükâfatlandırırız.',
        source: 'Qur\'an 54:35',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'شكر',
        forms: [
          { label: 'mudari', arabic: 'يَشْكُرُ' },
          { label: 'masdar', arabic: 'شُكْر' },
        ],
        occurrences: 46,
        occurringForm: 'شَكَرَ',
      },
    },
    {
      id: 'nabbaa',
      arabic: 'نَبَّأَ',
      english: 'to inform, to tell',
      turkish: 'haber vermek, bildirmek',
      example: {
        arabic: '۞ نَبِّئْ عِبَادِىٓ أَنِّىٓ أَنَا ٱلْغَفُورُ ٱلرَّحِيمُ',
        english: 'Inform My servants that it is I who am the Forgiving, the Merciful,',
        turkish: 'Kullarıma haber ver ki, bağışlayan ve merhamet eden benim,',
        source: 'Qur\'an 15:49',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نبأ',
        forms: [
          { label: 'mudari', arabic: 'يُنَبِّئُ' },
        ],
        occurrences: 46,
        occurringForm: 'نَبِّئْ',
      },
    },
    {
      id: 'iyman',
      arabic: 'إِيمان',
      english: 'faith, belief',
      turkish: 'iman',
      example: {
        arabic: 'ٱلَّذِينَ ءَامَنُوا۟ وَلَمْ يَلْبِسُوٓا۟ إِيمَٰنَهُم بِظُلْمٍ أُو۟لَٰٓئِكَ لَهُمُ ٱلْأَمْنُ وَهُم مُّهْتَدُونَ',
        english: 'They who believed and did not mix their belief with injustice — those will have security, and they are rightly guided.',
        turkish: 'İman edip imanlarına zulüm karıştırmayanlar var ya, güven onlarındır ve doğru yolu bulanlar onlardır.',
        source: 'Qur\'an 6:82',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أمن',
        occurrences: 45,
        occurringForm: 'إِيمَٰنَهُم',
      },
    },
    {
      id: 'hakama',
      arabic: 'حَكَمَ',
      english: 'to judge, to rule',
      turkish: 'hükmetmek, karar vermek',
      example: {
        arabic: 'ٱللَّهُ يَحْكُمُ بَيْنَكُمْ يَوْمَ ٱلْقِيَٰمَةِ فِيمَا كُنتُمْ فِيهِ تَخْتَلِفُونَ',
        english: 'Allah will judge between you on the Day of Resurrection concerning that over which you used to differ.',
        turkish: 'Allah, ayrılığa düştüğünüz konularda kıyamet günü aranızda hükmedecektir.',
        source: 'Qur\'an 22:69',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حكم',
        forms: [
          { label: 'mudari', arabic: 'يَحْكُمُ' },
          { label: 'masdar', arabic: 'حُكْم' },
        ],
        occurrences: 45,
        occurringForm: 'يَحْكُمُ',
      },
    },
    {
      id: 'khabiyr',
      arabic: 'خَبِير',
      english: 'all-aware',
      turkish: 'her şeyden haberdar, habîr',
      example: {
        arabic: 'الٓر ۚ كِتَٰبٌ أُحْكِمَتْ ءَايَٰتُهُۥ ثُمَّ فُصِّلَتْ مِن لَّدُنْ حَكِيمٍ خَبِيرٍ',
        english: 'Alif Lam Ra. A Book whose verses are perfected and then detailed, from one Wise and Aware,',
        turkish: 'Elif Lâm Râ. Bu, ayetleri sağlamlaştırılmış, sonra hikmet sahibi ve her şeyden haberdar olan tarafından açıklanmış bir kitaptır,',
        source: 'Qur\'an 11:1',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'خبر',
        occurrences: 45,
        occurringForm: 'خَبِيرٍ',
      },
    },
    {
      id: 'sirat',
      arabic: 'صِراط',
      english: 'path, way',
      turkish: 'yol, sırat',
      example: {
        arabic: 'وَلَهَدَيْنَٰهُمْ صِرَٰطًۭا مُّسْتَقِيمًۭا',
        english: 'and We would have guided them to a straight path.',
        turkish: 've onları dosdoğru bir yola iletirdik.',
        source: 'Qur\'an 4:68',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صرط',
        occurrences: 45,
        occurringForm: 'صِرَٰطًا',
      },
    },
    {
      id: 'qadiyr',
      arabic: 'قَدِير',
      english: 'all-powerful, able',
      turkish: 'her şeye gücü yeten, kadîr',
      example: {
        arabic: 'إِلَى ٱللَّهِ مَرْجِعُكُمْ ۖ وَهُوَ عَلَىٰ كُلِّ شَىْءٍۢ قَدِيرٌ',
        english: 'To Allah is your return, and He is over all things competent.',
        turkish: 'Dönüşünüz Allah’adır; O’nun her şeye gücü yeter.',
        source: 'Qur\'an 11:4',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قدر',
        occurrences: 45,
        occurringForm: 'قَدِيرٌ',
      },
    },
    {
      id: 'yadhara',
      arabic: 'يَذَرَ',
      english: 'to leave, to forsake',
      turkish: 'bırakmak, terk etmek',
      example: {
        arabic: 'لَا تُبْقِى وَلَا تَذَرُ',
        english: 'It lets nothing remain and leaves nothing.',
        turkish: 'Ne bırakır ne de vazgeçer.',
        source: 'Qur\'an 74:28',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'وذر',
        occurrences: 45,
        occurringForm: 'تَذَرُ',
      },
    },
    {
      id: 'andhara',
      arabic: 'أَنذَرَ',
      english: 'to warn',
      turkish: 'uyarmak',
      example: {
        arabic: 'لِتُنذِرَ قَوْمًۭا مَّآ أُنذِرَ ءَابَآؤُهُمْ فَهُمْ غَٰفِلُونَ',
        english: 'that you may warn a people whose forefathers were not warned, so they are unaware.',
        turkish: 'Ataları uyarılmamış, bu yüzden gaflette olan bir kavmi uyarasın diye.',
        source: 'Qur\'an 36:6',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نذر',
        forms: [
          { label: 'mudari', arabic: 'يُنْذِرُ' },
          { label: 'masdar', arabic: 'إِنْذَار' },
        ],
        occurrences: 44,
        occurringForm: 'أُنذِرَ',
      },
    },
    {
      id: 'hasiba',
      arabic: 'حَسِبَ',
      english: 'to reckon, to think',
      turkish: 'saymak, zannetmek',
      example: {
        arabic: 'يَحْسَبُ أَنَّ مَالَهُۥٓ أَخْلَدَهُۥ',
        english: 'He thinks that his wealth will make him immortal.',
        turkish: 'Malının kendisini ebedi kılacağını sanır.',
        source: 'Qur\'an 104:3',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حسب',
        forms: [
          { label: 'mudari', arabic: 'يَحْسَبُ' },
        ],
        occurrences: 44,
        occurringForm: 'يَحْسَبُ',
      },
    },
    {
      id: 'shahida',
      arabic: 'شَهِدَ',
      english: 'to witness, to testify',
      turkish: 'şahit olmak, tanıklık etmek',
      example: {
        arabic: 'يَوْمَ تَشْهَدُ عَلَيْهِمْ أَلْسِنَتُهُمْ وَأَيْدِيهِمْ وَأَرْجُلُهُم بِمَا كَانُوا۟ يَعْمَلُونَ',
        english: 'On a Day when their tongues, their hands and their feet will bear witness against them as to what they used to do.',
        turkish: 'O gün dilleri, elleri ve ayakları yaptıklarına dair aleyhlerine şahitlik edecektir.',
        source: 'Qur\'an 24:24',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'شهد',
        forms: [
          { label: 'mudari', arabic: 'يَشْهَدُ' },
          { label: 'masdar', arabic: 'شَهَادَة' },
        ],
        occurrences: 44,
        occurringForm: 'تَشْهَدُ',
      },
    },
    {
      id: 'sadr',
      arabic: 'صَدْر',
      english: 'breast, chest',
      turkish: 'göğüs, sadr',
      example: {
        arabic: 'ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ',
        english: 'who whispers into the breasts of mankind,',
        turkish: 'O ki insanların göğüslerine vesvese verir,',
        source: 'Qur\'an 114:5',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صدر',
        forms: [
          { label: 'plural', arabic: 'صُدُور' },
        ],
        occurrences: 44,
        occurringForm: 'صُدُورِ',
      },
    },
    {
      id: 'mushrik',
      arabic: 'مُشْرِك',
      english: 'one who associates partners with Allah',
      turkish: 'müşrik, ortak koşan',
      example: {
        arabic: 'وَمَا يُؤْمِنُ أَكْثَرُهُم بِٱللَّهِ إِلَّا وَهُم مُّشْرِكُونَ',
        english: 'And most of them believe not in Allah except while they associate others with Him.',
        turkish: 'Onların çoğu, ortak koşmadan Allah’a inanmazlar.',
        source: 'Qur\'an 12:106',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شرك',
        forms: [
          { label: 'plural', arabic: 'مُشْرِكُون' },
        ],
        occurrences: 44,
        occurringForm: 'مُّشْرِكُونَ',
      },
    },
    {
      id: 'malaka',
      arabic: 'مَلَكَتْ',
      english: 'to own, to have power over',
      turkish: 'sahip olmak, güç yetirmek',
      example: {
        arabic: 'قُلْ إِنِّى لَآ أَمْلِكُ لَكُمْ ضَرًّۭا وَلَا رَشَدًۭا',
        english: 'Say: Indeed, I do not possess for you any harm or right direction.',
        turkish: 'De ki: Ben size ne bir zarar ne de bir doğruya ulaştırma gücüne sahibim.',
        source: 'Qur\'an 72:21',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ملك',
        forms: [
          { label: 'mudari', arabic: 'يَمْلِكُ' },
          { label: 'masdar', arabic: 'مُلْك' },
        ],
        occurrences: 44,
        occurringForm: 'أَمْلِكُ',
      },
    },
    {
      id: 'nadaa',
      arabic: 'نادَى',
      english: 'to call out',
      turkish: 'seslenmek, çağırmak',
      example: {
        arabic: 'فَلَمَّآ أَتَىٰهَا نُودِىَ يَٰمُوسَىٰٓ',
        english: 'And when he came to it, he was called: O Moses!',
        turkish: 'Oraya geldiğinde kendisine seslenildi: Ey Musa!',
        source: 'Qur\'an 20:11',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ندي',
        forms: [
          { label: 'mudari', arabic: 'يُنَادِي' },
          { label: 'masdar', arabic: 'نِدَاء' },
        ],
        occurrences: 44,
        occurringForm: 'نُودِىَ',
      },
    },
    {
      id: 'israiyl',
      arabic: 'إِسْرائِيل',
      english: 'Israel (in: the Children of Israel)',
      turkish: 'İsrail (İsrailoğulları’nda)',
      example: {
        arabic: 'كَذَٰلِكَ وَأَوْرَثْنَٰهَا بَنِىٓ إِسْرَٰٓءِيلَ',
        english: 'Thus. And We caused the Children of Israel to inherit it.',
        turkish: 'İşte böyle. Onu İsrailoğulları’na miras bıraktık.',
        source: 'Qur\'an 26:59',
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 43,
        occurringForm: 'إِسْرَٰٓءِيلَ',
      },
    },
    {
      id: 'hamd',
      arabic: 'حَمْد',
      english: 'praise',
      turkish: 'hamd, övgü',
      example: {
        arabic: 'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ',
        english: 'All praise is due to Allah, Lord of the worlds,',
        turkish: 'Hamd, âlemlerin Rabbi Allah’a mahsustur,',
        source: 'Qur\'an 1:2',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حمد',
        occurrences: 43,
        occurringForm: 'ٱلْحَمْدُ',
      },
    },
    {
      id: 'nuwh',
      arabic: 'نُوح',
      english: 'Noah',
      turkish: 'Nuh',
      example: {
        arabic: 'كَذَّبَتْ قَوْمُ نُوحٍ ٱلْمُرْسَلِينَ',
        english: 'The people of Noah denied the messengers,',
        turkish: 'Nuh kavmi peygamberleri yalanladı,',
        source: 'Qur\'an 26:105',
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 43,
        occurringForm: 'نُوحٍ',
      },
    },
    {
      id: 'nuwr',
      arabic: 'نُور',
      english: 'light',
      turkish: 'nur, ışık',
      example: {
        arabic: 'وَجَعَلَ ٱلْقَمَرَ فِيهِنَّ نُورًۭا وَجَعَلَ ٱلشَّمْسَ سِرَاجًۭا',
        english: 'And made the moon therein a light and made the sun a lamp?',
        turkish: 'Aralarında ayı bir nur, güneşi de bir kandil yaptı.',
        source: 'Qur\'an 71:16',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نور',
        occurrences: 43,
        occurringForm: 'نُورًا',
      },
    },
    {
      id: 'udkhila',
      arabic: 'أُدْخِلَ',
      english: 'to be admitted, to be brought in',
      turkish: 'sokulmak, alınmak',
      example: {
        arabic: 'أَيَطْمَعُ كُلُّ ٱمْرِئٍۢ مِّنْهُمْ أَن يُدْخَلَ جَنَّةَ نَعِيمٍۢ',
        english: 'Does every person among them aspire to enter a garden of pleasure?',
        turkish: 'Onlardan her biri nimet cennetine sokulmayı mı umuyor?',
        source: 'Qur\'an 70:38',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'دخل',
        occurrences: 42,
        occurringForm: 'يُدْخَلَ',
      },
    },
    {
      id: 'astataa',
      arabic: 'اسْتَطاعَ',
      english: 'to be able to',
      turkish: 'gücü yetmek, muktedir olmak',
      example: {
        arabic: 'قَالَ إِنَّكَ لَن تَسْتَطِيعَ مَعِىَ صَبْرًۭا',
        english: 'He said: Indeed, you will never be able to have patience with me.',
        turkish: 'Dedi ki: Sen benimle beraber sabretmeye asla güç yetiremezsin.',
        source: 'Qur\'an 18:67',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'طوع',
        forms: [
          { label: 'mudari', arabic: 'يَسْتَطِيعُ' },
        ],
        occurrences: 42,
        occurringForm: 'تَسْتَطِيعَ',
      },
    },
    {
      id: 'jaza',
      arabic: 'جَزاء',
      english: 'recompense, reward',
      turkish: 'karşılık, ceza, mükâfat',
      example: {
        arabic: 'جَزَآءًۭ وِفَاقًا',
        english: 'an appropriate recompense.',
        turkish: 'Yaptıklarına uygun bir karşılık olarak.',
        source: 'Qur\'an 78:26',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'جزي',
        occurrences: 42,
        occurringForm: 'جَزَآءً',
      },
    },
    {
      id: 'sabbaha',
      arabic: 'سَبَّحَ',
      english: 'to glorify, to exalt',
      turkish: 'tesbih etmek, yüceltmek',
      example: {
        arabic: 'سَبِّحِ ٱسْمَ رَبِّكَ ٱلْأَعْلَى',
        english: 'Exalt the name of your Lord, the Most High,',
        turkish: 'Yüce Rabbinin adını tesbih et,',
        source: 'Qur\'an 87:1',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سبح',
        forms: [
          { label: 'mudari', arabic: 'يُسَبِّحُ' },
          { label: 'masdar', arabic: 'تَسْبِيح' },
        ],
        occurrences: 42,
        occurringForm: 'سَبِّحِ',
      },
    },
    {
      id: 'salam',
      arabic: 'سَلام',
      english: 'peace',
      turkish: 'selam, barış',
      example: {
        arabic: 'سَلَٰمٌ عَلَىٰٓ إِبْرَٰهِيمَ',
        english: 'Peace upon Abraham.',
        turkish: 'İbrahim’e selam olsun.',
        source: 'Qur\'an 37:109',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سلم',
        occurrences: 42,
        occurringForm: 'سَلَٰمٌ',
      },
    },
    {
      id: 'sawf',
      arabic: 'سَوْف',
      english: 'will, shall (future)',
      turkish: '-ecek, -acak (gelecek edatı)',
      example: {
        arabic: 'كَلَّا سَوْفَ تَعْلَمُونَ',
        english: 'No! You are going to know.',
        turkish: 'Hayır! Yakında bileceksiniz.',
        source: 'Qur\'an 102:3',
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 42,
        occurringForm: 'سَوْفَ',
      },
    },
  ],
}
