import type { DeckDef } from '../types'

// Quran Vocabulary, level 3. See GitHub issue #8.
//
// Scaffolded by scripts/generateVocab.ts: the headword, root, occurrence count,
// ayah and citation come from the corpus and the canonical text. The meanings,
// principal parts and ayah translations were authored on top of that scaffold.
//
// Where the corpus lemmatizes a word to a passive, an imperative or a mudari
// that nobody looks up, the note id is the dictionary form while the headword
// stays as the corpus has it, since that is what the ayah shows.
//
// DRAFT: verify every English meaning before memorizing it. Turkish is
// convenience text and stays draft - correct it on sight while studying.
//
// Locked until the previous level is mostly graduated; see quranVocabTrack.ts.

export const quranVocab3: DeckDef = {
  id: 'quran-vocab-3',
  name: 'Quran Vocabulary 3',
  nameArabic: 'مُفْرَدَاتُ الْقُرْآنِ ٣',
  description:
    'Frequency band 3 of the Quran vocabulary track, each word with an ayah where it occurs.',
  directions: ['ar-to-meaning'],
  newPerDay: 10,
  burySiblings: true,
  notes: [
    {
      id: 'hal',
      arabic: 'هَل',
      english: 'is it? did? (question particle)',
      turkish: 'mi, mı (soru edatı)',
      example: {
        arabic: 'هَلْ أَتَىٰكَ حَدِيثُ مُوسَىٰٓ',
        english: 'Has the story of Moses reached you?',
        turkish: 'Musa\'nın haberi sana geldi mi?',
        source: 'Qur\'an 79:15',
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 93,
        occurringForm: 'هَلْ',
      },
    },
    {
      id: 'diyn',
      arabic: 'دِين',
      english: 'religion; judgment, recompense',
      turkish: 'din; hüküm, ceza',
      example: {
        arabic: 'وَرَأَيْتَ ٱلنَّاسَ يَدْخُلُونَ فِى دِينِ ٱللَّهِ أَفْوَاجًۭا',
        english: 'and you see the people entering into the religion of Allah in crowds,',
        turkish: 've insanların bölük bölük Allah\'ın dinine girdiklerini gördüğünde,',
        source: 'Qur\'an 110:2',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'دين',
        forms: [
          { label: 'plural', arabic: 'أَدْيَان' },
        ],
        occurrences: 92,
        occurringForm: 'دِينِ',
      },
    },
    {
      id: 'qawl',
      arabic: 'قَوْل',
      english: 'word, speech, saying',
      turkish: 'söz, kelam',
      example: {
        arabic: 'إِنَّكُمْ لَفِى قَوْلٍۢ مُّخْتَلِفٍۢ',
        english: 'Indeed, you are in differing speech.',
        turkish: 'Şüphesiz siz çelişkili bir söz içindesiniz.',
        source: 'Qur\'an 51:8',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قول',
        forms: [
          { label: 'plural', arabic: 'أَقْوَال' },
        ],
        occurrences: 92,
        occurringForm: 'قَوْلٍ',
      },
    },
    {
      id: 'ghafuwr',
      arabic: 'غَفُور',
      english: 'forgiving, ever-forgiving',
      turkish: 'bağışlayan, çok affedici',
      example: {
        arabic: 'نُزُلًۭا مِّنْ غَفُورٍۢ رَّحِيمٍۢ',
        english: 'an accommodation from a Forgiving, Merciful One.',
        turkish: 'Çok bağışlayan, çok merhamet eden tarafından bir ağırlama olarak.',
        source: 'Qur\'an 41:32',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'غفر',
        occurrences: 91,
        occurringForm: 'غَفُورٍ',
      },
    },
    {
      id: 'laysa',
      arabic: 'لَيْسَ',
      english: 'not to be, is not',
      turkish: 'değildir, yoktur',
      example: {
        arabic: 'لَيْسَ لِوَقْعَتِهَا كَاذِبَةٌ',
        english: 'There is no denying its occurrence.',
        turkish: 'Onun gerçekleşmesini yalanlayacak hiçbir şey yoktur.',
        source: 'Qur\'an 56:2',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ليس',
        occurrences: 89,
        occurringForm: 'لَيْسَ',
      },
    },
    {
      id: 'shaytan',
      arabic: 'شَيْطان',
      english: 'devil, satan',
      turkish: 'şeytan',
      example: {
        arabic: 'وَمَا هُوَ بِقَوْلِ شَيْطَٰنٍۢ رَّجِيمٍۢ',
        english: 'And it is not the word of an accursed devil.',
        turkish: 'O, kovulmuş bir şeytanın sözü değildir.',
        source: 'Qur\'an 81:25',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شطن',
        forms: [
          { label: 'plural', arabic: 'شَيَاطِين' },
        ],
        occurrences: 88,
        occurringForm: 'شَيْطَٰنٍ',
      },
    },
    {
      id: 'faala',
      arabic: 'فَعَلَ',
      english: 'to do, to act',
      turkish: 'yapmak, işlemek',
      example: {
        arabic: 'كَذَٰلِكَ نَفْعَلُ بِٱلْمُجْرِمِينَ',
        english: 'Thus do We deal with the criminals.',
        turkish: 'İşte biz suçlulara böyle yaparız.',
        source: 'Qur\'an 77:18',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'فعل',
        forms: [
          { label: 'mudari', arabic: 'يَفْعَلُ' },
          { label: 'masdar', arabic: 'فِعْل' },
        ],
        occurrences: 88,
        occurringForm: 'نَفْعَلُ',
      },
    },
    {
      id: 'mathal',
      arabic: 'مَثَل',
      english: 'example, parable, likeness',
      turkish: 'örnek, misal, benzetme',
      example: {
        arabic: 'فَأَهْلَكْنَآ أَشَدَّ مِنْهُم بَطْشًۭا وَمَضَىٰ مَثَلُ ٱلْأَوَّلِينَ',
        english: 'So We destroyed those stronger than them in power, and the example of the former peoples has passed on.',
        turkish: 'Biz onlardan daha güçlü olanları helak ettik; öncekilerin örneği geçti.',
        source: 'Qur\'an 43:8',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'مثل',
        forms: [
          { label: 'plural', arabic: 'أَمْثَال' },
        ],
        occurrences: 88,
        occurringForm: 'مَثَلُ',
      },
    },
    {
      id: 'malak',
      arabic: 'مَلَك',
      english: 'angel',
      turkish: 'melek',
      example: {
        arabic: 'وَلَوْ نَشَآءُ لَجَعَلْنَا مِنكُم مَّلَٰٓئِكَةًۭ فِى ٱلْأَرْضِ يَخْلُفُونَ',
        english: 'And if We willed, We could have made from among you angels on the earth, succeeding one another.',
        turkish: 'Dileseydik, sizden yeryüzünde birbiri ardınca gelen melekler yapardık.',
        source: 'Qur\'an 43:60',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ملك',
        forms: [
          { label: 'plural', arabic: 'مَلَائِكَة' },
        ],
        occurrences: 88,
        occurringForm: 'مَّلَٰٓئِكَةً',
      },
    },
    {
      id: 'nazara',
      arabic: 'نَظَرَ',
      english: 'to look, to consider',
      turkish: 'bakmak, düşünmek',
      example: {
        arabic: 'ثُمَّ نَظَرَ',
        english: 'Then he considered.',
        turkish: 'Sonra düşündü.',
        source: 'Qur\'an 74:21',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نظر',
        forms: [
          { label: 'mudari', arabic: 'يَنْظُرُ' },
          { label: 'masdar', arabic: 'نَظَر' },
        ],
        occurrences: 87,
        occurringForm: 'نَظَرَ',
      },
    },
    {
      id: 'mal',
      arabic: 'مال',
      english: 'wealth, property',
      turkish: 'mal, servet',
      example: {
        arabic: 'يَقُولُ أَهْلَكْتُ مَالًۭا لُّبَدًا',
        english: 'He says: I have squandered abundant wealth.',
        turkish: 'Yığınla mal harcadım, diyor.',
        source: 'Qur\'an 90:6',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'مول',
        forms: [
          { label: 'plural', arabic: 'أَمْوَال' },
        ],
        occurrences: 86,
        occurringForm: 'مَالًا',
      },
    },
    {
      id: 'waliyy',
      arabic: 'وَلِيّ',
      english: 'protector, ally, friend',
      turkish: 'veli, dost, koruyucu',
      example: {
        arabic: 'خَٰلِدِينَ فِيهَآ أَبَدًۭا ۖ لَّا يَجِدُونَ وَلِيًّۭا وَلَا نَصِيرًۭا',
        english: 'abiding therein forever; they will find no protector and no helper.',
        turkish: 'Orada ebedî kalıcıdırlar; ne bir dost ne de bir yardımcı bulurlar.',
        source: 'Qur\'an 33:65',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ولي',
        forms: [
          { label: 'plural', arabic: 'أَوْلِيَاء' },
        ],
        occurrences: 86,
        occurringForm: 'وَلِيًّا',
      },
    },
    {
      id: 'hudana',
      arabic: 'هُدًى',
      english: 'guidance',
      turkish: 'hidayet, yol gösterme',
      example: {
        arabic: 'هُدًۭى وَبُشْرَىٰ لِلْمُؤْمِنِينَ',
        english: 'a guidance and good tidings for the believers,',
        turkish: 'müminler için bir hidayet ve müjde olarak,',
        source: 'Qur\'an 27:2',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'هدي',
        occurrences: 85,
        occurringForm: 'هُدًى',
      },
    },
    {
      id: 'dhakara',
      arabic: 'ذَكَرَ',
      english: 'to mention, to remember',
      turkish: 'anmak, zikretmek, hatırlamak',
      example: {
        arabic: 'فَكُلُوا۟ مِمَّا ذُكِرَ ٱسْمُ ٱللَّهِ عَلَيْهِ إِن كُنتُم بِـَٔايَٰتِهِۦ مُؤْمِنِينَ',
        english: 'So eat of that over which the name of Allah has been mentioned, if you are believers in His verses.',
        turkish: 'Ayetlerine inanıyorsanız, üzerine Allah\'ın adı anılan şeylerden yiyin.',
        source: 'Qur\'an 6:118',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ذكر',
        forms: [
          { label: 'mudari', arabic: 'يَذْكُرُ' },
          { label: 'masdar', arabic: 'ذِكْر' },
        ],
        occurrences: 84,
        occurringForm: 'ذُكِرَ',
      },
    },
    {
      id: 'fadl',
      arabic: 'فَضْل',
      english: 'bounty, favor, grace',
      turkish: 'lütuf, ihsan, fazl',
      example: {
        arabic: 'فَضْلًۭا مِّن رَّبِّكَ ۚ ذَٰلِكَ هُوَ ٱلْفَوْزُ ٱلْعَظِيمُ',
        english: 'As a bounty from your Lord. That is the great attainment.',
        turkish: 'Rabbinden bir lütuf olarak. İşte bu, büyük kurtuluştur.',
        source: 'Qur\'an 44:57',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'فضل',
        occurrences: 84,
        occurringForm: 'فَضْلًا',
      },
    },
    {
      id: 'layl',
      arabic: 'لَيْل',
      english: 'night',
      turkish: 'gece',
      example: {
        arabic: 'فَأَسْرِ بِعِبَادِى لَيْلًا إِنَّكُم مُّتَّبَعُونَ',
        english: 'So set out with My servants by night; indeed, you will be pursued.',
        turkish: 'Kullarımı geceleyin yürüt; şüphesiz siz takip edileceksiniz.',
        source: 'Qur\'an 44:23',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ليل',
        forms: [
          { label: 'plural', arabic: 'لَيَالٍ' },
        ],
        occurrences: 84,
        occurringForm: 'لَيْلًا',
      },
    },
    {
      id: 'khafa',
      arabic: 'خافَ',
      english: 'to fear',
      turkish: 'korkmak',
      example: {
        arabic: 'وَلَا يَخَافُ عُقْبَٰهَا',
        english: 'And He does not fear its consequence.',
        turkish: 'O, bunun sonucundan korkmaz.',
        source: 'Qur\'an 91:15',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'خوف',
        forms: [
          { label: 'mudari', arabic: 'يَخَافُ' },
          { label: 'masdar', arabic: 'خَوْف' },
        ],
        occurrences: 83,
        occurringForm: 'يَخَافُ',
      },
    },
    {
      id: 'sala',
      arabic: 'صَلاة',
      english: 'prayer; blessing',
      turkish: 'namaz, dua; salât, rahmet',
      example: {
        arabic: 'أُو۟لَٰٓئِكَ عَلَيْهِمْ صَلَوَٰتٌۭ مِّن رَّبِّهِمْ وَرَحْمَةٌۭ ۖ وَأُو۟لَٰٓئِكَ هُمُ ٱلْمُهْتَدُونَ',
        english: 'Those are the ones upon whom are blessings from their Lord and mercy, and it is those who are the rightly guided.',
        turkish: 'İşte Rablerinden bağışlamalar ve rahmet onlaradır; doğru yolu bulanlar da onlardır.',
        source: 'Qur\'an 2:157',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صلو',
        forms: [
          { label: 'plural', arabic: 'صَلَوَات' },
        ],
        occurrences: 83,
        occurringForm: 'صَلَوَٰتٌ',
      },
    },
    {
      id: 'qatala',
      arabic: 'قَتَلَ',
      english: 'to kill, to slay',
      turkish: 'öldürmek',
      example: {
        arabic: 'قُتِلَ ٱلْخَرَّٰصُونَ',
        english: 'Slain be the conjecturers,',
        turkish: 'Kahrolsun o yalan uyduranlar,',
        source: 'Qur\'an 51:10',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'قتل',
        forms: [
          { label: 'mudari', arabic: 'يَقْتُلُ' },
          { label: 'masdar', arabic: 'قَتْل' },
        ],
        occurrences: 83,
        occurringForm: 'قُتِلَ',
      },
    },
    {
      id: 'kayf',
      arabic: 'كَيْف',
      english: 'how',
      turkish: 'nasıl',
      example: {
        arabic: 'فَقُتِلَ كَيْفَ قَدَّرَ',
        english: 'So slain be he, how he plotted!',
        turkish: 'Kahrolası, nasıl da ölçüp biçti!',
        source: 'Qur\'an 74:19',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كيف',
        occurrences: 83,
        occurringForm: 'كَيْفَ',
      },
    },
    {
      id: 'awwal',
      arabic: 'أَوَّل',
      english: 'first, foremost',
      turkish: 'ilk, birinci',
      example: {
        arabic: 'وَأُمِرْتُ لِأَنْ أَكُونَ أَوَّلَ ٱلْمُسْلِمِينَ',
        english: 'And I have been commanded to be the first of the Muslims.',
        turkish: 'Ve bana Müslümanların ilki olmam emredildi.',
        source: 'Qur\'an 39:12',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أول',
        forms: [
          { label: 'plural', arabic: 'أَوَّلُونَ' },
        ],
        occurrences: 82,
        occurringForm: 'أَوَّلَ',
      },
    },
    {
      id: 'akthar',
      arabic: 'أَكْثَر',
      english: 'most, more, the majority',
      turkish: 'çoğu, daha çok',
      example: {
        arabic: 'وَلَقَدْ ضَلَّ قَبْلَهُمْ أَكْثَرُ ٱلْأَوَّلِينَ',
        english: 'And already most of the former peoples had gone astray before them.',
        turkish: 'Andolsun, onlardan önce evvelkilerin çoğu sapmıştı.',
        source: 'Qur\'an 37:71',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كثر',
        occurrences: 80,
        occurringForm: 'أَكْثَرُ',
      },
    },
    {
      id: 'bunaan',
      arabic: 'بُنَىّ',
      english: 'son; sons, children',
      turkish: 'oğul; oğullar, çocuklar',
      example: {
        arabic: 'كَذَٰلِكَ وَأَوْرَثْنَٰهَا بَنِىٓ إِسْرَٰٓءِيلَ',
        english: 'Thus. And We caused the Children of Israel to inherit it.',
        turkish: 'İşte böyle. Onu İsrailoğullarına miras kıldık.',
        source: 'Qur\'an 26:59',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بني',
        forms: [
          { label: 'plural', arabic: 'بَنُونَ' },
        ],
        occurrences: 80,
        occurringForm: 'بَنِىٓ',
      },
    },
    {
      id: 'rajaa',
      arabic: 'رَجَعَ',
      english: 'to return, to come back',
      turkish: 'dönmek, geri gelmek',
      example: {
        arabic: 'وَإِنِّى مُرْسِلَةٌ إِلَيْهِم بِهَدِيَّةٍۢ فَنَاظِرَةٌۢ بِمَ يَرْجِعُ ٱلْمُرْسَلُونَ',
        english: 'And indeed, I am going to send them a gift and see with what the envoys return.',
        turkish: 'Ben onlara bir hediye göndereceğim ve elçilerin ne ile döneceklerine bakacağım.',
        source: 'Qur\'an 27:35',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'رجع',
        forms: [
          { label: 'mudari', arabic: 'يَرْجِعُ' },
          { label: 'masdar', arabic: 'رُجُوع' },
        ],
        occurrences: 79,
        occurringForm: 'يَرْجِعُ',
      },
    },
    {
      id: 'ashab',
      arabic: 'أَصْحاب',
      english: 'companions, people of',
      turkish: 'arkadaşlar, ashab, sahipleri',
      example: {
        arabic: 'قُتِلَ أَصْحَٰبُ ٱلْأُخْدُودِ',
        english: 'Slain were the companions of the trench,',
        turkish: 'Kahrolsun o hendek halkı,',
        source: 'Qur\'an 85:4',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صحب',
        occurrences: 78,
        occurringForm: 'أَصْحَٰبُ',
      },
    },
    {
      id: 'tawallaa',
      arabic: 'تَوَلَّى',
      english: 'to turn away, to turn one\'s back',
      turkish: 'yüz çevirmek, sırt dönmek',
      example: {
        arabic: 'أَفَرَءَيْتَ ٱلَّذِى تَوَلَّىٰ',
        english: 'Have you seen the one who turned away,',
        turkish: 'Gördün mü o yüz çevireni,',
        source: 'Qur\'an 53:33',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ولي',
        forms: [
          { label: 'mudari', arabic: 'يَتَوَلَّى' },
          { label: 'masdar', arabic: 'تَوَلِّي' },
        ],
        occurrences: 78,
        occurringForm: 'تَوَلَّىٰ',
      },
    },
    {
      id: 'samia',
      arabic: 'سَمِعَ',
      english: 'to hear, to listen',
      turkish: 'işitmek, duymak',
      example: {
        arabic: 'لَّا تَسْمَعُ فِيهَا لَٰغِيَةًۭ',
        english: 'Wherein you will hear no vain talk.',
        turkish: 'Orada boş bir söz işitmezsin.',
        source: 'Qur\'an 88:11',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سمع',
        forms: [
          { label: 'mudari', arabic: 'يَسْمَعُ' },
          { label: 'masdar', arabic: 'سَمْع' },
        ],
        occurrences: 78,
        occurringForm: 'تَسْمَعُ',
      },
    },
    {
      id: 'amara',
      arabic: 'أَمَرَ',
      english: 'to command, to enjoin',
      turkish: 'emretmek, buyurmak',
      example: {
        arabic: 'أَوْ أَمَرَ بِٱلتَّقْوَىٰٓ',
        english: 'or enjoined righteousness?',
        turkish: 'yahut takvayı emrettiyse?',
        source: 'Qur\'an 96:12',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'أمر',
        forms: [
          { label: 'mudari', arabic: 'يَأْمُرُ' },
          { label: 'masdar', arabic: 'أَمْر' },
        ],
        occurrences: 77,
        occurringForm: 'أَمَرَ',
      },
    },
    {
      id: 'jahannam',
      arabic: 'جَهَنَّم',
      english: 'Hell',
      turkish: 'cehennem',
      example: {
        arabic: 'إِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًۭا',
        english: 'Indeed, Hell has been lying in wait,',
        turkish: 'Şüphesiz cehennem bir gözetleme yeridir,',
        source: 'Qur\'an 78:21',
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 77,
        occurringForm: 'جَهَنَّمَ',
      },
    },
    {
      id: 'haya',
      arabic: 'حَياة',
      english: 'life',
      turkish: 'hayat, yaşam',
      example: {
        arabic: 'وَلَكُمْ فِى ٱلْقِصَاصِ حَيَوٰةٌۭ يَٰٓأُو۟لِى ٱلْأَلْبَٰبِ لَعَلَّكُمْ تَتَّقُونَ',
        english: 'And there is for you in retribution life, O people of understanding, that you may become righteous.',
        turkish: 'Ey akıl sahipleri, kısasta sizin için hayat vardır; umulur ki sakınırsınız.',
        source: 'Qur\'an 2:179',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حيي',
        occurrences: 76,
        occurringForm: 'حَيَوٰةٌ',
      },
    },
    {
      id: 'dakhala',
      arabic: 'دَخَلَ',
      english: 'to enter',
      turkish: 'girmek',
      example: {
        arabic: 'قِيلَ ٱدْخُلِ ٱلْجَنَّةَ ۖ قَالَ يَٰلَيْتَ قَوْمِى يَعْلَمُونَ',
        english: 'It was said: Enter Paradise. He said: I wish my people knew,',
        turkish: 'Ona: Cennete gir, denildi. Dedi ki: Keşke kavmim bilseydi,',
        source: 'Qur\'an 36:26',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'دخل',
        forms: [
          { label: 'mudari', arabic: 'يَدْخُلُ' },
          { label: 'masdar', arabic: 'دُخُول' },
        ],
        occurrences: 76,
        occurringForm: 'ٱدْخُلِ',
      },
    },
    {
      id: 'dhikr',
      arabic: 'ذِكْر',
      english: 'remembrance, mention, reminder',
      turkish: 'zikir, anma, öğüt',
      example: {
        arabic: 'فَٱلتَّٰلِيَٰتِ ذِكْرًا',
        english: 'and those who recite a reminder,',
        turkish: 've zikir okuyanlara,',
        source: 'Qur\'an 37:3',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ذكر',
        forms: [
          { label: 'plural', arabic: 'أَذْكَار' },
        ],
        occurrences: 76,
        occurringForm: 'ذِكْرًا',
      },
    },
    {
      id: 'zawj',
      arabic: 'زَوْج',
      english: 'spouse, mate, pair',
      turkish: 'eş, çift',
      example: {
        arabic: 'وَخَلَقْنَٰكُمْ أَزْوَٰجًۭا',
        english: 'And We created you in pairs,',
        turkish: 'Sizi çift çift yarattık,',
        source: 'Qur\'an 78:8',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'زوج',
        forms: [
          { label: 'plural', arabic: 'أَزْوَاج' },
        ],
        occurrences: 76,
        occurringForm: 'أَزْوَٰجًا',
      },
    },
    {
      id: 'akh',
      arabic: 'أَخ',
      english: 'brother',
      turkish: 'kardeş',
      example: {
        arabic: 'إِنَّ ٱلْمُبَذِّرِينَ كَانُوٓا۟ إِخْوَٰنَ ٱلشَّيَٰطِينِ ۖ وَكَانَ ٱلشَّيْطَٰنُ لِرَبِّهِۦ كَفُورًۭا',
        english: 'Indeed, the squanderers are brothers of the devils, and the devil is ever ungrateful to his Lord.',
        turkish: 'Şüphesiz saçıp savuranlar şeytanların kardeşleridir; şeytan da Rabbine karşı çok nankördür.',
        source: 'Qur\'an 17:27',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أخو',
        forms: [
          { label: 'plural', arabic: 'إِخْوَة' },
        ],
        occurrences: 75,
        occurringForm: 'إِخْوَٰنَ',
      },
    },
    {
      id: 'lawla',
      arabic: 'لَوْلا',
      english: 'if not for, were it not for; why not (in reproach)',
      turkish: 'olmasaydı, -meseydi; neden ... -mez? (kınama)',
      example: {
        arabic: 'قَالَ أَوْسَطُهُمْ أَلَمْ أَقُل لَّكُمْ لَوْلَا تُسَبِّحُونَ',
        english: 'The most moderate of them said: Did I not say to you, why do you not glorify Him?',
        turkish: 'İçlerinden en insaflı olanı dedi ki: Ben size, tesbih etsenize, demedim mi?',
        source: 'Qur\'an 68:28',
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 75,
        occurringForm: 'لَوْلَا',
      },
    },
    {
      id: 'mithl',
      arabic: 'مِثْل',
      english: 'like, similar to; likeness',
      turkish: 'gibi, benzer; benzeri',
      example: {
        arabic: 'بَلْ قَالُوا۟ مِثْلَ مَا قَالَ ٱلْأَوَّلُونَ',
        english: 'Rather, they said the like of what the former peoples said.',
        turkish: 'Hayır, onlar da öncekilerin dediğinin benzerini dediler.',
        source: 'Qur\'an 23:81',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'مثل',
        forms: [
          { label: 'plural', arabic: 'أَمْثَال' },
        ],
        occurrences: 75,
        occurringForm: 'مِثْلَ',
      },
    },
    {
      id: 'nabiyy',
      arabic: 'نَبِيّ',
      english: 'prophet',
      turkish: 'peygamber, nebi',
      example: {
        arabic: 'وَبَشَّرْنَٰهُ بِإِسْحَٰقَ نَبِيًّۭا مِّنَ ٱلصَّٰلِحِينَ',
        english: 'And We gave him good tidings of Isaac, a prophet from among the righteous.',
        turkish: 'Ona, salihlerden bir peygamber olarak İshak\'ı müjdeledik.',
        source: 'Qur\'an 37:112',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نبأ',
        forms: [
          { label: 'plural', arabic: 'أَنْبِيَاء' },
        ],
        occurrences: 75,
        occurringForm: 'نَبِيًّا',
      },
    },
    {
      id: 'ahad',
      arabic: 'أَحَد',
      english: 'one, anyone, someone',
      turkish: 'bir, biri, hiç kimse',
      example: {
        arabic: 'وَلَا يُوثِقُ وَثَاقَهُۥٓ أَحَدٌۭ',
        english: 'And none will bind as He binds.',
        turkish: 'Onun bağladığı gibi kimse bağlayamaz.',
        source: 'Qur\'an 89:26',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أحد',
        occurrences: 74,
        occurringForm: 'أَحَدٌ',
      },
    },
    {
      id: 'khalid',
      arabic: 'خالِد',
      english: 'abiding forever, everlasting',
      turkish: 'ebedî kalan, sürekli',
      example: {
        arabic: 'خَٰلِدِينَ فِيهَا ۚ حَسُنَتْ مُسْتَقَرًّۭا وَمُقَامًۭا',
        english: 'abiding therein forever. Good is it as a settlement and a residence.',
        turkish: 'Orada ebedî kalıcıdırlar. Ne güzel bir karargâh ve ne güzel bir konaktır.',
        source: 'Qur\'an 25:76',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'خلد',
        forms: [
          { label: 'plural', arabic: 'خَالِدُونَ' },
        ],
        occurrences: 74,
        occurringForm: 'خَٰلِدِينَ',
      },
    },
    {
      id: 'salih',
      arabic: 'صالِح',
      english: 'righteous, sound; Salih (the prophet)',
      turkish: 'salih, iyi, doğru; Salih (peygamber)',
      example: {
        arabic: 'إِذْ قَالَ لَهُمْ أَخُوهُمْ صَٰلِحٌ أَلَا تَتَّقُونَ',
        english: 'When their brother Salih said to them: Will you not fear Allah?',
        turkish: 'Kardeşleri Salih onlara demişti ki: Sakınmaz mısınız?',
        source: 'Qur\'an 26:142',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صلح',
        forms: [
          { label: 'plural', arabic: 'صَالِحُونَ' },
        ],
        occurrences: 74,
        occurringForm: 'صَٰلِحٌ',
      },
    },
    {
      id: 'firawn',
      arabic: 'فِرْعَوْن',
      english: 'Pharaoh',
      turkish: 'Firavun',
      example: {
        arabic: 'فِرْعَوْنَ وَثَمُودَ',
        english: 'Pharaoh and Thamud?',
        turkish: 'Firavun ve Semûd\'un?',
        source: 'Qur\'an 85:18',
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 74,
        occurringForm: 'فِرْعَوْنَ',
      },
    },
    {
      id: 'jazaa',
      arabic: 'جَزَى',
      english: 'to recompense, to repay, to reward',
      turkish: 'karşılığını vermek, mükâfatlandırmak',
      example: {
        arabic: 'كَذَٰلِكَ نَجْزِى ٱلْمُحْسِنِينَ',
        english: 'Thus do We reward the doers of good.',
        turkish: 'İşte biz iyilik edenleri böyle mükâfatlandırırız.',
        source: 'Qur\'an 37:110',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'جزي',
        forms: [
          { label: 'mudari', arabic: 'يَجْزِي' },
          { label: 'masdar', arabic: 'جَزَاء' },
        ],
        occurrences: 73,
        occurringForm: 'نَجْزِى',
      },
    },
    {
      id: 'alam',
      arabic: 'عالَم',
      english: 'world, realm',
      turkish: 'âlem, dünya',
      example: {
        arabic: 'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ',
        english: 'All praise is for Allah, Lord of the worlds,',
        turkish: 'Hamd, âlemlerin Rabbi Allah\'a mahsustur,',
        source: 'Qur\'an 1:2',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'علم',
        forms: [
          { label: 'plural', arabic: 'عَالَمُونَ' },
        ],
        occurrences: 73,
        occurringForm: 'ٱلْعَٰلَمِينَ',
      },
    },
    {
      id: 'ataa-2',
      arabic: 'أَطاعَ',
      english: 'to obey',
      turkish: 'itaat etmek, boyun eğmek',
      example: {
        arabic: 'فَلَا تُطِعِ ٱلْمُكَذِّبِينَ',
        english: 'So do not obey the deniers.',
        turkish: 'Öyleyse yalanlayanlara itaat etme.',
        source: 'Qur\'an 68:8',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'طوع',
        forms: [
          { label: 'mudari', arabic: 'يُطِيعُ' },
          { label: 'masdar', arabic: 'إِطَاعَة' },
        ],
        occurrences: 72,
        occurringForm: 'تُطِعِ',
      },
    },
    {
      id: 'aliym-2',
      arabic: 'أَلِيم',
      english: 'painful, agonizing',
      turkish: 'acı veren, elem verici',
      example: {
        arabic: 'فَبَشِّرْهُم بِعَذَابٍ أَلِيمٍ',
        english: 'So give them tidings of a painful punishment,',
        turkish: 'Onlara acı bir azabı müjdele,',
        source: 'Qur\'an 84:24',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ألم',
        occurrences: 72,
        occurringForm: 'أَلِيمٍ',
      },
    },
    {
      id: 'awhaa',
      arabic: 'أَوْحَى',
      english: 'to reveal, to inspire',
      turkish: 'vahyetmek, ilham etmek',
      example: {
        arabic: 'بِأَنَّ رَبَّكَ أَوْحَىٰ لَهَا',
        english: 'because your Lord has inspired it.',
        turkish: 'Çünkü Rabbin ona vahyetmiştir.',
        source: 'Qur\'an 99:5',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'وحي',
        forms: [
          { label: 'mudari', arabic: 'يُوحِي' },
          { label: 'masdar', arabic: 'إِيحَاء' },
        ],
        occurrences: 72,
        occurringForm: 'أَوْحَىٰ',
      },
    },
    {
      id: 'wajh',
      arabic: 'وَجْه',
      english: 'face',
      turkish: 'yüz, çehre',
      example: {
        arabic: 'وُجُوهٌۭ يَوْمَئِذٍۢ مُّسْفِرَةٌۭ',
        english: 'Some faces, that day, will be bright,',
        turkish: 'O gün birtakım yüzler parıldar,',
        source: 'Qur\'an 80:38',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'وجه',
        forms: [
          { label: 'plural', arabic: 'وُجُوه' },
        ],
        occurrences: 72,
        occurringForm: 'وُجُوهٌ',
      },
    },
    {
      id: 'ashraka',
      arabic: 'أَشْرَكَ',
      english: 'to associate partners with God',
      turkish: 'ortak koşmak, şirk koşmak',
      example: {
        arabic: 'لَّٰكِنَّا۠ هُوَ ٱللَّهُ رَبِّى وَلَآ أُشْرِكُ بِرَبِّىٓ أَحَدًۭا',
        english: 'But as for me, He is Allah, my Lord, and I do not associate anyone with my Lord.',
        turkish: 'Fakat ben derim ki: O Allah benim Rabbimdir ve ben Rabbime hiç kimseyi ortak koşmam.',
        source: 'Qur\'an 18:38',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'شرك',
        forms: [
          { label: 'mudari', arabic: 'يُشْرِكُ' },
          { label: 'masdar', arabic: 'إِشْرَاك' },
        ],
        occurrences: 71,
        occurringForm: 'أُشْرِكُ',
      },
    },
    {
      id: 'alqaa',
      arabic: 'أَلْقَى',
      english: 'to cast, to throw; to put forth, to present',
      turkish: 'atmak, bırakmak; ortaya koymak',
      example: {
        arabic: 'وَلَوْ أَلْقَىٰ مَعَاذِيرَهُۥ',
        english: 'even if he puts forth his excuses.',
        turkish: 'mazeretlerini ortaya dökse bile.',
        source: 'Qur\'an 75:15',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'لقي',
        forms: [
          { label: 'mudari', arabic: 'يُلْقِي' },
          { label: 'masdar', arabic: 'إِلْقَاء' },
        ],
        occurrences: 71,
        occurringForm: 'أَلْقَىٰ',
      },
    },
    {
      id: 'insan',
      arabic: 'إِنسان',
      english: 'man, human being',
      turkish: 'insan',
      example: {
        arabic: 'خَلَقَ ٱلْإِنسَٰنَ',
        english: 'He created man,',
        turkish: 'İnsanı yarattı,',
        source: 'Qur\'an 55:3',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أنس',
        occurrences: 71,
        occurringForm: 'ٱلْإِنسَٰنَ',
      },
    },
  ],
}
