import type { DeckDef } from '../types'

// Quran Vocabulary, level 12. See GitHub issue #8.
//
// Scaffolded by scripts/generateVocab.ts: the headword, root, occurrence count,
// ayah and citation come from the corpus and the canonical text. The meanings,
// principal parts and ayah translations were authored on top of that scaffold.
//
// Where the corpus lemmatizes a word to a passive, an imperative or a mudari
// that nobody looks up, the note id is the dictionary form while the headword
// stays as the corpus has it, since that is what the ayah shows.
//
// DRAFT: verify every English meaning before memorizing it. Turkish is
// convenience text and stays draft - correct it on sight while studying.
//
// Locked until the previous level is mostly graduated; see quranVocabTrack.ts.

export const quranVocab12: DeckDef = {
  id: 'quran-vocab-12',
  name: { english: 'Quran Vocabulary 12', turkish: 'Kur’an Kelimeleri 12' },
  nameArabic: 'مُفْرَدَاتُ الْقُرْآنِ ١٢',
  description: {
    english:
      'Frequency band 12 of the Quran vocabulary track, each word with an ayah where it occurs.',
    turkish:
      'Kur’an kelime yolunun 12. sıklık kuşağı; her kelime geçtiği bir ayetle.',
  },
  directions: ['ar-to-meaning'],
  newPerDay: 10,
  burySiblings: true,
  notes: [
    {
      id: 'qaim',
      arabic: 'قائِم',
      english: 'standing; upholding, maintaining',
      turkish: 'ayakta duran; yerine getiren, gözeten',
      example: {
        arabic: 'وَٱلَّذِينَ هُم بِشَهَٰدَٰتِهِمْ قَآئِمُونَ',
        english: 'and those who are upright in their testimonies,',
        turkish: 've şahitliklerinde dosdoğru duranlar,',
        source: 'Qur\'an 70:33',
        highlight: { english: 'upright', turkish: 'dosdoğru duranlar' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قوم',
        forms: [
          { label: 'plural', arabic: 'قَائِمُونَ' },
        ],
        occurrences: 17,
        occurringForm: 'قَآئِمُونَ',
      },
    },
    {
      id: 'kariha',
      arabic: 'كَرِهَ',
      english: 'to dislike, to hate',
      turkish: 'hoşlanmamak, nefret etmek',
      example: {
        arabic: 'لِيُحِقَّ ٱلْحَقَّ وَيُبْطِلَ ٱلْبَٰطِلَ وَلَوْ كَرِهَ ٱلْمُجْرِمُونَ',
        english: 'so that He may establish the truth and abolish falsehood, even if the criminals dislike it.',
        turkish: 'Hakkı gerçekleştirsin ve batılı ortadan kaldırsın diye; suçlular hoşlanmasa da.',
        source: 'Qur\'an 8:8',
        highlight: { english: 'dislike', turkish: 'hoşlanmasa' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'كره',
        forms: [
          { label: 'mudari', arabic: 'يَكْرَهُ' },
          { label: 'masdar', arabic: 'كُرْه' },
        ],
        occurrences: 17,
        occurringForm: 'كَرِهَ',
      },
    },
    {
      id: 'muhtady',
      arabic: 'مُهْتَدي',
      english: 'rightly guided',
      turkish: 'hidayete ermiş, doğru yolu bulmuş',
      example: {
        arabic: 'ٱتَّبِعُوا۟ مَن لَّا يَسْـَٔلُكُمْ أَجْرًۭا وَهُم مُّهْتَدُونَ',
        english: 'Follow those who do not ask you for a reward, and they are rightly guided.',
        turkish: 'Sizden bir ücret istemeyenlere uyun; onlar hidayete ermiş kimselerdir.',
        source: 'Qur\'an 36:21',
        highlight: { english: 'rightly guided', turkish: 'hidayete ermiş' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'هدي',
        forms: [
          { label: 'plural', arabic: 'مُهْتَدُونَ' },
        ],
        occurrences: 17,
        occurringForm: 'مُّهْتَدُونَ',
      },
    },
    {
      id: 'naiym',
      arabic: 'نَعِيم',
      english: 'bliss, delight',
      turkish: 'nimet, huzur',
      example: {
        arabic: 'إِنَّ ٱلْأَبْرَارَ لَفِى نَعِيمٍۢ',
        english: 'Indeed, the righteous will be in bliss.',
        turkish: 'Şüphesiz iyiler nimet içindedir.',
        source: 'Qur\'an 82:13',
        highlight: { english: 'bliss', turkish: 'nimet' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نعم',
        occurrences: 17,
        occurringForm: 'نَعِيمٍ',
      },
    },
    {
      id: 'wadda',
      arabic: 'وَدَّ',
      english: 'to wish, to desire',
      turkish: 'arzu etmek, istemek',
      example: {
        arabic: 'رُّبَمَا يَوَدُّ ٱلَّذِينَ كَفَرُوا۟ لَوْ كَانُوا۟ مُسْلِمِينَ',
        english: 'Perhaps those who disbelieve will wish that they had been Muslims.',
        turkish: 'İnkâr edenler, keşke Müslüman olsaydık diye çokça arzu edecekler.',
        source: 'Qur\'an 15:2',
        highlight: { english: 'will wish', turkish: 'arzu edecekler' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ودد',
        forms: [
          { label: 'mudari', arabic: 'يَوَدُّ' },
          { label: 'masdar', arabic: 'وُدّ' },
        ],
        occurrences: 17,
        occurringForm: 'يَوَدُّ',
      },
    },
    {
      id: 'tafakkara',
      arabic: 'يَتَفَكَّرُ',
      english: 'to reflect, to ponder',
      turkish: 'tefekkür etmek, düşünmek',
      example: {
        arabic: 'أَوَلَمْ يَتَفَكَّرُوا۟ ۗ مَا بِصَاحِبِهِم مِّن جِنَّةٍ ۚ إِنْ هُوَ إِلَّا نَذِيرٌۭ مُّبِينٌ',
        english: 'Have they not reflected? There is no madness in their companion. He is only a clear warner.',
        turkish: 'Hiç tefekkür etmediler mi? Arkadaşlarında delilik yoktur. O ancak apaçık bir uyarıcıdır.',
        source: 'Qur\'an 7:184',
        highlight: { english: 'reflected', turkish: 'tefekkür etmediler' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'فكر',
        forms: [
          { label: 'mudari', arabic: 'يَتَفَكَّرُ' },
          { label: 'masdar', arabic: 'تَفَكُّر' },
        ],
        occurrences: 17,
        occurringForm: 'يَتَفَكَّرُوا۟',
      },
    },
    {
      id: 'amin',
      arabic: 'آمِن',
      english: 'safe, secure',
      turkish: 'güvende, emin',
      example: {
        arabic: 'ٱدْخُلُوهَا بِسَلَٰمٍ ءَامِنِينَ',
        english: 'Enter it in peace, secure.',
        turkish: 'Oraya esenlikle, güven içinde girin.',
        source: 'Qur\'an 15:46',
        highlight: { english: 'secure', turkish: 'güven içinde' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أمن',
        forms: [
          { label: 'plural', arabic: 'آمِنُونَ' },
        ],
        occurrences: 16,
        occurringForm: 'ءَامِنِينَ',
      },
    },
    {
      id: 'atamma',
      arabic: 'أَتَمَّ',
      english: 'to complete, to perfect',
      turkish: 'tamamlamak',
      example: {
        arabic: 'يُرِيدُونَ أَن يُطْفِـُٔوا۟ نُورَ ٱللَّهِ بِأَفْوَٰهِهِمْ وَيَأْبَى ٱللَّهُ إِلَّآ أَن يُتِمَّ نُورَهُۥ وَلَوْ كَرِهَ ٱلْكَٰفِرُونَ',
        english: 'They want to extinguish the light of Allah with their mouths, but Allah refuses anything but to perfect His light, even if the disbelievers dislike it.',
        turkish: 'Allah\'ın nurunu ağızlarıyla söndürmek istiyorlar; ama kâfirler hoşlanmasa da Allah nurunu tamamlamaktan başkasını kabul etmez.',
        source: 'Qur\'an 9:32',
        highlight: { english: 'to perfect', turkish: 'tamamlamaktan' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'تمم',
        forms: [
          { label: 'mudari', arabic: 'يُتِمُّ' },
          { label: 'masdar', arabic: 'إِتْمَام' },
        ],
        occurrences: 16,
        occurringForm: 'يُتِمَّ',
      },
    },
    {
      id: 'azlam',
      arabic: 'أَظْلَم',
      english: 'more unjust, most unjust',
      turkish: 'daha zalim, en zalim',
      example: {
        arabic: 'وَقَوْمَ نُوحٍۢ مِّن قَبْلُ ۖ إِنَّهُمْ كَانُوا۟ هُمْ أَظْلَمَ وَأَطْغَىٰ',
        english: 'and the people of Noah before; indeed, they were more unjust and more rebellious.',
        turkish: 'Daha önce de Nuh kavmini; çünkü onlar daha zalim ve daha azgındılar.',
        source: 'Qur\'an 53:52',
        highlight: { english: 'more unjust', turkish: 'daha zalim' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ظلم',
        occurrences: 16,
        occurringForm: 'أَظْلَمَ',
      },
    },
    {
      id: 'afaka',
      arabic: 'أُفِكَ',
      english: 'to turn away, to divert; to delude',
      turkish: 'çevirmek, saptırmak, aldatmak',
      example: {
        arabic: 'يُؤْفَكُ عَنْهُ مَنْ أُفِكَ',
        english: 'Turned away from it is whoever is turned away.',
        turkish: 'Ondan döndürülen kimse döndürülür.',
        source: 'Qur\'an 51:9',
        highlight: { english: 'Turned away', turkish: 'döndürülen' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'أفك',
        forms: [
          { label: 'mudari', arabic: 'يَأْفِكُ' },
          { label: 'masdar', arabic: 'إِفْك' },
        ],
        occurrences: 16,
        occurringForm: 'يُؤْفَكُ',
      },
    },
    {
      id: 'albab',
      arabic: 'أَلْباب',
      english: 'minds, understanding (pl. of lubb)',
      turkish: 'akıllar, kavrayış',
      example: {
        arabic: 'هُدًۭى وَذِكْرَىٰ لِأُو۟لِى ٱلْأَلْبَٰبِ',
        english: 'a guidance and a reminder for people of understanding.',
        turkish: 'Akıl sahipleri için bir yol gösterici ve bir öğüt olarak.',
        source: 'Qur\'an 40:54',
        highlight: { english: 'understanding', turkish: 'Akıl sahipleri' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'لبب',
        occurrences: 16,
        occurringForm: 'ٱلْأَلْبَٰبِ',
      },
    },
    {
      id: 'anbata',
      arabic: 'أَنۢبَتَ',
      english: 'to make grow, to bring forth',
      turkish: 'bitirmek, yetiştirmek',
      example: {
        arabic: 'وَٱللَّهُ أَنۢبَتَكُم مِّنَ ٱلْأَرْضِ نَبَاتًۭا',
        english: 'And Allah made you grow from the earth as a growth,',
        turkish: 'Allah sizi yerden bir bitki gibi bitirdi,',
        source: 'Qur\'an 71:17',
        highlight: { english: 'made you grow', turkish: 'bitirdi' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نبت',
        forms: [
          { label: 'mudari', arabic: 'يُنْبِتُ' },
          { label: 'masdar', arabic: 'إِنْبَات' },
        ],
        occurrences: 16,
        occurringForm: 'أَنۢبَتَكُم',
      },
    },
    {
      id: 'astamaa',
      arabic: 'اسْتَمَعَ',
      english: 'to listen',
      turkish: 'dinlemek',
      example: {
        arabic: 'وَأَنَا ٱخْتَرْتُكَ فَٱسْتَمِعْ لِمَا يُوحَىٰٓ',
        english: 'And I have chosen you, so listen to what is revealed.',
        turkish: 'Ben seni seçtim; şimdi vahyolunanı dinle.',
        source: 'Qur\'an 20:13',
        highlight: { english: 'listen', turkish: 'dinle' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سمع',
        forms: [
          { label: 'mudari', arabic: 'يَسْتَمِعُ' },
          { label: 'masdar', arabic: 'اسْتِمَاع' },
        ],
        occurrences: 16,
        occurringForm: 'فَٱسْتَمِعْ',
      },
    },
    {
      id: 'antahaa',
      arabic: 'انتَهَى',
      english: 'to desist, to refrain; to come to an end',
      turkish: 'vazgeçmek, son bulmak',
      example: {
        arabic: 'كَلَّا لَئِن لَّمْ يَنتَهِ لَنَسْفَعًۢا بِٱلنَّاصِيَةِ',
        english: 'No! If he does not desist, We will surely drag him by the forelock.',
        turkish: 'Hayır! Eğer vazgeçmezse, andolsun onu perçeminden yakalayıp sürükleriz.',
        source: 'Qur\'an 96:15',
        highlight: { english: 'desist', turkish: 'vazgeçmezse' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نهي',
        forms: [
          { label: 'mudari', arabic: 'يَنْتَهِي' },
          { label: 'masdar', arabic: 'انْتِهَاء' },
        ],
        occurrences: 16,
        occurringForm: 'يَنتَهِ',
      },
    },
    {
      id: 'basata',
      arabic: 'بَسَطَ',
      english: 'to spread out, to extend',
      turkish: 'yaymak, genişletmek',
      example: {
        arabic: 'إِنَّ رَبَّكَ يَبْسُطُ ٱلرِّزْقَ لِمَن يَشَآءُ وَيَقْدِرُ ۚ إِنَّهُۥ كَانَ بِعِبَادِهِۦ خَبِيرًۢا بَصِيرًۭا',
        english: 'Indeed, your Lord extends provision for whom He wills and restricts it. Indeed, He is ever Aware and Seeing of His servants.',
        turkish: 'Şüphesiz Rabbin dilediğine rızkı genişletir ve daraltır. Kuşkusuz O, kullarından haberdardır, onları görmektedir.',
        source: 'Qur\'an 17:30',
        highlight: { english: 'extends', turkish: 'genişletir' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بسط',
        forms: [
          { label: 'mudari', arabic: 'يَبْسُطُ' },
          { label: 'masdar', arabic: 'بَسْط' },
        ],
        occurrences: 16,
        occurringForm: 'يَبْسُطُ',
      },
    },
    {
      id: 'khasira',
      arabic: 'خَسِرَ',
      english: 'to lose, to suffer loss',
      turkish: 'hüsrana uğramak, kaybetmek',
      example: {
        arabic: 'وَلِلَّهِ مُلْكُ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ ۚ وَيَوْمَ تَقُومُ ٱلسَّاعَةُ يَوْمَئِذٍۢ يَخْسَرُ ٱلْمُبْطِلُونَ',
        english: 'And to Allah belongs the dominion of the heavens and the earth. And on the Day the Hour comes to pass, that Day the falsifiers will lose.',
        turkish: 'Göklerin ve yerin mülkü Allah\'ındır. Kıyamet saatinin kopacağı gün, işte o gün batıla sapanlar hüsrana uğrarlar.',
        source: 'Qur\'an 45:27',
        highlight: { english: 'will lose', turkish: 'hüsrana uğrarlar' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'خسر',
        forms: [
          { label: 'mudari', arabic: 'يَخْسَرُ' },
          { label: 'masdar', arabic: 'خُسْرَان' },
        ],
        occurrences: 16,
        occurringForm: 'يَخْسَرُ',
      },
    },
    {
      id: 'dawud',
      arabic: 'داوُد',
      english: 'David (prophet)',
      turkish: 'Davud (peygamber)',
      example: {
        arabic: 'ٱصْبِرْ عَلَىٰ مَا يَقُولُونَ وَٱذْكُرْ عَبْدَنَا دَاوُۥدَ ذَا ٱلْأَيْدِ ۖ إِنَّهُۥٓ أَوَّابٌ',
        english: 'Be patient over what they say, and remember Our servant David, the possessor of strength; indeed, he was one who turned back constantly.',
        turkish: 'Onların söylediklerine sabret ve güçlü kulumuz Davud\'u an; şüphesiz o, daima Allah\'a yönelen biriydi.',
        source: 'Qur\'an 38:17',
        highlight: { english: 'David', turkish: 'Davud' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 16,
        occurringForm: 'دَاوُۥدَ',
      },
    },
    {
      id: 'sara',
      arabic: 'سارَ',
      english: 'to travel, to move along',
      turkish: 'yürümek, yol almak',
      example: {
        arabic: 'وَتَسِيرُ ٱلْجِبَالُ سَيْرًۭا',
        english: 'and the mountains move away, moving.',
        turkish: 've dağlar yürüdükçe yürür.',
        source: 'Qur\'an 52:10',
        highlight: { english: 'move away', turkish: 'yürüdükçe yürür' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سير',
        forms: [
          { label: 'mudari', arabic: 'يَسِيرُ' },
          { label: 'masdar', arabic: 'سَيْر' },
        ],
        occurrences: 16,
        occurringForm: 'وَتَسِيرُ',
      },
    },
    {
      id: 'saiyr',
      arabic: 'سَعِير',
      english: 'blazing fire, blaze',
      turkish: 'alevli ateş, çılgın alev',
      example: {
        arabic: 'وَيَصْلَىٰ سَعِيرًا',
        english: 'and he will burn in a Blaze.',
        turkish: 've alevli ateşe girer.',
        source: 'Qur\'an 84:12',
        highlight: { english: 'Blaze', turkish: 'alevli ateşe' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سعر',
        occurrences: 16,
        occurringForm: 'سَعِيرًا',
      },
    },
    {
      id: 'sunna',
      arabic: 'سُنَّة',
      english: 'way, custom, established practice',
      turkish: 'sünnet, adet, yol',
      example: {
        arabic: 'لَا يُؤْمِنُونَ بِهِۦ ۖ وَقَدْ خَلَتْ سُنَّةُ ٱلْأَوَّلِينَ',
        english: 'They will not believe in it, though the way of the former peoples has already passed.',
        turkish: 'Ona inanmazlar; oysa öncekilerin sünneti gelip geçmiştir.',
        source: 'Qur\'an 15:13',
        highlight: { english: 'the way', turkish: 'sünneti' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سنن',
        forms: [
          { label: 'plural', arabic: 'سُنَن' },
        ],
        occurrences: 16,
        occurringForm: 'سُنَّةُ',
      },
    },
    {
      id: 'tayyib',
      arabic: 'طَيِّب',
      english: 'good, pure, wholesome',
      turkish: 'temiz, hoş, helal',
      example: {
        arabic: 'فَكُلُوا۟ مِمَّا غَنِمْتُمْ حَلَٰلًۭا طَيِّبًۭا ۚ وَٱتَّقُوا۟ ٱللَّهَ ۚ إِنَّ ٱللَّهَ غَفُورٌۭ رَّحِيمٌۭ',
        english: 'So eat of what you have taken as spoils, lawful and good, and fear Allah. Indeed, Allah is Forgiving and Merciful.',
        turkish: 'Ganimet olarak aldıklarınızdan helal ve temiz olarak yiyin; Allah\'tan korkun. Şüphesiz Allah bağışlayandır, merhamet edendir.',
        source: 'Qur\'an 8:69',
        highlight: { english: 'good', turkish: 'temiz' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'طيب',
        forms: [
          { label: 'plural', arabic: 'طَيِّبَات' },
        ],
        occurrences: 16,
        occurringForm: 'طَيِّبًا',
      },
    },
    {
      id: 'fuad',
      arabic: 'فُؤاد',
      english: 'heart',
      turkish: 'kalp, gönül',
      example: {
        arabic: 'وَلِتَصْغَىٰٓ إِلَيْهِ أَفْـِٔدَةُ ٱلَّذِينَ لَا يُؤْمِنُونَ بِٱلْءَاخِرَةِ وَلِيَرْضَوْهُ وَلِيَقْتَرِفُوا۟ مَا هُم مُّقْتَرِفُونَ',
        english: 'and so that the hearts of those who do not believe in the Hereafter may incline toward it, and that they may be pleased with it, and that they may commit what they are committing.',
        turkish: 'Bir de ahirete inanmayanların kalpleri ona meyletsin, ondan hoşnut olsunlar ve işledikleri günahları işlemeye devam etsinler diye.',
        source: 'Qur\'an 6:113',
        highlight: { english: 'hearts', turkish: 'kalpleri' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'فأد',
        forms: [
          { label: 'plural', arabic: 'أَفْئِدَة' },
        ],
        occurrences: 16,
        occurringForm: 'أَفْـِٔدَةُ',
      },
    },
    {
      id: 'fataha',
      arabic: 'فَتَحَ',
      english: 'to open',
      turkish: 'açmak',
      example: {
        arabic: 'حَتَّىٰٓ إِذَا فُتِحَتْ يَأْجُوجُ وَمَأْجُوجُ وَهُم مِّن كُلِّ حَدَبٍۢ يَنسِلُونَ',
        english: 'until, when Gog and Magog are opened up, and they hasten down from every height,',
        turkish: 'Nihayet Ye\'cûc ve Me\'cûc\'ün önü açıldığı zaman, onlar her tepeden akın ederler,',
        source: 'Qur\'an 21:96',
        highlight: { english: 'opened up', turkish: 'açıldığı' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'فتح',
        forms: [
          { label: 'mudari', arabic: 'يَفْتَحُ' },
          { label: 'masdar', arabic: 'فَتْح' },
        ],
        occurrences: 16,
        occurringForm: 'فُتِحَتْ',
      },
    },
    {
      id: 'fariha',
      arabic: 'فَرِحَ',
      english: 'to rejoice, to be glad',
      turkish: 'sevinmek',
      example: {
        arabic: 'فِى بِضْعِ سِنِينَ ۗ لِلَّهِ ٱلْأَمْرُ مِن قَبْلُ وَمِنۢ بَعْدُ ۚ وَيَوْمَئِذٍۢ يَفْرَحُ ٱلْمُؤْمِنُونَ',
        english: 'within a few years. To Allah belongs the command before and after. And that day the believers will rejoice,',
        turkish: 'birkaç yıl içinde. Önce de sonra da emir Allah\'ındır. O gün müminler sevinecekler,',
        source: 'Qur\'an 30:4',
        highlight: { english: 'rejoice', turkish: 'sevinecekler' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'فرح',
        forms: [
          { label: 'mudari', arabic: 'يَفْرَحُ' },
          { label: 'masdar', arabic: 'فَرَح' },
        ],
        occurrences: 16,
        occurringForm: 'يَفْرَحُ',
      },
    },
    {
      id: 'qaddara',
      arabic: 'قَدَّرَ',
      english: 'to determine, to measure out, to decree',
      turkish: 'takdir etmek, ölçüp belirlemek',
      example: {
        arabic: 'وَٱلَّذِى قَدَّرَ فَهَدَىٰ',
        english: 'and who determined and then guided,',
        turkish: 've O ki ölçüp biçti, sonra yol gösterdi,',
        source: 'Qur\'an 87:3',
        highlight: { english: 'determined', turkish: 'ölçüp biçti' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'قدر',
        forms: [
          { label: 'mudari', arabic: 'يُقَدِّرُ' },
          { label: 'masdar', arabic: 'تَقْدِير' },
        ],
        occurrences: 16,
        occurringForm: 'قَدَّرَ',
      },
    },
    {
      id: 'qaraa',
      arabic: 'قَرَأَ',
      english: 'to read, to recite',
      turkish: 'kıraat etmek, okumak',
      example: {
        arabic: 'ٱقْرَأْ وَرَبُّكَ ٱلْأَكْرَمُ',
        english: 'Recite, and your Lord is the most Generous,',
        turkish: 'Oku! Rabbin en kerîm olandır,',
        source: 'Qur\'an 96:3',
        highlight: { english: 'Recite', turkish: 'Oku' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'قرأ',
        forms: [
          { label: 'mudari', arabic: 'يَقْرَأُ' },
          { label: 'masdar', arabic: 'قِرَاءَة' },
        ],
        occurrences: 16,
        occurringForm: 'ٱقْرَأْ',
      },
    },
    {
      id: 'qurbaa',
      arabic: 'قُرْبَى',
      english: 'kinship, near relationship',
      turkish: 'akrabalık, yakınlık',
      example: {
        arabic: 'وَءَاتِ ذَا ٱلْقُرْبَىٰ حَقَّهُۥ وَٱلْمِسْكِينَ وَٱبْنَ ٱلسَّبِيلِ وَلَا تُبَذِّرْ تَبْذِيرًا',
        english: 'And give the relative his right, and the poor and the traveler, and do not spend wastefully.',
        turkish: 'Akrabaya hakkını ver, yoksula ve yolcuya da; sakın saçıp savurma.',
        source: 'Qur\'an 17:26',
        highlight: { english: 'the relative', turkish: 'Akrabaya' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قرب',
        occurrences: 16,
        occurringForm: 'ٱلْقُرْبَىٰ',
      },
    },
    {
      id: 'marji',
      arabic: 'مَرْجِع',
      english: 'return, place of return',
      turkish: 'merci, dönülecek yer',
      example: {
        arabic: 'ثُمَّ إِنَّ مَرْجِعَهُمْ لَإِلَى ٱلْجَحِيمِ',
        english: 'Then indeed, their return will be to the Hellfire.',
        turkish: 'Sonra şüphesiz onların mercii cehennemdir.',
        source: 'Qur\'an 37:68',
        highlight: { english: 'return', turkish: 'merci' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'رجع',
        forms: [
          { label: 'plural', arabic: 'مَرَاجِع' },
        ],
        occurrences: 16,
        occurringForm: 'مَرْجِعَهُمْ',
      },
    },
    {
      id: 'miyzan',
      arabic: 'مِيزان',
      english: 'balance, scale',
      turkish: 'mizan, terazi, ölçü',
      example: {
        arabic: 'فَأَمَّا مَن ثَقُلَتْ مَوَٰزِينُهُۥ',
        english: 'As for one whose scales are heavy,',
        turkish: 'Kimin mizanı ağır gelirse,',
        source: 'Qur\'an 101:6',
        highlight: { english: 'scales', turkish: 'mizan' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'وزن',
        forms: [
          { label: 'plural', arabic: 'مَوَازِين' },
        ],
        occurrences: 16,
        occurringForm: 'مَوَٰزِينُهُۥ',
      },
    },
    {
      id: 'hajara',
      arabic: 'هاجَرَ',
      english: 'to emigrate, to migrate',
      turkish: 'hicret etmek, göç etmek',
      example: {
        arabic: '۞ وَمَن يُهَاجِرْ فِى سَبِيلِ ٱللَّهِ يَجِدْ فِى ٱلْأَرْضِ مُرَٰغَمًۭا كَثِيرًۭا وَسَعَةًۭ ۚ وَمَن يَخْرُجْ مِنۢ بَيْتِهِۦ مُهَاجِرًا إِلَى ٱللَّهِ وَرَسُولِهِۦ ثُمَّ يُدْرِكْهُ ٱلْمَوْتُ فَقَدْ وَقَعَ أَجْرُهُۥ عَلَى ٱللَّهِ ۗ وَكَانَ ٱللَّهُ غَفُورًۭا رَّحِيمًۭا',
        english: 'And whoever emigrates in the way of Allah will find on the earth many places of refuge and abundance. And whoever leaves his home emigrating to Allah and His Messenger and then death overtakes him, his reward has already fallen upon Allah. And Allah is ever Forgiving and Merciful.',
        turkish: 'Kim Allah yolunda hicret ederse, yeryüzünde barınacak birçok yer ve genişlik bulur. Kim de Allah\'a ve Resulüne hicret etmek üzere evinden çıkar, sonra kendisine ölüm yetişirse, onun ecri Allah\'a düşmüştür. Allah çok bağışlayandır, çok merhametlidir.',
        source: 'Qur\'an 4:100',
        highlight: { english: 'emigrates', turkish: 'hicret ederse' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'هجر',
        forms: [
          { label: 'mudari', arabic: 'يُهَاجِرُ' },
          { label: 'masdar', arabic: 'مُهَاجَرَة' },
        ],
        occurrences: 16,
        occurringForm: 'يُهَاجِرْ',
      },
    },
    {
      id: 'waqaa',
      arabic: 'وَقَى',
      english: 'to protect, to guard',
      turkish: 'korumak',
      example: {
        arabic: 'وَقِهِمُ ٱلسَّيِّـَٔاتِ ۚ وَمَن تَقِ ٱلسَّيِّـَٔاتِ يَوْمَئِذٍۢ فَقَدْ رَحِمْتَهُۥ ۚ وَذَٰلِكَ هُوَ ٱلْفَوْزُ ٱلْعَظِيمُ',
        english: 'And protect them from the evil deeds. And whoever You protect from evil deeds that Day, You have indeed shown him mercy. And that is the great attainment.',
        turkish: 'Onları kötülüklerden koru. O gün kimi kötülüklerden korursan, ona rahmet etmiş olursun. İşte büyük kurtuluş budur.',
        source: 'Qur\'an 40:9',
        highlight: { english: 'And protect them', turkish: 'Onları kötülüklerden koru' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'وقي',
        forms: [
          { label: 'mudari', arabic: 'يَقِي' },
          { label: 'masdar', arabic: 'وِقَايَة' },
        ],
        occurrences: 16,
        occurringForm: 'تَقِ',
      },
    },
    {
      id: 'yaquwb',
      arabic: 'يَعْقُوب',
      english: 'Jacob (prophet)',
      turkish: 'Yakub (peygamber)',
      example: {
        arabic: 'يَرِثُنِى وَيَرِثُ مِنْ ءَالِ يَعْقُوبَ ۖ وَٱجْعَلْهُ رَبِّ رَضِيًّۭا',
        english: 'who will inherit from me and inherit from the family of Jacob. And make him, my Lord, pleasing.',
        turkish: 'Bana da Yakub ailesine de mirasçı olsun; Rabbim, onu razı olunan biri kıl.',
        source: 'Qur\'an 19:6',
        highlight: { english: 'Jacob', turkish: 'Yakub' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 16,
        occurringForm: 'يَعْقُوبَ',
      },
    },
    {
      id: 'atbaa',
      arabic: 'أَتْبَعَ',
      english: 'to follow, to pursue; to make follow',
      turkish: 'takip etmek, ardınca gitmek',
      example: {
        arabic: 'ثُمَّ أَتْبَعَ سَبَبًا',
        english: 'Then he followed a course.',
        turkish: 'Sonra bir yol daha tuttu.',
        source: 'Qur\'an 18:89',
        highlight: { english: 'followed', turkish: 'tuttu' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'تبع',
        forms: [
          { label: 'mudari', arabic: 'يُتْبِعُ' },
          { label: 'masdar', arabic: 'إِتْبَاع' },
        ],
        occurrences: 15,
        occurringForm: 'أَتْبَعَ',
      },
    },
    {
      id: 'akhkhara',
      arabic: 'أَخَّرَ',
      english: 'to delay, to postpone',
      turkish: 'ertelemek, geciktirmek',
      example: {
        arabic: 'وَلَن يُؤَخِّرَ ٱللَّهُ نَفْسًا إِذَا جَآءَ أَجَلُهَا ۚ وَٱللَّهُ خَبِيرٌۢ بِمَا تَعْمَلُونَ',
        english: 'And Allah will never delay a soul when its appointed time has come. And Allah is Aware of what you do.',
        turkish: 'Eceli geldiğinde Allah hiçbir cana asla mühlet vermez. Allah yaptıklarınızdan haberdardır.',
        source: 'Qur\'an 63:11',
        highlight: { english: 'delay', turkish: 'mühlet vermez' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'أخر',
        forms: [
          { label: 'mudari', arabic: 'يُؤَخِّرُ' },
          { label: 'masdar', arabic: 'تَأْخِير' },
        ],
        occurrences: 15,
        occurringForm: 'يُؤَخِّرَ',
      },
    },
    {
      id: 'aghnaa-2',
      arabic: 'أَغْنَى',
      english: 'to enrich, to free from need',
      turkish: 'zengin etmek, ihtiyaçtan kurtarmak',
      example: {
        arabic: 'وَأَنَّهُۥ هُوَ أَغْنَىٰ وَأَقْنَىٰ',
        english: 'and that it is He who enriched and gave possessions,',
        turkish: 've şüphesiz zengin eden de, varlık sahibi kılan da O\'dur,',
        source: 'Qur\'an 53:48',
        highlight: { english: 'enriched', turkish: 'zengin eden' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'غني',
        forms: [
          { label: 'mudari', arabic: 'يُغْنِي' },
          { label: 'masdar', arabic: 'إِغْنَاء' },
        ],
        occurrences: 15,
        occurringForm: 'أَغْنَىٰ',
      },
    },
    {
      id: 'afsada',
      arabic: 'أَفْسَدُ',
      english: 'to cause corruption, to spoil',
      turkish: 'bozgunculuk yapmak, bozmak',
      example: {
        arabic: 'ٱلَّذِينَ يُفْسِدُونَ فِى ٱلْأَرْضِ وَلَا يُصْلِحُونَ',
        english: 'who cause corruption in the earth and do not set things right.',
        turkish: 'Onlar ki yeryüzünde bozgunculuk yaparlar da düzeltmezler.',
        source: 'Qur\'an 26:152',
        highlight: { english: 'cause corruption', turkish: 'bozgunculuk yaparlar' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'فسد',
        forms: [
          { label: 'mudari', arabic: 'يُفْسِدُ' },
          { label: 'masdar', arabic: 'إِفْسَاد' },
        ],
        occurrences: 15,
        occurringForm: 'يُفْسِدُونَ',
      },
    },
    {
      id: 'adha',
      arabic: 'أُوذِيَ',
      english: 'to harm, to hurt, to offend',
      turkish: 'eziyet etmek, incitmek',
      example: {
        arabic: 'وَٱلَّذِينَ يُؤْذُونَ ٱلْمُؤْمِنِينَ وَٱلْمُؤْمِنَٰتِ بِغَيْرِ مَا ٱكْتَسَبُوا۟ فَقَدِ ٱحْتَمَلُوا۟ بُهْتَٰنًۭا وَإِثْمًۭا مُّبِينًۭا',
        english: 'And those who harm believing men and believing women for something other than what they have earned have certainly borne a slander and a manifest sin.',
        turkish: 'Mümin erkeklere ve mümin kadınlara, yapmadıkları bir şey yüzünden eziyet edenler, şüphesiz bir iftirayı ve apaçık bir günahı yüklenmişlerdir.',
        source: 'Qur\'an 33:58',
        highlight: { english: 'harm', turkish: 'eziyet edenler' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'أذي',
        forms: [
          { label: 'mudari', arabic: 'يُؤْذِي' },
          { label: 'masdar', arabic: 'إِيذَاء' },
        ],
        occurrences: 15,
        occurringForm: 'يُؤْذُونَ',
      },
    },
    {
      id: 'atadaa',
      arabic: 'اعْتَدَى',
      english: 'to transgress, to overstep',
      turkish: 'haddi aşmak, saldırmak',
      example: {
        arabic: 'وَلَقَدْ عَلِمْتُمُ ٱلَّذِينَ ٱعْتَدَوْا۟ مِنكُمْ فِى ٱلسَّبْتِ فَقُلْنَا لَهُمْ كُونُوا۟ قِرَدَةً خَٰسِـِٔينَ',
        english: 'And you had certainly known about those among you who transgressed on the Sabbath, so We said to them: Be apes, despised.',
        turkish: 'Andolsun, içinizden cumartesi günü haddi aşanları elbette bildiniz. Onlara: Aşağılık maymunlar olun, dedik.',
        source: 'Qur\'an 2:65',
        highlight: { english: 'transgressed', turkish: 'haddi aşanları' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عدو',
        forms: [
          { label: 'mudari', arabic: 'يَعْتَدِي' },
          { label: 'masdar', arabic: 'اعْتِدَاء' },
        ],
        occurrences: 15,
        occurringForm: 'ٱعْتَدَوْا۟',
      },
    },
    {
      id: 'bushraa',
      arabic: 'بُشْرَى',
      english: 'good tidings, glad news',
      turkish: 'müjde',
      example: {
        arabic: 'يَوْمَ يَرَوْنَ ٱلْمَلَٰٓئِكَةَ لَا بُشْرَىٰ يَوْمَئِذٍۢ لِّلْمُجْرِمِينَ وَيَقُولُونَ حِجْرًۭا مَّحْجُورًۭا',
        english: 'The Day they see the angels, no good tidings will there be that Day for the criminals, and they will say: a forbidding barrier.',
        turkish: 'Melekleri görecekleri gün, işte o gün suçlulara hiçbir müjde yoktur; ve onlar: Yasaktır, yasak, derler.',
        source: 'Qur\'an 25:22',
        highlight: { english: 'good tidings', turkish: 'müjde' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بشر',
        occurrences: 15,
        occurringForm: 'بُشْرَىٰ',
      },
    },
    {
      id: 'balagh',
      arabic: 'بَلاغ',
      english: 'conveyance of a message, notification',
      turkish: 'tebliğ, bildirme',
      example: {
        arabic: 'وَمَا عَلَيْنَآ إِلَّا ٱلْبَلَٰغُ ٱلْمُبِينُ',
        english: 'And nothing is upon us except the clear conveyance of the message.',
        turkish: 'Bize düşen ancak apaçık tebliğdir.',
        source: 'Qur\'an 36:17',
        highlight: { english: 'conveyance of the message', turkish: 'tebliğdir' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بلغ',
        occurrences: 15,
        occurringForm: 'ٱلْبَلَٰغُ',
      },
    },
    {
      id: 'tanziyl',
      arabic: 'تَنزِيل',
      english: 'sending down, revelation',
      turkish: 'indirme, indirilen vahiy',
      example: {
        arabic: 'تَنزِيلَ ٱلْعَزِيزِ ٱلرَّحِيمِ',
        english: 'a revelation of the Exalted in Might, the Merciful,',
        turkish: 'Azîz ve Rahîm olanın indirmesidir,',
        source: 'Qur\'an 36:5',
        highlight: { english: 'a revelation', turkish: 'indirmesidir' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نزل',
        occurrences: 15,
        occurringForm: 'تَنزِيلَ',
      },
    },
    {
      id: 'haraj',
      arabic: 'حَرَج',
      english: 'distress, discomfort, constraint',
      turkish: 'sıkıntı, güçlük, darlık',
      example: {
        arabic: 'كِتَٰبٌ أُنزِلَ إِلَيْكَ فَلَا يَكُن فِى صَدْرِكَ حَرَجٌۭ مِّنْهُ لِتُنذِرَ بِهِۦ وَذِكْرَىٰ لِلْمُؤْمِنِينَ',
        english: 'A Book revealed to you, so let there be no distress in your breast because of it, that you may warn thereby, and as a reminder to the believers.',
        turkish: 'Sana indirilen bir kitaptır; onunla uyarman ve müminlere öğüt olması için göğsünde ondan dolayı bir sıkıntı olmasın.',
        source: 'Qur\'an 7:2',
        highlight: { english: 'distress', turkish: 'sıkıntı' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حرج',
        occurrences: 15,
        occurringForm: 'حَرَجٌ',
      },
    },
    {
      id: 'haliym',
      arabic: 'حَلِيم',
      english: 'forbearing, clement',
      turkish: 'halim, yumuşak huylu',
      example: {
        arabic: 'فَبَشَّرْنَٰهُ بِغُلَٰمٍ حَلِيمٍۢ',
        english: 'So We gave him good tidings of a forbearing boy.',
        turkish: 'Biz de ona halim bir oğul müjdeledik.',
        source: 'Qur\'an 37:101',
        highlight: { english: 'forbearing', turkish: 'halim' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حلم',
        forms: [
          { label: 'plural', arabic: 'حُلَمَاء' },
        ],
        occurrences: 15,
        occurringForm: 'حَلِيمٍ',
      },
    },
    {
      id: 'rijl',
      arabic: 'رِجْل',
      english: 'foot, leg',
      turkish: 'ayak',
      example: {
        arabic: 'ٱلْيَوْمَ نَخْتِمُ عَلَىٰٓ أَفْوَٰهِهِمْ وَتُكَلِّمُنَآ أَيْدِيهِمْ وَتَشْهَدُ أَرْجُلُهُم بِمَا كَانُوا۟ يَكْسِبُونَ',
        english: 'That Day We will seal over their mouths, and their hands will speak to Us, and their feet will testify about what they used to earn.',
        turkish: 'O gün ağızlarını mühürleriz; elleri bize konuşur, ayakları da kazandıklarına şahitlik eder.',
        source: 'Qur\'an 36:65',
        highlight: { english: 'feet', turkish: 'ayakları' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'رجل',
        forms: [
          { label: 'plural', arabic: 'أَرْجُل' },
        ],
        occurrences: 15,
        occurringForm: 'أَرْجُلُهُم',
      },
    },
    {
      id: 'sakana',
      arabic: 'سَكَنَ',
      english: 'to rest, to be still; to dwell',
      turkish: 'durmak, sükûn bulmak; barınmak',
      example: {
        arabic: '۞ وَلَهُۥ مَا سَكَنَ فِى ٱلَّيْلِ وَٱلنَّهَارِ ۚ وَهُوَ ٱلسَّمِيعُ ٱلْعَلِيمُ',
        english: 'And to Him belongs whatever rests in the night and the day, and He is the Hearing, the Knowing.',
        turkish: 'Gecede ve gündüzde barınan her şey O\'nundur. O işitendir, bilendir.',
        source: 'Qur\'an 6:13',
        highlight: { english: 'rests', turkish: 'barınan' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سكن',
        forms: [
          { label: 'mudari', arabic: 'يَسْكُنُ' },
          { label: 'masdar', arabic: 'سُكُون' },
        ],
        occurrences: 15,
        occurringForm: 'سَكَنَ',
      },
    },
    {
      id: 'shariba',
      arabic: 'شَرِبَ',
      english: 'to drink',
      turkish: 'içmek',
      example: {
        arabic: 'عَيْنًۭا يَشْرَبُ بِهَا ٱلْمُقَرَّبُونَ',
        english: 'a spring from which those brought near will drink.',
        turkish: 'Bir pınar ki, ondan Allah\'a yakın kılınanlar içer.',
        source: 'Qur\'an 83:28',
        highlight: { english: 'drink', turkish: 'içer' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'شرب',
        forms: [
          { label: 'mudari', arabic: 'يَشْرَبُ' },
          { label: 'masdar', arabic: 'شُرْب' },
        ],
        occurrences: 15,
        occurringForm: 'يَشْرَبُ',
      },
    },
    {
      id: 'shakk',
      arabic: 'شَكّ',
      english: 'doubt',
      turkish: 'şüphe',
      example: {
        arabic: 'بَلْ هُمْ فِى شَكٍّۢ يَلْعَبُونَ',
        english: 'Rather, they are in doubt, amusing themselves.',
        turkish: 'Hayır, onlar şüphe içinde oynayıp duruyorlar.',
        source: 'Qur\'an 44:9',
        highlight: { english: 'doubt', turkish: 'şüphe' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شكك',
        forms: [
          { label: 'plural', arabic: 'شُكُوك' },
        ],
        occurrences: 15,
        occurringForm: 'شَكٍّ',
      },
    },
    {
      id: 'sabr',
      arabic: 'صَبْر',
      english: 'patience, endurance',
      turkish: 'sabır',
      example: {
        arabic: 'فَٱصْبِرْ صَبْرًۭا جَمِيلًا',
        english: 'So be patient with a beautiful patience.',
        turkish: 'Şimdi güzel bir sabırla sabret.',
        source: 'Qur\'an 70:5',
        highlight: { english: 'patience', turkish: 'sabırla' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صبر',
        occurrences: 15,
        occurringForm: 'صَبْرًا',
      },
    },
    {
      id: 'sadaqa',
      arabic: 'صَدَقَ',
      english: 'to speak the truth, to be truthful',
      turkish: 'doğru söylemek',
      example: {
        arabic: 'قُلْ صَدَقَ ٱللَّهُ ۗ فَٱتَّبِعُوا۟ مِلَّةَ إِبْرَٰهِيمَ حَنِيفًۭا وَمَا كَانَ مِنَ ٱلْمُشْرِكِينَ',
        english: 'Say: Allah has spoken the truth. So follow the religion of Abraham, inclining to truth; and he was not of the polytheists.',
        turkish: 'De ki: Allah doğru söyledi. Öyleyse hanif olan İbrahim\'in dinine uyun; o müşriklerden değildi.',
        source: 'Qur\'an 3:95',
        highlight: { english: 'has spoken the truth', turkish: 'doğru söyledi' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'صدق',
        forms: [
          { label: 'mudari', arabic: 'يَصْدُقُ' },
          { label: 'masdar', arabic: 'صِدْق' },
        ],
        occurrences: 15,
        occurringForm: 'صَدَقَ',
      },
    },
    {
      id: 'sanaa',
      arabic: 'صَنَعُ',
      english: 'to make, to craft, to build',
      turkish: 'yapmak, imal etmek',
      example: {
        arabic: 'وَٱصْنَعِ ٱلْفُلْكَ بِأَعْيُنِنَا وَوَحْيِنَا وَلَا تُخَٰطِبْنِى فِى ٱلَّذِينَ ظَلَمُوٓا۟ ۚ إِنَّهُم مُّغْرَقُونَ',
        english: 'And build the ship under Our eyes and Our inspiration, and do not address Me concerning those who have wronged; indeed, they are to be drowned.',
        turkish: 'Gözetimimiz ve vahyimizle gemiyi yap; zulmedenler hakkında bana bir şey söyleme; şüphesiz onlar boğulacaklardır.',
        source: 'Qur\'an 11:37',
        highlight: { english: 'build', turkish: 'yap' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'صنع',
        forms: [
          { label: 'mudari', arabic: 'يَصْنَعُ' },
          { label: 'masdar', arabic: 'صُنْع' },
        ],
        occurrences: 15,
        occurringForm: 'وَٱصْنَعِ',
      },
    },
  ],
}
