import type { DeckDef } from '../types'

// Quran Vocabulary, level 7. See GitHub issue #8.
//
// Scaffolded by scripts/generateVocab.ts: the headword, root, occurrence count,
// ayah and citation come from the corpus and the canonical text. The meanings,
// principal parts and ayah translations were authored on top of that scaffold.
//
// Where the corpus lemmatizes a word to a passive, an imperative or a mudari
// that nobody looks up, the note id is the dictionary form while the headword
// stays as the corpus has it, since that is what the ayah shows.
//
// DRAFT: verify every English meaning before memorizing it. Turkish is
// convenience text and stays draft - correct it on sight while studying.
//
// Locked until the previous level is mostly graduated; see quranVocabTrack.ts.

export const quranVocab7: DeckDef = {
  id: 'quran-vocab-7',
  name: 'Quran Vocabulary 7',
  nameArabic: 'مُفْرَدَاتُ الْقُرْآنِ ٧',
  description:
    'Frequency band 7 of the Quran vocabulary track, each word with an ayah where it occurs.',
  directions: ['ar-to-meaning'],
  newPerDay: 10,
  burySiblings: true,
  notes: [
    {
      id: 'hazina',
      arabic: 'يَحْزُن',
      english: 'to grieve, to be sad',
      turkish: 'üzülmek, kederlenmek',
      example: {
        arabic: 'وَلَا تَحْزَنْ عَلَيْهِمْ وَلَا تَكُن فِى ضَيْقٍۢ مِّمَّا يَمْكُرُونَ',
        english: 'And do not grieve over them, and do not be in distress over what they plot.',
        turkish: 'Onlara üzülme ve kurdukları tuzaklardan dolayı sıkıntıya düşme.',
        source: 'Qur\'an 27:70',
        highlight: { english: 'grieve', turkish: 'üzülme' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حزن',
        forms: [
          { label: 'mudari', arabic: 'يَحْزَنُ' },
          { label: 'masdar', arabic: 'حُزْن' },
        ],
        occurrences: 37,
        occurringForm: 'تَحْزَنْ',
      },
    },
    {
      id: 'ahsan',
      arabic: 'أَحْسَن',
      english: 'best, finest',
      turkish: 'en güzel, en iyi',
      example: {
        arabic: 'أَتَدْعُونَ بَعْلًۭا وَتَذَرُونَ أَحْسَنَ ٱلْخَٰلِقِينَ',
        english: 'Do you call upon Baal and leave the best of creators,',
        turkish: 'Baal’e mi yalvarıyorsunuz da yaratıcıların en güzelini bırakıyorsunuz,',
        source: 'Qur\'an 37:125',
        highlight: { english: 'the best', turkish: 'en güzelini' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حسن',
        occurrences: 36,
        occurringForm: 'أَحْسَنَ',
      },
    },
    {
      id: 'dhaqa',
      arabic: 'ذاقُ',
      english: 'to taste',
      turkish: 'tatmak',
      example: {
        arabic: 'ذُقْ إِنَّكَ أَنتَ ٱلْعَزِيزُ ٱلْكَرِيمُ',
        english: 'Taste! Indeed, you are the mighty, the noble one.',
        turkish: 'Tat! Şüphesiz sen güçlüsün, değerlisin.',
        source: 'Qur\'an 44:49',
        highlight: { english: 'Taste', turkish: 'Tat' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ذوق',
        forms: [
          { label: 'mudari', arabic: 'يَذُوقُ' },
          { label: 'masdar', arabic: 'ذَوْق' },
        ],
        occurrences: 36,
        occurringForm: 'ذُقْ',
      },
    },
    {
      id: 'radda',
      arabic: 'رَدَّ',
      english: 'to return, to give back; to repel',
      turkish: 'geri çevirmek, geri vermek',
      example: {
        arabic: 'ثُمَّ رَدَدْنَا لَكُمُ ٱلْكَرَّةَ عَلَيْهِمْ وَأَمْدَدْنَٰكُم بِأَمْوَٰلٍۢ وَبَنِينَ وَجَعَلْنَٰكُمْ أَكْثَرَ نَفِيرًا',
        english: 'Then We gave you back the turn against them, and supplied you with wealth and sons, and made you more numerous in manpower.',
        turkish: 'Sonra onlara karşı size tekrar üstünlük verdik; sizi mallarla ve oğullarla destekledik ve sayıca daha çok kıldık.',
        source: 'Qur\'an 17:6',
        highlight: { english: 'gave you back', turkish: 'tekrar üstünlük verdik' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ردد',
        forms: [
          { label: 'mudari', arabic: 'يَرُدُّ' },
          { label: 'masdar', arabic: 'رَدّ' },
        ],
        occurrences: 36,
        occurringForm: 'رَدَدْنَا',
      },
    },
    {
      id: 'umm',
      arabic: 'أُمّ',
      english: 'mother; source, origin',
      turkish: 'anne; asıl, kaynak',
      example: {
        arabic: 'وَإِنَّهُۥ فِىٓ أُمِّ ٱلْكِتَٰبِ لَدَيْنَا لَعَلِىٌّ حَكِيمٌ',
        english: 'And indeed it is, in the Mother of the Book with Us, exalted and full of wisdom.',
        turkish: 'Şüphesiz o, katımızdaki Ana Kitap’ta yücedir, hikmet doludur.',
        source: 'Qur\'an 43:4',
        highlight: { english: 'Mother', turkish: 'Ana' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أمم',
        forms: [
          { label: 'plural', arabic: 'أُمَّهَات' },
        ],
        occurrences: 35,
        occurringForm: 'أُمِّ',
      },
    },
    {
      id: 'ithm',
      arabic: 'إِثْم',
      english: 'sin, guilt',
      turkish: 'günah',
      example: {
        arabic: 'ٱنظُرْ كَيْفَ يَفْتَرُونَ عَلَى ٱللَّهِ ٱلْكَذِبَ ۖ وَكَفَىٰ بِهِۦٓ إِثْمًۭا مُّبِينًا',
        english: 'Look how they invent lies about Allah, and sufficient is that as a manifest sin.',
        turkish: 'Bak, Allah’a karşı nasıl yalan uyduruyorlar! Apaçık bir günah olarak bu yeter.',
        source: 'Qur\'an 4:50',
        highlight: { english: 'sin', turkish: 'günah' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أثم',
        forms: [
          { label: 'plural', arabic: 'آثَام' },
        ],
        occurrences: 35,
        occurringForm: 'إِثْمًا',
      },
    },
    {
      id: 'akhtalafa',
      arabic: 'اخْتَلَفَ',
      english: 'to differ, to disagree',
      turkish: 'ayrılığa düşmek, ihtilaf etmek',
      example: {
        arabic: 'ٱللَّهُ يَحْكُمُ بَيْنَكُمْ يَوْمَ ٱلْقِيَٰمَةِ فِيمَا كُنتُمْ فِيهِ تَخْتَلِفُونَ',
        english: 'Allah will judge between you on the Day of Resurrection concerning that over which you used to differ.',
        turkish: 'Allah, kıyamet günü, ayrılığa düştüğünüz konularda aranızda hüküm verecektir.',
        source: 'Qur\'an 22:69',
        highlight: { english: 'differ', turkish: 'ayrılığa düştüğünüz' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'خلف',
        forms: [
          { label: 'mudari', arabic: 'يَخْتَلِفُ' },
          { label: 'masdar', arabic: 'اِخْتِلَاف' },
        ],
        occurrences: 35,
        occurringForm: 'تَخْتَلِفُونَ',
      },
    },
    {
      id: 'astawaa',
      arabic: 'اسْتَوَى',
      english: 'to establish oneself, to settle; to be even, equal',
      turkish: 'istiva etmek, yerleşmek; eşit olmak',
      example: {
        arabic: 'ٱلرَّحْمَٰنُ عَلَى ٱلْعَرْشِ ٱسْتَوَىٰ',
        english: 'The Most Merciful established Himself over the Throne.',
        turkish: 'Rahmân, Arş’a istiva etti.',
        source: 'Qur\'an 20:5',
        highlight: { english: 'established Himself', turkish: 'istiva etti' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سوي',
        forms: [
          { label: 'mudari', arabic: 'يَسْتَوِي' },
          { label: 'masdar', arabic: 'اِسْتِوَاء' },
        ],
        occurrences: 35,
        occurringForm: 'ٱسْتَوَىٰ',
      },
    },
    {
      id: 'bayyana',
      arabic: 'بَيَّنُ',
      english: 'to make clear, to explain',
      turkish: 'açıklamak, beyan etmek',
      example: {
        arabic: 'كَذَٰلِكَ يُبَيِّنُ ٱللَّهُ لَكُمْ ءَايَٰتِهِۦ لَعَلَّكُمْ تَعْقِلُونَ',
        english: 'Thus does Allah make clear to you His verses, that you might use reason.',
        turkish: 'Allah size ayetlerini böyle açıklıyor ki akledesiniz.',
        source: 'Qur\'an 2:242',
        highlight: { english: 'make clear', turkish: 'açıklıyor' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بين',
        forms: [
          { label: 'mudari', arabic: 'يُبَيِّنُ' },
          { label: 'masdar', arabic: 'تَبْيِين' },
        ],
        occurrences: 35,
        occurringForm: 'يُبَيِّنُ',
      },
    },
    {
      id: 'hiyn',
      arabic: 'حِين',
      english: 'time, while, moment',
      turkish: 'vakit, zaman, an',
      example: {
        arabic: 'وَأَنتُمْ حِينَئِذٍۢ تَنظُرُونَ',
        english: 'and you at that moment are looking on,',
        turkish: 've siz o anda bakıp durursunuz,',
        source: 'Qur\'an 56:84',
        highlight: { english: 'at that moment', turkish: 'o anda' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حين',
        forms: [
          { label: 'plural', arabic: 'أَحْيَان' },
        ],
        occurrences: 35,
        occurringForm: 'حِينَئِذٍ',
      },
    },
    {
      id: 'dhahaba',
      arabic: 'ذَهَبَ',
      english: 'to go, to depart',
      turkish: 'gitmek',
      example: {
        arabic: 'ٱذْهَبْ إِلَىٰ فِرْعَوْنَ إِنَّهُۥ طَغَىٰ',
        english: 'Go to Pharaoh; indeed, he has transgressed.',
        turkish: 'Firavun’a git; çünkü o azdı.',
        source: 'Qur\'an 79:17',
        highlight: { english: 'Go', turkish: 'git' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ذهب',
        forms: [
          { label: 'mudari', arabic: 'يَذْهَبُ' },
          { label: 'masdar', arabic: 'ذَهَاب' },
        ],
        occurrences: 35,
        occurringForm: 'ٱذْهَبْ',
      },
    },
    {
      id: 'sajada',
      arabic: 'سَجَدَ',
      english: 'to prostrate, to bow down',
      turkish: 'secde etmek',
      example: {
        arabic: 'وَلِلَّهِ يَسْجُدُ مَن فِى ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ طَوْعًۭا وَكَرْهًۭا وَظِلَٰلُهُم بِٱلْغُدُوِّ وَٱلْءَاصَالِ ۩',
        english: 'And to Allah prostrates whoever is in the heavens and the earth, willingly or unwillingly, and their shadows too, in the mornings and the evenings.',
        turkish: 'Göklerde ve yerde kim varsa, gölgeleri de sabah akşam, ister istemez Allah’a secde eder.',
        source: 'Qur\'an 13:15',
        highlight: { english: 'prostrates', turkish: 'secde eder' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سجد',
        forms: [
          { label: 'mudari', arabic: 'يَسْجُدُ' },
          { label: 'masdar', arabic: 'سُجُود' },
        ],
        occurrences: 35,
        occurringForm: 'يَسْجُدُ',
      },
    },
    {
      id: 'mata-2',
      arabic: 'مَتاع',
      english: 'provision, enjoyment, goods',
      turkish: 'geçimlik, fayda, mal',
      example: {
        arabic: 'مَتَٰعًۭا لَّكُمْ وَلِأَنْعَٰمِكُمْ',
        english: 'as provision for you and for your livestock.',
        turkish: 'size ve hayvanlarınıza geçimlik olarak.',
        source: 'Qur\'an 79:33',
        highlight: { english: 'provision', turkish: 'geçimlik' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'متع',
        forms: [
          { label: 'plural', arabic: 'أَمْتِعَة' },
        ],
        occurrences: 35,
        occurringForm: 'مَتَٰعًا',
      },
    },
    {
      id: 'mursal',
      arabic: 'مُرْسَل',
      english: 'sent one, messenger',
      turkish: 'gönderilen, elçi',
      example: {
        arabic: 'إِذْ أَرْسَلْنَآ إِلَيْهِمُ ٱثْنَيْنِ فَكَذَّبُوهُمَا فَعَزَّزْنَا بِثَالِثٍۢ فَقَالُوٓا۟ إِنَّآ إِلَيْكُم مُّرْسَلُونَ',
        english: 'When We sent to them two, but they denied them, so We strengthened them with a third, and they said: Indeed, we are messengers sent to you.',
        turkish: 'Onlara iki elçi göndermiştik de onları yalanlamışlardı; biz de bir üçüncüsüyle destekledik ve dediler ki: Şüphesiz biz size gönderilmiş elçileriz.',
        source: 'Qur\'an 36:14',
        highlight: { english: 'messengers sent', turkish: 'gönderilmiş elçileriz' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'رسل',
        forms: [
          { label: 'plural', arabic: 'مُرْسَلُون' },
        ],
        occurrences: 35,
        occurringForm: 'مُّرْسَلُونَ',
      },
    },
    {
      id: 'nasiya',
      arabic: 'نَسِيَ',
      english: 'to forget',
      turkish: 'unutmak',
      example: {
        arabic: 'سَنُقْرِئُكَ فَلَا تَنسَىٰٓ',
        english: 'We will make you recite, so you will not forget,',
        turkish: 'Sana okutacağız ve unutmayacaksın,',
        source: 'Qur\'an 87:6',
        highlight: { english: 'forget', turkish: 'unutmayacaksın' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نسي',
        forms: [
          { label: 'mudari', arabic: 'يَنْسَى' },
          { label: 'masdar', arabic: 'نِسْيَان' },
        ],
        occurrences: 35,
        occurringForm: 'تَنسَىٰٓ',
      },
    },
    {
      id: 'nasiyr',
      arabic: 'نَصِير',
      english: 'helper, supporter',
      turkish: 'yardımcı',
      example: {
        arabic: 'خَٰلِدِينَ فِيهَآ أَبَدًۭا ۖ لَّا يَجِدُونَ وَلِيًّۭا وَلَا نَصِيرًۭا',
        english: 'abiding therein forever; they will find no protector and no helper.',
        turkish: 'Orada ebediyen kalıcıdırlar; ne bir dost ne de bir yardımcı bulurlar.',
        source: 'Qur\'an 33:65',
        highlight: { english: 'helper', turkish: 'yardımcı' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نصر',
        forms: [
          { label: 'plural', arabic: 'نُصَرَاء' },
        ],
        occurrences: 35,
        occurringForm: 'نَصِيرًا',
      },
    },
    {
      id: 'ala-2-2',
      arabic: 'آلاء',
      english: 'favours, blessings',
      turkish: 'nimetler',
      example: {
        arabic: 'فَبِأَىِّ ءَالَآءِ رَبِّكَ تَتَمَارَىٰ',
        english: 'Then which of the favours of your Lord do you doubt?',
        turkish: 'Öyleyse Rabbinin nimetlerinin hangisinden şüphe edersin?',
        source: 'Qur\'an 53:55',
        highlight: { english: 'favours', turkish: 'nimetlerinin' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ألو',
        occurrences: 34,
        occurringForm: 'ءَالَآءِ',
      },
    },
    {
      id: 'abtaghaa',
      arabic: 'ابْتَغَى',
      english: 'to seek, to desire',
      turkish: 'aramak, istemek',
      example: {
        arabic: 'فَمَنِ ٱبْتَغَىٰ وَرَآءَ ذَٰلِكَ فَأُو۟لَٰٓئِكَ هُمُ ٱلْعَادُونَ',
        english: 'But whoever seeks beyond that, those are the transgressors.',
        turkish: 'Kim bunun ötesini ararsa, işte onlar haddi aşanlardır.',
        source: 'Qur\'an 23:7',
        highlight: { english: 'seeks', turkish: 'ararsa' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بغي',
        forms: [
          { label: 'mudari', arabic: 'يَبْتَغِي' },
          { label: 'masdar', arabic: 'اِبْتِغَاء' },
        ],
        occurrences: 34,
        occurringForm: 'ٱبْتَغَىٰ',
      },
    },
    {
      id: 'fitna',
      arabic: 'فِتْنَة',
      english: 'trial, temptation; discord',
      turkish: 'imtihan, fitne, ayartma',
      example: {
        arabic: 'إِنَّا جَعَلْنَٰهَا فِتْنَةًۭ لِّلظَّٰلِمِينَ',
        english: 'Indeed, We have made it a trial for the wrongdoers.',
        turkish: 'Şüphesiz biz onu zalimler için bir imtihan kıldık.',
        source: 'Qur\'an 37:63',
        highlight: { english: 'trial', turkish: 'imtihan' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'فتن',
        forms: [
          { label: 'plural', arabic: 'فِتَن' },
        ],
        occurrences: 34,
        occurringForm: 'فِتْنَةً',
      },
    },
    {
      id: 'maryam',
      arabic: 'مَرْيَم',
      english: 'Mary',
      turkish: 'Meryem',
      example: {
        arabic: 'وَبِكُفْرِهِمْ وَقَوْلِهِمْ عَلَىٰ مَرْيَمَ بُهْتَٰنًا عَظِيمًۭا',
        english: 'and for their disbelief and their utterance against Mary of a great slander,',
        turkish: 'İnkârları ve Meryem’e karşı büyük bir iftira söylemeleri sebebiyle,',
        source: 'Qur\'an 4:156',
        highlight: { english: 'Mary', turkish: 'Meryem' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 34,
        occurringForm: 'مَرْيَمَ',
      },
    },
    {
      id: 'haram',
      arabic: 'حَرام',
      english: 'forbidden; sacred, inviolable',
      turkish: 'haram, yasak; dokunulmaz',
      example: {
        arabic: 'وَحَرَٰمٌ عَلَىٰ قَرْيَةٍ أَهْلَكْنَٰهَآ أَنَّهُمْ لَا يَرْجِعُونَ',
        english: 'And it is forbidden for a town which We have destroyed that they should return.',
        turkish: 'Helak ettiğimiz bir beldenin geri dönmesi haram kılınmıştır.',
        source: 'Qur\'an 21:95',
        highlight: { english: 'forbidden', turkish: 'haram kılınmıştır' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حرم',
        forms: [
          { label: 'plural', arabic: 'حُرُم' },
        ],
        occurrences: 33,
        occurringForm: 'وَحَرَٰمٌ',
      },
    },
    {
      id: 'shams',
      arabic: 'شَمْس',
      english: 'sun',
      turkish: 'güneş',
      example: {
        arabic: 'مُّتَّكِـِٔينَ فِيهَا عَلَى ٱلْأَرَآئِكِ ۖ لَا يَرَوْنَ فِيهَا شَمْسًۭا وَلَا زَمْهَرِيرًۭا',
        english: 'Reclining therein on couches, they will see there neither sun nor bitter cold.',
        turkish: 'Orada tahtlara kurulmuşlardır; ne yakıcı bir güneş ne de dondurucu bir soğuk görürler.',
        source: 'Qur\'an 76:13',
        highlight: { english: 'sun', turkish: 'güneş' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شمس',
        forms: [
          { label: 'plural', arabic: 'شُمُوس' },
        ],
        occurrences: 33,
        occurringForm: 'شَمْسًا',
      },
    },
    {
      id: 'fariyq',
      arabic: 'فَرِيق',
      english: 'party, group',
      turkish: 'grup, taraf, bölük',
      example: {
        arabic: 'أَوَكُلَّمَا عَٰهَدُوا۟ عَهْدًۭا نَّبَذَهُۥ فَرِيقٌۭ مِّنْهُم ۚ بَلْ أَكْثَرُهُمْ لَا يُؤْمِنُونَ',
        english: 'Is it not that every time they made a covenant, a party of them cast it aside? Rather, most of them do not believe.',
        turkish: 'Ne zaman bir ahit yaptılarsa, içlerinden bir grup onu bozup atmadı mı? Doğrusu onların çoğu iman etmez.',
        source: 'Qur\'an 2:100',
        highlight: { english: 'a party', turkish: 'bir grup' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'فرق',
        occurrences: 33,
        occurringForm: 'فَرِيقٌ',
      },
    },
    {
      id: 'qama',
      arabic: 'قامَ',
      english: 'to stand, to rise',
      turkish: 'kalkmak, ayağa kalkmak',
      example: {
        arabic: 'قُمْ فَأَنذِرْ',
        english: 'Arise and warn,',
        turkish: 'Kalk ve uyar,',
        source: 'Qur\'an 74:2',
        highlight: { english: 'Arise', turkish: 'Kalk' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'قوم',
        forms: [
          { label: 'mudari', arabic: 'يَقُومُ' },
          { label: 'masdar', arabic: 'قِيَام' },
        ],
        occurrences: 33,
        occurringForm: 'قُمْ',
      },
    },
    {
      id: 'kadhib',
      arabic: 'كَذِب',
      english: 'lie, falsehood',
      turkish: 'yalan',
      example: {
        arabic: 'وَأَنَّا ظَنَنَّآ أَن لَّن تَقُولَ ٱلْإِنسُ وَٱلْجِنُّ عَلَى ٱللَّهِ كَذِبًۭا',
        english: 'And we had thought that mankind and the jinn would never speak a lie about Allah.',
        turkish: 'Biz, insanların ve cinlerin Allah’a karşı asla yalan söylemeyeceğini sanmıştık.',
        source: 'Qur\'an 72:5',
        highlight: { english: 'a lie', turkish: 'yalan' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كذب',
        occurrences: 33,
        occurringForm: 'كَذِبًا',
      },
    },
    {
      id: 'kalla',
      arabic: 'كَلّا',
      english: 'nay, by no means',
      turkish: 'hayır, asla',
      example: {
        arabic: 'كَلَّا سَيَعْلَمُونَ',
        english: 'No! They are going to know.',
        turkish: 'Hayır! Yakında bilecekler.',
        source: 'Qur\'an 78:4',
        highlight: { english: 'No', turkish: 'Hayır' },
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 33,
        occurringForm: 'كَلَّا',
      },
    },
    {
      id: 'arada-2',
      arabic: 'أَعْرَضَ',
      english: 'to turn away, to shun',
      turkish: 'yüz çevirmek',
      example: {
        arabic: 'مَّنْ أَعْرَضَ عَنْهُ فَإِنَّهُۥ يَحْمِلُ يَوْمَ ٱلْقِيَٰمَةِ وِزْرًا',
        english: 'Whoever turns away from it will bear a burden on the Day of Resurrection,',
        turkish: 'Kim ondan yüz çevirirse, kıyamet günü bir günah yükü taşıyacaktır,',
        source: 'Qur\'an 20:100',
        highlight: { english: 'turns away', turkish: 'yüz çevirirse' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عرض',
        forms: [
          { label: 'mudari', arabic: 'يُعْرِضُ' },
          { label: 'masdar', arabic: 'إِعْرَاض' },
        ],
        occurrences: 32,
        occurringForm: 'أَعْرَضَ',
      },
    },
    {
      id: 'khasir',
      arabic: 'خاسِر',
      english: 'loser, one who loses out',
      turkish: 'kaybeden, hüsrana uğrayan',
      example: {
        arabic: 'يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوٓا۟ إِن تُطِيعُوا۟ ٱلَّذِينَ كَفَرُوا۟ يَرُدُّوكُمْ عَلَىٰٓ أَعْقَٰبِكُمْ فَتَنقَلِبُوا۟ خَٰسِرِينَ',
        english: 'O you who have believed, if you obey those who disbelieve, they will turn you back on your heels, and you will turn back as losers.',
        turkish: 'Ey iman edenler! İnkâr edenlere itaat ederseniz, sizi topuklarınız üzerinde gerisin geri çevirirler de hüsrana uğrayanlar olarak dönersiniz.',
        source: 'Qur\'an 3:149',
        highlight: { english: 'losers', turkish: 'hüsrana uğrayanlar' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'خسر',
        forms: [
          { label: 'plural', arabic: 'خَاسِرُون' },
        ],
        occurrences: 32,
        occurringForm: 'خَٰسِرِينَ',
      },
    },
    {
      id: 'dhurriyya',
      arabic: 'ذُرِّيَّة',
      english: 'offspring, progeny',
      turkish: 'zürriyet, soy, nesil',
      example: {
        arabic: 'ذُرِّيَّةًۢ بَعْضُهَا مِنۢ بَعْضٍۢ ۗ وَٱللَّهُ سَمِيعٌ عَلِيمٌ',
        english: 'descendants, some of them from others. And Allah is Hearing and Knowing.',
        turkish: 'Birbirinden gelen bir soy olarak. Allah işitendir, bilendir.',
        source: 'Qur\'an 3:34',
        highlight: { english: 'descendants', turkish: 'soy' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ذرر',
        forms: [
          { label: 'plural', arabic: 'ذُرِّيَّات' },
        ],
        occurrences: 32,
        occurringForm: 'ذُرِّيَّةًۢ',
      },
    },
    {
      id: 'zaka',
      arabic: 'زَكاة',
      english: 'purity; alms, zakat',
      turkish: 'arınmışlık, temizlik; zekât',
      example: {
        arabic: 'فَأَرَدْنَآ أَن يُبْدِلَهُمَا رَبُّهُمَا خَيْرًۭا مِّنْهُ زَكَوٰةًۭ وَأَقْرَبَ رُحْمًۭا',
        english: 'So we intended that their Lord should give them in exchange one better than him in purity and nearer to mercy.',
        turkish: 'Rablerinin onlara, ondan daha temiz ve merhamete daha yakın birini vermesini diledik.',
        source: 'Qur\'an 18:81',
        highlight: { english: 'purity', turkish: 'temiz' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'زكو',
        occurrences: 32,
        occurringForm: 'زَكَوٰةً',
      },
    },
    {
      id: 'aqiba',
      arabic: 'عاقِبَة',
      english: 'outcome, end, consequence',
      turkish: 'akıbet, son',
      example: {
        arabic: 'فَٱنظُرْ كَيْفَ كَانَ عَٰقِبَةُ ٱلْمُنذَرِينَ',
        english: 'Then look how was the end of those who were warned,',
        turkish: 'Bak, uyarılanların sonu nasıl oldu,',
        source: 'Qur\'an 37:73',
        highlight: { english: 'the end', turkish: 'sonu' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عقب',
        forms: [
          { label: 'plural', arabic: 'عَوَاقِب' },
        ],
        occurrences: 32,
        occurringForm: 'عَٰقِبَةُ',
      },
    },
    {
      id: 'kadhib-2',
      arabic: 'كاذِب',
      english: 'liar, lying',
      turkish: 'yalancı',
      example: {
        arabic: 'نَاصِيَةٍۢ كَٰذِبَةٍ خَاطِئَةٍۢ',
        english: 'a lying, sinful forelock.',
        turkish: 'Yalancı, günahkâr bir perçemi.',
        source: 'Qur\'an 96:16',
        highlight: { english: 'lying', turkish: 'Yalancı' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كذب',
        forms: [
          { label: 'plural', arabic: 'كَاذِبُون' },
        ],
        occurrences: 32,
        occurringForm: 'كَٰذِبَةٍ',
      },
    },
    {
      id: 'kafaa',
      arabic: 'كَفَى',
      english: 'to suffice, to be enough',
      turkish: 'yetmek, kâfi gelmek',
      example: {
        arabic: 'ٱقْرَأْ كِتَٰبَكَ كَفَىٰ بِنَفْسِكَ ٱلْيَوْمَ عَلَيْكَ حَسِيبًۭا',
        english: 'Read your record. Sufficient is your own self this day as an accountant against you.',
        turkish: 'Kitabını oku! Bugün kendi nefsin, sana karşı hesap görücü olarak yeter.',
        source: 'Qur\'an 17:14',
        highlight: { english: 'Sufficient', turkish: 'yeter' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'كفي',
        forms: [
          { label: 'mudari', arabic: 'يَكْفِي' },
          { label: 'masdar', arabic: 'كِفَايَة' },
        ],
        occurrences: 32,
        occurringForm: 'كَفَىٰ',
      },
    },
    {
      id: 'nahaa',
      arabic: 'نَهَى',
      english: 'to forbid, to prohibit',
      turkish: 'yasaklamak, menetmek',
      example: {
        arabic: 'أَرَءَيْتَ ٱلَّذِى يَنْهَىٰ',
        english: 'Have you seen the one who forbids',
        turkish: 'Gördün mü şu engelleyeni,',
        source: 'Qur\'an 96:9',
        highlight: { english: 'forbids', turkish: 'engelleyeni' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نهي',
        forms: [
          { label: 'mudari', arabic: 'يَنْهَى' },
          { label: 'masdar', arabic: 'نَهْي' },
        ],
        occurrences: 32,
        occurringForm: 'يَنْهَىٰ',
      },
    },
    {
      id: 'ashadd',
      arabic: 'أَشَدّ',
      english: 'stronger, more severe',
      turkish: 'daha güçlü, daha şiddetli',
      example: {
        arabic: 'ءَأَنتُمْ أَشَدُّ خَلْقًا أَمِ ٱلسَّمَآءُ ۚ بَنَىٰهَا',
        english: 'Are you harder to create, or the sky? He built it.',
        turkish: 'Sizi yaratmak mı daha güçtür, yoksa göğü mü? Onu O bina etti.',
        source: 'Qur\'an 79:27',
        highlight: { english: 'harder', turkish: 'daha güçtür' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شدد',
        occurrences: 31,
        occurringForm: 'أَشَدُّ',
      },
    },
    {
      id: 'idhana',
      arabic: 'إِذًا',
      english: 'then, in that case',
      turkish: 'öyleyse, o halde',
      example: {
        arabic: 'تِلْكَ إِذًۭا قِسْمَةٌۭ ضِيزَىٰٓ',
        english: 'That, then, is an unfair division.',
        turkish: 'Öyleyse bu, insafsız bir paylaştırmadır.',
        source: 'Qur\'an 53:22',
        highlight: { english: 'then', turkish: 'Öyleyse' },
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 31,
        occurringForm: 'إِذًا',
      },
    },
    {
      id: 'hasana',
      arabic: 'حَسَنَة',
      english: 'good deed, good thing',
      turkish: 'iyilik, güzellik',
      example: {
        arabic: 'وَءَاتَيْنَٰهُ فِى ٱلدُّنْيَا حَسَنَةًۭ ۖ وَإِنَّهُۥ فِى ٱلْءَاخِرَةِ لَمِنَ ٱلصَّٰلِحِينَ',
        english: 'And We gave him good in this world, and indeed, in the Hereafter he is among the righteous.',
        turkish: 'Ona dünyada iyilik verdik; şüphesiz o, ahirette de salihlerdendir.',
        source: 'Qur\'an 16:122',
        highlight: { english: 'good', turkish: 'iyilik' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حسن',
        forms: [
          { label: 'plural', arabic: 'حَسَنَات' },
        ],
        occurrences: 31,
        occurringForm: 'حَسَنَةً',
      },
    },
    {
      id: 'hayth',
      arabic: 'حَيْث',
      english: 'where, wherever',
      turkish: '-dığı yer, nerede',
      example: {
        arabic: 'وَٱلَّذِينَ كَذَّبُوا۟ بِـَٔايَٰتِنَا سَنَسْتَدْرِجُهُم مِّنْ حَيْثُ لَا يَعْلَمُونَ',
        english: 'And those who denied Our signs, We will lead them on step by step from where they do not know.',
        turkish: 'Ayetlerimizi yalanlayanları, bilmedikleri yerden adım adım helake götüreceğiz.',
        source: 'Qur\'an 7:182',
        highlight: { english: 'from where', turkish: 'yerden' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حيث',
        occurrences: 31,
        occurringForm: 'حَيْثُ',
      },
    },
    {
      id: 'kaann',
      arabic: 'كَأَنّ',
      english: 'as if, as though',
      turkish: 'sanki, -mış gibi',
      example: {
        arabic: 'كَأَنَّهُنَّ بَيْضٌۭ مَّكْنُونٌۭ',
        english: 'as if they were eggs, carefully sheltered.',
        turkish: 'Sanki onlar, korunmuş yumurtalardır.',
        source: 'Qur\'an 37:49',
        highlight: { english: 'as if', turkish: 'Sanki' },
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 31,
        occurringForm: 'كَأَنَّهُنَّ',
      },
    },
    {
      id: 'nafaa',
      arabic: 'نَفَعَ',
      english: 'to benefit, to profit',
      turkish: 'fayda vermek, yararlı olmak',
      example: {
        arabic: 'فَذَكِّرْ إِن نَّفَعَتِ ٱلذِّكْرَىٰ',
        english: 'So remind, if the reminder benefits.',
        turkish: 'Öğüt ver, eğer öğüt fayda verirse.',
        source: 'Qur\'an 87:9',
        highlight: { english: 'benefits', turkish: 'fayda verirse' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نفع',
        forms: [
          { label: 'mudari', arabic: 'يَنْفَعُ' },
          { label: 'masdar', arabic: 'نَفْع' },
        ],
        occurrences: 31,
        occurringForm: 'نَّفَعَتِ',
      },
    },
    {
      id: 'wahida',
      arabic: 'واحِدَة',
      english: 'one, single',
      turkish: 'bir, tek',
      example: {
        arabic: 'فَإِنَّمَا هِىَ زَجْرَةٌۭ وَٰحِدَةٌۭ',
        english: 'It will be but a single shout,',
        turkish: 'O, ancak tek bir haykırıştır,',
        source: 'Qur\'an 79:13',
        highlight: { english: 'a single', turkish: 'tek' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'وحد',
        occurrences: 31,
        occurringForm: 'وَٰحِدَةٌ',
      },
    },
    {
      id: 'hukm',
      arabic: 'حُكْم',
      english: 'judgment, authority to judge; wisdom',
      turkish: 'hüküm, yargı; hikmet',
      example: {
        arabic: 'رَبِّ هَبْ لِى حُكْمًۭا وَأَلْحِقْنِى بِٱلصَّٰلِحِينَ',
        english: 'My Lord, grant me judgment and join me with the righteous,',
        turkish: 'Rabbim! Bana hüküm ver ve beni salihlere kat,',
        source: 'Qur\'an 26:83',
        highlight: { english: 'judgment', turkish: 'hüküm' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حكم',
        forms: [
          { label: 'plural', arabic: 'أَحْكَام' },
        ],
        occurrences: 30,
        occurringForm: 'حُكْمًا',
      },
    },
    {
      id: 'saa-2',
      arabic: 'ساءَ',
      english: 'to be evil, to be wretched',
      turkish: 'kötü olmak, fena olmak',
      example: {
        arabic: 'إِنَّهَا سَآءَتْ مُسْتَقَرًّۭا وَمُقَامًۭا',
        english: 'Indeed, it is evil as a settlement and a residence.',
        turkish: 'Şüphesiz orası, durak ve konak olarak ne kötüdür.',
        source: 'Qur\'an 25:66',
        highlight: { english: 'is evil', turkish: 'ne kötüdür' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سوأ',
        forms: [
          { label: 'mudari', arabic: 'يَسُوءُ' },
          { label: 'masdar', arabic: 'سُوء' },
        ],
        occurrences: 30,
        occurringForm: 'سَآءَتْ',
      },
    },
    {
      id: 'sharr',
      arabic: 'شَرّ',
      english: 'evil, harm',
      turkish: 'kötülük, şer',
      example: {
        arabic: 'مِن شَرِّ مَا خَلَقَ',
        english: 'from the evil of what He created,',
        turkish: 'Yarattığı şeylerin şerrinden,',
        source: 'Qur\'an 113:2',
        highlight: { english: 'the evil', turkish: 'şerrinden' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شرر',
        forms: [
          { label: 'plural', arabic: 'شُرُور' },
        ],
        occurrences: 30,
        occurringForm: 'شَرِّ',
      },
    },
    {
      id: 'tayyiba',
      arabic: 'طَيِّبَة',
      english: 'good, pure, wholesome',
      turkish: 'temiz, hoş, güzel',
      example: {
        arabic: 'يَٰٓأَيُّهَا ٱلرُّسُلُ كُلُوا۟ مِنَ ٱلطَّيِّبَٰتِ وَٱعْمَلُوا۟ صَٰلِحًا ۖ إِنِّى بِمَا تَعْمَلُونَ عَلِيمٌۭ',
        english: 'O messengers, eat from the good things and do righteousness; indeed, I am Knowing of what you do.',
        turkish: 'Ey elçiler! Temiz şeylerden yiyin ve salih amel işleyin; şüphesiz ben, yaptıklarınızı bilirim.',
        source: 'Qur\'an 23:51',
        highlight: { english: 'good things', turkish: 'Temiz' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'طيب',
        forms: [
          { label: 'plural', arabic: 'طَيِّبَات' },
        ],
        occurrences: 30,
        occurringForm: 'ٱلطَّيِّبَٰتِ',
      },
    },
    {
      id: 'ad',
      arabic: 'عاد',
      english: 'Ad (the people of Hud)',
      turkish: 'Âd (kavmi)',
      example: {
        arabic: 'كَذَّبَتْ عَادٌ ٱلْمُرْسَلِينَ',
        english: 'Ad denied the messengers,',
        turkish: 'Âd kavmi de elçileri yalanladı,',
        source: 'Qur\'an 26:123',
        highlight: { english: 'Ad', turkish: 'Âd' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عدو',
        occurrences: 30,
        occurringForm: 'عَادٌ',
      },
    },
    {
      id: 'asaa',
      arabic: 'عَسَى',
      english: 'perhaps, it may be that',
      turkish: 'belki, umulur ki',
      example: {
        arabic: 'قُلْ عَسَىٰٓ أَن يَكُونَ رَدِفَ لَكُم بَعْضُ ٱلَّذِى تَسْتَعْجِلُونَ',
        english: 'Say: Perhaps some of what you seek to hasten has drawn up close behind you.',
        turkish: 'De ki: Belki de acele istediğiniz şeyin bir kısmı ardınıza takılmıştır.',
        source: 'Qur\'an 27:72',
        highlight: { english: 'Perhaps', turkish: 'Belki' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عسي',
        occurrences: 30,
        occurringForm: 'عَسَىٰٓ',
      },
    },
    {
      id: 'quwwa',
      arabic: 'قُوَّة',
      english: 'strength, power',
      turkish: 'güç, kuvvet',
      example: {
        arabic: 'ذِى قُوَّةٍ عِندَ ذِى ٱلْعَرْشِ مَكِينٍۢ',
        english: 'possessor of strength, secure in rank with the Owner of the Throne,',
        turkish: 'Güç sahibi, Arş’ın sahibi katında itibarlı,',
        source: 'Qur\'an 81:20',
        highlight: { english: 'strength', turkish: 'Güç' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قوي',
        forms: [
          { label: 'plural', arabic: 'قُوَى' },
        ],
        occurrences: 30,
        occurringForm: 'قُوَّةٍ',
      },
    },
    {
      id: 'kariym',
      arabic: 'كَرِيم',
      english: 'noble, generous, honourable',
      turkish: 'cömert, değerli, şerefli',
      example: {
        arabic: 'كِرَامٍۭ بَرَرَةٍۢ',
        english: 'noble and dutiful.',
        turkish: 'Şerefli ve iyilik sever olan.',
        source: 'Qur\'an 80:16',
        highlight: { english: 'noble', turkish: 'Şerefli' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كرم',
        forms: [
          { label: 'plural', arabic: 'كِرَام' },
        ],
        occurrences: 30,
        occurringForm: 'كِرَامٍۭ',
      },
    },
    {
      id: 'labitha',
      arabic: 'لَبِثَ',
      english: 'to remain, to stay, to tarry',
      turkish: 'kalmak, durmak',
      example: {
        arabic: 'يَتَخَٰفَتُونَ بَيْنَهُمْ إِن لَّبِثْتُمْ إِلَّا عَشْرًۭا',
        english: 'They will murmur among themselves: You remained only ten.',
        turkish: 'Aralarında fısıldaşırlar: Ancak on gün kaldınız.',
        source: 'Qur\'an 20:103',
        highlight: { english: 'remained', turkish: 'kaldınız' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'لبث',
        forms: [
          { label: 'mudari', arabic: 'يَلْبَثُ' },
        ],
        occurrences: 30,
        occurringForm: 'لَّبِثْتُمْ',
      },
    },
  ],
}
