import type { DeckDef } from '../types'

// Quran Vocabulary, level 11. See GitHub issue #8.
//
// Scaffolded by scripts/generateVocab.ts: the headword, root, occurrence count,
// ayah and citation come from the corpus and the canonical text. The meanings,
// principal parts and ayah translations were authored on top of that scaffold.
//
// Where the corpus lemmatizes a word to a passive, an imperative or a mudari
// that nobody looks up, the note id is the dictionary form while the headword
// stays as the corpus has it, since that is what the ayah shows.
//
// DRAFT: verify every English meaning before memorizing it. Turkish is
// convenience text and stays draft - correct it on sight while studying.
//
// Locked until the previous level is mostly graduated; see quranVocabTrack.ts.

export const quranVocab11: DeckDef = {
  id: 'quran-vocab-11',
  name: { english: 'Quran Vocabulary 11', turkish: 'Kur’an Kelimeleri 11' },
  nameArabic: 'مُفْرَدَاتُ الْقُرْآنِ ١١',
  description: {
    english:
      'Frequency band 11 of the Quran vocabulary track, each word with an ayah where it occurs.',
    turkish:
      'Kur’an kelime yolunun 11. sıklık kuşağı; her kelime geçtiği bir ayetle.',
  },
  directions: ['ar-to-meaning'],
  newPerDay: 10,
  burySiblings: true,
  notes: [
    {
      id: 'fawz',
      arabic: 'فَوْز',
      english: 'success, attainment, triumph',
      turkish: 'kurtuluş, zafer, başarı',
      example: {
        arabic: 'إِنَّ هَٰذَا لَهُوَ ٱلْفَوْزُ ٱلْعَظِيمُ',
        english: 'Indeed, this is the great attainment.',
        turkish: 'Şüphesiz bu, gerçekten büyük kurtuluştur.',
        source: 'Qur\'an 37:60',
        highlight: { english: 'attainment', turkish: 'kurtuluştur' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'فوز',
        occurrences: 19,
        occurringForm: 'ٱلْفَوْزُ',
      },
    },
    {
      id: 'musaddiq',
      arabic: 'مُصَدِّق',
      english: 'confirming, confirmer',
      turkish: 'doğrulayıcı, tasdik eden',
      example: {
        arabic: 'نَزَّلَ عَلَيْكَ ٱلْكِتَٰبَ بِٱلْحَقِّ مُصَدِّقًۭا لِّمَا بَيْنَ يَدَيْهِ وَأَنزَلَ ٱلتَّوْرَىٰةَ وَٱلْإِنجِيلَ',
        english: 'He sent down to you the Book in truth, confirming what came before it, and He sent down the Torah and the Gospel,',
        turkish: 'Sana Kitab’ı, kendinden öncekini doğrulayıcı olarak hak ile indirdi; Tevrat’ı ve İncil’i de indirdi,',
        source: 'Qur\'an 3:3',
        highlight: { english: 'confirming', turkish: 'doğrulayıcı' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صدق',
        forms: [
          { label: 'plural', arabic: 'مُصَدِّقُونَ' },
        ],
        occurrences: 19,
        occurringForm: 'مُصَدِّقًا',
      },
    },
    {
      id: 'murid',
      arabic: 'مُعْرِض',
      english: 'turning away, averse',
      turkish: 'yüz çeviren, aldırmayan',
      example: {
        arabic: 'أَنتُمْ عَنْهُ مُعْرِضُونَ',
        english: 'from which you turn away.',
        turkish: 'Sizin ondan yüz çevirdiğiniz.',
        source: 'Qur\'an 38:68',
        highlight: { english: 'turn away', turkish: 'yüz çevirdiğiniz' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عرض',
        forms: [
          { label: 'plural', arabic: 'مُعْرِضُونَ' },
        ],
        occurrences: 19,
        occurringForm: 'مُعْرِضُونَ',
      },
    },
    {
      id: 'makr',
      arabic: 'مَكْر',
      english: 'plot, scheme, cunning',
      turkish: 'tuzak, hile, düzen',
      example: {
        arabic: 'وَمَكَرُوا۟ مَكْرًۭا كُبَّارًۭا',
        english: 'And they plotted a mighty plot.',
        turkish: 'Ve büyük bir tuzak kurdular.',
        source: 'Qur\'an 71:22',
        highlight: { english: 'a mighty plot', turkish: 'tuzak' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'مكر',
        occurrences: 19,
        occurringForm: 'مَكْرًا',
      },
    },
    {
      id: 'nafakha',
      arabic: 'نَفَخَ',
      english: 'to blow, to breathe into',
      turkish: 'üflemek',
      example: {
        arabic: 'يَوْمَ يُنفَخُ فِى ٱلصُّورِ فَتَأْتُونَ أَفْوَاجًۭا',
        english: 'The Day the Horn is blown, and you will come in crowds,',
        turkish: 'Sûr’a üflendiği gün, bölük bölük gelirsiniz,',
        source: 'Qur\'an 78:18',
        highlight: { english: 'is blown', turkish: 'üflendiği' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نفخ',
        forms: [
          { label: 'mudari', arabic: 'يَنْفُخُ' },
          { label: 'masdar', arabic: 'نَفْخ' },
        ],
        occurrences: 19,
        occurringForm: 'يُنفَخُ',
      },
    },
    {
      id: 'darra',
      arabic: 'يَضُرَّ',
      english: 'to harm, to hurt',
      turkish: 'zarar vermek',
      example: {
        arabic: 'أَوْ يَنفَعُونَكُمْ أَوْ يَضُرُّونَ',
        english: 'or do they benefit you, or harm you?',
        turkish: 'yahut size fayda veya zarar verirler mi?',
        source: 'Qur\'an 26:73',
        highlight: { english: 'harm', turkish: 'zarar' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ضرر',
        forms: [
          { label: 'mudari', arabic: 'يَضُرُّ' },
        ],
        occurrences: 19,
        occurringForm: 'يَضُرُّونَ',
      },
    },
    {
      id: 'faqiha',
      arabic: 'يَفْقَهُ',
      english: 'to understand, to grasp',
      turkish: 'anlamak, kavramak',
      example: {
        arabic: 'يَفْقَهُوا۟ قَوْلِى',
        english: 'that they may understand my speech.',
        turkish: 'Sözümü anlasınlar.',
        source: 'Qur\'an 20:28',
        highlight: { english: 'understand', turkish: 'anlasınlar' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'فقه',
        forms: [
          { label: 'mudari', arabic: 'يَفْقَهُ' },
          { label: 'masdar', arabic: 'فِقْه' },
        ],
        occurrences: 19,
        occurringForm: 'يَفْقَهُوا۟',
      },
    },
    {
      id: 'akhfaa',
      arabic: 'أُخْفِيَ',
      english: 'to hide, to conceal',
      turkish: 'gizlemek, saklamak',
      example: {
        arabic: 'يَعْلَمُ خَآئِنَةَ ٱلْأَعْيُنِ وَمَا تُخْفِى ٱلصُّدُورُ',
        english: 'He knows the treachery of the eyes and what the breasts conceal.',
        turkish: 'O, gözlerin hain bakışını ve göğüslerin gizlediğini bilir.',
        source: 'Qur\'an 40:19',
        highlight: { english: 'conceal', turkish: 'gizlediğini' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'خفي',
        forms: [
          { label: 'mudari', arabic: 'يُخْفِي' },
          { label: 'masdar', arabic: 'إِخْفَاء' },
        ],
        occurrences: 18,
        occurringForm: 'تُخْفِى',
      },
    },
    {
      id: 'udhun',
      arabic: 'أُذُن',
      english: 'ear',
      turkish: 'kulak',
      example: {
        arabic: 'لِنَجْعَلَهَا لَكُمْ تَذْكِرَةًۭ وَتَعِيَهَآ أُذُنٌۭ وَٰعِيَةٌۭ',
        english: 'so that We might make it a reminder for you, and that a retaining ear might retain it.',
        turkish: 'Onu sizin için bir hatırlatma yapalım ve belleyen kulaklar bellesin diye.',
        source: 'Qur\'an 69:12',
        highlight: { english: 'ear', turkish: 'kulaklar' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أذن',
        forms: [
          { label: 'plural', arabic: 'آذَان' },
        ],
        occurrences: 18,
        occurringForm: 'أُذُنٌ',
      },
    },
    {
      id: 'asarra',
      arabic: 'أَسَرَّ',
      english: 'to conceal, to keep secret',
      turkish: 'gizlemek, sır tutmak',
      example: {
        arabic: 'وَٱللَّهُ يَعْلَمُ مَا تُسِرُّونَ وَمَا تُعْلِنُونَ',
        english: 'And Allah knows what you conceal and what you declare.',
        turkish: 'Allah gizlediğinizi de açıkladığınızı da bilir.',
        source: 'Qur\'an 16:19',
        highlight: { english: 'conceal', turkish: 'gizlediğinizi' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سرر',
        forms: [
          { label: 'mudari', arabic: 'يُسِرُّ' },
          { label: 'masdar', arabic: 'إِسْرَار' },
        ],
        occurrences: 18,
        occurringForm: 'تُسِرُّونَ',
      },
    },
    {
      id: 'aada',
      arabic: 'أُعِيدُ',
      english: 'to bring back, to restore, to repeat',
      turkish: 'geri getirmek, iade etmek, tekrarlamak',
      example: {
        arabic: 'قُلْ جَآءَ ٱلْحَقُّ وَمَا يُبْدِئُ ٱلْبَٰطِلُ وَمَا يُعِيدُ',
        english: 'Say: The truth has come, and falsehood neither originates anything nor brings it back.',
        turkish: 'De ki: Hak geldi; batıl ne bir şey ortaya çıkarır ne de onu geri getirir.',
        source: 'Qur\'an 34:49',
        highlight: { english: 'brings it back', turkish: 'geri getirir' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عود',
        forms: [
          { label: 'mudari', arabic: 'يُعِيدُ' },
          { label: 'masdar', arabic: 'إِعَادَة' },
        ],
        occurrences: 18,
        occurringForm: 'يُعِيدُ',
      },
    },
    {
      id: 'amsaka',
      arabic: 'أَمْسَكَ',
      english: 'to hold back, to withhold, to grasp',
      turkish: 'tutmak, alıkoymak, vermemek',
      example: {
        arabic: 'هَٰذَا عَطَآؤُنَا فَٱمْنُنْ أَوْ أَمْسِكْ بِغَيْرِ حِسَابٍۢ',
        english: 'This is Our gift, so grant or withhold, without account.',
        turkish: 'Bu bizim bağışımızdır; ister ver, ister tut; hesabı sorulmaz.',
        source: 'Qur\'an 38:39',
        highlight: { english: 'withhold', turkish: 'tut' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'مسك',
        forms: [
          { label: 'mudari', arabic: 'يُمْسِكُ' },
          { label: 'masdar', arabic: 'إِمْسَاك' },
        ],
        occurrences: 18,
        occurringForm: 'أَمْسِكْ',
      },
    },
    {
      id: 'ins',
      arabic: 'إِنس',
      english: 'human beings, mankind (as against jinn)',
      turkish: 'insan, insanlar (cinlerin karşıtı)',
      example: {
        arabic: 'لَمْ يَطْمِثْهُنَّ إِنسٌۭ قَبْلَهُمْ وَلَا جَآنٌّۭ',
        english: 'whom no man has touched before them, nor any jinn.',
        turkish: 'Onlardan önce onlara ne bir insan ne de bir cin dokunmuştur.',
        source: 'Qur\'an 55:74',
        highlight: { english: 'man', turkish: 'insan' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أنس',
        occurrences: 18,
        occurringForm: 'إِنسٌ',
      },
    },
    {
      id: 'tabayyana',
      arabic: 'تَبَيَّنَ',
      english: 'to become clear, to be made evident',
      turkish: 'açığa çıkmak, belli olmak',
      example: {
        arabic: 'يُجَٰدِلُونَكَ فِى ٱلْحَقِّ بَعْدَمَا تَبَيَّنَ كَأَنَّمَا يُسَاقُونَ إِلَى ٱلْمَوْتِ وَهُمْ يَنظُرُونَ',
        english: 'They dispute with you about the truth after it had become clear, as if they were being driven to death while they looked on.',
        turkish: 'Gerçek apaçık ortaya çıktıktan sonra bile seninle onun hakkında tartışıyorlar; sanki göre göre ölüme sürükleniyorlar.',
        source: 'Qur\'an 8:6',
        highlight: { english: 'had become clear', turkish: 'ortaya çıktıktan' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بين',
        forms: [
          { label: 'mudari', arabic: 'يَتَبَيَّنُ' },
          { label: 'masdar', arabic: 'تَبَيُّن' },
        ],
        occurrences: 18,
        occurringForm: 'تَبَيَّنَ',
      },
    },
    {
      id: 'tawra',
      arabic: 'تَوْراة',
      english: 'Torah',
      turkish: 'Tevrat',
      example: {
        arabic: 'نَزَّلَ عَلَيْكَ ٱلْكِتَٰبَ بِٱلْحَقِّ مُصَدِّقًۭا لِّمَا بَيْنَ يَدَيْهِ وَأَنزَلَ ٱلتَّوْرَىٰةَ وَٱلْإِنجِيلَ',
        english: 'He sent down to you the Book in truth, confirming what came before it, and He sent down the Torah and the Gospel,',
        turkish: 'Sana Kitab’ı, kendinden öncekini doğrulayıcı olarak hak ile indirdi; Tevrat’ı ve İncil’i de indirdi,',
        source: 'Qur\'an 3:3',
        highlight: { english: 'Torah', turkish: 'Tevrat' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 18,
        occurringForm: 'ٱلتَّوْرَىٰةَ',
      },
    },
    {
      id: 'dabba',
      arabic: 'دابَّة',
      english: 'moving creature, beast',
      turkish: 'canlı, hayvan, yürüyen mahluk',
      example: {
        arabic: 'وَفِى خَلْقِكُمْ وَمَا يَبُثُّ مِن دَآبَّةٍ ءَايَٰتٌۭ لِّقَوْمٍۢ يُوقِنُونَ',
        english: 'And in your creation, and in the creatures He scatters abroad, are signs for a people who are certain.',
        turkish: 'Sizin yaratılışınızda ve yaydığı canlılarda, kesin olarak inanan bir topluluk için ayetler vardır.',
        source: 'Qur\'an 45:4',
        highlight: { english: 'creatures', turkish: 'canlılarda' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'دبب',
        forms: [
          { label: 'plural', arabic: 'دَوَابّ' },
        ],
        occurrences: 18,
        occurringForm: 'دَآبَّةٍ',
      },
    },
    {
      id: 'dubur',
      arabic: 'دُبُر',
      english: 'back, rear',
      turkish: 'arka, sırt',
      example: {
        arabic: 'وَإِن كَانَ قَمِيصُهُۥ قُدَّ مِن دُبُرٍۢ فَكَذَبَتْ وَهُوَ مِنَ ٱلصَّٰدِقِينَ',
        english: 'But if his shirt was torn from the back, then she has lied and he is of the truthful.',
        turkish: 'Eğer gömleği arkadan yırtılmışsa, kadın yalan söylemiştir, o ise doğru söyleyenlerdendir.',
        source: 'Qur\'an 12:27',
        highlight: { english: 'the back', turkish: 'arkadan' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'دبر',
        forms: [
          { label: 'plural', arabic: 'أَدْبَار' },
        ],
        occurrences: 18,
        occurringForm: 'دُبُرٍ',
      },
    },
    {
      id: 'daraja',
      arabic: 'دَرَجَة',
      english: 'degree, rank, step',
      turkish: 'derece, mertebe, basamak',
      example: {
        arabic: 'هُمْ دَرَجَٰتٌ عِندَ ٱللَّهِ ۗ وَٱللَّهُ بَصِيرٌۢ بِمَا يَعْمَلُونَ',
        english: 'They are of differing degrees with Allah, and Allah sees what they do.',
        turkish: 'Onlar Allah katında derece derecedir; Allah yaptıklarını görmektedir.',
        source: 'Qur\'an 3:163',
        highlight: { english: 'degrees', turkish: 'derece derecedir' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'درج',
        forms: [
          { label: 'plural', arabic: 'دَرَجَات' },
        ],
        occurrences: 18,
        occurringForm: 'دَرَجَٰتٌ',
      },
    },
    {
      id: 'dhakar',
      arabic: 'ذَكَر',
      english: 'male',
      turkish: 'erkek',
      example: {
        arabic: 'أَوْ يُزَوِّجُهُمْ ذُكْرَانًۭا وَإِنَٰثًۭا ۖ وَيَجْعَلُ مَن يَشَآءُ عَقِيمًا ۚ إِنَّهُۥ عَلِيمٌۭ قَدِيرٌۭ',
        english: 'or He pairs them, males and females, and He makes barren whom He wills. Indeed, He is Knowing, Powerful.',
        turkish: 'yahut onları erkekler ve dişiler olarak çift kılar; dilediğini de kısır yapar. Şüphesiz O bilendir, gücü yetendir.',
        source: 'Qur\'an 42:50',
        highlight: { english: 'males and', turkish: 'erkekler' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ذكر',
        forms: [
          { label: 'plural', arabic: 'ذُكُور' },
        ],
        occurrences: 18,
        occurringForm: 'ذُكْرَانًا',
      },
    },
    {
      id: 'dhakkara',
      arabic: 'ذُكِّرَ',
      english: 'to remind, to admonish',
      turkish: 'hatırlatmak, öğüt vermek',
      example: {
        arabic: 'فَذَكِّرْ إِن نَّفَعَتِ ٱلذِّكْرَىٰ',
        english: 'So remind, if the reminder benefits.',
        turkish: 'Öğüt ver, eğer öğüt fayda verirse.',
        source: 'Qur\'an 87:9',
        highlight: { english: 'So remind', turkish: 'Öğüt ver' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ذكر',
        forms: [
          { label: 'mudari', arabic: 'يُذَكِّرُ' },
          { label: 'masdar', arabic: 'تَذْكِير' },
        ],
        occurrences: 18,
        occurringForm: 'فَذَكِّرْ',
      },
    },
    {
      id: 'ras',
      arabic: 'رَأْس',
      english: 'head',
      turkish: 'baş, kafa',
      example: {
        arabic: 'طَلْعُهَا كَأَنَّهُۥ رُءُوسُ ٱلشَّيَٰطِينِ',
        english: 'Its emerging fruit is as if it were the heads of devils.',
        turkish: 'Onun tomurcukları sanki şeytanların başlarıdır.',
        source: 'Qur\'an 37:65',
        highlight: { english: 'heads', turkish: 'başlarıdır' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'رأس',
        forms: [
          { label: 'plural', arabic: 'رُؤُوس' },
        ],
        occurrences: 18,
        occurringForm: 'رُءُوسُ',
      },
    },
    {
      id: 'rayb',
      arabic: 'رَيْب',
      english: 'doubt, suspicion',
      turkish: 'şüphe, kuşku',
      example: {
        arabic: 'ذَٰلِكَ ٱلْكِتَٰبُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًۭى لِّلْمُتَّقِينَ',
        english: 'That is the Book about which there is no doubt, a guidance for the righteous.',
        turkish: 'İşte o kitap, kendisinde şüphe yoktur; takva sahipleri için bir yol göstericidir.',
        source: 'Qur\'an 2:2',
        highlight: { english: 'doubt', turkish: 'şüphe' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ريب',
        occurrences: 18,
        occurringForm: 'رَيْبَ',
      },
    },
    {
      id: 'ada',
      arabic: 'عادَ',
      english: 'to return, to go back',
      turkish: 'dönmek, geri dönmek',
      example: {
        arabic: 'وَٱلْقَمَرَ قَدَّرْنَٰهُ مَنَازِلَ حَتَّىٰ عَادَ كَٱلْعُرْجُونِ ٱلْقَدِيمِ',
        english: 'And the moon: We have determined phases for it, until it returns like an old date stalk.',
        turkish: 'Ay’a da konaklar takdir ettik; sonunda eski bir hurma dalı gibi döner.',
        source: 'Qur\'an 36:39',
        highlight: { english: 'returns', turkish: 'döner' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عود',
        forms: [
          { label: 'mudari', arabic: 'يَعُودُ' },
          { label: 'masdar', arabic: 'عَوْدَة' },
        ],
        occurrences: 18,
        occurringForm: 'عَادَ',
      },
    },
    {
      id: 'alim',
      arabic: 'عالِم',
      english: 'knower, one who knows',
      turkish: 'bilen, âlim',
      example: {
        arabic: 'عَٰلِمُ ٱلْغَيْبِ وَٱلشَّهَٰدَةِ ٱلْكَبِيرُ ٱلْمُتَعَالِ',
        english: 'Knower of the unseen and the witnessed, the Great, the Exalted.',
        turkish: 'Görülmeyeni de görüleni de bilendir; büyüktür, yücedir.',
        source: 'Qur\'an 13:9',
        highlight: { english: 'Knower', turkish: 'bilendir' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'علم',
        forms: [
          { label: 'plural', arabic: 'عُلَمَاء' },
        ],
        occurrences: 18,
        occurringForm: 'عَٰلِمُ',
      },
    },
    {
      id: 'ladun',
      arabic: 'لَدُن',
      english: 'presence, side; from (with min)',
      turkish: 'kat, yan; katından (min ile)',
      example: {
        arabic: 'وَإِنَّكَ لَتُلَقَّى ٱلْقُرْءَانَ مِن لَّدُنْ حَكِيمٍ عَلِيمٍ',
        english: 'And indeed, you receive the Qur\'an from one Wise, Knowing.',
        turkish: 'Şüphesiz sen Kur’an’ı hikmet sahibi, her şeyi bilen birinin katından almaktasın.',
        source: 'Qur\'an 27:6',
        highlight: { english: 'from', turkish: 'katından' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'لدن',
        occurrences: 18,
        occurringForm: 'لَّدُنْ',
      },
    },
    {
      id: 'mattaa',
      arabic: 'مَتَّعْ',
      english: 'to let enjoy, to grant comforts',
      turkish: 'faydalandırmak, geçindirmek',
      example: {
        arabic: 'مَآ أَغْنَىٰ عَنْهُم مَّا كَانُوا۟ يُمَتَّعُونَ',
        english: 'What they were given to enjoy will not avail them.',
        turkish: 'Faydalandırıldıkları şeyler onlara bir yarar sağlamadı.',
        source: 'Qur\'an 26:207',
        highlight: { english: 'given to enjoy', turkish: 'Faydalandırıldıkları' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'متع',
        forms: [
          { label: 'mudari', arabic: 'يُمَتِّعُ' },
          { label: 'masdar', arabic: 'تَمْتِيع' },
        ],
        occurrences: 18,
        occurringForm: 'يُمَتَّعُونَ',
      },
    },
    {
      id: 'munkar',
      arabic: 'مُنكَر',
      english: 'unknown, unfamiliar; wrong, reprehensible',
      turkish: 'tanınmayan, yabancı; kötülük, münker',
      example: {
        arabic: 'قَالَ إِنَّكُمْ قَوْمٌۭ مُّنكَرُونَ',
        english: 'He said: Indeed, you are a people unknown.',
        turkish: 'Dedi ki: Doğrusu siz tanınmayan bir topluluksunuz.',
        source: 'Qur\'an 15:62',
        highlight: { english: 'unknown', turkish: 'tanınmayan' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نكر',
        forms: [
          { label: 'plural', arabic: 'مُنكَرُونَ' },
        ],
        occurrences: 18,
        occurringForm: 'مُّنكَرُونَ',
      },
    },
    {
      id: 'mawlaa',
      arabic: 'مَوْلَى',
      english: 'protector, ally, master',
      turkish: 'dost, veli, efendi',
      example: {
        arabic: 'يَوْمَ لَا يُغْنِى مَوْلًى عَن مَّوْلًۭى شَيْـًۭٔا وَلَا هُمْ يُنصَرُونَ',
        english: 'The Day no ally will avail an ally in anything, nor will they be helped,',
        turkish: 'O gün dost dosttan bir şeyi savamaz ve onlara yardım da edilmez,',
        source: 'Qur\'an 44:41',
        highlight: { english: 'no ally', turkish: 'dost dosttan' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ولي',
        forms: [
          { label: 'plural', arabic: 'مَوَالِي' },
        ],
        occurrences: 18,
        occurringForm: 'مَوْلًى',
      },
    },
    {
      id: 'nima-2',
      arabic: 'نِعْمَ',
      english: 'how excellent!, what a fine (verb of praise)',
      turkish: 'ne güzel!, ne iyi! (övgü fiili)',
      example: {
        arabic: 'وَوَهَبْنَا لِدَاوُۥدَ سُلَيْمَٰنَ ۚ نِعْمَ ٱلْعَبْدُ ۖ إِنَّهُۥٓ أَوَّابٌ',
        english: 'And to David We granted Solomon. What an excellent servant! Indeed, he turned back constantly.',
        turkish: 'Davud’a Süleyman’ı bağışladık. Ne güzel kuldu! Doğrusu o, daima Allah’a yönelirdi.',
        source: 'Qur\'an 38:30',
        highlight: { english: 'What an excellent', turkish: 'Ne güzel' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نعم',
        occurrences: 18,
        occurringForm: 'نِعْمَ',
      },
    },
    {
      id: 'waffaa',
      arabic: 'وَفَّى',
      english: 'to fulfil, to discharge fully',
      turkish: 'yerine getirmek, tam olarak ifa etmek',
      example: {
        arabic: 'وَإِبْرَٰهِيمَ ٱلَّذِى وَفَّىٰٓ',
        english: 'and Abraham, who fulfilled his covenant,',
        turkish: 've ahdini yerine getiren İbrahim’in,',
        source: 'Qur\'an 53:37',
        highlight: { english: 'fulfilled', turkish: 'yerine getiren' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'وفي',
        forms: [
          { label: 'mudari', arabic: 'يُوَفِّي' },
        ],
        occurrences: 18,
        occurringForm: 'وَفَّىٰٓ',
      },
    },
    {
      id: 'ahata',
      arabic: 'أَحاطَ',
      english: 'to encompass, to encircle, to comprehend',
      turkish: 'kuşatmak, kavramak',
      example: {
        arabic: 'وَكَيْفَ تَصْبِرُ عَلَىٰ مَا لَمْ تُحِطْ بِهِۦ خُبْرًۭا',
        english: 'And how can you be patient about what you do not encompass in knowledge?',
        turkish: 'Bilgice kavrayamadığın bir şeye nasıl sabredeceksin?',
        source: 'Qur\'an 18:68',
        highlight: { english: 'encompass', turkish: 'kavrayamadığın' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حوط',
        forms: [
          { label: 'mudari', arabic: 'يُحِيطُ' },
          { label: 'masdar', arabic: 'إِحَاطَة' },
        ],
        occurrences: 17,
        occurringForm: 'تُحِطْ',
      },
    },
    {
      id: 'adraa',
      arabic: 'أَدْرَى',
      english: 'to make know, to inform',
      turkish: 'bildirmek, haber vermek',
      example: {
        arabic: 'وَمَا يُدْرِيكَ لَعَلَّهُۥ يَزَّكَّىٰٓ',
        english: 'And what would make you know that perhaps he might purify himself,',
        turkish: 'Ne bilirsin, belki de o arınacaktır,',
        source: 'Qur\'an 80:3',
        highlight: { english: 'make you know', turkish: 'Ne bilirsin' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'دري',
        forms: [
          { label: 'mudari', arabic: 'يُدْرِي' },
        ],
        occurrences: 17,
        occurringForm: 'يُدْرِيكَ',
      },
    },
    {
      id: 'aghraqa',
      arabic: 'أُغْرِقُ',
      english: 'to drown',
      turkish: 'boğmak, suda boğmak',
      example: {
        arabic: 'ثُمَّ أَغْرَقْنَا ٱلْءَاخَرِينَ',
        english: 'Then We drowned the others.',
        turkish: 'Sonra diğerlerini suda boğduk.',
        source: 'Qur\'an 26:66',
        highlight: { english: 'drowned', turkish: 'suda boğduk' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'غرق',
        forms: [
          { label: 'mudari', arabic: 'يُغْرِقُ' },
          { label: 'masdar', arabic: 'إِغْرَاق' },
        ],
        occurrences: 17,
        occurringForm: 'أَغْرَقْنَا',
      },
    },
    {
      id: 'anama',
      arabic: 'أَنْعَمَ',
      english: 'to bestow favour, to show grace',
      turkish: 'nimet vermek, lütufta bulunmak',
      example: {
        arabic: 'صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ',
        english: 'the path of those upon whom You have bestowed favour, not of those who have earned anger, nor of those who go astray.',
        turkish: 'Kendilerine nimet verdiklerinin yoluna; gazaba uğrayanların ve sapkınların yoluna değil.',
        source: 'Qur\'an 1:7',
        highlight: { english: 'bestowed favour', turkish: 'nimet verdiklerinin' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نعم',
        forms: [
          { label: 'mudari', arabic: 'يُنْعِمُ' },
          { label: 'masdar', arabic: 'إِنْعَام' },
        ],
        occurrences: 17,
        occurringForm: 'أَنْعَمْتَ',
      },
    },
    {
      id: 'ahwa',
      arabic: 'أَهْواء',
      english: 'whims, vain desires, caprices',
      turkish: 'hevesler, nefsî arzular',
      example: {
        arabic: 'وَكَذَّبُوا۟ وَٱتَّبَعُوٓا۟ أَهْوَآءَهُمْ ۚ وَكُلُّ أَمْرٍۢ مُّسْتَقِرٌّۭ',
        english: 'And they denied and followed their own desires, yet every matter will settle in its place.',
        turkish: 'Yalanladılar ve kendi heveslerine uydular; oysa her iş yerini bulacaktır.',
        source: 'Qur\'an 54:3',
        highlight: { english: 'desires', turkish: 'heveslerine' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'هوي',
        occurrences: 17,
        occurringForm: 'أَهْوَآءَهُمْ',
      },
    },
    {
      id: 'ishaq',
      arabic: 'إِسْحاق',
      english: 'Isaac',
      turkish: 'İshak',
      example: {
        arabic: 'وَوَهَبْنَا لَهُۥٓ إِسْحَٰقَ وَيَعْقُوبَ نَافِلَةًۭ ۖ وَكُلًّۭا جَعَلْنَا صَٰلِحِينَ',
        english: 'And We granted him Isaac and Jacob in addition, and each of them We made righteous.',
        turkish: 'Ona İshak’ı, üstelik Yakub’u da bağışladık ve hepsini salih kimseler kıldık.',
        source: 'Qur\'an 21:72',
        highlight: { english: 'Isaac', turkish: 'İshak' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 17,
        occurringForm: 'إِسْحَٰقَ',
      },
    },
    {
      id: 'anqalaba',
      arabic: 'انقَلَبَ',
      english: 'to turn back, to return; to be overturned',
      turkish: 'geri dönmek; altüst olmak',
      example: {
        arabic: 'ثُمَّ ٱرْجِعِ ٱلْبَصَرَ كَرَّتَيْنِ يَنقَلِبْ إِلَيْكَ ٱلْبَصَرُ خَاسِئًۭا وَهُوَ حَسِيرٌۭ',
        english: 'Then return your gaze twice again: the gaze will come back to you humbled and worn out.',
        turkish: 'Sonra gözünü iki kez daha çevir; göz sana aciz ve bitkin olarak dönecektir.',
        source: 'Qur\'an 67:4',
        highlight: { english: 'come back', turkish: 'dönecektir' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'قلب',
        forms: [
          { label: 'mudari', arabic: 'يَنْقَلِبُ' },
          { label: 'masdar', arabic: 'انْقِلَاب' },
        ],
        occurrences: 17,
        occurringForm: 'يَنقَلِبْ',
      },
    },
    {
      id: 'batn',
      arabic: 'بَطْن',
      english: 'belly, stomach',
      turkish: 'karın, mide',
      example: {
        arabic: 'فَمَالِـُٔونَ مِنْهَا ٱلْبُطُونَ',
        english: 'and filling your bellies with it,',
        turkish: 've karınlarınızı ondan dolduracaksınız,',
        source: 'Qur\'an 56:53',
        highlight: { english: 'bellies', turkish: 'karınlarınızı' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بطن',
        forms: [
          { label: 'plural', arabic: 'بُطُون' },
        ],
        occurrences: 17,
        occurringForm: 'ٱلْبُطُونَ',
      },
    },
    {
      id: 'bint',
      arabic: 'بِنْت',
      english: 'daughter, girl',
      turkish: 'kız, kız evlat',
      example: {
        arabic: 'أَمِ ٱتَّخَذَ مِمَّا يَخْلُقُ بَنَاتٍۢ وَأَصْفَىٰكُم بِٱلْبَنِينَ',
        english: 'Or has He taken daughters from what He creates and chosen you for sons?',
        turkish: 'Yoksa O, yarattıklarından kızlar edindi de oğulları size mi seçti?',
        source: 'Qur\'an 43:16',
        highlight: { english: 'daughters', turkish: 'kızlar' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بني',
        forms: [
          { label: 'plural', arabic: 'بَنَات' },
        ],
        occurrences: 17,
        occurringForm: 'بَنَاتٍ',
      },
    },
    {
      id: 'tawiyl',
      arabic: 'تَأْوِيل',
      english: 'interpretation; outcome, final result',
      turkish: 'yorum, tevil; sonuç, akıbet',
      example: {
        arabic: 'وَأَوْفُوا۟ ٱلْكَيْلَ إِذَا كِلْتُمْ وَزِنُوا۟ بِٱلْقِسْطَاسِ ٱلْمُسْتَقِيمِ ۚ ذَٰلِكَ خَيْرٌۭ وَأَحْسَنُ تَأْوِيلًۭا',
        english: 'And give full measure when you measure, and weigh with an even balance. That is better and finer in outcome.',
        turkish: 'Ölçtüğünüzde ölçüyü tam yapın ve doğru terazi ile tartın. Bu daha hayırlı ve sonuç bakımından daha güzeldir.',
        source: 'Qur\'an 17:35',
        highlight: { english: 'outcome', turkish: 'sonuç' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أول',
        occurrences: 17,
        occurringForm: 'تَأْوِيلًا',
      },
    },
    {
      id: 'turab',
      arabic: 'تُراب',
      english: 'dust, soil, earth',
      turkish: 'toprak, toz',
      example: {
        arabic: 'أَءِذَا مِتْنَا وَكُنَّا تُرَابًۭا وَعِظَٰمًا أَءِنَّا لَمَبْعُوثُونَ',
        english: 'When we have died and become dust and bones, will we indeed be raised up?',
        turkish: 'Ölüp toprak ve kemik olduğumuzda mı, gerçekten diriltilecek miyiz?',
        source: 'Qur\'an 37:16',
        highlight: { english: 'dust', turkish: 'toprak' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ترب',
        occurrences: 17,
        occurringForm: 'تُرَابًا',
      },
    },
    {
      id: 'taqwaa',
      arabic: 'تَقْوَى',
      english: 'piety, godliness, fear of God',
      turkish: 'takva, Allah korkusu, sakınma',
      example: {
        arabic: 'ذَٰلِكَ وَمَن يُعَظِّمْ شَعَٰٓئِرَ ٱللَّهِ فَإِنَّهَا مِن تَقْوَى ٱلْقُلُوبِ',
        english: 'That is so. And whoever honours the symbols of Allah, that comes from the piety of hearts.',
        turkish: 'İşte böyle. Kim Allah’ın nişanelerine saygı gösterirse, bu kalplerin takvasındandır.',
        source: 'Qur\'an 22:32',
        highlight: { english: 'piety', turkish: 'takvasındandır' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'وقي',
        occurrences: 17,
        occurringForm: 'تَقْوَى',
      },
    },
    {
      id: 'thamara',
      arabic: 'ثَمَرَة',
      english: 'fruit, produce',
      turkish: 'meyve, ürün',
      example: {
        arabic: 'وَلَقَدْ أَخَذْنَآ ءَالَ فِرْعَوْنَ بِٱلسِّنِينَ وَنَقْصٍۢ مِّنَ ٱلثَّمَرَٰتِ لَعَلَّهُمْ يَذَّكَّرُونَ',
        english: 'And We certainly seized the people of Pharaoh with years of drought and a loss of fruits, so that they might take heed.',
        turkish: 'Andolsun ki Firavun ailesini, öğüt alsınlar diye kıtlık yılları ve ürün eksikliği ile yakaladık.',
        source: 'Qur\'an 7:130',
        highlight: { english: 'fruits', turkish: 'ürün' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ثمر',
        forms: [
          { label: 'plural', arabic: 'ثَمَرَات' },
        ],
        occurrences: 17,
        occurringForm: 'ٱلثَّمَرَٰتِ',
      },
    },
    {
      id: 'husnaa',
      arabic: 'حُسْنَى',
      english: 'most beautiful, finest; best reward',
      turkish: 'en güzel; en güzel karşılık',
      example: {
        arabic: 'ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ ۖ لَهُ ٱلْأَسْمَآءُ ٱلْحُسْنَىٰ',
        english: 'Allah, there is no god but He. To Him belong the most beautiful names.',
        turkish: 'Allah, kendisinden başka ilah olmayandır. En güzel isimler O’nundur.',
        source: 'Qur\'an 20:8',
        highlight: { english: 'most beautiful', turkish: 'En güzel' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حسن',
        occurrences: 17,
        occurringForm: 'ٱلْحُسْنَىٰ',
      },
    },
    {
      id: 'hamiyd',
      arabic: 'حَمِيد',
      english: 'praiseworthy, worthy of praise',
      turkish: 'övgüye layık, hamde layık',
      example: {
        arabic: 'وَمَا نَقَمُوا۟ مِنْهُمْ إِلَّآ أَن يُؤْمِنُوا۟ بِٱللَّهِ ٱلْعَزِيزِ ٱلْحَمِيدِ',
        english: 'And they resented them only because they believed in Allah, the Mighty, the Praiseworthy,',
        turkish: 'Onlardan, yalnızca aziz ve övgüye layık olan Allah’a iman ettikleri için öç aldılar,',
        source: 'Qur\'an 85:8',
        highlight: { english: 'Praiseworthy', turkish: 'övgüye layık' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حمد',
        occurrences: 17,
        occurringForm: 'ٱلْحَمِيدِ',
      },
    },
    {
      id: 'hawl',
      arabic: 'حَوْل',
      english: 'around, surroundings',
      turkish: 'çevre, etraf; çevresinde',
      example: {
        arabic: 'فَوَرَبِّكَ لَنَحْشُرَنَّهُمْ وَٱلشَّيَٰطِينَ ثُمَّ لَنُحْضِرَنَّهُمْ حَوْلَ جَهَنَّمَ جِثِيًّۭا',
        english: 'So by your Lord, We will surely gather them and the devils, then We will surely bring them around Hell on their knees.',
        turkish: 'Rabbine andolsun ki onları da şeytanları da mutlaka toplayacağız, sonra cehennemin çevresinde diz üstü çökmüş halde hazır bulunduracağız.',
        source: 'Qur\'an 19:68',
        highlight: { english: 'around', turkish: 'çevresinde' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حول',
        occurrences: 17,
        occurringForm: 'حَوْلَ',
      },
    },
    {
      id: 'sulayman',
      arabic: 'سُلَيْمان',
      english: 'Solomon',
      turkish: 'Süleyman',
      example: {
        arabic: 'وَوَهَبْنَا لِدَاوُۥدَ سُلَيْمَٰنَ ۚ نِعْمَ ٱلْعَبْدُ ۖ إِنَّهُۥٓ أَوَّابٌ',
        english: 'And to David We granted Solomon. What an excellent servant! Indeed, he turned back constantly.',
        turkish: 'Davud’a Süleyman’ı bağışladık. Ne güzel kuldu! Doğrusu o, daima Allah’a yönelirdi.',
        source: 'Qur\'an 38:30',
        highlight: { english: 'Solomon', turkish: 'Süleyman' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 17,
        occurringForm: 'سُلَيْمَٰنَ',
      },
    },
    {
      id: 'fahisha',
      arabic: 'فاحِشَة',
      english: 'immorality, indecency, shameful deed',
      turkish: 'hayâsızlık, çirkin iş, fuhuş',
      example: {
        arabic: 'وَلَا تَقْرَبُوا۟ ٱلزِّنَىٰٓ ۖ إِنَّهُۥ كَانَ فَٰحِشَةًۭ وَسَآءَ سَبِيلًۭا',
        english: 'And do not come near fornication. Indeed, it is an immorality and an evil way.',
        turkish: 'Zinaya yaklaşmayın; çünkü o bir hayâsızlıktır ve kötü bir yoldur.',
        source: 'Qur\'an 17:32',
        highlight: { english: 'immorality', turkish: 'hayâsızlıktır' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'فحش',
        forms: [
          { label: 'plural', arabic: 'فَوَاحِش' },
        ],
        occurrences: 17,
        occurringForm: 'فَٰحِشَةً',
      },
    },
    {
      id: 'fassala',
      arabic: 'فَصَّلَ',
      english: 'to explain in detail, to set out distinctly',
      turkish: 'ayrıntılı açıklamak, tafsil etmek',
      example: {
        arabic: 'وَكَذَٰلِكَ نُفَصِّلُ ٱلْءَايَٰتِ وَلَعَلَّهُمْ يَرْجِعُونَ',
        english: 'And thus do We explain the signs in detail, so that perhaps they will return.',
        turkish: 'İşte ayetleri böyle ayrıntılı açıklıyoruz; belki dönerler.',
        source: 'Qur\'an 7:174',
        highlight: { english: 'explain the signs in detail', turkish: 'ayrıntılı açıklıyoruz' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'فصل',
        forms: [
          { label: 'mudari', arabic: 'يُفَصِّلُ' },
          { label: 'masdar', arabic: 'تَفْصِيل' },
        ],
        occurrences: 17,
        occurringForm: 'نُفَصِّلُ',
      },
    },
    {
      id: 'faddala',
      arabic: 'فَضَّلَ',
      english: 'to prefer, to favour above',
      turkish: 'üstün kılmak, tercih etmek',
      example: {
        arabic: 'وَإِسْمَٰعِيلَ وَٱلْيَسَعَ وَيُونُسَ وَلُوطًۭا ۚ وَكُلًّۭا فَضَّلْنَا عَلَى ٱلْعَٰلَمِينَ',
        english: 'And Ishmael and Elisha and Jonah and Lot: each of them We preferred over the worlds.',
        turkish: 'İsmail’i, Elyesa’yı, Yunus’u ve Lut’u da; hepsini âlemlere üstün kıldık.',
        source: 'Qur\'an 6:86',
        highlight: { english: 'preferred', turkish: 'üstün kıldık' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'فضل',
        forms: [
          { label: 'mudari', arabic: 'يُفَضِّلُ' },
          { label: 'masdar', arabic: 'تَفْضِيل' },
        ],
        occurrences: 17,
        occurringForm: 'فَضَّلْنَا',
      },
    },
  ],
}
