import type { DeckDef } from '../types'

// Quran Vocabulary, level 10. See GitHub issue #8.
//
// Scaffolded by scripts/generateVocab.ts: the headword, root, occurrence count,
// ayah and citation come from the corpus and the canonical text. The meanings,
// principal parts and ayah translations were authored on top of that scaffold.
//
// Where the corpus lemmatizes a word to a passive, an imperative or a mudari
// that nobody looks up, the note id is the dictionary form while the headword
// stays as the corpus has it, since that is what the ayah shows.
//
// DRAFT: verify every English meaning before memorizing it. Turkish is
// convenience text and stays draft - correct it on sight while studying.
//
// Locked until the previous level is mostly graduated; see quranVocabTrack.ts.

export const quranVocab10: DeckDef = {
  id: 'quran-vocab-10',
  name: { english: 'Quran Vocabulary 10', turkish: 'Kur’an Kelimeleri 10' },
  nameArabic: 'مُفْرَدَاتُ الْقُرْآنِ ١٠',
  description: {
    english:
      'Frequency band 10 of the Quran vocabulary track, each word with an ayah where it occurs.',
    turkish:
      'Kur’an kelime yolunun 10. sıklık kuşağı; her kelime geçtiği bir ayetle.',
  },
  directions: ['ar-to-meaning'],
  newPerDay: 10,
  burySiblings: true,
  notes: [
    {
      id: 'makara',
      arabic: 'مَكَرَ',
      english: 'to plot, to scheme',
      turkish: 'tuzak kurmak, hile yapmak',
      example: {
        arabic: 'وَمَكَرُوا۟ وَمَكَرَ ٱللَّهُ ۖ وَٱللَّهُ خَيْرُ ٱلْمَٰكِرِينَ',
        english: 'And they plotted, and Allah planned. And Allah is the best of planners.',
        turkish: 'Onlar tuzak kurdular, Allah da tuzak kurdu. Allah tuzak kuranların en hayırlısıdır.',
        source: 'Qur\'an 3:54',
        highlight: { english: 'plotted', turkish: 'tuzak kurdular' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'مكر',
        forms: [
          { label: 'mudari', arabic: 'يَمْكُرُ' },
          { label: 'masdar', arabic: 'مَكْر' },
        ],
        occurrences: 22,
        occurringForm: 'وَمَكَرَ',
      },
    },
    {
      id: 'nasr',
      arabic: 'نَصْر',
      english: 'help, victory',
      turkish: 'yardım, zafer',
      example: {
        arabic: 'وَيَنصُرَكَ ٱللَّهُ نَصْرًا عَزِيزًا',
        english: 'and that Allah may help you with a mighty help.',
        turkish: 've Allah sana şanlı bir yardımla yardım etsin.',
        source: 'Qur\'an 48:3',
        highlight: { english: 'a mighty help', turkish: 'yardımla' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نصر',
        occurrences: 22,
        occurringForm: 'نَصْرًا',
      },
    },
    {
      id: 'wahaba',
      arabic: 'وَهَبَ',
      english: 'to grant, to bestow',
      turkish: 'bağışlamak, ihsan etmek',
      example: {
        arabic: 'رَبِّ هَبْ لِى مِنَ ٱلصَّٰلِحِينَ',
        english: 'My Lord, grant me one of the righteous.',
        turkish: 'Rabbim, bana salihlerden birini bağışla.',
        source: 'Qur\'an 37:100',
        highlight: { english: 'grant', turkish: 'bağışla' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'وهب',
        forms: [
          { label: 'mudari', arabic: 'يَهَبُ' },
          { label: 'masdar', arabic: 'هِبَة' },
        ],
        occurrences: 22,
        occurringForm: 'هَبْ',
      },
    },
    {
      id: 'raja',
      arabic: 'يَرْجُوا۟',
      english: 'to hope for, to expect',
      turkish: 'ummak, beklemek',
      example: {
        arabic: 'مَن كَانَ يَرْجُوا۟ لِقَآءَ ٱللَّهِ فَإِنَّ أَجَلَ ٱللَّهِ لَءَاتٍۢ ۚ وَهُوَ ٱلسَّمِيعُ ٱلْعَلِيمُ',
        english: 'Whoever hopes for the meeting with Allah, then indeed the term of Allah is coming. And He is the Hearing, the Knowing.',
        turkish: 'Kim Allah\'a kavuşmayı umuyorsa, şüphesiz Allah\'ın belirlediği vakit gelecektir. O, işitendir, bilendir.',
        source: 'Qur\'an 29:5',
        highlight: { english: 'hopes', turkish: 'umuyorsa' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'رجو',
        forms: [
          { label: 'mudari', arabic: 'يَرْجُو' },
          { label: 'masdar', arabic: 'رَجَاء' },
        ],
        occurrences: 22,
        occurringForm: 'يَرْجُوا۟',
      },
    },
    {
      id: 'ahsana',
      arabic: 'أَحْسَنَ',
      english: 'to do well, to make perfect',
      turkish: 'güzel yapmak, iyilik etmek',
      example: {
        arabic: 'ٱلَّذِىٓ أَحْسَنَ كُلَّ شَىْءٍ خَلَقَهُۥ ۖ وَبَدَأَ خَلْقَ ٱلْإِنسَٰنِ مِن طِينٍۢ',
        english: 'who made perfect everything He created, and He began the creation of man from clay.',
        turkish: 'O ki yarattığı her şeyi güzel yaptı ve insanın yaratılışına çamurdan başladı.',
        source: 'Qur\'an 32:7',
        highlight: { english: 'made perfect', turkish: 'güzel yaptı' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حسن',
        forms: [
          { label: 'mudari', arabic: 'يُحْسِنُ' },
          { label: 'masdar', arabic: 'إِحْسَان' },
        ],
        occurrences: 21,
        occurringForm: 'أَحْسَنَ',
      },
    },
    {
      id: 'amaa',
      arabic: 'أَعْمَى',
      english: 'blind',
      turkish: 'kör, âmâ',
      example: {
        arabic: 'صُمٌّۢ بُكْمٌ عُمْىٌۭ فَهُمْ لَا يَرْجِعُونَ',
        english: 'Deaf, dumb, blind, so they will not return.',
        turkish: 'Sağırdırlar, dilsizdirler, kördürler; artık dönmezler.',
        source: 'Qur\'an 2:18',
        highlight: { english: 'blind', turkish: 'kördürler' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عمي',
        forms: [
          { label: 'plural', arabic: 'عُمْي' },
        ],
        occurrences: 21,
        occurringForm: 'عُمْىٌ',
      },
    },
    {
      id: 'amata',
      arabic: 'أَماتَ',
      english: 'to cause to die, to put to death',
      turkish: 'öldürmek',
      example: {
        arabic: 'وَأَنَّهُۥ هُوَ أَمَاتَ وَأَحْيَا',
        english: 'and that it is He who causes death and gives life,',
        turkish: 've şüphesiz öldüren de dirilten de O\'dur,',
        source: 'Qur\'an 53:44',
        highlight: { english: 'causes death', turkish: 'öldüren' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'موت',
        forms: [
          { label: 'mudari', arabic: 'يُمِيتُ' },
          { label: 'masdar', arabic: 'إِمَاتَة' },
        ],
        occurrences: 21,
        occurringForm: 'أَمَاتَ',
      },
    },
    {
      id: 'astahzaa',
      arabic: 'اسْتُهْزِئَ',
      english: 'to mock, to ridicule',
      turkish: 'alay etmek, eğlenmek',
      example: {
        arabic: 'ٱللَّهُ يَسْتَهْزِئُ بِهِمْ وَيَمُدُّهُمْ فِى طُغْيَٰنِهِمْ يَعْمَهُونَ',
        english: 'Allah mocks them and prolongs them in their transgression, wandering blindly.',
        turkish: 'Allah onlarla alay eder ve onları azgınlıkları içinde şaşkın şaşkın dolaşır halde bırakır.',
        source: 'Qur\'an 2:15',
        highlight: { english: 'mocks', turkish: 'alay eder' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'هزأ',
        forms: [
          { label: 'mudari', arabic: 'يَسْتَهْزِئُ' },
          { label: 'masdar', arabic: 'اسْتِهْزَاء' },
        ],
        occurrences: 21,
        occurringForm: 'يَسْتَهْزِئُ',
      },
    },
    {
      id: 'ashtaraa',
      arabic: 'اشْتَرَى',
      english: 'to buy, to purchase',
      turkish: 'satın almak',
      example: {
        arabic: 'أُو۟لَٰٓئِكَ ٱلَّذِينَ ٱشْتَرَوُا۟ ٱلضَّلَٰلَةَ بِٱلْهُدَىٰ فَمَا رَبِحَت تِّجَٰرَتُهُمْ وَمَا كَانُوا۟ مُهْتَدِينَ',
        english: 'Those are the ones who have bought error with guidance, so their trade has not profited them, nor were they guided.',
        turkish: 'İşte onlar hidayet karşılığında sapıklığı satın alanlardır; ticaretleri kâr etmemiş ve doğru yolu bulamamışlardır.',
        source: 'Qur\'an 2:16',
        highlight: { english: 'have bought', turkish: 'satın alanlardır' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'شري',
        forms: [
          { label: 'mudari', arabic: 'يَشْتَرِي' },
          { label: 'masdar', arabic: 'اشْتِرَاء' },
        ],
        occurrences: 21,
        occurringForm: 'ٱشْتَرَوُا۟',
      },
    },
    {
      id: 'hasan',
      arabic: 'حَسَن',
      english: 'good, beautiful',
      turkish: 'güzel, iyi',
      example: {
        arabic: 'فِيهِنَّ خَيْرَٰتٌ حِسَانٌۭ',
        english: 'In them are good and beautiful ones,',
        turkish: 'Onlarda iyi huylu, güzel olanlar vardır,',
        source: 'Qur\'an 55:70',
        highlight: { english: 'good', turkish: 'iyi huylu' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حسن',
        forms: [
          { label: 'plural', arabic: 'حِسَان' },
        ],
        occurrences: 21,
        occurringForm: 'حِسَانٌ',
      },
    },
    {
      id: 'ruwh',
      arabic: 'رُوح',
      english: 'spirit, soul',
      turkish: 'ruh',
      example: {
        arabic: 'نَزَلَ بِهِ ٱلرُّوحُ ٱلْأَمِينُ',
        english: 'The Trustworthy Spirit brought it down,',
        turkish: 'Onu güvenilir Ruh indirdi,',
        source: 'Qur\'an 26:193',
        highlight: { english: 'Spirit', turkish: 'Ruh' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'روح',
        forms: [
          { label: 'plural', arabic: 'أَرْوَاح' },
        ],
        occurrences: 21,
        occurringForm: 'ٱلرُّوحُ',
      },
    },
    {
      id: 'shahid',
      arabic: 'شاهِد',
      english: 'witness, one present',
      turkish: 'şahit, hazır bulunan',
      example: {
        arabic: 'وَبَنِينَ شُهُودًۭا',
        english: 'and sons present before him,',
        turkish: 've yanında hazır duran oğullar,',
        source: 'Qur\'an 74:13',
        highlight: { english: 'present', turkish: 'hazır duran' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شهد',
        forms: [
          { label: 'plural', arabic: 'شُهُود' },
        ],
        occurrences: 21,
        occurringForm: 'شُهُودًا',
      },
    },
    {
      id: 'shahr',
      arabic: 'شَهْر',
      english: 'month',
      turkish: 'ay',
      example: {
        arabic: 'لَيْلَةُ ٱلْقَدْرِ خَيْرٌۭ مِّنْ أَلْفِ شَهْرٍۢ',
        english: 'The Night of Decree is better than a thousand months.',
        turkish: 'Kadir gecesi bin aydan daha hayırlıdır.',
        source: 'Qur\'an 97:3',
        highlight: { english: 'months', turkish: 'aydan' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شهر',
        forms: [
          { label: 'plural', arabic: 'أَشْهُر' },
        ],
        occurrences: 21,
        occurringForm: 'شَهْرٍ',
      },
    },
    {
      id: 'zann',
      arabic: 'ظَنّ',
      english: 'assumption, thought, conjecture',
      turkish: 'zan, sanı',
      example: {
        arabic: 'فَمَا ظَنُّكُم بِرَبِّ ٱلْعَٰلَمِينَ',
        english: 'Then what is your assumption about the Lord of the worlds?',
        turkish: 'Peki, âlemlerin Rabbi hakkındaki zannınız nedir?',
        source: 'Qur\'an 37:87',
        highlight: { english: 'assumption', turkish: 'zannınız' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ظنن',
        forms: [
          { label: 'plural', arabic: 'ظُنُون' },
        ],
        occurrences: 21,
        occurringForm: 'ظَنُّكُم',
      },
    },
    {
      id: 'katama',
      arabic: 'كَتَمَ',
      english: 'to conceal, to hide',
      turkish: 'gizlemek, saklamak',
      example: {
        arabic: 'إِنَّهُۥ يَعْلَمُ ٱلْجَهْرَ مِنَ ٱلْقَوْلِ وَيَعْلَمُ مَا تَكْتُمُونَ',
        english: 'Indeed, He knows what is spoken aloud and He knows what you conceal.',
        turkish: 'Şüphesiz O, sözün açığa vurulanını da bilir, gizlediklerinizi de bilir.',
        source: 'Qur\'an 21:110',
        highlight: { english: 'conceal', turkish: 'gizlediklerinizi' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'كتم',
        forms: [
          { label: 'mudari', arabic: 'يَكْتُمُ' },
          { label: 'masdar', arabic: 'كِتْمَان' },
        ],
        occurrences: 21,
        occurringForm: 'تَكْتُمُونَ',
      },
    },
    {
      id: 'kam',
      arabic: 'كَم',
      english: 'how many, how much',
      turkish: 'kaç, ne kadar',
      example: {
        arabic: 'كَمْ تَرَكُوا۟ مِن جَنَّٰتٍۢ وَعُيُونٍۢ',
        english: 'How many gardens and springs they left behind,',
        turkish: 'Nice bahçeler ve pınarlar bıraktılar,',
        source: 'Qur\'an 44:25',
        highlight: { english: 'How many', turkish: 'Nice' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 21,
        occurringForm: 'كَمْ',
      },
    },
    {
      id: 'musammana',
      arabic: 'مُسَمًّى',
      english: 'named, appointed, specified',
      turkish: 'belirlenmiş, adı konmuş',
      example: {
        arabic: 'وَلَوْلَا كَلِمَةٌۭ سَبَقَتْ مِن رَّبِّكَ لَكَانَ لِزَامًۭا وَأَجَلٌۭ مُّسَمًّۭى',
        english: 'And if not for a word that preceded from your Lord and an appointed term, it would have been unavoidable.',
        turkish: 'Rabbinden önceden geçmiş bir söz ve belirlenmiş bir süre olmasaydı, o kaçınılmaz olurdu.',
        source: 'Qur\'an 20:129',
        highlight: { english: 'appointed', turkish: 'belirlenmiş' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سمو',
        occurrences: 21,
        occurringForm: 'مُّسَمًّى',
      },
    },
    {
      id: 'masha',
      arabic: 'مَشَ',
      english: 'to walk',
      turkish: 'yürümek',
      example: {
        arabic: 'أَفَمَن يَمْشِى مُكِبًّا عَلَىٰ وَجْهِهِۦٓ أَهْدَىٰٓ أَمَّن يَمْشِى سَوِيًّا عَلَىٰ صِرَٰطٍۢ مُّسْتَقِيمٍۢ',
        english: 'Is one who walks fallen on his face better guided, or one who walks upright on a straight path?',
        turkish: 'Yüzüstü kapanarak yürüyen mi daha doğru yoldadır, yoksa dosdoğru bir yolda dimdik yürüyen mi?',
        source: 'Qur\'an 67:22',
        highlight: { english: 'who walks fallen', turkish: 'kapanarak yürüyen' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'مشي',
        forms: [
          { label: 'mudari', arabic: 'يَمْشِي' },
          { label: 'masdar', arabic: 'مَشْي' },
        ],
        occurrences: 21,
        occurringForm: 'يَمْشِى',
      },
    },
    {
      id: 'mufsid',
      arabic: 'مُفْسِد',
      english: 'corrupter, one who spreads corruption',
      turkish: 'bozguncu, fesat çıkaran',
      example: {
        arabic: 'وَلَا تَبْخَسُوا۟ ٱلنَّاسَ أَشْيَآءَهُمْ وَلَا تَعْثَوْا۟ فِى ٱلْأَرْضِ مُفْسِدِينَ',
        english: 'And do not deprive people of their things, and do not roam the earth spreading corruption.',
        turkish: 'İnsanların mallarını eksik vermeyin ve yeryüzünde bozgunculuk yaparak karışıklık çıkarmayın.',
        source: 'Qur\'an 26:183',
        highlight: { english: 'spreading corruption', turkish: 'bozgunculuk yaparak' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'فسد',
        forms: [
          { label: 'plural', arabic: 'مُفْسِدُون' },
        ],
        occurrences: 21,
        occurringForm: 'مُفْسِدِينَ',
      },
    },
    {
      id: 'mukadhdhib',
      arabic: 'مُكَذِّب',
      english: 'denier, one who calls a lie',
      turkish: 'yalanlayan, yalancı sayan',
      example: {
        arabic: 'وَإِنَّا لَنَعْلَمُ أَنَّ مِنكُم مُّكَذِّبِينَ',
        english: 'And indeed, We know that among you are deniers.',
        turkish: 'Şüphesiz biz, içinizde yalanlayanlar olduğunu elbette biliyoruz.',
        source: 'Qur\'an 69:49',
        highlight: { english: 'deniers', turkish: 'yalanlayanlar' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كذب',
        forms: [
          { label: 'plural', arabic: 'مُكَذِّبُون' },
        ],
        occurrences: 21,
        occurringForm: 'مُّكَذِّبِينَ',
      },
    },
    {
      id: 'nasiyb',
      arabic: 'نَصِيب',
      english: 'share, portion',
      turkish: 'pay, nasip',
      example: {
        arabic: 'أُو۟لَٰٓئِكَ لَهُمْ نَصِيبٌۭ مِّمَّا كَسَبُوا۟ ۚ وَٱللَّهُ سَرِيعُ ٱلْحِسَابِ',
        english: 'Those will have a share of what they have earned, and Allah is swift in account.',
        turkish: 'İşte onlara kazandıklarından bir pay vardır. Allah hesabı çabuk görendir.',
        source: 'Qur\'an 2:202',
        highlight: { english: 'a share', turkish: 'bir pay' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نصب',
        occurrences: 21,
        occurringForm: 'نَصِيبٌ',
      },
    },
    {
      id: 'wadaa',
      arabic: 'وَضَعَ',
      english: 'to put, to place, to set down',
      turkish: 'koymak, yerleştirmek',
      example: {
        arabic: 'إِنَّ أَوَّلَ بَيْتٍۢ وُضِعَ لِلنَّاسِ لَلَّذِى بِبَكَّةَ مُبَارَكًۭا وَهُدًۭى لِّلْعَٰلَمِينَ',
        english: 'Indeed, the first House set up for mankind was the one at Bakkah, blessed and a guidance for the worlds.',
        turkish: 'Şüphesiz insanlar için kurulan ilk ev, Bekke\'deki, mübarek ve âlemler için bir hidayet olan evdir.',
        source: 'Qur\'an 3:96',
        highlight: { english: 'set up', turkish: 'kurulan' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'وضع',
        forms: [
          { label: 'mudari', arabic: 'يَضَعُ' },
          { label: 'masdar', arabic: 'وَضْع' },
        ],
        occurrences: 21,
        occurringForm: 'وُضِعَ',
      },
    },
    {
      id: 'ahalla',
      arabic: 'أَحَلَّ',
      english: 'to make lawful; to bring down to settle',
      turkish: 'helal kılmak; (bir yere) indirmek',
      example: {
        arabic: '۞ أَلَمْ تَرَ إِلَى ٱلَّذِينَ بَدَّلُوا۟ نِعْمَتَ ٱللَّهِ كُفْرًۭا وَأَحَلُّوا۟ قَوْمَهُمْ دَارَ ٱلْبَوَارِ',
        english: 'Have you not seen those who exchanged the favor of Allah for disbelief and brought their people down to the home of ruin?',
        turkish: 'Allah\'ın nimetini nankörlükle değiştiren ve kavimlerini helak yurduna indirenleri görmedin mi?',
        source: 'Qur\'an 14:28',
        highlight: { english: 'brought their people down', turkish: 'indirenleri' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حلل',
        forms: [
          { label: 'mudari', arabic: 'يُحِلُّ' },
          { label: 'masdar', arabic: 'إِحْلَال' },
        ],
        occurrences: 20,
        occurringForm: 'وَأَحَلُّوا۟',
      },
    },
    {
      id: 'aadda',
      arabic: 'أَعَدَّ',
      english: 'to prepare, to make ready',
      turkish: 'hazırlamak',
      example: {
        arabic: 'وَٱتَّقُوا۟ ٱلنَّارَ ٱلَّتِىٓ أُعِدَّتْ لِلْكَٰفِرِينَ',
        english: 'And fear the Fire which has been prepared for the disbelievers.',
        turkish: 'Kâfirler için hazırlanmış olan ateşten sakının.',
        source: 'Qur\'an 3:131',
        highlight: { english: 'prepared', turkish: 'hazırlanmış' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عدد',
        forms: [
          { label: 'mudari', arabic: 'يُعِدُّ' },
          { label: 'masdar', arabic: 'إِعْدَاد' },
        ],
        occurrences: 20,
        occurringForm: 'أُعِدَّتْ',
      },
    },
    {
      id: 'aqsama',
      arabic: 'أَقْسَمُ',
      english: 'to swear, to take an oath',
      turkish: 'yemin etmek, ant içmek',
      example: {
        arabic: 'فَلَآ أُقْسِمُ بِٱلْخُنَّسِ',
        english: 'So I swear by the retreating stars,',
        turkish: 'Yemin ederim geri dönüp gizlenen yıldızlara,',
        source: 'Qur\'an 81:15',
        highlight: { english: 'I swear', turkish: 'Yemin ederim' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'قسم',
        forms: [
          { label: 'mudari', arabic: 'يُقْسِمُ' },
          { label: 'masdar', arabic: 'إِقْسَام' },
        ],
        occurrences: 20,
        occurringForm: 'أُقْسِمُ',
      },
    },
    {
      id: 'amina',
      arabic: 'أَمِنَ',
      english: 'to be safe, to feel secure',
      turkish: 'güvende olmak, emin olmak',
      example: {
        arabic: 'أَفَأَمِنُوا۟ مَكْرَ ٱللَّهِ ۚ فَلَا يَأْمَنُ مَكْرَ ٱللَّهِ إِلَّا ٱلْقَوْمُ ٱلْخَٰسِرُونَ',
        english: 'Did they then feel secure from the plan of Allah? But none feels secure from the plan of Allah except the losing people.',
        turkish: 'Allah\'ın tuzağından emin mi oldular? Allah\'ın tuzağından ancak hüsrana uğrayan topluluk emin olur.',
        source: 'Qur\'an 7:99',
        highlight: { english: 'feel secure', turkish: 'emin mi oldular' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'أمن',
        forms: [
          { label: 'mudari', arabic: 'يَأْمَنُ' },
          { label: 'masdar', arabic: 'أَمْن' },
        ],
        occurrences: 20,
        occurringForm: 'يَأْمَنُ',
      },
    },
    {
      id: 'anshaa',
      arabic: 'أَنشَأَ',
      english: 'to bring into being, to produce',
      turkish: 'var etmek, meydana getirmek',
      example: {
        arabic: 'وَهُوَ ٱلَّذِىٓ أَنشَأَ لَكُمُ ٱلسَّمْعَ وَٱلْأَبْصَٰرَ وَٱلْأَفْـِٔدَةَ ۚ قَلِيلًۭا مَّا تَشْكُرُونَ',
        english: 'And it is He who brought into being for you hearing and sight and hearts. Little are you grateful.',
        turkish: 'Sizin için işitmeyi, gözleri ve gönülleri var eden O\'dur. Ne kadar az şükrediyorsunuz!',
        source: 'Qur\'an 23:78',
        highlight: { english: 'brought into being', turkish: 'var eden' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نشأ',
        forms: [
          { label: 'mudari', arabic: 'يُنْشِئُ' },
          { label: 'masdar', arabic: 'إِنْشَاء' },
        ],
        occurrences: 20,
        occurringForm: 'أَنشَأَ',
      },
    },
    {
      id: 'awfaa',
      arabic: 'أَوْفَى',
      english: 'to fulfill, to discharge fully',
      turkish: 'yerine getirmek, tam olarak ifa etmek',
      example: {
        arabic: 'بَلَىٰ مَنْ أَوْفَىٰ بِعَهْدِهِۦ وَٱتَّقَىٰ فَإِنَّ ٱللَّهَ يُحِبُّ ٱلْمُتَّقِينَ',
        english: 'Yes, whoever fulfills his covenant and fears Allah, then indeed Allah loves the righteous.',
        turkish: 'Hayır! Kim sözünü yerine getirir ve sakınırsa, şüphesiz Allah sakınanları sever.',
        source: 'Qur\'an 3:76',
        highlight: { english: 'fulfills', turkish: 'yerine getirir' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'وفي',
        forms: [
          { label: 'mudari', arabic: 'يُوفِي' },
          { label: 'masdar', arabic: 'إِيفَاء' },
        ],
        occurrences: 20,
        occurringForm: 'أَوْفَىٰ',
      },
    },
    {
      id: 'balaw',
      arabic: 'بَلَوْ',
      english: 'to test, to try',
      turkish: 'sınamak, denemek',
      example: {
        arabic: 'يَوْمَ تُبْلَى ٱلسَّرَآئِرُ',
        english: 'on the Day when the secrets are put to the test,',
        turkish: 'Sırların sınanacağı gün,',
        source: 'Qur\'an 86:9',
        highlight: { english: 'put to the test', turkish: 'sınanacağı' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بلو',
        forms: [
          { label: 'mudari', arabic: 'يَبْلُو' },
          { label: 'masdar', arabic: 'بَلَاء' },
        ],
        occurrences: 20,
        occurringForm: 'تُبْلَى',
      },
    },
    {
      id: 'hizb',
      arabic: 'حِزْب',
      english: 'party, faction, group',
      turkish: 'grup, hizip, taraf',
      example: {
        arabic: 'فَتَقَطَّعُوٓا۟ أَمْرَهُم بَيْنَهُمْ زُبُرًۭا ۖ كُلُّ حِزْبٍۭ بِمَا لَدَيْهِمْ فَرِحُونَ',
        english: 'But they cut up their affair among themselves into pieces, each party rejoicing in what it has.',
        turkish: 'Ama işlerini aralarında parça parça ettiler; her grup kendi elindekiyle sevinmektedir.',
        source: 'Qur\'an 23:53',
        highlight: { english: 'each party', turkish: 'her grup' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حزب',
        forms: [
          { label: 'plural', arabic: 'أَحْزَاب' },
        ],
        occurrences: 20,
        occurringForm: 'حِزْبٍۭ',
      },
    },
    {
      id: 'haqqa',
      arabic: 'حَقَّ',
      english: 'to come true, to become due',
      turkish: 'gerçekleşmek, hak olmak',
      example: {
        arabic: 'إِنَّ ٱلَّذِينَ حَقَّتْ عَلَيْهِمْ كَلِمَتُ رَبِّكَ لَا يُؤْمِنُونَ',
        english: 'Indeed, those upon whom the word of your Lord has become due will not believe,',
        turkish: 'Şüphesiz Rablerinin sözü aleyhlerine gerçekleşmiş olanlar iman etmezler,',
        source: 'Qur\'an 10:96',
        highlight: { english: 'has become due', turkish: 'gerçekleşmiş' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حقق',
        forms: [
          { label: 'mudari', arabic: 'يَحِقُّ' },
        ],
        occurrences: 20,
        occurringForm: 'حَقَّتْ',
      },
    },
    {
      id: 'hikma',
      arabic: 'حِكْمَة',
      english: 'wisdom',
      turkish: 'hikmet, bilgelik',
      example: {
        arabic: 'حِكْمَةٌۢ بَٰلِغَةٌۭ ۖ فَمَا تُغْنِ ٱلنُّذُرُ',
        english: 'Far-reaching wisdom, but the warnings do not avail.',
        turkish: 'Üstün bir hikmettir; ama uyarılar fayda vermiyor.',
        source: 'Qur\'an 54:5',
        highlight: { english: 'wisdom', turkish: 'hikmettir' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حكم',
        forms: [
          { label: 'plural', arabic: 'حِكَم' },
        ],
        occurrences: 20,
        occurringForm: 'حِكْمَةٌۢ',
      },
    },
    {
      id: 'hamiym',
      arabic: 'حَمِيم',
      english: 'scalding water; close friend',
      turkish: 'kaynar su; yakın dost',
      example: {
        arabic: 'إِلَّا حَمِيمًۭا وَغَسَّاقًۭا',
        english: 'except scalding water and a foul discharge,',
        turkish: 'ancak kaynar su ve irin,',
        source: 'Qur\'an 78:25',
        highlight: { english: 'scalding water', turkish: 'kaynar su' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حمم',
        occurrences: 20,
        occurringForm: 'حَمِيمًا',
      },
    },
    {
      id: 'sabaqa',
      arabic: 'سَبَقَ',
      english: 'to precede, to outstrip',
      turkish: 'geçmek, önce gelmek',
      example: {
        arabic: 'وَلَقَدْ سَبَقَتْ كَلِمَتُنَا لِعِبَادِنَا ٱلْمُرْسَلِينَ',
        english: 'And Our word has already preceded for Our servants, the messengers,',
        turkish: 'Andolsun, gönderilen kullarımız hakkında sözümüz önceden geçmiştir,',
        source: 'Qur\'an 37:171',
        highlight: { english: 'has already preceded', turkish: 'önceden geçmiştir' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سبق',
        forms: [
          { label: 'mudari', arabic: 'يَسْبِقُ' },
          { label: 'masdar', arabic: 'سَبْق' },
        ],
        occurrences: 20,
        occurringForm: 'سَبَقَتْ',
      },
    },
    {
      id: 'saa-3',
      arabic: 'سَعَى',
      english: 'to strive, to hasten',
      turkish: 'koşmak, çabalamak',
      example: {
        arabic: 'ثُمَّ أَدْبَرَ يَسْعَىٰ',
        english: 'Then he turned his back, hastening.',
        turkish: 'Sonra sırtını dönüp koşarak gitti.',
        source: 'Qur\'an 79:22',
        highlight: { english: 'hastening', turkish: 'koşarak' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سعي',
        forms: [
          { label: 'mudari', arabic: 'يَسْعَى' },
          { label: 'masdar', arabic: 'سَعْي' },
        ],
        occurrences: 20,
        occurringForm: 'يَسْعَىٰ',
      },
    },
    {
      id: 'sabir',
      arabic: 'صابِر',
      english: 'patient, steadfast',
      turkish: 'sabreden, sabırlı',
      example: {
        arabic: 'قَالَ سَتَجِدُنِىٓ إِن شَآءَ ٱللَّهُ صَابِرًۭا وَلَآ أَعْصِى لَكَ أَمْرًۭا',
        english: 'He said: You will find me, if Allah wills, patient, and I will not disobey you in any matter.',
        turkish: 'Dedi ki: İnşallah beni sabırlı bulacaksın ve senin hiçbir emrine karşı gelmeyeceğim.',
        source: 'Qur\'an 18:69',
        highlight: { english: 'patient', turkish: 'sabırlı' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صبر',
        forms: [
          { label: 'plural', arabic: 'صَابِرُون' },
        ],
        occurrences: 20,
        occurringForm: 'صَابِرًا',
      },
    },
    {
      id: 'zulm',
      arabic: 'ظُلْم',
      english: 'wrongdoing, injustice',
      turkish: 'zulüm, haksızlık',
      example: {
        arabic: '۞ وَعَنَتِ ٱلْوُجُوهُ لِلْحَىِّ ٱلْقَيُّومِ ۖ وَقَدْ خَابَ مَنْ حَمَلَ ظُلْمًۭا',
        english: 'And the faces will be humbled before the Ever-Living, the Sustainer, and he who carries wrongdoing will have failed.',
        turkish: 'Yüzler, diri ve her şeyi ayakta tutan Allah\'a boyun eğmiştir. Zulüm yüklenen ise hüsrana uğramıştır.',
        source: 'Qur\'an 20:111',
        highlight: { english: 'wrongdoing', turkish: 'Zulüm' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ظلم',
        occurrences: 20,
        occurringForm: 'ظُلْمًا',
      },
    },
    {
      id: 'arafa',
      arabic: 'عَرَفَ',
      english: 'to know, to recognize',
      turkish: 'tanımak, bilmek',
      example: {
        arabic: 'تَعْرِفُ فِى وُجُوهِهِمْ نَضْرَةَ ٱلنَّعِيمِ',
        english: 'You will recognize in their faces the radiance of bliss.',
        turkish: 'Onların yüzlerinde nimetin parlaklığını tanırsın.',
        source: 'Qur\'an 83:24',
        highlight: { english: 'recognize', turkish: 'tanırsın' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عرف',
        forms: [
          { label: 'mudari', arabic: 'يَعْرِفُ' },
          { label: 'masdar', arabic: 'مَعْرِفَة' },
        ],
        occurrences: 20,
        occurringForm: 'تَعْرِفُ',
      },
    },
    {
      id: 'iqab',
      arabic: 'عِقاب',
      english: 'punishment, retribution',
      turkish: 'ceza, azap',
      example: {
        arabic: 'إِن كُلٌّ إِلَّا كَذَّبَ ٱلرُّسُلَ فَحَقَّ عِقَابِ',
        english: 'Each of them did nothing but deny the messengers, so My punishment became due.',
        turkish: 'Hepsi de peygamberleri yalanladı; böylece azabım hak oldu.',
        source: 'Qur\'an 38:14',
        highlight: { english: 'punishment', turkish: 'azabım' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عقب',
        occurrences: 20,
        occurringForm: 'عِقَابِ',
      },
    },
    {
      id: 'qassa',
      arabic: 'قَصَّ',
      english: 'to relate, to narrate',
      turkish: 'anlatmak, kıssa etmek',
      example: {
        arabic: 'نَّحْنُ نَقُصُّ عَلَيْكَ نَبَأَهُم بِٱلْحَقِّ ۚ إِنَّهُمْ فِتْيَةٌ ءَامَنُوا۟ بِرَبِّهِمْ وَزِدْنَٰهُمْ هُدًۭى',
        english: 'We relate to you their story in truth. Indeed, they were youths who believed in their Lord, and We increased them in guidance.',
        turkish: 'Biz sana onların haberini gerçek olarak anlatıyoruz. Onlar Rablerine inanmış gençlerdi; biz de onların hidayetini artırdık.',
        source: 'Qur\'an 18:13',
        highlight: { english: 'relate', turkish: 'anlatıyoruz' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'قصص',
        forms: [
          { label: 'mudari', arabic: 'يَقُصُّ' },
          { label: 'masdar', arabic: 'قَصَص' },
        ],
        occurrences: 20,
        occurringForm: 'نَقُصُّ',
      },
    },
    {
      id: 'kallama',
      arabic: 'كَلَّمَ',
      english: 'to speak to, to address',
      turkish: 'konuşmak, söz söylemek',
      example: {
        arabic: 'فَأَشَارَتْ إِلَيْهِ ۖ قَالُوا۟ كَيْفَ نُكَلِّمُ مَن كَانَ فِى ٱلْمَهْدِ صَبِيًّۭا',
        english: 'So she pointed to him. They said: How can we speak to one who is a child in the cradle?',
        turkish: 'Bunun üzerine ona işaret etti. Dediler ki: Beşikteki bir çocukla nasıl konuşuruz?',
        source: 'Qur\'an 19:29',
        highlight: { english: 'speak to', turkish: 'konuşuruz' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'كلم',
        forms: [
          { label: 'mudari', arabic: 'يُكَلِّمُ' },
          { label: 'masdar', arabic: 'تَكْلِيم' },
        ],
        occurrences: 20,
        occurringForm: 'نُكَلِّمُ',
      },
    },
    {
      id: 'marra',
      arabic: 'مَرَّة',
      english: 'time, occasion',
      turkish: 'kez, defa',
      example: {
        arabic: 'وَلَقَدْ مَنَنَّا عَلَيْكَ مَرَّةً أُخْرَىٰٓ',
        english: 'And We had certainly shown favor to you another time,',
        turkish: 'Andolsun, sana bir kez daha lütufta bulunmuştuk,',
        source: 'Qur\'an 20:37',
        highlight: { english: 'another time', turkish: 'bir kez' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'مرر',
        forms: [
          { label: 'plural', arabic: 'مَرَّات' },
        ],
        occurrences: 20,
        occurringForm: 'مَرَّةً',
      },
    },
    {
      id: 'haruwn',
      arabic: 'هارُون',
      english: 'Aaron',
      turkish: 'Harun',
      example: {
        arabic: 'هَٰرُونَ أَخِى',
        english: 'Aaron, my brother,',
        turkish: 'Kardeşim Harun\'u,',
        source: 'Qur\'an 20:30',
        highlight: { english: 'Aaron', turkish: 'Harun' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 20,
        occurringForm: 'هَٰرُونَ',
      },
    },
    {
      id: 'aqrab',
      arabic: 'أَقْرَب',
      english: 'nearer, nearest',
      turkish: 'daha yakın, en yakın',
      example: {
        arabic: 'وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنكُمْ وَلَٰكِن لَّا تُبْصِرُونَ',
        english: 'And We are nearer to him than you, but you do not see.',
        turkish: 'Biz ona sizden daha yakınız, fakat siz görmezsiniz.',
        source: 'Qur\'an 56:85',
        highlight: { english: 'nearer', turkish: 'daha yakınız' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قرب',
        occurrences: 19,
        occurringForm: 'أَقْرَبُ',
      },
    },
    {
      id: 'ayn-2',
      arabic: 'أَيْن',
      english: 'where',
      turkish: 'nerede',
      example: {
        arabic: 'يَقُولُ ٱلْإِنسَٰنُ يَوْمَئِذٍ أَيْنَ ٱلْمَفَرُّ',
        english: 'Man will say that Day: Where is the place of escape?',
        turkish: 'O gün insan: Kaçacak yer nerede? der.',
        source: 'Qur\'an 75:10',
        highlight: { english: 'Where', turkish: 'nerede' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 19,
        occurringForm: 'أَيْنَ',
      },
    },
    {
      id: 'astajala',
      arabic: 'اسْتَعْجَلَ',
      english: 'to seek to hasten, to be impatient for',
      turkish: 'acele istemek, çabuklaştırmak istemek',
      example: {
        arabic: 'قُلْ أَرَءَيْتُمْ إِنْ أَتَىٰكُمْ عَذَابُهُۥ بَيَٰتًا أَوْ نَهَارًۭا مَّاذَا يَسْتَعْجِلُ مِنْهُ ٱلْمُجْرِمُونَ',
        english: 'Say: Have you considered, if His punishment came to you by night or by day, what part of it would the criminals seek to hasten?',
        turkish: 'De ki: Söyleyin bakalım, O\'nun azabı size geceleyin ya da gündüzün gelse, suçlular onun neyini acele isterler?',
        source: 'Qur\'an 10:50',
        highlight: { english: 'seek to hasten', turkish: 'acele isterler' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عجل',
        forms: [
          { label: 'mudari', arabic: 'يَسْتَعْجِلُ' },
          { label: 'masdar', arabic: 'اسْتِعْجَال' },
        ],
        occurrences: 19,
        occurringForm: 'يَسْتَعْجِلُ',
      },
    },
    {
      id: 'ziyna',
      arabic: 'زِينَة',
      english: 'adornment, ornament',
      turkish: 'süs, ziynet',
      example: {
        arabic: 'إِنَّا جَعَلْنَا مَا عَلَى ٱلْأَرْضِ زِينَةًۭ لَّهَا لِنَبْلُوَهُمْ أَيُّهُمْ أَحْسَنُ عَمَلًۭا',
        english: 'Indeed, We have made what is on the earth an adornment for it, so that We may test them as to which of them is best in deed.',
        turkish: 'Biz yeryüzündeki şeyleri ona bir süs yaptık ki, hangisinin daha güzel iş yaptığını sınayalım.',
        source: 'Qur\'an 18:7',
        highlight: { english: 'adornment', turkish: 'süs' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'زين',
        occurrences: 19,
        occurringForm: 'زِينَةً',
      },
    },
    {
      id: 'shajara',
      arabic: 'شَجَرَة',
      english: 'tree',
      turkish: 'ağaç',
      example: {
        arabic: 'إِنَّ شَجَرَتَ ٱلزَّقُّومِ',
        english: 'Indeed, the tree of Zaqqum',
        turkish: 'Şüphesiz zakkum ağacı,',
        source: 'Qur\'an 44:43',
        highlight: { english: 'tree', turkish: 'ağacı' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شجر',
        forms: [
          { label: 'plural', arabic: 'أَشْجَار' },
        ],
        occurrences: 19,
        occurringForm: 'شَجَرَتَ',
      },
    },
    {
      id: 'durr',
      arabic: 'ضُرّ',
      english: 'harm, affliction',
      turkish: 'zarar, sıkıntı',
      example: {
        arabic: '۞ وَلَوْ رَحِمْنَٰهُمْ وَكَشَفْنَا مَا بِهِم مِّن ضُرٍّۢ لَّلَجُّوا۟ فِى طُغْيَٰنِهِمْ يَعْمَهُونَ',
        english: 'And if We had mercy upon them and removed the harm that was upon them, they would persist in their transgression, wandering blindly.',
        turkish: 'Onlara acıyıp başlarındaki sıkıntıyı gidersek bile, azgınlıkları içinde şaşkın şaşkın direnip dururlar.',
        source: 'Qur\'an 23:75',
        highlight: { english: 'the harm', turkish: 'sıkıntıyı' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ضرر',
        occurrences: 19,
        occurringForm: 'ضُرٍّ',
      },
    },
    {
      id: 'tayr',
      arabic: 'طَيْر',
      english: 'bird, birds',
      turkish: 'kuş',
      example: {
        arabic: 'وَأَرْسَلَ عَلَيْهِمْ طَيْرًا أَبَابِيلَ',
        english: 'And He sent against them birds in flocks,',
        turkish: 'Üzerlerine sürü sürü kuşlar gönderdi,',
        source: 'Qur\'an 105:3',
        highlight: { english: 'birds', turkish: 'kuşlar' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'طير',
        forms: [
          { label: 'plural', arabic: 'طُيُور' },
        ],
        occurrences: 19,
        occurringForm: 'طَيْرًا',
      },
    },
  ],
}
