import type { DeckDef } from '../types'

// Quran Vocabulary, level 6. See GitHub issue #8.
//
// Scaffolded by scripts/generateVocab.ts: the headword, root, occurrence count,
// ayah and citation come from the corpus and the canonical text. The meanings,
// principal parts and ayah translations were authored on top of that scaffold.
//
// Where the corpus lemmatizes a word to a passive, an imperative or a mudari
// that nobody looks up, the note id is the dictionary form while the headword
// stays as the corpus has it, since that is what the ayah shows.
//
// DRAFT: verify every English meaning before memorizing it. Turkish is
// convenience text and stays draft - correct it on sight while studying.
//
// Locked until the previous level is mostly graduated; see quranVocabTrack.ts.

export const quranVocab6: DeckDef = {
  id: 'quran-vocab-6',
  name: { english: 'Quran Vocabulary 6', turkish: 'Kur’an Kelimeleri 6' },
  nameArabic: 'مُفْرَدَاتُ الْقُرْآنِ ٦',
  description: {
    english:
      'Frequency band 6 of the Quran vocabulary track, each word with an ayah where it occurs.',
    turkish:
      'Kur’an kelime yolunun 6. sıklık kuşağı; her kelime geçtiği bir ayetle.',
  },
  directions: ['ar-to-meaning'],
  newPerDay: 10,
  burySiblings: true,
  notes: [
    {
      id: 'adkhala',
      arabic: 'أُدْخِلَ',
      english: 'to admit, to cause to enter',
      turkish: 'sokmak, dahil etmek',
      example: {
        arabic: 'أَيَطْمَعُ كُلُّ ٱمْرِئٍۢ مِّنْهُمْ أَن يُدْخَلَ جَنَّةَ نَعِيمٍۢ',
        english: 'Does every man among them long to be admitted into a Garden of Bliss?',
        turkish: 'Onlardan her biri bir nimet cennetine sokulmayı mı umuyor?',
        source: 'Qur\'an 70:38',
        highlight: { english: 'admitted', turkish: 'sokulmayı' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'دخل',
        forms: [
          { label: 'mudari', arabic: 'يُدْخِلُ' },
          { label: 'masdar', arabic: 'إِدْخَال' },
        ],
        occurrences: 42,
        occurringForm: 'يُدْخَلَ',
      },
    },
    {
      id: 'astataa',
      arabic: 'اسْتَطاعَ',
      english: 'to be able, to have the power to',
      turkish: 'gücü yetmek, -ebilmek',
      example: {
        arabic: 'قَالَ إِنَّكَ لَن تَسْتَطِيعَ مَعِىَ صَبْرًۭا',
        english: 'He said: Indeed, you will never be able to have patience with me.',
        turkish: 'Dedi ki: Sen benimle beraber sabretmeye asla güç yetiremezsin.',
        source: 'Qur\'an 18:67',
        highlight: { english: 'be able', turkish: 'güç yetiremezsin' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'طوع',
        forms: [
          { label: 'mudari', arabic: 'يَسْتَطِيعُ' },
          { label: 'masdar', arabic: 'اِسْتِطَاعَة' },
        ],
        occurrences: 42,
        occurringForm: 'تَسْتَطِيعَ',
      },
    },
    {
      id: 'jaza',
      arabic: 'جَزاء',
      english: 'recompense, requital, reward',
      turkish: 'karşılık, ceza, mükâfat',
      example: {
        arabic: 'جَزَآءًۭ وِفَاقًا',
        english: 'a fitting recompense.',
        turkish: 'Yaptıklarına uygun bir karşılık olarak.',
        source: 'Qur\'an 78:26',
        highlight: { english: 'recompense', turkish: 'karşılık' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'جزي',
        occurrences: 42,
        occurringForm: 'جَزَآءً',
      },
    },
    {
      id: 'sabbaha',
      arabic: 'سَبَّحَ',
      english: 'to glorify, to exalt',
      turkish: 'tesbih etmek, yüceltmek',
      example: {
        arabic: 'سَبِّحِ ٱسْمَ رَبِّكَ ٱلْأَعْلَى',
        english: 'Glorify the name of your Lord, the Most High,',
        turkish: 'Yüce Rabbinin adını tesbih et,',
        source: 'Qur\'an 87:1',
        highlight: { english: 'Glorify', turkish: 'tesbih et' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سبح',
        forms: [
          { label: 'mudari', arabic: 'يُسَبِّحُ' },
          { label: 'masdar', arabic: 'تَسْبِيح' },
        ],
        occurrences: 42,
        occurringForm: 'سَبِّحِ',
      },
    },
    {
      id: 'salam',
      arabic: 'سَلام',
      english: 'peace, safety',
      turkish: 'selam, esenlik, barış',
      example: {
        arabic: 'سَلَٰمٌ عَلَىٰٓ إِبْرَٰهِيمَ',
        english: 'Peace be upon Ibrahim.',
        turkish: 'İbrahim\'e selam olsun.',
        source: 'Qur\'an 37:109',
        highlight: { english: 'Peace', turkish: 'selam' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سلم',
        occurrences: 42,
        occurringForm: 'سَلَٰمٌ',
      },
    },
    {
      id: 'sawf',
      arabic: 'سَوْف',
      english: 'will, shall (future particle)',
      turkish: '-ecek, yakında (istikbal edatı)',
      example: {
        arabic: 'كَلَّا سَوْفَ تَعْلَمُونَ',
        english: 'No! You are going to know.',
        turkish: 'Hayır! Yakında bileceksiniz.',
        source: 'Qur\'an 102:3',
        highlight: { english: 'going to', turkish: 'Yakında' },
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 42,
        occurringForm: 'سَوْفَ',
      },
    },
    {
      id: 'kalima',
      arabic: 'كَلِمَة',
      english: 'word, utterance',
      turkish: 'kelime, söz',
      example: {
        arabic: 'وَجَعَلَهَا كَلِمَةًۢ بَاقِيَةًۭ فِى عَقِبِهِۦ لَعَلَّهُمْ يَرْجِعُونَ',
        english: 'And he made it a word remaining among his descendants, that they might return.',
        turkish: 'Ve onu, ardından geleceklere kalıcı bir söz kıldı; belki dönerler diye.',
        source: 'Qur\'an 43:28',
        highlight: { english: 'a word', turkish: 'söz' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كلم',
        forms: [
          { label: 'plural', arabic: 'كَلِمَات' },
        ],
        occurrences: 42,
        occurringForm: 'كَلِمَةًۢ',
      },
    },
    {
      id: 'bahr',
      arabic: 'بَحْر',
      english: 'sea',
      turkish: 'deniz',
      example: {
        arabic: 'وَإِذَا ٱلْبِحَارُ سُجِّرَتْ',
        english: 'And when the seas are set ablaze,',
        turkish: 'Denizler kaynatıldığı zaman,',
        source: 'Qur\'an 81:6',
        highlight: { english: 'seas', turkish: 'Denizler' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بحر',
        forms: [
          { label: 'plural', arabic: 'بِحَار' },
        ],
        occurrences: 41,
        occurringForm: 'ٱلْبِحَارُ',
      },
    },
    {
      id: 'hamala',
      arabic: 'حَمَلَ',
      english: 'to carry, to bear',
      turkish: 'taşımak, yüklenmek',
      example: {
        arabic: 'مَّنْ أَعْرَضَ عَنْهُ فَإِنَّهُۥ يَحْمِلُ يَوْمَ ٱلْقِيَٰمَةِ وِزْرًا',
        english: 'Whoever turns away from it will bear a burden on the Day of Resurrection,',
        turkish: 'Kim ondan yüz çevirirse, kıyamet günü ağır bir yük taşır,',
        source: 'Qur\'an 20:100',
        highlight: { english: 'bear', turkish: 'taşır' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حمل',
        forms: [
          { label: 'mudari', arabic: 'يَحْمِلُ' },
          { label: 'masdar', arabic: 'حَمْل' },
        ],
        occurrences: 41,
        occurringForm: 'يَحْمِلُ',
      },
    },
    {
      id: 'subhan',
      arabic: 'سُبْحان',
      english: 'glory, exaltedness',
      turkish: 'tesbih, münezzeh oluş',
      example: {
        arabic: 'سُبْحَٰنَ ٱللَّهِ عَمَّا يَصِفُونَ',
        english: 'Exalted is Allah above what they describe,',
        turkish: 'Allah, onların nitelendirdiklerinden münezzehtir,',
        source: 'Qur\'an 37:159',
        highlight: { english: 'Exalted is', turkish: 'münezzehtir' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سبح',
        occurrences: 41,
        occurringForm: 'سُبْحَٰنَ',
      },
    },
    {
      id: 'adhdhaba',
      arabic: 'عَذَّبَ',
      english: 'to punish, to torment',
      turkish: 'azap etmek, cezalandırmak',
      example: {
        arabic: 'فَيَوْمَئِذٍۢ لَّا يُعَذِّبُ عَذَابَهُۥٓ أَحَدٌۭ',
        english: 'So on that Day none will punish as He punishes,',
        turkish: 'O gün hiç kimse O\'nun azabı gibi azap edemez,',
        source: 'Qur\'an 89:25',
        highlight: { english: 'will punish', turkish: 'azap edemez' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عذب',
        forms: [
          { label: 'mudari', arabic: 'يُعَذِّبُ' },
          { label: 'masdar', arabic: 'تَعْذِيب' },
        ],
        occurrences: 41,
        occurringForm: 'يُعَذِّبُ',
      },
    },
    {
      id: 'allama',
      arabic: 'عَلَّمَ',
      english: 'to teach',
      turkish: 'öğretmek',
      example: {
        arabic: 'عَلَّمَ ٱلْقُرْءَانَ',
        english: 'He taught the Qur\'an.',
        turkish: 'Kur\'an\'ı öğretti.',
        source: 'Qur\'an 55:2',
        highlight: { english: 'taught', turkish: 'öğretti' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'علم',
        forms: [
          { label: 'mudari', arabic: 'يُعَلِّمُ' },
          { label: 'masdar', arabic: 'تَعْلِيم' },
        ],
        occurrences: 41,
        occurringForm: 'عَلَّمَ',
      },
    },
    {
      id: 'fawq',
      arabic: 'فَوْق',
      english: 'above, over',
      turkish: 'üstünde, üzerinde',
      example: {
        arabic: 'وَهُوَ ٱلْقَاهِرُ فَوْقَ عِبَادِهِۦ ۚ وَهُوَ ٱلْحَكِيمُ ٱلْخَبِيرُ',
        english: 'And He is the Subjugator over His servants, and He is the Wise, the Aware.',
        turkish: 'O, kullarının üstünde mutlak hâkimdir. O, hikmet sahibidir, her şeyden haberdardır.',
        source: 'Qur\'an 6:18',
        highlight: { english: 'over', turkish: 'üstünde' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'فوق',
        occurrences: 41,
        occurringForm: 'فَوْقَ',
      },
    },
    {
      id: 'araa',
      arabic: 'أَرَيْ',
      english: 'to show, to make see',
      turkish: 'göstermek',
      example: {
        arabic: 'وَكَذَٰلِكَ نُرِىٓ إِبْرَٰهِيمَ مَلَكُوتَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ وَلِيَكُونَ مِنَ ٱلْمُوقِنِينَ',
        english: 'And thus We show Ibrahim the dominion of the heavens and the earth, so that he would be among the certain in faith.',
        turkish: 'İşte böylece İbrahim\'e göklerin ve yerin melekûtunu gösteriyorduk, kesin olarak inananlardan olsun diye.',
        source: 'Qur\'an 6:75',
        highlight: { english: 'show', turkish: 'gösteriyorduk' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'رأي',
        forms: [
          { label: 'mudari', arabic: 'يُرِي' },
        ],
        occurrences: 40,
        occurringForm: 'نُرِىٓ',
      },
    },
    {
      id: 'astaghfara',
      arabic: 'اسْتَغْفَرَ',
      english: 'to ask forgiveness',
      turkish: 'istiğfar etmek, bağışlanma dilemek',
      example: {
        arabic: 'قَالُوا۟ يَٰٓأَبَانَا ٱسْتَغْفِرْ لَنَا ذُنُوبَنَآ إِنَّا كُنَّا خَٰطِـِٔينَ',
        english: 'They said: O our father, ask forgiveness for us for our sins; indeed, we have been sinners.',
        turkish: 'Dediler ki: Ey babamız! Günahlarımız için bizim adımıza bağışlanma dile; doğrusu biz hata edenlerdik.',
        source: 'Qur\'an 12:97',
        highlight: { english: 'ask forgiveness', turkish: 'bağışlanma dile' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'غفر',
        forms: [
          { label: 'mudari', arabic: 'يَسْتَغْفِرُ' },
          { label: 'masdar', arabic: 'اِسْتِغْفَار' },
        ],
        occurrences: 40,
        occurringForm: 'ٱسْتَغْفِرْ',
      },
    },
    {
      id: 'astakbara',
      arabic: 'اسْتَكْبَرَ',
      english: 'to be arrogant, to scorn',
      turkish: 'kibirlenmek, büyüklenmek',
      example: {
        arabic: 'إِلَّآ إِبْلِيسَ ٱسْتَكْبَرَ وَكَانَ مِنَ ٱلْكَٰفِرِينَ',
        english: 'except Iblis; he was arrogant and was one of the disbelievers.',
        turkish: 'Ancak İblis hariç; o büyüklendi ve kâfirlerden oldu.',
        source: 'Qur\'an 38:74',
        highlight: { english: 'was arrogant', turkish: 'büyüklendi' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'كبر',
        forms: [
          { label: 'mudari', arabic: 'يَسْتَكْبِرُ' },
          { label: 'masdar', arabic: 'اِسْتِكْبَار' },
        ],
        occurrences: 40,
        occurringForm: 'ٱسْتَكْبَرَ',
      },
    },
    {
      id: 'ahtadaa',
      arabic: 'اهْتَدَى',
      english: 'to be guided, to follow guidance',
      turkish: 'hidayete ermek, doğru yolu bulmak',
      example: {
        arabic: 'وَإِنِّى لَغَفَّارٌۭ لِّمَن تَابَ وَءَامَنَ وَعَمِلَ صَٰلِحًۭا ثُمَّ ٱهْتَدَىٰ',
        english: 'And indeed, I am the Perpetual Forgiver of whoever repents and believes and does righteousness and then is guided.',
        turkish: 'Ve ben, tövbe edip iman eden, salih amel işleyen, sonra da doğru yolu tutan kimseyi elbette çok bağışlarım.',
        source: 'Qur\'an 20:82',
        highlight: { english: 'is guided', turkish: 'doğru yolu tutan' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'هدي',
        forms: [
          { label: 'mudari', arabic: 'يَهْتَدِي' },
          { label: 'masdar', arabic: 'اِهْتِدَاء' },
        ],
        occurrences: 40,
        occurringForm: 'ٱهْتَدَىٰ',
      },
    },
    {
      id: 'bisa',
      arabic: 'بِئْسَ',
      english: 'how wretched is, evil is (verb of blame)',
      turkish: 'ne kötü, ne fena (zem fiili)',
      example: {
        arabic: 'وَأُتْبِعُوا۟ فِى هَٰذِهِۦ لَعْنَةًۭ وَيَوْمَ ٱلْقِيَٰمَةِ ۚ بِئْسَ ٱلرِّفْدُ ٱلْمَرْفُودُ',
        english: 'And they were followed in this world by a curse, and on the Day of Resurrection. Wretched is the gift that is given.',
        turkish: 'Bu dünyada da kıyamet gününde de lanete uğratıldılar. Verilen o bağış ne kötü bağıştır!',
        source: 'Qur\'an 11:99',
        highlight: { english: 'Wretched is', turkish: 'ne kötü' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بأس',
        occurrences: 40,
        occurringForm: 'بِئْسَ',
      },
    },
    {
      id: 'balagha',
      arabic: 'بَلَغَ',
      english: 'to reach, to attain',
      turkish: 'ulaşmak, erişmek',
      example: {
        arabic: 'فَلَوْلَآ إِذَا بَلَغَتِ ٱلْحُلْقُومَ',
        english: 'Then why, when it reaches the throat,',
        turkish: 'Peki, can boğaza ulaştığı zaman,',
        source: 'Qur\'an 56:83',
        highlight: { english: 'reaches', turkish: 'ulaştığı' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بلغ',
        forms: [
          { label: 'mudari', arabic: 'يَبْلُغُ' },
          { label: 'masdar', arabic: 'بُلُوغ' },
        ],
        occurrences: 40,
        occurringForm: 'بَلَغَتِ',
      },
    },
    {
      id: 'taraka',
      arabic: 'تَرَكَ',
      english: 'to leave, to abandon',
      turkish: 'bırakmak, terk etmek',
      example: {
        arabic: 'أَيَحْسَبُ ٱلْإِنسَٰنُ أَن يُتْرَكَ سُدًى',
        english: 'Does man think that he will be left neglected?',
        turkish: 'İnsan başıboş bırakılacağını mı sanıyor?',
        source: 'Qur\'an 75:36',
        highlight: { english: 'left', turkish: 'bırakılacağını' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ترك',
        forms: [
          { label: 'mudari', arabic: 'يَتْرُكُ' },
          { label: 'masdar', arabic: 'تَرْك' },
        ],
        occurrences: 40,
        occurringForm: 'يُتْرَكَ',
      },
    },
    {
      id: 'tawakkala',
      arabic: 'تَوَكَّلْ',
      english: 'to trust, to rely upon',
      turkish: 'tevekkül etmek, güvenip dayanmak',
      example: {
        arabic: 'وَتَوَكَّلْ عَلَى ٱلْعَزِيزِ ٱلرَّحِيمِ',
        english: 'And rely upon the Exalted in Might, the Merciful,',
        turkish: 'Ve Azîz olana, Rahîm olana güvenip dayan,',
        source: 'Qur\'an 26:217',
        highlight: { english: 'rely upon', turkish: 'güvenip dayan' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'وكل',
        forms: [
          { label: 'mudari', arabic: 'يَتَوَكَّلُ' },
          { label: 'masdar', arabic: 'تَوَكُّل' },
        ],
        occurrences: 40,
        occurringForm: 'وَتَوَكَّلْ',
      },
    },
    {
      id: 'khashiya',
      arabic: 'خَشِيَ',
      english: 'to fear, to stand in awe of',
      turkish: 'korkmak, haşyet duymak',
      example: {
        arabic: 'وَهُوَ يَخْشَىٰ',
        english: 'while he fears,',
        turkish: 've o korkuyorken,',
        source: 'Qur\'an 80:9',
        highlight: { english: 'fears', turkish: 'korkuyorken' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'خشي',
        forms: [
          { label: 'mudari', arabic: 'يَخْشَى' },
          { label: 'masdar', arabic: 'خَشْيَة' },
        ],
        occurrences: 40,
        occurringForm: 'يَخْشَىٰ',
      },
    },
    {
      id: 'shariyk',
      arabic: 'شَرِيك',
      english: 'partner, associate',
      turkish: 'şerik, ortak',
      example: {
        arabic: 'لَا شَرِيكَ لَهُۥ ۖ وَبِذَٰلِكَ أُمِرْتُ وَأَنَا۠ أَوَّلُ ٱلْمُسْلِمِينَ',
        english: 'He has no partner. And this I have been commanded, and I am the first of those who submit.',
        turkish: 'O\'nun ortağı yoktur. Bana böyle emrolundu ve ben müslümanların ilkiyim.',
        source: 'Qur\'an 6:163',
        highlight: { english: 'partner', turkish: 'ortağı' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شرك',
        forms: [
          { label: 'plural', arabic: 'شُرَكَاء' },
        ],
        occurrences: 40,
        occurringForm: 'شَرِيكَ',
      },
    },
    {
      id: 'kabiyr',
      arabic: 'كَبِير',
      english: 'great, big',
      turkish: 'büyük, ulu',
      example: {
        arabic: 'سُبْحَٰنَهُۥ وَتَعَٰلَىٰ عَمَّا يَقُولُونَ عُلُوًّۭا كَبِيرًۭا',
        english: 'Exalted is He and high above what they say, by a great exaltation.',
        turkish: 'O, onların söylediklerinden münezzehtir ve büyük bir yücelikle yücedir.',
        source: 'Qur\'an 17:43',
        highlight: { english: 'great', turkish: 'büyük' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كبر',
        forms: [
          { label: 'plural', arabic: 'كِبَار' },
        ],
        occurrences: 40,
        occurringForm: 'كَبِيرًا',
      },
    },
    {
      id: 'wayl',
      arabic: 'وَيْل',
      english: 'woe, destruction',
      turkish: 'vay hâline, yazıklar olsun',
      example: {
        arabic: 'وَيْلٌۭ لِّلْمُطَفِّفِينَ',
        english: 'Woe to those who give short measure,',
        turkish: 'Ölçüyü eksik tutanların vay hâline,',
        source: 'Qur\'an 83:1',
        highlight: { english: 'Woe', turkish: 'vay hâline' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 40,
        occurringForm: 'وَيْلٌ',
      },
    },
    {
      id: 'ala-2',
      arabic: 'أَلا',
      english: 'behold, indeed (attention particle)',
      turkish: 'dikkat edin, iyi bilin ki (tenbih edatı)',
      example: {
        arabic: 'أَلَآ إِنَّهُم مِّنْ إِفْكِهِمْ لَيَقُولُونَ',
        english: 'Unquestionably, out of their falsehood they say,',
        turkish: 'İyi bilin ki onlar, uydurdukları yalan yüzünden şöyle diyorlar,',
        source: 'Qur\'an 37:151',
        highlight: { english: 'Unquestionably', turkish: 'İyi bilin ki' },
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 39,
        occurringForm: 'أَلَآ',
      },
    },
    {
      id: 'idhn',
      arabic: 'إِذْن',
      english: 'permission, leave',
      turkish: 'izin',
      example: {
        arabic: 'تَنَزَّلُ ٱلْمَلَٰٓئِكَةُ وَٱلرُّوحُ فِيهَا بِإِذْنِ رَبِّهِم مِّن كُلِّ أَمْرٍۢ',
        english: 'The angels and the Spirit descend therein by the permission of their Lord for every matter.',
        turkish: 'Melekler ve Ruh, o gecede Rablerinin izniyle her iş için iner.',
        source: 'Qur\'an 97:4',
        highlight: { english: 'permission', turkish: 'izniyle' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أذن',
        occurrences: 39,
        occurringForm: 'بِإِذْنِ',
      },
    },
    {
      id: 'asm',
      arabic: 'اسْم',
      english: 'name',
      turkish: 'isim, ad',
      example: {
        arabic: 'سَبِّحِ ٱسْمَ رَبِّكَ ٱلْأَعْلَى',
        english: 'Glorify the name of your Lord, the Most High,',
        turkish: 'Yüce Rabbinin adını tesbih et,',
        source: 'Qur\'an 87:1',
        highlight: { english: 'name', turkish: 'adını' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سمو',
        forms: [
          { label: 'plural', arabic: 'أَسْمَاء' },
        ],
        occurrences: 39,
        occurringForm: 'ٱسْمَ',
      },
    },
    {
      id: 'jabal',
      arabic: 'جَبَل',
      english: 'mountain',
      turkish: 'dağ',
      example: {
        arabic: 'وَإِذَا ٱلْجِبَالُ سُيِّرَتْ',
        english: 'And when the mountains are set moving,',
        turkish: 'Dağlar yürütüldüğü zaman,',
        source: 'Qur\'an 81:3',
        highlight: { english: 'mountains', turkish: 'Dağlar' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'جبل',
        forms: [
          { label: 'plural', arabic: 'جِبَال' },
        ],
        occurrences: 39,
        occurringForm: 'ٱلْجِبَالُ',
      },
    },
    {
      id: 'harrama',
      arabic: 'حَرَّمَ',
      english: 'to forbid, to make unlawful',
      turkish: 'haram kılmak, yasaklamak',
      example: {
        arabic: 'يَٰٓأَيُّهَا ٱلنَّبِىُّ لِمَ تُحَرِّمُ مَآ أَحَلَّ ٱللَّهُ لَكَ ۖ تَبْتَغِى مَرْضَاتَ أَزْوَٰجِكَ ۚ وَٱللَّهُ غَفُورٌۭ رَّحِيمٌۭ',
        english: 'O Prophet, why do you forbid what Allah has made lawful for you, seeking the pleasure of your wives? And Allah is Forgiving and Merciful.',
        turkish: 'Ey Peygamber! Eşlerinin hoşnutluğunu arayarak, Allah\'ın sana helal kıldığını niçin kendine haram kılıyorsun? Allah çok bağışlayandır, çok merhametlidir.',
        source: 'Qur\'an 66:1',
        highlight: { english: 'forbid', turkish: 'haram kılıyorsun' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حرم',
        forms: [
          { label: 'mudari', arabic: 'يُحَرِّمُ' },
          { label: 'masdar', arabic: 'تَحْرِيم' },
        ],
        occurrences: 39,
        occurringForm: 'تُحَرِّمُ',
      },
    },
    {
      id: 'hisab',
      arabic: 'حِساب',
      english: 'reckoning, account',
      turkish: 'hesap',
      example: {
        arabic: 'فَسَوْفَ يُحَاسَبُ حِسَابًۭا يَسِيرًۭا',
        english: 'he will be called to an easy reckoning,',
        turkish: 'kolay bir hesapla hesaba çekilecek,',
        source: 'Qur\'an 84:8',
        highlight: { english: 'reckoning', turkish: 'hesapla' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حسب',
        occurrences: 39,
        occurringForm: 'حِسَابًا',
      },
    },
    {
      id: 'mata',
      arabic: 'ماتَ',
      english: 'to die',
      turkish: 'ölmek',
      example: {
        arabic: 'ثُمَّ لَا يَمُوتُ فِيهَا وَلَا يَحْيَىٰ',
        english: 'Then he will neither die therein nor live.',
        turkish: 'Sonra orada ne ölür ne de yaşar.',
        source: 'Qur\'an 87:13',
        highlight: { english: 'die', turkish: 'ölür' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'موت',
        forms: [
          { label: 'mudari', arabic: 'يَمُوتُ' },
          { label: 'masdar', arabic: 'مَوْت' },
        ],
        occurrences: 39,
        occurringForm: 'يَمُوتُ',
      },
    },
    {
      id: 'muslim',
      arabic: 'مُسْلِم',
      english: 'Muslim, one who submits',
      turkish: 'müslüman, teslim olan',
      example: {
        arabic: 'أَلَّا تَعْلُوا۟ عَلَىَّ وَأْتُونِى مُسْلِمِينَ',
        english: 'Do not be haughty with me, and come to me in submission.',
        turkish: 'Bana karşı büyüklenmeyin ve teslim olarak bana gelin.',
        source: 'Qur\'an 27:31',
        highlight: { english: 'in submission', turkish: 'teslim olarak' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سلم',
        forms: [
          { label: 'plural', arabic: 'مُسْلِمُون' },
        ],
        occurrences: 39,
        occurringForm: 'مُسْلِمِينَ',
      },
    },
    {
      id: 'bashshara',
      arabic: 'بُشِّرَ',
      english: 'to give good news, to announce tidings',
      turkish: 'müjdelemek',
      example: {
        arabic: 'بَشِّرِ ٱلْمُنَٰفِقِينَ بِأَنَّ لَهُمْ عَذَابًا أَلِيمًا',
        english: 'Give the hypocrites the tidings that for them is a painful punishment,',
        turkish: 'Münafıklara, kendileri için acı bir azap olduğunu müjdele,',
        source: 'Qur\'an 4:138',
        highlight: { english: 'the tidings', turkish: 'müjdele' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بشر',
        forms: [
          { label: 'mudari', arabic: 'يُبَشِّرُ' },
          { label: 'masdar', arabic: 'تَبْشِير' },
        ],
        occurrences: 38,
        occurringForm: 'بَشِّرِ',
      },
    },
    {
      id: 'radiya',
      arabic: 'رَضِيَ',
      english: 'to be pleased, to be satisfied',
      turkish: 'razı olmak, hoşnut olmak',
      example: {
        arabic: 'وَلَسَوْفَ يَرْضَىٰ',
        english: 'And he is going to be satisfied.',
        turkish: 'Ve o elbette hoşnut olacaktır.',
        source: 'Qur\'an 92:21',
        highlight: { english: 'satisfied', turkish: 'hoşnut olacaktır' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'رضو',
        forms: [
          { label: 'mudari', arabic: 'يَرْضَى' },
          { label: 'masdar', arabic: 'رِضًا' },
        ],
        occurrences: 38,
        occurringForm: 'يَرْضَىٰ',
      },
    },
    {
      id: 'dalal',
      arabic: 'ضَلال',
      english: 'error, straying',
      turkish: 'dalâlet, sapıklık',
      example: {
        arabic: 'إِنِّىٓ إِذًۭا لَّفِى ضَلَٰلٍۢ مُّبِينٍ',
        english: 'Indeed, I would then be in clear error.',
        turkish: 'Doğrusu o zaman ben apaçık bir sapıklık içinde olurum.',
        source: 'Qur\'an 36:24',
        highlight: { english: 'error', turkish: 'sapıklık' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ضلل',
        occurrences: 38,
        occurringForm: 'ضَلَٰلٍ',
      },
    },
    {
      id: 'muhsin',
      arabic: 'مُحْسِن',
      english: 'doer of good',
      turkish: 'muhsin, iyilik eden',
      example: {
        arabic: 'إِنَّ ٱللَّهَ مَعَ ٱلَّذِينَ ٱتَّقَوا۟ وَّٱلَّذِينَ هُم مُّحْسِنُونَ',
        english: 'Indeed, Allah is with those who fear Him and those who are doers of good.',
        turkish: 'Şüphesiz Allah, sakınanlarla ve iyilik edenlerle beraberdir.',
        source: 'Qur\'an 16:128',
        highlight: { english: 'doers of good', turkish: 'iyilik edenlerle' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حسن',
        forms: [
          { label: 'plural', arabic: 'مُحْسِنُون' },
        ],
        occurrences: 38,
        occurringForm: 'مُّحْسِنُونَ',
      },
    },
    {
      id: 'maruwf',
      arabic: 'مَعْرُوف',
      english: 'kindness, what is right; known',
      turkish: 'iyilik, uygun olan; bilinen',
      example: {
        arabic: '۞ قَوْلٌۭ مَّعْرُوفٌۭ وَمَغْفِرَةٌ خَيْرٌۭ مِّن صَدَقَةٍۢ يَتْبَعُهَآ أَذًۭى ۗ وَٱللَّهُ غَنِىٌّ حَلِيمٌۭ',
        english: 'A kind word and forgiveness are better than a charity followed by injury. And Allah is Free of need, Forbearing.',
        turkish: 'Güzel bir söz ve bağışlama, ardından eziyet gelen bir sadakadan hayırlıdır. Allah hiçbir şeye muhtaç değildir, halîmdir.',
        source: 'Qur\'an 2:263',
        highlight: { english: 'kind', turkish: 'Güzel' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عرف',
        occurrences: 38,
        occurringForm: 'مَّعْرُوفٌ',
      },
    },
    {
      id: 'mayyit',
      arabic: 'مَيِّت',
      english: 'dead; mortal',
      turkish: 'ölü; ölümlü',
      example: {
        arabic: 'إِنَّكَ مَيِّتٌۭ وَإِنَّهُم مَّيِّتُونَ',
        english: 'Indeed, you will die, and indeed, they will die.',
        turkish: 'Şüphesiz sen de öleceksin, onlar da ölecekler.',
        source: 'Qur\'an 39:30',
        highlight: { english: 'you will die', turkish: 'öleceksin' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'موت',
        forms: [
          { label: 'plural', arabic: 'أَمْوَات' },
        ],
        occurrences: 38,
        occurringForm: 'مَيِّتٌ',
      },
    },
    {
      id: 'bashar',
      arabic: 'بَشَر',
      english: 'human being, mortal',
      turkish: 'beşer, insan',
      example: {
        arabic: 'وَلَئِنْ أَطَعْتُم بَشَرًۭا مِّثْلَكُمْ إِنَّكُمْ إِذًۭا لَّخَٰسِرُونَ',
        english: 'And if you obey a human being like yourselves, indeed you would then be losers.',
        turkish: 'Eğer kendiniz gibi bir insana itaat ederseniz, o zaman siz mutlaka hüsrana uğrayanlardan olursunuz.',
        source: 'Qur\'an 23:34',
        highlight: { english: 'human being', turkish: 'insana' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بشر',
        occurrences: 37,
        occurringForm: 'بَشَرًا',
      },
    },
    {
      id: 'hashara',
      arabic: 'حَشَرَ',
      english: 'to gather, to assemble',
      turkish: 'toplamak, haşretmek',
      example: {
        arabic: 'وَإِذَا ٱلْوُحُوشُ حُشِرَتْ',
        english: 'And when the wild beasts are gathered,',
        turkish: 'Vahşi hayvanlar bir araya toplandığı zaman,',
        source: 'Qur\'an 81:5',
        highlight: { english: 'gathered', turkish: 'toplandığı' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حشر',
        forms: [
          { label: 'mudari', arabic: 'يَحْشُرُ' },
          { label: 'masdar', arabic: 'حَشْر' },
        ],
        occurrences: 37,
        occurringForm: 'حُشِرَتْ',
      },
    },
    {
      id: 'dhanb',
      arabic: 'ذَنب',
      english: 'sin, offense',
      turkish: 'günah, suç',
      example: {
        arabic: 'بِأَىِّ ذَنۢبٍۢ قُتِلَتْ',
        english: 'for what sin she was killed,',
        turkish: 'hangi günah yüzünden öldürüldüğü,',
        source: 'Qur\'an 81:9',
        highlight: { english: 'sin', turkish: 'günah' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ذنب',
        forms: [
          { label: 'plural', arabic: 'ذُنُوب' },
        ],
        occurrences: 37,
        occurringForm: 'ذَنۢبٍ',
      },
    },
    {
      id: 'sultan',
      arabic: 'سُلْطان',
      english: 'authority, warrant, proof',
      turkish: 'yetki, delil, güç',
      example: {
        arabic: 'أَمْ لَكُمْ سُلْطَٰنٌۭ مُّبِينٌۭ',
        english: 'Or do you have a clear authority?',
        turkish: 'Yoksa sizin apaçık bir deliliniz mi var?',
        source: 'Qur\'an 37:156',
        highlight: { english: 'authority', turkish: 'deliliniz' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سلط',
        occurrences: 37,
        occurringForm: 'سُلْطَٰنٌ',
      },
    },
    {
      id: 'sadda',
      arabic: 'صَدَّ',
      english: 'to turn away; to hinder, to bar',
      turkish: 'yüz çevirmek; alıkoymak, engellemek',
      example: {
        arabic: 'فَمِنْهُم مَّنْ ءَامَنَ بِهِۦ وَمِنْهُم مَّن صَدَّ عَنْهُ ۚ وَكَفَىٰ بِجَهَنَّمَ سَعِيرًا',
        english: 'And some of them believed in it, and some of them turned away from it. And sufficient is Hell as a blaze.',
        turkish: 'Onlardan kimi ona iman etti, kimi de ondan yüz çevirdi. Çılgın alevli cehennem yeter.',
        source: 'Qur\'an 4:55',
        highlight: { english: 'turned away', turkish: 'yüz çevirdi' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'صدد',
        forms: [
          { label: 'mudari', arabic: 'يَصُدُّ' },
          { label: 'masdar', arabic: 'صَدّ' },
        ],
        occurrences: 37,
        occurringForm: 'صَدَّ',
      },
    },
    {
      id: 'asa',
      arabic: 'عَصا',
      english: 'to disobey, to rebel against',
      turkish: 'isyan etmek, karşı gelmek',
      example: {
        arabic: 'قَالَ سَتَجِدُنِىٓ إِن شَآءَ ٱللَّهُ صَابِرًۭا وَلَآ أَعْصِى لَكَ أَمْرًۭا',
        english: 'He said: You will find me, if Allah wills, patient, and I will not disobey you in any order.',
        turkish: 'Dedi ki: İnşallah beni sabırlı bulacaksın; senin hiçbir emrine karşı gelmeyeceğim.',
        source: 'Qur\'an 18:69',
        highlight: { english: 'disobey', turkish: 'karşı gelmeyeceğim' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عصو',
        forms: [
          { label: 'mudari', arabic: 'يَعْصِي' },
          { label: 'masdar', arabic: 'عِصْيَان' },
        ],
        occurrences: 37,
        occurringForm: 'أَعْصِى',
      },
    },
    {
      id: 'fasiq',
      arabic: 'فاسِق',
      english: 'transgressor, defiantly disobedient',
      turkish: 'fasık, yoldan çıkmış',
      example: {
        arabic: 'فَٱسْتَخَفَّ قَوْمَهُۥ فَأَطَاعُوهُ ۚ إِنَّهُمْ كَانُوا۟ قَوْمًۭا فَٰسِقِينَ',
        english: 'So he made light of his people, and they obeyed him. Indeed, they were a defiantly disobedient people.',
        turkish: 'Böylece kavmini hafife aldı, onlar da ona itaat ettiler. Şüphesiz onlar yoldan çıkmış bir kavimdi.',
        source: 'Qur\'an 43:54',
        highlight: { english: 'defiantly disobedient', turkish: 'yoldan çıkmış' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'فسق',
        forms: [
          { label: 'plural', arabic: 'فَاسِقُون' },
        ],
        occurrences: 37,
        occurringForm: 'فَٰسِقِينَ',
      },
    },
    {
      id: 'kufr',
      arabic: 'كُفْر',
      english: 'disbelief, ingratitude',
      turkish: 'küfür, inkâr, nankörlük',
      example: {
        arabic: '۞ أَلَمْ تَرَ إِلَى ٱلَّذِينَ بَدَّلُوا۟ نِعْمَتَ ٱللَّهِ كُفْرًۭا وَأَحَلُّوا۟ قَوْمَهُمْ دَارَ ٱلْبَوَارِ',
        english: 'Have you not seen those who exchanged the favor of Allah for disbelief and settled their people in the home of ruin?',
        turkish: 'Allah\'ın nimetini nankörlükle değiştiren ve kavimlerini helak yurduna indirenleri görmedin mi?',
        source: 'Qur\'an 14:28',
        highlight: { english: 'disbelief', turkish: 'nankörlükle' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كفر',
        occurrences: 37,
        occurringForm: 'كُفْرًا',
      },
    },
    {
      id: 'mustaqiym',
      arabic: 'مُسْتَقِيم',
      english: 'straight, upright',
      turkish: 'dosdoğru, düz',
      example: {
        arabic: 'وَلَهَدَيْنَٰهُمْ صِرَٰطًۭا مُّسْتَقِيمًۭا',
        english: 'And We would have guided them to a straight path.',
        turkish: 'Ve onları elbette dosdoğru bir yola iletirdik.',
        source: 'Qur\'an 4:68',
        highlight: { english: 'straight', turkish: 'dosdoğru' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قوم',
        occurrences: 37,
        occurringForm: 'مُّسْتَقِيمًا',
      },
    },
    {
      id: 'najjaa',
      arabic: 'نَجَّى',
      english: 'to save, to deliver',
      turkish: 'kurtarmak',
      example: {
        arabic: 'ثُمَّ نُنَجِّى ٱلَّذِينَ ٱتَّقَوا۟ وَّنَذَرُ ٱلظَّٰلِمِينَ فِيهَا جِثِيًّۭا',
        english: 'Then We will save those who feared Allah and leave the wrongdoers therein on their knees.',
        turkish: 'Sonra sakınanları kurtarırız ve zalimleri orada diz üstü çökmüş halde bırakırız.',
        source: 'Qur\'an 19:72',
        highlight: { english: 'save', turkish: 'kurtarırız' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نجو',
        forms: [
          { label: 'mudari', arabic: 'يُنَجِّي' },
          { label: 'masdar', arabic: 'تَنْجِيَة' },
        ],
        occurrences: 37,
        occurringForm: 'نُنَجِّى',
      },
    },
    {
      id: 'naam',
      arabic: 'نَعَم',
      english: 'yes',
      turkish: 'evet',
      example: {
        arabic: 'قُلْ نَعَمْ وَأَنتُمْ دَٰخِرُونَ',
        english: 'Say: Yes, and you will be humbled.',
        turkish: 'De ki: Evet, hem de küçük düşmüş olarak.',
        source: 'Qur\'an 37:18',
        highlight: { english: 'Yes', turkish: 'Evet' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نعم',
        occurrences: 37,
        occurringForm: 'نَعَمْ',
      },
    },
  ],
}
