import type { DeckDef } from '../types'

// Quran Vocabulary, level 4. See GitHub issue #8.
//
// Scaffolded by scripts/generateVocab.ts: the headword, root, occurrence count,
// ayah and citation come from the corpus and the canonical text. The meanings,
// principal parts and ayah translations were authored on top of that scaffold.
//
// Where the corpus lemmatizes a word to a passive, an imperative or a mudari
// that nobody looks up, the note id is the dictionary form while the headword
// stays as the corpus has it, since that is what the ayah shows.
//
// DRAFT: verify every English meaning before memorizing it. Turkish is
// convenience text and stays draft - correct it on sight while studying.
//
// Locked until the previous level is mostly graduated; see quranVocabTrack.ts.

export const quranVocab4: DeckDef = {
  id: 'quran-vocab-4',
  name: { english: 'Quran Vocabulary 4', turkish: 'Kur’an Kelimeleri 4' },
  nameArabic: 'مُفْرَدَاتُ الْقُرْآنِ ٤',
  description: {
    english:
      'Frequency band 4 of the Quran vocabulary track, each word with an ayah where it occurs.',
    turkish:
      'Kur’an kelime yolunun 4. sıklık kuşağı; her kelime geçtiği bir ayetle.',
  },
  directions: ['ar-to-meaning'],
  newPerDay: 10,
  burySiblings: true,
  notes: [
    {
      id: 'bayyina',
      arabic: 'بَيِّنَة',
      english: 'clear proof, clear sign; clear, evident',
      turkish: 'apaçık delil, açık işaret; apaçık',
      example: {
        arabic: 'وَلَقَد تَّرَكْنَا مِنْهَآ ءَايَةًۢ بَيِّنَةًۭ لِّقَوْمٍۢ يَعْقِلُونَ',
        english: 'And We have certainly left of it a clear sign for a people who use reason.',
        turkish: 'Andolsun ki ondan, akleden bir topluluk için apaçık bir işaret bıraktık.',
        source: 'Qur\'an 29:35',
        highlight: { english: 'clear sign', turkish: 'apaçık' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بين',
        forms: [
          { label: 'plural', arabic: 'بَيِّنَات' },
        ],
        occurrences: 71,
        occurringForm: 'بَيِّنَةً',
      },
    },
    {
      id: 'amal',
      arabic: 'عَمَل',
      english: 'deed, work',
      turkish: 'amel, iş',
      example: {
        arabic: 'قُلْ هَلْ نُنَبِّئُكُم بِٱلْأَخْسَرِينَ أَعْمَٰلًا',
        english: 'Say: Shall We inform you of the greatest losers in deeds?',
        turkish: 'De ki: Amelleri bakımından en çok ziyana uğrayanları size haber verelim mi?',
        source: 'Qur\'an 18:103',
        highlight: { english: 'deeds', turkish: 'Amelleri' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عمل',
        forms: [
          { label: 'plural', arabic: 'أَعْمَال' },
        ],
        occurrences: 71,
        occurringForm: 'أَعْمَٰلًا',
      },
    },
    {
      id: 'akhar',
      arabic: 'آخَر',
      english: 'other, another',
      turkish: 'başka, diğer',
      example: {
        arabic: 'كَذَٰلِكَ ۖ وَأَوْرَثْنَٰهَا قَوْمًا ءَاخَرِينَ',
        english: 'Thus it was. And We made another people inherit it.',
        turkish: 'İşte böyle. Onu başka bir topluluğa miras bıraktık.',
        source: 'Qur\'an 44:28',
        highlight: { english: 'another', turkish: 'başka' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أخر',
        forms: [
          { label: 'plural', arabic: 'آخَرُونَ' },
        ],
        occurrences: 70,
        occurringForm: 'ءَاخَرِينَ',
      },
    },
    {
      id: 'quran',
      arabic: 'قُرْءان',
      english: 'Qur\'an; recitation',
      turkish: 'Kur\'an; okuma',
      example: {
        arabic: 'بَلْ هُوَ قُرْءَانٌۭ مَّجِيدٌۭ',
        english: 'Rather, it is a glorious Qur\'an,',
        turkish: 'Hayır, o şanlı bir Kur\'an\'dır,',
        source: 'Qur\'an 85:21',
        highlight: { english: 'Qur\'an', turkish: 'Kur\'an' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قرأ',
        occurrences: 70,
        occurringForm: 'قُرْءَانٌ',
      },
    },
    {
      id: 'qaliyl',
      arabic: 'قَلِيل',
      english: 'little, few',
      turkish: 'az',
      example: {
        arabic: 'وَأَعْطَىٰ قَلِيلًۭا وَأَكْدَىٰٓ',
        english: 'and gave a little, then withheld.',
        turkish: 'Azıcık verdi, sonra da vermez oldu.',
        source: 'Qur\'an 53:34',
        highlight: { english: 'a little', turkish: 'Azıcık' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قلل',
        forms: [
          { label: 'plural', arabic: 'قَلِيلُونَ' },
        ],
        occurrences: 70,
        occurringForm: 'قَلِيلًا',
      },
    },
    {
      id: 'qiyama',
      arabic: 'قِيامَة',
      english: 'resurrection',
      turkish: 'kıyamet, diriliş',
      example: {
        arabic: 'لَآ أُقْسِمُ بِيَوْمِ ٱلْقِيَٰمَةِ',
        english: 'I swear by the Day of Resurrection.',
        turkish: 'Kıyamet gününe yemin ederim.',
        source: 'Qur\'an 75:1',
        highlight: { english: 'Resurrection', turkish: 'Kıyamet' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قوم',
        occurrences: 70,
        occurringForm: 'ٱلْقِيَٰمَةِ',
      },
    },
    {
      id: 'waada',
      arabic: 'وَعَدَ',
      english: 'to promise',
      turkish: 'vaat etmek, söz vermek',
      example: {
        arabic: 'وَعَدَ ٱللَّهُ ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ ۙ لَهُم مَّغْفِرَةٌۭ وَأَجْرٌ عَظِيمٌۭ',
        english: 'Allah has promised those who believe and do righteous deeds: for them is forgiveness and a great reward.',
        turkish: 'Allah, iman edip salih ameller işleyenlere vaat etti: onlar için bir bağışlanma ve büyük bir ödül vardır.',
        source: 'Qur\'an 5:9',
        highlight: { english: 'promised', turkish: 'vaat etti' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'وعد',
        forms: [
          { label: 'mudari', arabic: 'يَعِدُ' },
          { label: 'masdar', arabic: 'وَعْد' },
        ],
        occurrences: 70,
        occurringForm: 'وَعَدَ',
      },
    },
    {
      id: 'ibrahiym',
      arabic: 'إِبْراهِيم',
      english: 'Abraham',
      turkish: 'İbrahim',
      example: {
        arabic: 'صُحُفِ إِبْرَٰهِيمَ وَمُوسَىٰ',
        english: 'the scriptures of Abraham and Moses.',
        turkish: 'İbrahim\'in ve Musa\'nın sahifeleri.',
        source: 'Qur\'an 87:19',
        highlight: { english: 'Abraham', turkish: 'İbrahim' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 69,
        occurringForm: 'إِبْرَٰهِيمَ',
      },
    },
    {
      id: 'anfaqa',
      arabic: 'أَنفَقَ',
      english: 'to spend',
      turkish: 'harcamak, infak etmek',
      example: {
        arabic: 'ٱلَّذِينَ يُقِيمُونَ ٱلصَّلَوٰةَ وَمِمَّا رَزَقْنَٰهُمْ يُنفِقُونَ',
        english: 'those who establish the prayer and spend out of what We have provided them.',
        turkish: 'Onlar namazı kılar ve kendilerine rızık olarak verdiğimizden infak ederler.',
        source: 'Qur\'an 8:3',
        highlight: { english: 'spend', turkish: 'infak ederler' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نفق',
        forms: [
          { label: 'mudari', arabic: 'يُنْفِقُ' },
          { label: 'masdar', arabic: 'إِنْفَاق' },
        ],
        occurrences: 68,
        occurringForm: 'يُنفِقُونَ',
      },
    },
    {
      id: 'bayt',
      arabic: 'بَيْت',
      english: 'house, home',
      turkish: 'ev',
      example: {
        arabic: 'وَتَنْحِتُونَ مِنَ ٱلْجِبَالِ بُيُوتًۭا فَٰرِهِينَ',
        english: 'And you carve houses out of the mountains, skillfully.',
        turkish: 'Dağlardan ustalıkla evler yontuyorsunuz.',
        source: 'Qur\'an 26:149',
        highlight: { english: 'houses', turkish: 'evler' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بيت',
        forms: [
          { label: 'plural', arabic: 'بُيُوت' },
        ],
        occurrences: 65,
        occurringForm: 'بُيُوتًا',
      },
    },
    {
      id: 'ghafara',
      arabic: 'غَفَرَ',
      english: 'to forgive',
      turkish: 'bağışlamak, affetmek',
      example: {
        arabic: 'وَقُل رَّبِّ ٱغْفِرْ وَٱرْحَمْ وَأَنتَ خَيْرُ ٱلرَّٰحِمِينَ',
        english: 'And say: My Lord, forgive and have mercy, and You are the best of the merciful.',
        turkish: 'De ki: Rabbim, bağışla ve merhamet et; sen merhamet edenlerin en hayırlısısın.',
        source: 'Qur\'an 23:118',
        highlight: { english: 'forgive', turkish: 'bağışla' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'غفر',
        forms: [
          { label: 'mudari', arabic: 'يَغْفِرُ' },
          { label: 'masdar', arabic: 'مَغْفِرَة' },
        ],
        occurrences: 65,
        occurringForm: 'ٱغْفِرْ',
      },
    },
    {
      id: 'lakin',
      arabic: 'لٰكِن',
      english: 'but, however',
      turkish: 'fakat, ama',
      example: {
        arabic: 'أَسْمِعْ بِهِمْ وَأَبْصِرْ يَوْمَ يَأْتُونَنَا ۖ لَٰكِنِ ٱلظَّٰلِمُونَ ٱلْيَوْمَ فِى ضَلَٰلٍۢ مُّبِينٍۢ',
        english: 'How well they will hear and see the Day they come to Us! But the wrongdoers today are in clear error.',
        turkish: 'Bize gelecekleri gün ne iyi işitir, ne iyi görürler! Ama zalimler bugün apaçık bir sapıklık içindedir.',
        source: 'Qur\'an 19:38',
        highlight: { english: 'But', turkish: 'Ama' },
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 65,
        occurringForm: 'لَٰكِنِ',
      },
    },
    {
      id: 'lakinn',
      arabic: 'لٰكِنّ',
      english: 'but, however (with an accusative noun)',
      turkish: 'fakat, ama (ismi nasb eder)',
      example: {
        arabic: 'لَقَدْ جِئْنَٰكُم بِٱلْحَقِّ وَلَٰكِنَّ أَكْثَرَكُمْ لِلْحَقِّ كَٰرِهُونَ',
        english: 'We had certainly brought you the truth, but most of you were averse to the truth.',
        turkish: 'Andolsun size hakkı getirdik; fakat çoğunuz haktan hoşlanmıyordunuz.',
        source: 'Qur\'an 43:78',
        highlight: { english: 'but', turkish: 'fakat' },
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 65,
        occurringForm: 'وَلَٰكِنَّ',
      },
    },
    {
      id: 'yamiyn',
      arabic: 'يَمِين',
      english: 'right hand, right side; oath',
      turkish: 'sağ el, sağ taraf; yemin',
      example: {
        arabic: 'أَمْ لَكُمْ أَيْمَٰنٌ عَلَيْنَا بَٰلِغَةٌ إِلَىٰ يَوْمِ ٱلْقِيَٰمَةِ ۙ إِنَّ لَكُمْ لَمَا تَحْكُمُونَ',
        english: 'Or do you have oaths binding on Us, reaching to the Day of Resurrection, that you shall have whatever you decide?',
        turkish: 'Yoksa kıyamet gününe kadar sürecek, bizden alınmış yeminleriniz mi var ki, hükmettiğiniz her şey sizin olsun?',
        source: 'Qur\'an 68:39',
        highlight: { english: 'oaths', turkish: 'yeminleriniz' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'يمن',
        forms: [
          { label: 'plural', arabic: 'أَيْمَان' },
        ],
        occurrences: 65,
        occurringForm: 'أَيْمَٰنٌ',
      },
    },
    {
      id: 'aba',
      arabic: 'آباء',
      english: 'fathers, forefathers',
      turkish: 'babalar, atalar',
      example: {
        arabic: 'إِنَّهُمْ أَلْفَوْا۟ ءَابَآءَهُمْ ضَآلِّينَ',
        english: 'Indeed, they found their fathers astray,',
        turkish: 'Çünkü onlar atalarını sapkın buldular,',
        source: 'Qur\'an 37:69',
        highlight: { english: 'fathers', turkish: 'atalarını' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أبو',
        occurrences: 64,
        occurringForm: 'ءَابَآءَهُمْ',
      },
    },
    {
      id: 'ahabba',
      arabic: 'أَحْبَبْ',
      english: 'to love, to like',
      turkish: 'sevmek',
      example: {
        arabic: 'ٱدْعُوا۟ رَبَّكُمْ تَضَرُّعًۭا وَخُفْيَةً ۚ إِنَّهُۥ لَا يُحِبُّ ٱلْمُعْتَدِينَ',
        english: 'Call upon your Lord humbly and in secret. Indeed, He does not love the transgressors.',
        turkish: 'Rabbinize yalvararak ve gizlice dua edin. Şüphesiz O, haddi aşanları sevmez.',
        source: 'Qur\'an 7:55',
        highlight: { english: 'love', turkish: 'sevmez' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حبب',
        forms: [
          { label: 'mudari', arabic: 'يُحِبُّ' },
        ],
        occurrences: 64,
        occurringForm: 'يُحِبُّ',
      },
    },
    {
      id: 'asaba',
      arabic: 'أَصابَ',
      english: 'to strike, to befall; to reach, to hit upon',
      turkish: 'isabet etmek, başına gelmek; ulaşmak',
      example: {
        arabic: 'فَسَخَّرْنَا لَهُ ٱلرِّيحَ تَجْرِى بِأَمْرِهِۦ رُخَآءً حَيْثُ أَصَابَ',
        english: 'So We subjected the wind to him, running gently by his command wherever he directed it.',
        turkish: 'Bunun üzerine rüzgârı ona boyun eğdirdik; onun emriyle, yöneldiği yere yumuşacık eserdi.',
        source: 'Qur\'an 38:36',
        highlight: { english: 'directed', turkish: 'yöneldiği' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'صوب',
        forms: [
          { label: 'mudari', arabic: 'يُصِيبُ' },
          { label: 'masdar', arabic: 'إِصَابَة' },
        ],
        occurrences: 64,
        occurringForm: 'أَصَابَ',
      },
    },
    {
      id: 'adalla',
      arabic: 'أَضَلَّ',
      english: 'to lead astray, to mislead',
      turkish: 'saptırmak',
      example: {
        arabic: 'وَلَقَدْ أَضَلَّ مِنكُمْ جِبِلًّۭا كَثِيرًا ۖ أَفَلَمْ تَكُونُوا۟ تَعْقِلُونَ',
        english: 'And he had already led astray a great many of your generations. Did you not then use reason?',
        turkish: 'Andolsun ki o, içinizden birçok nesli saptırdı. Hiç akletmiyor muydunuz?',
        source: 'Qur\'an 36:62',
        highlight: { english: 'led astray', turkish: 'saptırdı' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ضلل',
        forms: [
          { label: 'mudari', arabic: 'يُضِلُّ' },
          { label: 'masdar', arabic: 'إِضْلَال' },
        ],
        occurrences: 64,
        occurringForm: 'أَضَلَّ',
      },
    },
    {
      id: 'umma',
      arabic: 'أُمَّة',
      english: 'community, nation',
      turkish: 'ümmet, topluluk',
      example: {
        arabic: 'وَمِمَّنْ خَلَقْنَآ أُمَّةٌۭ يَهْدُونَ بِٱلْحَقِّ وَبِهِۦ يَعْدِلُونَ',
        english: 'And among those We created is a community that guides by the truth and by it does justice.',
        turkish: 'Yarattıklarımızdan, hakka yönelten ve onunla adaleti uygulayan bir topluluk vardır.',
        source: 'Qur\'an 7:181',
        highlight: { english: 'community', turkish: 'topluluk' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أمم',
        forms: [
          { label: 'plural', arabic: 'أُمَم' },
        ],
        occurrences: 64,
        occurringForm: 'أُمَّةٌ',
      },
    },
    {
      id: 'abn',
      arabic: 'ابْن',
      english: 'son',
      turkish: 'oğul',
      example: {
        arabic: 'ذَٰلِكَ عِيسَى ٱبْنُ مَرْيَمَ ۚ قَوْلَ ٱلْحَقِّ ٱلَّذِى فِيهِ يَمْتَرُونَ',
        english: 'That is Jesus, son of Mary — the word of truth about which they are in doubt.',
        turkish: 'İşte, hakkında şüpheye düştükleri Meryem oğlu İsa; bu hak sözdür.',
        source: 'Qur\'an 19:34',
        highlight: { english: 'son of', turkish: 'oğlu' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بني',
        forms: [
          { label: 'plural', arabic: 'أَبْنَاء' },
        ],
        occurrences: 63,
        occurringForm: 'ٱبْنُ',
      },
    },
    {
      id: 'taba',
      arabic: 'تابَ',
      english: 'to repent, to turn back in repentance',
      turkish: 'tövbe etmek',
      example: {
        arabic: 'وَإِنِّى لَغَفَّارٌۭ لِّمَن تَابَ وَءَامَنَ وَعَمِلَ صَٰلِحًۭا ثُمَّ ٱهْتَدَىٰ',
        english: 'And indeed, I am most forgiving toward whoever repents and believes and does righteousness and then stays guided.',
        turkish: 'Şüphesiz ben, tövbe eden, iman eden, salih amel işleyen, sonra da doğru yolda giden kimseyi çokça bağışlayıcıyım.',
        source: 'Qur\'an 20:82',
        highlight: { english: 'repents', turkish: 'tövbe eden' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'توب',
        forms: [
          { label: 'mudari', arabic: 'يَتُوبُ' },
          { label: 'masdar', arabic: 'تَوْبَة' },
        ],
        occurrences: 63,
        occurringForm: 'تَابَ',
      },
    },
    {
      id: 'kathiyr',
      arabic: 'كَثِير',
      english: 'many, much',
      turkish: 'çok',
      example: {
        arabic: 'وَنَذْكُرَكَ كَثِيرًا',
        english: 'and remember You much.',
        turkish: 've seni çokça analım.',
        source: 'Qur\'an 20:34',
        highlight: { english: 'much', turkish: 'çokça' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كثر',
        forms: [
          { label: 'plural', arabic: 'كَثِيرُونَ' },
        ],
        occurrences: 63,
        occurringForm: 'كَثِيرًا',
      },
    },
    {
      id: 'ma-2-2',
      arabic: 'ماء',
      english: 'water',
      turkish: 'su',
      example: {
        arabic: 'خُلِقَ مِن مَّآءٍۢ دَافِقٍۢ',
        english: 'He was created from a gushing water,',
        turkish: 'Atılan bir sudan yaratıldı,',
        source: 'Qur\'an 86:6',
        highlight: { english: 'water', turkish: 'su' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'موه',
        forms: [
          { label: 'plural', arabic: 'مِيَاه' },
        ],
        occurrences: 63,
        occurringForm: 'مَّآءٍ',
      },
    },
    {
      id: 'saliha',
      arabic: 'صالِحَة',
      english: 'righteous deed, good deed',
      turkish: 'salih amel, iyi iş',
      example: {
        arabic: 'وَٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ لَنُدْخِلَنَّهُمْ فِى ٱلصَّٰلِحِينَ',
        english: 'And those who believe and do righteous deeds — We will surely admit them among the righteous.',
        turkish: 'İman edip salih ameller işleyenleri elbette salihler arasına katacağız.',
        source: 'Qur\'an 29:9',
        highlight: { english: 'righteous deeds', turkish: 'salih ameller' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صلح',
        forms: [
          { label: 'plural', arabic: 'صَالِحَات' },
        ],
        occurrences: 62,
        occurringForm: 'ٱلصَّٰلِحَٰتِ',
      },
    },
    {
      id: 'kasaba',
      arabic: 'كَسَبَ',
      english: 'to earn, to acquire',
      turkish: 'kazanmak',
      example: {
        arabic: 'كُلُّ نَفْسٍۭ بِمَا كَسَبَتْ رَهِينَةٌ',
        english: 'Every soul is held in pledge for what it has earned,',
        turkish: 'Her nefis, kazandığına karşılık bir rehinedir,',
        source: 'Qur\'an 74:38',
        highlight: { english: 'earned', turkish: 'kazandığına' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'كسب',
        forms: [
          { label: 'mudari', arabic: 'يَكْسِبُ' },
          { label: 'masdar', arabic: 'كَسْب' },
        ],
        occurrences: 62,
        occurringForm: 'كَسَبَتْ',
      },
    },
    {
      id: 'nazzala',
      arabic: 'نَزَّلَ',
      english: 'to send down, to reveal gradually',
      turkish: 'indirmek, peyderpey indirmek',
      example: {
        arabic: 'وَقَالُوا۟ يَٰٓأَيُّهَا ٱلَّذِى نُزِّلَ عَلَيْهِ ٱلذِّكْرُ إِنَّكَ لَمَجْنُونٌۭ',
        english: 'And they said: O you upon whom the Reminder has been sent down, you are surely mad.',
        turkish: 'Dediler ki: Ey kendisine Zikir indirilen kişi! Sen gerçekten delisin.',
        source: 'Qur\'an 15:6',
        highlight: { english: 'sent down', turkish: 'indirilen' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نزل',
        forms: [
          { label: 'mudari', arabic: 'يُنَزِّلُ' },
          { label: 'masdar', arabic: 'تَنْزِيل' },
        ],
        occurrences: 62,
        occurringForm: 'نُزِّلَ',
      },
    },
    {
      id: 'talaa',
      arabic: 'تَلَى',
      english: 'to recite; to follow',
      turkish: 'okumak; ardından gitmek',
      example: {
        arabic: 'رَسُولٌۭ مِّنَ ٱللَّهِ يَتْلُوا۟ صُحُفًۭا مُّطَهَّرَةًۭ',
        english: 'a messenger from Allah reciting purified scriptures,',
        turkish: 'Allah\'tan gelen, tertemiz sahifeler okuyan bir elçi,',
        source: 'Qur\'an 98:2',
        highlight: { english: 'reciting', turkish: 'okuyan' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'تلو',
        forms: [
          { label: 'mudari', arabic: 'يَتْلُو' },
          { label: 'masdar', arabic: 'تِلَاوَة' },
        ],
        occurrences: 61,
        occurringForm: 'يَتْلُوا۟',
      },
    },
    {
      id: 'razaqa',
      arabic: 'رَزَقَ',
      english: 'to provide, to give provision',
      turkish: 'rızık vermek',
      example: {
        arabic: 'ٱللَّهُ لَطِيفٌۢ بِعِبَادِهِۦ يَرْزُقُ مَن يَشَآءُ ۖ وَهُوَ ٱلْقَوِىُّ ٱلْعَزِيزُ',
        english: 'Allah is subtle with His servants; He provides for whom He wills, and He is the Strong, the Mighty.',
        turkish: 'Allah kullarına lütufkârdır; dilediğine rızık verir. O güçlüdür, üstündür.',
        source: 'Qur\'an 42:19',
        highlight: { english: 'provides', turkish: 'rızık verir' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'رزق',
        forms: [
          { label: 'mudari', arabic: 'يَرْزُقُ' },
          { label: 'masdar', arabic: 'رِزْق' },
        ],
        occurrences: 61,
        occurringForm: 'يَرْزُقُ',
      },
    },
    {
      id: 'sadiq',
      arabic: 'صادِق',
      english: 'truthful, sincere',
      turkish: 'doğru sözlü, sadık',
      example: {
        arabic: 'تَرْجِعُونَهَآ إِن كُنتُمْ صَٰدِقِينَ',
        english: 'bring it back, if you are truthful.',
        turkish: 'onu geri çevirsenize, eğer doğru söyleyenlerseniz.',
        source: 'Qur\'an 56:87',
        highlight: { english: 'truthful', turkish: 'doğru söyleyenlerseniz' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صدق',
        forms: [
          { label: 'plural', arabic: 'صَادِقُونَ' },
        ],
        occurrences: 59,
        occurringForm: 'صَٰدِقِينَ',
      },
    },
    {
      id: 'qadaa',
      arabic: 'قَضَى',
      english: 'to decree, to decide; to carry out, to fulfil',
      turkish: 'hükmetmek, takdir etmek; yerine getirmek',
      example: {
        arabic: 'كَلَّا لَمَّا يَقْضِ مَآ أَمَرَهُۥ',
        english: 'No! He has not yet carried out what He commanded him.',
        turkish: 'Hayır! O, kendisine emredileni henüz yerine getirmedi.',
        source: 'Qur\'an 80:23',
        highlight: { english: 'carried out', turkish: 'yerine getirmedi' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'قضي',
        forms: [
          { label: 'mudari', arabic: 'يَقْضِي' },
          { label: 'masdar', arabic: 'قَضَاء' },
        ],
        occurrences: 59,
        occurringForm: 'يَقْضِ',
      },
    },
    {
      id: 'nisa',
      arabic: 'نِساء',
      english: 'women',
      turkish: 'kadınlar',
      example: {
        arabic: 'وَإِذْ قَالَتِ ٱلْمَلَٰٓئِكَةُ يَٰمَرْيَمُ إِنَّ ٱللَّهَ ٱصْطَفَىٰكِ وَطَهَّرَكِ وَٱصْطَفَىٰكِ عَلَىٰ نِسَآءِ ٱلْعَٰلَمِينَ',
        english: 'And when the angels said: O Mary, indeed Allah has chosen you and purified you and chosen you above the women of the worlds.',
        turkish: 'Hani melekler demişti ki: Ey Meryem! Allah seni seçti, seni tertemiz kıldı ve seni âlemlerin kadınlarına üstün kıldı.',
        source: 'Qur\'an 3:42',
        highlight: { english: 'women', turkish: 'kadınlarına' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نسو',
        occurrences: 59,
        occurringForm: 'نِسَآءِ',
      },
    },
    {
      id: 'nasara',
      arabic: 'نَصَرَ',
      english: 'to help, to give victory',
      turkish: 'yardım etmek, zafer vermek',
      example: {
        arabic: 'بِنَصْرِ ٱللَّهِ ۚ يَنصُرُ مَن يَشَآءُ ۖ وَهُوَ ٱلْعَزِيزُ ٱلرَّحِيمُ',
        english: 'with the help of Allah. He helps whom He wills, and He is the Mighty, the Merciful.',
        turkish: 'Allah\'ın yardımıyla. O dilediğine yardım eder; O üstündür, merhametlidir.',
        source: 'Qur\'an 30:5',
        highlight: { english: 'helps', turkish: 'yardım eder' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نصر',
        forms: [
          { label: 'mudari', arabic: 'يَنْصُرُ' },
          { label: 'masdar', arabic: 'نَصْر' },
        ],
        occurrences: 59,
        occurringForm: 'يَنصُرُ',
      },
    },
    {
      id: 'sayyia',
      arabic: 'سَيِّئَة',
      english: 'evil deed, misdeed, evil',
      turkish: 'kötülük, günah',
      example: {
        arabic: 'فَأَصَابَهُمْ سَيِّـَٔاتُ مَا عَمِلُوا۟ وَحَاقَ بِهِم مَّا كَانُوا۟ بِهِۦ يَسْتَهْزِءُونَ',
        english: 'So the evils of what they did struck them, and what they used to mock closed in on them.',
        turkish: 'Böylece yaptıklarının kötülükleri başlarına geldi ve alay ettikleri şey onları kuşattı.',
        source: 'Qur\'an 16:34',
        highlight: { english: 'evils', turkish: 'kötülükleri' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سوأ',
        forms: [
          { label: 'plural', arabic: 'سَيِّئَات' },
        ],
        occurrences: 58,
        occurringForm: 'سَيِّـَٔاتُ',
      },
    },
    {
      id: 'sabara',
      arabic: 'صَبَرَ',
      english: 'to be patient, to endure',
      turkish: 'sabretmek, dayanmak',
      example: {
        arabic: 'وَكَيْفَ تَصْبِرُ عَلَىٰ مَا لَمْ تُحِطْ بِهِۦ خُبْرًۭا',
        english: 'And how can you be patient about what you do not encompass in knowledge?',
        turkish: 'Bilgice kavrayamadığın bir şeye nasıl sabredeceksin?',
        source: 'Qur\'an 18:68',
        highlight: { english: 'be patient', turkish: 'sabredeceksin' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'صبر',
        forms: [
          { label: 'mudari', arabic: 'يَصْبِرُ' },
          { label: 'masdar', arabic: 'صَبْر' },
        ],
        occurrences: 58,
        occurringForm: 'تَصْبِرُ',
      },
    },
    {
      id: 'nadhiyr',
      arabic: 'نَذِير',
      english: 'warner',
      turkish: 'uyarıcı',
      example: {
        arabic: 'نَذِيرًۭا لِّلْبَشَرِ',
        english: 'a warner to mankind,',
        turkish: 'insanlar için bir uyarıcı olarak,',
        source: 'Qur\'an 74:36',
        highlight: { english: 'warner', turkish: 'uyarıcı' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نذر',
        forms: [
          { label: 'plural', arabic: 'نُذُر' },
        ],
        occurrences: 58,
        occurringForm: 'نَذِيرًا',
      },
    },
    {
      id: 'jaray',
      arabic: 'جَرَيْ',
      english: 'to flow, to run',
      turkish: 'akmak, cereyan etmek',
      example: {
        arabic: 'تَجْرِى بِأَعْيُنِنَا جَزَآءًۭ لِّمَن كَانَ كُفِرَ',
        english: 'running before Our eyes, as a reward for the one who had been rejected.',
        turkish: 'Gözlerimizin önünde akıp gidiyordu; inkâr edilmiş olan kimseye bir mükâfat olarak.',
        source: 'Qur\'an 54:14',
        highlight: { english: 'running', turkish: 'akıp gidiyordu' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'جري',
        forms: [
          { label: 'mudari', arabic: 'يَجْرِي' },
        ],
        occurrences: 57,
        occurringForm: 'تَجْرِى',
      },
    },
    {
      id: 'rahman',
      arabic: 'رَحْمٰن',
      english: 'the Most Merciful, the All-Compassionate',
      turkish: 'Rahman, çok merhametli',
      example: {
        arabic: 'ٱلرَّحْمَٰنُ',
        english: 'The Most Merciful.',
        turkish: 'Rahman.',
        source: 'Qur\'an 55:1',
        highlight: { english: 'The Most Merciful', turkish: 'Rahman' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'رحم',
        occurrences: 57,
        occurringForm: 'ٱلرَّحْمَٰنُ',
      },
    },
    {
      id: 'ayn',
      arabic: 'عَيْن',
      english: 'eye; spring, fountain',
      turkish: 'göz; pınar, kaynak',
      example: {
        arabic: 'فِيهَا عَيْنٌۭ جَارِيَةٌۭ',
        english: 'In it is a flowing spring.',
        turkish: 'Orada akan bir pınar vardır.',
        source: 'Qur\'an 88:12',
        highlight: { english: 'spring', turkish: 'pınar' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عين',
        forms: [
          { label: 'plural', arabic: 'عُيُون' },
        ],
        occurrences: 57,
        occurringForm: 'عَيْنٌ',
      },
    },
    {
      id: 'qarya',
      arabic: 'قَرْيَة',
      english: 'town, village',
      turkish: 'şehir, kasaba, belde',
      example: {
        arabic: 'وَحَرَٰمٌ عَلَىٰ قَرْيَةٍ أَهْلَكْنَٰهَآ أَنَّهُمْ لَا يَرْجِعُونَ',
        english: 'And it is forbidden for a town that We destroyed that they should return.',
        turkish: 'Helak ettiğimiz bir beldeye haramdır ki onlar geri dönsünler.',
        source: 'Qur\'an 21:95',
        highlight: { english: 'town', turkish: 'beldeye' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قري',
        forms: [
          { label: 'plural', arabic: 'قُرَى' },
        ],
        occurrences: 57,
        occurringForm: 'قَرْيَةٍ',
      },
    },
    {
      id: 'nahar',
      arabic: 'نَهار',
      english: 'daytime, day',
      turkish: 'gündüz',
      example: {
        arabic: 'قُلْ أَرَءَيْتُمْ إِنْ أَتَىٰكُمْ عَذَابُهُۥ بَيَٰتًا أَوْ نَهَارًۭا مَّاذَا يَسْتَعْجِلُ مِنْهُ ٱلْمُجْرِمُونَ',
        english: 'Say: Have you considered — if His punishment came to you by night or by day, what part of it would the criminals seek to hasten?',
        turkish: 'De ki: Söyleyin bakalım, O\'nun azabı size geceleyin veya gündüzün gelse, suçlular ondan neyi acele isterler?',
        source: 'Qur\'an 10:50',
        highlight: { english: 'by day', turkish: 'gündüzün' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نهر',
        occurrences: 57,
        occurringForm: 'نَهَارًا',
      },
    },
    {
      id: 'shadiyd',
      arabic: 'شَدِيد',
      english: 'severe, intense, strong',
      turkish: 'şiddetli, güçlü',
      example: {
        arabic: 'عَلَّمَهُۥ شَدِيدُ ٱلْقُوَىٰ',
        english: 'One of mighty powers taught him,',
        turkish: 'Ona, üstün güçlere sahip olan öğretti,',
        source: 'Qur\'an 53:5',
        highlight: { english: 'mighty', turkish: 'üstün' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شدد',
        forms: [
          { label: 'plural', arabic: 'شِدَاد' },
        ],
        occurrences: 56,
        occurringForm: 'شَدِيدُ',
      },
    },
    {
      id: 'shahiyd',
      arabic: 'شَهِيد',
      english: 'witness; martyr',
      turkish: 'şahit; şehit',
      example: {
        arabic: 'ٱلَّذِى لَهُۥ مُلْكُ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ ۚ وَٱللَّهُ عَلَىٰ كُلِّ شَىْءٍۢ شَهِيدٌ',
        english: 'the One to whom belongs the dominion of the heavens and the earth. And Allah is Witness over everything.',
        turkish: 'Göklerin ve yerin mülkü kendisine ait olan. Allah her şeye şahittir.',
        source: 'Qur\'an 85:9',
        highlight: { english: 'Witness', turkish: 'şahittir' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شهد',
        forms: [
          { label: 'plural', arabic: 'شُهَدَاء' },
        ],
        occurrences: 56,
        occurringForm: 'شَهِيدٌ',
      },
    },
    {
      id: 'massa',
      arabic: 'مَسَّ',
      english: 'to touch; to afflict',
      turkish: 'dokunmak; isabet etmek',
      example: {
        arabic: 'لَّا يَمَسُّهُۥٓ إِلَّا ٱلْمُطَهَّرُونَ',
        english: 'None touch it except the purified.',
        turkish: 'Ona ancak tertemiz olanlar dokunur.',
        source: 'Qur\'an 56:79',
        highlight: { english: 'touch', turkish: 'dokunur' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'مسس',
        forms: [
          { label: 'mudari', arabic: 'يَمَسُّ' },
          { label: 'masdar', arabic: 'مَسّ' },
        ],
        occurrences: 56,
        occurringForm: 'يَمَسُّهُۥٓ',
      },
    },
    {
      id: 'walad',
      arabic: 'وَلَد',
      english: 'child, son, offspring',
      turkish: 'çocuk, evlat',
      example: {
        arabic: 'وَقَالُوا۟ ٱتَّخَذَ ٱلرَّحْمَٰنُ وَلَدًۭا',
        english: 'And they said: The Most Merciful has taken a son.',
        turkish: 'Dediler ki: Rahman bir çocuk edindi.',
        source: 'Qur\'an 19:88',
        highlight: { english: 'son', turkish: 'çocuk' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ولد',
        forms: [
          { label: 'plural', arabic: 'أَوْلَاد' },
        ],
        occurrences: 56,
        occurringForm: 'وَلَدًا',
      },
    },
    {
      id: 'amma',
      arabic: 'أَمّا',
      english: 'as for',
      turkish: '-e gelince',
      example: {
        arabic: 'أَمَّا مَنِ ٱسْتَغْنَىٰ',
        english: 'As for him who thinks himself free of need,',
        turkish: 'Kendini müstağni gören kimseye gelince,',
        source: 'Qur\'an 80:5',
        highlight: { english: 'As for', turkish: 'gelince' },
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 55,
        occurringForm: 'أَمَّا',
      },
    },
    {
      id: 'rizq',
      arabic: 'رِزْق',
      english: 'provision, sustenance',
      turkish: 'rızık, azık',
      example: {
        arabic: 'أُو۟لَٰٓئِكَ لَهُمْ رِزْقٌۭ مَّعْلُومٌۭ',
        english: 'Those will have a known provision,',
        turkish: 'İşte onlar için belli bir rızık vardır,',
        source: 'Qur\'an 37:41',
        highlight: { english: 'provision', turkish: 'rızık' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'رزق',
        forms: [
          { label: 'plural', arabic: 'أَرْزَاق' },
        ],
        occurrences: 55,
        occurringForm: 'رِزْقٌ',
      },
    },
    {
      id: 'daraba',
      arabic: 'ضَرَبَ',
      english: 'to strike, to beat; to set forth (an example)',
      turkish: 'vurmak; misal vermek',
      example: {
        arabic: '۞ وَلَمَّا ضُرِبَ ٱبْنُ مَرْيَمَ مَثَلًا إِذَا قَوْمُكَ مِنْهُ يَصِدُّونَ',
        english: 'And when the son of Mary was set forth as an example, at once your people clamoured at it,',
        turkish: 'Meryem oğlu bir örnek olarak anlatılınca, kavmin hemen ondan dolayı bağrışmaya başladı,',
        source: 'Qur\'an 43:57',
        highlight: { english: 'set forth as an example', turkish: 'anlatılınca' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ضرب',
        forms: [
          { label: 'mudari', arabic: 'يَضْرِبُ' },
          { label: 'masdar', arabic: 'ضَرْب' },
        ],
        occurrences: 55,
        occurringForm: 'ضُرِبَ',
      },
    },
    {
      id: 'aqama',
      arabic: 'أَقامَ',
      english: 'to establish, to set up, to keep up',
      turkish: 'ikame etmek, ayakta tutmak, yöneltmek',
      example: {
        arabic: 'وَأَنْ أَقِمْ وَجْهَكَ لِلدِّينِ حَنِيفًۭا وَلَا تَكُونَنَّ مِنَ ٱلْمُشْرِكِينَ',
        english: 'And: Set your face toward the religion, inclining to truth, and never be of those who associate others with Allah.',
        turkish: 'Ve: Yüzünü hanif olarak dine çevir; sakın müşriklerden olma.',
        source: 'Qur\'an 10:105',
        highlight: { english: 'Set', turkish: 'çevir' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'قوم',
        forms: [
          { label: 'mudari', arabic: 'يُقِيمُ' },
          { label: 'masdar', arabic: 'إِقَامَة' },
        ],
        occurrences: 54,
        occurringForm: 'أَقِمْ',
      },
    },
    {
      id: 'qatala-2',
      arabic: 'قاتَلَ',
      english: 'to fight, to do battle',
      turkish: 'savaşmak, çarpışmak',
      example: {
        arabic: 'أُذِنَ لِلَّذِينَ يُقَٰتَلُونَ بِأَنَّهُمْ ظُلِمُوا۟ ۚ وَإِنَّ ٱللَّهَ عَلَىٰ نَصْرِهِمْ لَقَدِيرٌ',
        english: 'Permission is given to those who are fought against, because they have been wronged. And indeed, Allah is able to give them victory.',
        turkish: 'Kendilerine savaş açılanlara, zulme uğradıkları için izin verildi. Şüphesiz Allah onlara yardım etmeye kadirdir.',
        source: 'Qur\'an 22:39',
        highlight: { english: 'fought against', turkish: 'savaş açılanlara' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'قتل',
        forms: [
          { label: 'mudari', arabic: 'يُقَاتِلُ' },
          { label: 'masdar', arabic: 'قِتَال' },
        ],
        occurrences: 54,
        occurringForm: 'يُقَٰتَلُونَ',
      },
    },
    {
      id: 'nahar-2',
      arabic: 'نَهَر',
      english: 'river',
      turkish: 'nehir, ırmak',
      example: {
        arabic: 'وَيُمْدِدْكُم بِأَمْوَٰلٍۢ وَبَنِينَ وَيَجْعَل لَّكُمْ جَنَّٰتٍۢ وَيَجْعَل لَّكُمْ أَنْهَٰرًۭا',
        english: 'and increase you in wealth and children, and make for you gardens, and make for you rivers.',
        turkish: 'Sizi mallarla ve oğullarla desteklesin, size bahçeler versin ve size ırmaklar versin.',
        source: 'Qur\'an 71:12',
        highlight: { english: 'rivers', turkish: 'ırmaklar' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نهر',
        forms: [
          { label: 'plural', arabic: 'أَنْهَار' },
        ],
        occurrences: 54,
        occurringForm: 'أَنْهَٰرًا',
      },
    },
  ],
}
