import type { DeckDef } from '../types'

// Quran Vocabulary, level 8. See GitHub issue #8.
//
// Scaffolded by scripts/generateVocab.ts: the headword, root, occurrence count,
// ayah and citation come from the corpus and the canonical text. The meanings,
// principal parts and ayah translations were authored on top of that scaffold.
//
// Where the corpus lemmatizes a word to a passive, an imperative or a mudari
// that nobody looks up, the note id is the dictionary form while the headword
// stays as the corpus has it, since that is what the ayah shows.
//
// DRAFT: verify every English meaning before memorizing it. Turkish is
// convenience text and stays draft - correct it on sight while studying.
//
// Locked until the previous level is mostly graduated; see quranVocabTrack.ts.

export const quranVocab8: DeckDef = {
  id: 'quran-vocab-8',
  name: { english: 'Quran Vocabulary 8', turkish: 'Kur’an Kelimeleri 8' },
  nameArabic: 'مُفْرَدَاتُ الْقُرْآنِ ٨',
  description: {
    english:
      'Frequency band 8 of the Quran vocabulary track, each word with an ayah where it occurs.',
    turkish:
      'Kur’an kelime yolunun 8. sıklık kuşağı; her kelime geçtiği bir ayetle.',
  },
  directions: ['ar-to-meaning'],
  newPerDay: 10,
  burySiblings: true,
  notes: [
    {
      id: 'mala',
      arabic: 'مَلَأ',
      english: 'chiefs, notables, assembly of leaders',
      turkish: 'ileri gelenler, eşraf',
      example: {
        arabic: 'قَالَتْ يَٰٓأَيُّهَا ٱلْمَلَؤُا۟ إِنِّىٓ أُلْقِىَ إِلَىَّ كِتَٰبٌۭ كَرِيمٌ',
        english: 'She said: O chiefs, indeed a noble letter has been delivered to me.',
        turkish: 'Dedi ki: Ey ileri gelenler! Bana değerli bir mektup bırakıldı.',
        source: 'Qur\'an 27:29',
        highlight: { english: 'chiefs', turkish: 'ileri gelenler' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ملأ',
        occurrences: 30,
        occurringForm: 'ٱلْمَلَؤُا۟',
      },
    },
    {
      id: 'wahid',
      arabic: 'واحِد',
      english: 'one, single',
      turkish: 'bir, tek',
      example: {
        arabic: 'لَّا تَدْعُوا۟ ٱلْيَوْمَ ثُبُورًۭا وَٰحِدًۭا وَٱدْعُوا۟ ثُبُورًۭا كَثِيرًۭا',
        english: 'Do not call this Day for one destruction, but call for many destructions.',
        turkish: 'Bugün bir tek yok oluşu çağırmayın, birçok yok oluşu çağırın.',
        source: 'Qur\'an 25:14',
        highlight: { english: 'one', turkish: 'bir tek' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'وحد',
        occurrences: 30,
        occurringForm: 'وَٰحِدًا',
      },
    },
    {
      id: 'wallaa',
      arabic: 'وَلَّى',
      english: 'to turn away, to turn something; to make an ally, to put in charge',
      turkish: 'yüz çevirmek, çevirmek; dost kılmak, başa geçirmek',
      example: {
        arabic: 'وَكَذَٰلِكَ نُوَلِّى بَعْضَ ٱلظَّٰلِمِينَ بَعْضًۢا بِمَا كَانُوا۟ يَكْسِبُونَ',
        english: 'And thus We make some of the wrongdoers allies of others for what they used to earn.',
        turkish: 'İşte böylece, kazanmakta olduklarından dolayı zalimlerin bir kısmını diğerlerine dost kılarız.',
        source: 'Qur\'an 6:129',
        highlight: { english: 'allies', turkish: 'dost kılarız' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ولي',
        forms: [
          { label: 'mudari', arabic: 'يُوَلِّي' },
          { label: 'masdar', arabic: 'تَوْلِيَة' },
        ],
        occurrences: 30,
        occurringForm: 'نُوَلِّى',
      },
    },
    {
      id: 'absara',
      arabic: 'أَبْصَرَ',
      english: 'to see, to perceive',
      turkish: 'görmek, farkına varmak',
      example: {
        arabic: 'وَأَبْصِرْهُمْ فَسَوْفَ يُبْصِرُونَ',
        english: 'And watch them, for they are going to see.',
        turkish: 'Onları gözetle; onlar da yakında görecekler.',
        source: 'Qur\'an 37:175',
        highlight: { english: 'see', turkish: 'görecekler' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بصر',
        forms: [
          { label: 'mudari', arabic: 'يُبْصِرُ' },
          { label: 'masdar', arabic: 'إِبْصَار' },
        ],
        occurrences: 29,
        occurringForm: 'يُبْصِرُونَ',
      },
    },
    {
      id: 'jund',
      arabic: 'جُند',
      english: 'army, host, troops',
      turkish: 'ordu, asker',
      example: {
        arabic: 'جُندٌۭ مَّا هُنَالِكَ مَهْزُومٌۭ مِّنَ ٱلْأَحْزَابِ',
        english: 'A host there, from among the confederates, will be defeated.',
        turkish: 'Orada, o topluluklardan derlenmiş bir ordu bozguna uğratılacaktır.',
        source: 'Qur\'an 38:11',
        highlight: { english: 'A host', turkish: 'ordu' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'جند',
        forms: [
          { label: 'plural', arabic: 'جُنُود' },
        ],
        occurrences: 29,
        occurringForm: 'جُندٌ',
      },
    },
    {
      id: 'rajul',
      arabic: 'رَجُل',
      english: 'man',
      turkish: 'adam, erkek',
      example: {
        arabic: 'وَلَوْ جَعَلْنَٰهُ مَلَكًۭا لَّجَعَلْنَٰهُ رَجُلًۭا وَلَلَبَسْنَا عَلَيْهِم مَّا يَلْبِسُونَ',
        english: 'And if We had made him an angel, We would have made him a man, and We would have confused them just as they are confused.',
        turkish: 'Onu bir melek yapsaydık, yine onu bir adam kılardık ve düştükleri şüpheye yine düşürürdük.',
        source: 'Qur\'an 6:9',
        highlight: { english: 'a man', turkish: 'adam' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'رجل',
        forms: [
          { label: 'plural', arabic: 'رِجَال' },
        ],
        occurrences: 29,
        occurringForm: 'رَجُلًا',
      },
    },
    {
      id: 'riyh',
      arabic: 'رِيح',
      english: 'wind',
      turkish: 'rüzgâr',
      example: {
        arabic: 'وَلَئِنْ أَرْسَلْنَا رِيحًۭا فَرَأَوْهُ مُصْفَرًّۭا لَّظَلُّوا۟ مِنۢ بَعْدِهِۦ يَكْفُرُونَ',
        english: 'And if We sent a wind and they saw it turn yellow, they would after that remain ungrateful.',
        turkish: 'Andolsun, bir rüzgâr göndersek de onu sararmış görseler, ardından mutlaka nankörlük ederler.',
        source: 'Qur\'an 30:51',
        highlight: { english: 'a wind', turkish: 'rüzgâr' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'روح',
        forms: [
          { label: 'plural', arabic: 'رِيَاح' },
        ],
        occurrences: 29,
        occurringForm: 'رِيحًا',
      },
    },
    {
      id: 'arsh',
      arabic: 'عَرْش',
      english: 'throne',
      turkish: 'arş, taht',
      example: {
        arabic: 'وَٱلْمَلَكُ عَلَىٰٓ أَرْجَآئِهَا ۚ وَيَحْمِلُ عَرْشَ رَبِّكَ فَوْقَهُمْ يَوْمَئِذٍۢ ثَمَٰنِيَةٌۭ',
        english: 'And the angels are at its edges, and eight will bear the Throne of your Lord above them that Day.',
        turkish: 'Melekler onun çevresindedir; o gün Rabbinin arşını, üstlerinde sekizi taşır.',
        source: 'Qur\'an 69:17',
        highlight: { english: 'Throne', turkish: 'arşını' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عرش',
        forms: [
          { label: 'plural', arabic: 'عُرُوش' },
        ],
        occurrences: 29,
        occurringForm: 'عَرْشَ',
      },
    },
    {
      id: 'ahd',
      arabic: 'عَهْد',
      english: 'covenant, pledge, promise',
      turkish: 'ahit, söz, antlaşma',
      example: {
        arabic: 'أَطَّلَعَ ٱلْغَيْبَ أَمِ ٱتَّخَذَ عِندَ ٱلرَّحْمَٰنِ عَهْدًۭا',
        english: 'Has he looked into the unseen, or has he taken a covenant with the Most Merciful?',
        turkish: 'Gaybı mı gördü, yoksa Rahmân’ın katından bir ahit mi aldı?',
        source: 'Qur\'an 19:78',
        highlight: { english: 'covenant', turkish: 'ahit' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عهد',
        forms: [
          { label: 'plural', arabic: 'عُهُود' },
        ],
        occurrences: 29,
        occurringForm: 'عَهْدًا',
      },
    },
    {
      id: 'naba',
      arabic: 'نَبَأ',
      english: 'news, tidings, report',
      turkish: 'haber',
      example: {
        arabic: 'وَٱتْلُ عَلَيْهِمْ نَبَأَ إِبْرَٰهِيمَ',
        english: 'And recite to them the news of Abraham,',
        turkish: 'Onlara İbrahim’in haberini de oku,',
        source: 'Qur\'an 26:69',
        highlight: { english: 'news', turkish: 'haberini' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نبأ',
        forms: [
          { label: 'plural', arabic: 'أَنْبَاء' },
        ],
        occurrences: 29,
        occurringForm: 'نَبَأَ',
      },
    },
    {
      id: 'abadana',
      arabic: 'أَبَدًا',
      english: 'forever, ever',
      turkish: 'ebediyen, sonsuza dek',
      example: {
        arabic: 'مَّٰكِثِينَ فِيهِ أَبَدًۭا',
        english: 'remaining therein forever,',
        turkish: 'Orada ebediyen kalacak olarak,',
        source: 'Qur\'an 18:3',
        highlight: { english: 'forever', turkish: 'ebediyen' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أبد',
        occurrences: 28,
        occurringForm: 'أَبَدًا',
      },
    },
    {
      id: 'asbaha',
      arabic: 'أَصْبَحَ',
      english: 'to become; to enter upon morning',
      turkish: 'olmak, hale gelmek; sabahlamak',
      example: {
        arabic: 'أَوْ يُصْبِحَ مَآؤُهَا غَوْرًۭا فَلَن تَسْتَطِيعَ لَهُۥ طَلَبًۭا',
        english: 'Or its water may become sunken into the ground, so that you would never be able to seek it out.',
        turkish: 'Yahut suyu yerin dibine çekilir de bir daha onu aramaya güç yetiremezsin.',
        source: 'Qur\'an 18:41',
        highlight: { english: 'become', turkish: 'çekilir' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'صبح',
        forms: [
          { label: 'mudari', arabic: 'يُصْبِحُ' },
          { label: 'masdar', arabic: 'إِصْبَاح' },
        ],
        occurrences: 28,
        occurringForm: 'يُصْبِحَ',
      },
    },
    {
      id: 'aslaha',
      arabic: 'أَصْلَحَ',
      english: 'to set right, to reform, to make good',
      turkish: 'ıslah etmek, düzeltmek',
      example: {
        arabic: 'سَيَهْدِيهِمْ وَيُصْلِحُ بَالَهُمْ',
        english: 'He will guide them and set right their condition.',
        turkish: 'Onları doğru yola iletecek ve durumlarını düzeltecektir.',
        source: 'Qur\'an 47:5',
        highlight: { english: 'set right', turkish: 'düzeltecektir' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'صلح',
        forms: [
          { label: 'mudari', arabic: 'يُصْلِحُ' },
          { label: 'masdar', arabic: 'إِصْلَاح' },
        ],
        occurrences: 28,
        occurringForm: 'وَيُصْلِحُ',
      },
    },
    {
      id: 'aghnaa',
      arabic: 'أَغْنَتْ',
      english: 'to avail, to be of use; to enrich, to free from need',
      turkish: 'fayda vermek; zengin etmek, ihtiyaçtan kurtarmak',
      example: {
        arabic: 'حِكْمَةٌۢ بَٰلِغَةٌۭ ۖ فَمَا تُغْنِ ٱلنُّذُرُ',
        english: 'Far-reaching wisdom, but the warnings do not avail.',
        turkish: 'Üstün bir hikmettir; fakat uyarılar fayda vermiyor.',
        source: 'Qur\'an 54:5',
        highlight: { english: 'do not avail', turkish: 'fayda vermiyor' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'غني',
        forms: [
          { label: 'mudari', arabic: 'يُغْنِي' },
          { label: 'masdar', arabic: 'إِغْنَاء' },
        ],
        occurrences: 28,
        occurringForm: 'تُغْنِ',
      },
    },
    {
      id: 'annaa',
      arabic: 'أَنَّى',
      english: 'how, from where, whence',
      turkish: 'nasıl, nereden',
      example: {
        arabic: 'أَنَّىٰ لَهُمُ ٱلذِّكْرَىٰ وَقَدْ جَآءَهُمْ رَسُولٌۭ مُّبِينٌۭ',
        english: 'How can the reminder be for them, when a clear messenger had already come to them?',
        turkish: 'Onlar nerede, öğüt almak nerede! Oysa kendilerine apaçık bir elçi gelmişti.',
        source: 'Qur\'an 44:13',
        highlight: { english: 'How', turkish: 'Onlar nerede' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 28,
        occurringForm: 'أَنَّىٰ',
      },
    },
    {
      id: 'astajaba',
      arabic: 'اسْتَجابَ',
      english: 'to respond, to answer',
      turkish: 'icabet etmek, cevap vermek',
      example: {
        arabic: '۞ إِنَّمَا يَسْتَجِيبُ ٱلَّذِينَ يَسْمَعُونَ ۘ وَٱلْمَوْتَىٰ يَبْعَثُهُمُ ٱللَّهُ ثُمَّ إِلَيْهِ يُرْجَعُونَ',
        english: 'Only those who hear will respond. And the dead — Allah will raise them, then to Him they will be returned.',
        turkish: 'Ancak işitenler icabet eder. Ölüleri ise Allah diriltir; sonra O’na döndürülürler.',
        source: 'Qur\'an 6:36',
        highlight: { english: 'respond', turkish: 'icabet eder' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'جوب',
        forms: [
          { label: 'mudari', arabic: 'يَسْتَجِيبُ' },
          { label: 'masdar', arabic: 'اسْتِجَابَة' },
        ],
        occurrences: 28,
        occurringForm: 'يَسْتَجِيبُ',
      },
    },
    {
      id: 'hadiyth',
      arabic: 'حَدِيث',
      english: 'account, story, report; speech',
      turkish: 'haber, kıssa; söz',
      example: {
        arabic: 'هَلْ أَتَىٰكَ حَدِيثُ مُوسَىٰٓ',
        english: 'Has the story of Moses reached you?',
        turkish: 'Musa’nın haberi sana geldi mi?',
        source: 'Qur\'an 79:15',
        highlight: { english: 'story', turkish: 'haberi' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حدث',
        forms: [
          { label: 'plural', arabic: 'أَحَادِيث' },
        ],
        occurrences: 28,
        occurringForm: 'حَدِيثُ',
      },
    },
    {
      id: 'rijal',
      arabic: 'رِجال',
      english: 'men',
      turkish: 'adamlar, erkekler',
      example: {
        arabic: 'وَقَالُوا۟ مَا لَنَا لَا نَرَىٰ رِجَالًۭا كُنَّا نَعُدُّهُم مِّنَ ٱلْأَشْرَارِ',
        english: 'And they will say: What is with us that we do not see men whom we used to count among the worst?',
        turkish: 'Derler ki: Bize ne oldu ki, kötülerden saydığımız adamları görmüyoruz?',
        source: 'Qur\'an 38:62',
        highlight: { english: 'men', turkish: 'adamları' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'رجل',
        occurrences: 28,
        occurringForm: 'رِجَالًا',
      },
    },
    {
      id: 'rahima',
      arabic: 'رَحِمَ',
      english: 'to have mercy on, to show mercy',
      turkish: 'merhamet etmek, acımak',
      example: {
        arabic: 'إِلَّا مَن رَّحِمَ ٱللَّهُ ۚ إِنَّهُۥ هُوَ ٱلْعَزِيزُ ٱلرَّحِيمُ',
        english: 'except him on whom Allah has mercy. Indeed, He is the Exalted in Might, the Merciful.',
        turkish: 'Ancak Allah’ın merhamet ettiği kimse başka. Şüphesiz O, Azîz’dir, Rahîm’dir.',
        source: 'Qur\'an 44:42',
        highlight: { english: 'has mercy', turkish: 'merhamet ettiği' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'رحم',
        forms: [
          { label: 'mudari', arabic: 'يَرْحَمُ' },
          { label: 'masdar', arabic: 'رَحْمَة' },
        ],
        occurrences: 28,
        occurringForm: 'رَّحِمَ',
      },
    },
    {
      id: 'sihr',
      arabic: 'سِحْر',
      english: 'magic, sorcery',
      turkish: 'sihir, büyü',
      example: {
        arabic: 'وَقَالُوٓا۟ إِنْ هَٰذَآ إِلَّا سِحْرٌۭ مُّبِينٌ',
        english: 'And they say: This is nothing but clear magic.',
        turkish: 'Ve derler ki: Bu, apaçık bir büyüden başka bir şey değildir.',
        source: 'Qur\'an 37:15',
        highlight: { english: 'magic', turkish: 'büyüden' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سحر',
        occurrences: 28,
        occurringForm: 'سِحْرٌ',
      },
    },
    {
      id: 'mumina',
      arabic: 'مُؤْمِنَة',
      english: 'believing woman',
      turkish: 'mümin kadın',
      example: {
        arabic: 'لَّوْلَآ إِذْ سَمِعْتُمُوهُ ظَنَّ ٱلْمُؤْمِنُونَ وَٱلْمُؤْمِنَٰتُ بِأَنفُسِهِمْ خَيْرًۭا وَقَالُوا۟ هَٰذَآ إِفْكٌۭ مُّبِينٌۭ',
        english: 'Why, when you heard it, did the believing men and believing women not think well of themselves and say: This is an obvious falsehood?',
        turkish: 'Onu işittiğinizde, mümin erkeklerle mümin kadınların kendi haklarında iyi bir zan besleyip: Bu apaçık bir iftiradır, demeleri gerekmez miydi?',
        source: 'Qur\'an 24:12',
        highlight: { english: 'believing women', turkish: 'mümin kadınların' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أمن',
        forms: [
          { label: 'plural', arabic: 'مُؤْمِنَات' },
        ],
        occurrences: 28,
        occurringForm: 'وَٱلْمُؤْمِنَٰتُ',
      },
    },
    {
      id: 'masjid',
      arabic: 'مَسْجِد',
      english: 'place of prostration, mosque',
      turkish: 'mescit, secde yeri',
      example: {
        arabic: 'وَأَنَّ ٱلْمَسَٰجِدَ لِلَّهِ فَلَا تَدْعُوا۟ مَعَ ٱللَّهِ أَحَدًۭا',
        english: 'And that the places of worship are for Allah, so do not invoke anyone along with Allah.',
        turkish: 'Mescitler Allah’ındır; öyleyse Allah ile birlikte hiç kimseye yalvarmayın.',
        source: 'Qur\'an 72:18',
        highlight: { english: 'places of worship', turkish: 'Mescitler' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سجد',
        forms: [
          { label: 'plural', arabic: 'مَسَاجِد' },
        ],
        occurrences: 28,
        occurringForm: 'ٱلْمَسَٰجِدَ',
      },
    },
    {
      id: 'masiyr',
      arabic: 'مَصِير',
      english: 'destination, journey\'s end',
      turkish: 'dönüş yeri, varış',
      example: {
        arabic: 'إِنَّا نَحْنُ نُحْىِۦ وَنُمِيتُ وَإِلَيْنَا ٱلْمَصِيرُ',
        english: 'Indeed, it is We who give life and cause death, and to Us is the destination.',
        turkish: 'Şüphesiz biz diriltir ve öldürürüz; dönüş de bizedir.',
        source: 'Qur\'an 50:43',
        highlight: { english: 'destination', turkish: 'dönüş' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صير',
        forms: [
          { label: 'plural', arabic: 'مَصَائِر' },
        ],
        occurrences: 28,
        occurringForm: 'ٱلْمَصِيرُ',
      },
    },
    {
      id: 'maghfira',
      arabic: 'مَغْفِرَة',
      english: 'forgiveness, pardon',
      turkish: 'mağfiret, bağışlanma',
      example: {
        arabic: 'فَٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ لَهُم مَّغْفِرَةٌۭ وَرِزْقٌۭ كَرِيمٌۭ',
        english: 'So those who believe and do righteous deeds — for them is forgiveness and noble provision.',
        turkish: 'İman edip salih ameller işleyenlere mağfiret ve değerli bir rızık vardır.',
        source: 'Qur\'an 22:50',
        highlight: { english: 'forgiveness', turkish: 'mağfiret' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'غفر',
        occurrences: 28,
        occurringForm: 'مَّغْفِرَةٌ',
      },
    },
    {
      id: 'aflaha',
      arabic: 'أَفْلَحَ',
      english: 'to succeed, to prosper',
      turkish: 'felah bulmak, kurtuluşa ermek',
      example: {
        arabic: 'قَدْ أَفْلَحَ ٱلْمُؤْمِنُونَ',
        english: 'Certainly the believers have succeeded.',
        turkish: 'Müminler gerçekten felah bulmuştur.',
        source: 'Qur\'an 23:1',
        highlight: { english: 'have succeeded', turkish: 'felah bulmuştur' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'فلح',
        forms: [
          { label: 'mudari', arabic: 'يُفْلِحُ' },
          { label: 'masdar', arabic: 'إِفْلَاح' },
        ],
        occurrences: 27,
        occurringForm: 'أَفْلَحَ',
      },
    },
    {
      id: 'bab',
      arabic: 'باب',
      english: 'door, gate',
      turkish: 'kapı',
      example: {
        arabic: 'وَفُتِحَتِ ٱلسَّمَآءُ فَكَانَتْ أَبْوَٰبًۭا',
        english: 'And the sky is opened and becomes gateways,',
        turkish: 'Gök açılmış, kapı kapı olmuştur,',
        source: 'Qur\'an 78:19',
        highlight: { english: 'gateways', turkish: 'kapı kapı' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بوب',
        forms: [
          { label: 'plural', arabic: 'أَبْوَاب' },
        ],
        occurrences: 27,
        occurringForm: 'أَبْوَٰبًا',
      },
    },
    {
      id: 'jahada',
      arabic: 'جاهَدَ',
      english: 'to strive, to struggle, to exert oneself',
      turkish: 'cihat etmek, çaba göstermek',
      example: {
        arabic: 'وَمَن جَٰهَدَ فَإِنَّمَا يُجَٰهِدُ لِنَفْسِهِۦٓ ۚ إِنَّ ٱللَّهَ لَغَنِىٌّ عَنِ ٱلْعَٰلَمِينَ',
        english: 'And whoever strives only strives for himself. Indeed, Allah is free of need of the worlds.',
        turkish: 'Kim cihat ederse, ancak kendisi için cihat etmiş olur. Şüphesiz Allah, âlemlerden müstağnidir.',
        source: 'Qur\'an 29:6',
        highlight: { english: 'whoever strives', turkish: 'cihat ederse' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'جهد',
        forms: [
          { label: 'mudari', arabic: 'يُجَاهِدُ' },
          { label: 'masdar', arabic: 'جِهَاد' },
        ],
        occurrences: 27,
        occurringForm: 'جَٰهَدَ',
      },
    },
    {
      id: 'sawa',
      arabic: 'سَواء',
      english: 'equal, alike; midst, middle',
      turkish: 'eşit, aynı; orta',
      example: {
        arabic: 'فَٱطَّلَعَ فَرَءَاهُ فِى سَوَآءِ ٱلْجَحِيمِ',
        english: 'Then he looked and saw him in the midst of the Hellfire.',
        turkish: 'Bakınca onu cehennemin ortasında gördü.',
        source: 'Qur\'an 37:55',
        highlight: { english: 'the midst', turkish: 'ortasında' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سوي',
        occurrences: 27,
        occurringForm: 'سَوَآءِ',
      },
    },
    {
      id: 'afa',
      arabic: 'عَفا',
      english: 'to pardon, to forgive',
      turkish: 'affetmek, bağışlamak',
      example: {
        arabic: 'فَأُو۟لَٰٓئِكَ عَسَى ٱللَّهُ أَن يَعْفُوَ عَنْهُمْ ۚ وَكَانَ ٱللَّهُ عَفُوًّا غَفُورًۭا',
        english: 'For those, perhaps Allah will pardon them; and Allah is ever Pardoning and Forgiving.',
        turkish: 'İşte onları Allah’ın affetmesi umulur; Allah çok affedicidir, çok bağışlayıcıdır.',
        source: 'Qur\'an 4:99',
        highlight: { english: 'pardon', turkish: 'affetmesi' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عفو',
        forms: [
          { label: 'mudari', arabic: 'يَعْفُو' },
          { label: 'masdar', arabic: 'عَفْو' },
        ],
        occurrences: 27,
        occurringForm: 'يَعْفُوَ',
      },
    },
    {
      id: 'ghafil',
      arabic: 'غافِل',
      english: 'heedless, unaware',
      turkish: 'gafil, habersiz',
      example: {
        arabic: 'لِتُنذِرَ قَوْمًۭا مَّآ أُنذِرَ ءَابَآؤُهُمْ فَهُمْ غَٰفِلُونَ',
        english: 'that you may warn a people whose fathers were not warned, so they are heedless.',
        turkish: 'Ataları uyarılmamış, bu yüzden kendileri gafil olan bir kavmi uyarasın diye.',
        source: 'Qur\'an 36:6',
        highlight: { english: 'heedless', turkish: 'gafil' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'غفل',
        forms: [
          { label: 'plural', arabic: 'غَافِلُون' },
        ],
        occurrences: 27,
        occurringForm: 'غَٰفِلُونَ',
      },
    },
    {
      id: 'qaddama',
      arabic: 'قَدَّمَ',
      english: 'to put forward, to send ahead, to offer',
      turkish: 'takdim etmek, öne sürmek, önden göndermek',
      example: {
        arabic: 'عَلِمَتْ نَفْسٌۭ مَّا قَدَّمَتْ وَأَخَّرَتْ',
        english: 'A soul will know what it sent forward and what it left behind.',
        turkish: 'Her nefis, önden gönderdiğini ve geri bıraktığını bilecektir.',
        source: 'Qur\'an 82:5',
        highlight: { english: 'sent forward', turkish: 'önden gönderdiğini' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'قدم',
        forms: [
          { label: 'mudari', arabic: 'يُقَدِّمُ' },
          { label: 'masdar', arabic: 'تَقْدِيم' },
        ],
        occurrences: 27,
        occurringForm: 'قَدَّمَتْ',
      },
    },
    {
      id: 'qamar',
      arabic: 'قَمَر',
      english: 'moon',
      turkish: 'ay',
      example: {
        arabic: 'وَخَسَفَ ٱلْقَمَرُ',
        english: 'and the moon is eclipsed,',
        turkish: 've ay tutulduğunda,',
        source: 'Qur\'an 75:8',
        highlight: { english: 'moon', turkish: 'ay' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قمر',
        forms: [
          { label: 'plural', arabic: 'أَقْمَار' },
        ],
        occurrences: 27,
        occurringForm: 'ٱلْقَمَرُ',
      },
    },
    {
      id: 'luwt',
      arabic: 'لُوط',
      english: 'Lot (prophet)',
      turkish: 'Lût (peygamber)',
      example: {
        arabic: 'وَقَوْمُ إِبْرَٰهِيمَ وَقَوْمُ لُوطٍۢ',
        english: 'and the people of Abraham and the people of Lot,',
        turkish: 'İbrahim’in kavmi ve Lût’un kavmi de,',
        source: 'Qur\'an 22:43',
        highlight: { english: 'Lot', turkish: 'Lût' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 27,
        occurringForm: 'لُوطٍ',
      },
    },
    {
      id: 'makan',
      arabic: 'مَكان',
      english: 'place, position, station',
      turkish: 'mekân, yer, konum',
      example: {
        arabic: 'وَرَفَعْنَٰهُ مَكَانًا عَلِيًّا',
        english: 'And We raised him to a high station.',
        turkish: 'Onu yüce bir mekâna yükselttik.',
        source: 'Qur\'an 19:57',
        highlight: { english: 'station', turkish: 'mekâna' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كون',
        forms: [
          { label: 'plural', arabic: 'أَمْكِنَة' },
        ],
        occurrences: 27,
        occurringForm: 'مَكَانًا',
      },
    },
    {
      id: 'munafiq',
      arabic: 'مُنافِق',
      english: 'hypocrite',
      turkish: 'münafık, ikiyüzlü',
      example: {
        arabic: 'بَشِّرِ ٱلْمُنَٰفِقِينَ بِأَنَّ لَهُمْ عَذَابًا أَلِيمًا',
        english: 'Give tidings to the hypocrites that for them is a painful punishment,',
        turkish: 'Münafıklara, kendileri için acı bir azap olduğunu müjdele,',
        source: 'Qur\'an 4:138',
        highlight: { english: 'hypocrites', turkish: 'Münafıklara' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نفق',
        forms: [
          { label: 'plural', arabic: 'مُنَافِقُون' },
        ],
        occurrences: 27,
        occurringForm: 'ٱلْمُنَٰفِقِينَ',
      },
    },
    {
      id: 'yuwsuf',
      arabic: 'يُوسُف',
      english: 'Joseph (prophet)',
      turkish: 'Yusuf (peygamber)',
      example: {
        arabic: '۞ لَّقَدْ كَانَ فِى يُوسُفَ وَإِخْوَتِهِۦٓ ءَايَٰتٌۭ لِّلسَّآئِلِينَ',
        english: 'Certainly in Joseph and his brothers were signs for those who ask.',
        turkish: 'Andolsun, Yusuf ve kardeşlerinde soranlar için ibretler vardır.',
        source: 'Qur\'an 12:7',
        highlight: { english: 'Joseph', turkish: 'Yusuf' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 27,
        occurringForm: 'يُوسُفَ',
      },
    },
    {
      id: 'al',
      arabic: 'آل',
      english: 'family, household, folk of',
      turkish: 'aile, hane halkı, soy',
      example: {
        arabic: 'فَلَمَّا جَآءَ ءَالَ لُوطٍ ٱلْمُرْسَلُونَ',
        english: 'So when the messengers came to the family of Lot,',
        turkish: 'Elçiler Lût ailesine geldiklerinde,',
        source: 'Qur\'an 15:61',
        highlight: { english: 'family of', turkish: 'ailesine' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أول',
        occurrences: 26,
        occurringForm: 'ءَالَ',
      },
    },
    {
      id: 'ajma',
      arabic: 'أَجْمَع',
      english: 'all together, the whole of',
      turkish: 'hep birlikte, tümü',
      example: {
        arabic: 'فَوَرَبِّكَ لَنَسْـَٔلَنَّهُمْ أَجْمَعِينَ',
        english: 'So by your Lord, We will surely question them all,',
        turkish: 'Rabbine andolsun ki, onların hepsini mutlaka sorguya çekeceğiz,',
        source: 'Qur\'an 15:92',
        highlight: { english: 'them all', turkish: 'hepsini' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'جمع',
        forms: [
          { label: 'plural', arabic: 'أَجْمَعُونَ' },
        ],
        occurrences: 26,
        occurringForm: 'أَجْمَعِينَ',
      },
    },
    {
      id: 'amraat',
      arabic: 'امْرَأَت',
      english: 'woman, wife',
      turkish: 'kadın, eş',
      example: {
        arabic: 'إِنِّى وَجَدتُّ ٱمْرَأَةًۭ تَمْلِكُهُمْ وَأُوتِيَتْ مِن كُلِّ شَىْءٍۢ وَلَهَا عَرْشٌ عَظِيمٌۭ',
        english: 'Indeed, I found a woman ruling them, and she has been given of all things, and she has a great throne.',
        turkish: 'Ben, onlara hükmeden bir kadın buldum; kendisine her şeyden verilmiş ve onun büyük bir tahtı var.',
        source: 'Qur\'an 27:23',
        highlight: { english: 'a woman', turkish: 'kadın' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'مرأ',
        forms: [
          { label: 'plural', arabic: 'نِسَاء' },
        ],
        occurrences: 26,
        occurringForm: 'ٱمْرَأَةً',
      },
    },
    {
      id: 'batil',
      arabic: 'باطِل',
      english: 'falsehood, vain, futile',
      turkish: 'batıl, asılsız, boş',
      example: {
        arabic: 'لِيُحِقَّ ٱلْحَقَّ وَيُبْطِلَ ٱلْبَٰطِلَ وَلَوْ كَرِهَ ٱلْمُجْرِمُونَ',
        english: 'that He might establish the truth and bring falsehood to nothing, even though the criminals disliked it.',
        turkish: 'Hakkı ortaya çıkarmak ve batılı yok etmek için; suçlular hoşlanmasa da.',
        source: 'Qur\'an 8:8',
        highlight: { english: 'falsehood', turkish: 'batılı' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بطل',
        occurrences: 26,
        occurringForm: 'ٱلْبَٰطِلَ',
      },
    },
    {
      id: 'thamuwd',
      arabic: 'ثَمُود',
      english: 'Thamud (a people)',
      turkish: 'Semûd (kavmi)',
      example: {
        arabic: 'كَذَّبَتْ ثَمُودُ بِطَغْوَىٰهَآ',
        english: 'Thamud denied through their transgression,',
        turkish: 'Semûd, azgınlığı yüzünden yalanladı,',
        source: 'Qur\'an 91:11',
        highlight: { english: 'Thamud', turkish: 'Semûd' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 26,
        occurringForm: 'ثَمُودُ',
      },
    },
    {
      id: 'jahiym',
      arabic: 'جَحِيم',
      english: 'Hellfire, blazing fire',
      turkish: 'cehennem, alevli ateş',
      example: {
        arabic: 'وَتَصْلِيَةُ جَحِيمٍ',
        english: 'and a burning in a Hellfire.',
        turkish: 've alevli ateşte yanmak vardır.',
        source: 'Qur\'an 56:94',
        highlight: { english: 'Hellfire', turkish: 'alevli ateşte' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'جحم',
        occurrences: 26,
        occurringForm: 'جَحِيمٍ',
      },
    },
    {
      id: 'khawf',
      arabic: 'خَوْف',
      english: 'fear',
      turkish: 'korku',
      example: {
        arabic: 'ٱلَّذِىٓ أَطْعَمَهُم مِّن جُوعٍۢ وَءَامَنَهُم مِّنْ خَوْفٍۭ',
        english: 'who fed them against hunger and made them safe from fear.',
        turkish: 'O ki onları açlıktan doyurdu ve korkudan emin kıldı.',
        source: 'Qur\'an 106:4',
        highlight: { english: 'fear', turkish: 'korkudan' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'خوف',
        occurrences: 26,
        occurringForm: 'خَوْفٍۭ',
      },
    },
    {
      id: 'zayyana',
      arabic: 'زَيَّنَ',
      english: 'to adorn, to beautify, to make attractive',
      turkish: 'süslemek, güzel göstermek',
      example: {
        arabic: 'إِنَّا زَيَّنَّا ٱلسَّمَآءَ ٱلدُّنْيَا بِزِينَةٍ ٱلْكَوَاكِبِ',
        english: 'Indeed, We adorned the nearest heaven with an adornment, the stars.',
        turkish: 'Biz en yakın göğü bir süsle, yıldızlarla süsledik.',
        source: 'Qur\'an 37:6',
        highlight: { english: 'adorned', turkish: 'süsledik' },
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'زين',
        forms: [
          { label: 'mudari', arabic: 'يُزَيِّنُ' },
          { label: 'masdar', arabic: 'تَزْيِين' },
        ],
        occurrences: 26,
        occurringForm: 'زَيَّنَّا',
      },
    },
    {
      id: 'shahada',
      arabic: 'شَهادَة',
      english: 'testimony, witnessing',
      turkish: 'şahitlik, tanıklık',
      example: {
        arabic: 'وَيَدْرَؤُا۟ عَنْهَا ٱلْعَذَابَ أَن تَشْهَدَ أَرْبَعَ شَهَٰدَٰتٍۭ بِٱللَّهِ ۙ إِنَّهُۥ لَمِنَ ٱلْكَٰذِبِينَ',
        english: 'And it averts the punishment from her that she testify four testimonies by Allah that he is surely of the liars.',
        turkish: 'Kadının, onun kesinlikle yalancılardan olduğuna dair Allah adına dört kez şahitlik etmesi, kendisinden azabı savar.',
        source: 'Qur\'an 24:8',
        highlight: { english: 'testimonies', turkish: 'şahitlik' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شهد',
        forms: [
          { label: 'plural', arabic: 'شَهَادَات' },
        ],
        occurrences: 26,
        occurringForm: 'شَهَٰدَٰتٍۭ',
      },
    },
    {
      id: 'qariyb',
      arabic: 'قَرِيب',
      english: 'near, close',
      turkish: 'yakın',
      example: {
        arabic: 'وَنَرَىٰهُ قَرِيبًۭا',
        english: 'while We see it as near.',
        turkish: 'Biz ise onu yakın görüyoruz.',
        source: 'Qur\'an 70:7',
        highlight: { english: 'near', turkish: 'yakın' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قرب',
        occurrences: 26,
        occurringForm: 'قَرِيبًا',
      },
    },
    {
      id: 'kayd',
      arabic: 'كَيْد',
      english: 'plot, scheme, plan',
      turkish: 'tuzak, hile, düzen',
      example: {
        arabic: 'وَأَكِيدُ كَيْدًۭا',
        english: 'and I am devising a plan.',
        turkish: 'Ben de bir tuzak kurarım.',
        source: 'Qur\'an 86:16',
        highlight: { english: 'a plan', turkish: 'tuzak' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كيد',
        occurrences: 26,
        occurringForm: 'كَيْدًا',
      },
    },
    {
      id: 'madha',
      arabic: 'ماذا',
      english: 'what',
      turkish: 'ne',
      example: {
        arabic: 'قَالُوا۟ وَأَقْبَلُوا۟ عَلَيْهِم مَّاذَا تَفْقِدُونَ',
        english: 'They said, turning toward them: What is it that you are missing?',
        turkish: 'Onlara dönerek dediler ki: Ne kaybettiniz?',
        source: 'Qur\'an 12:71',
        highlight: { english: 'What', turkish: 'Ne' },
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 26,
        occurringForm: 'مَّاذَا',
      },
    },
    {
      id: 'adam',
      arabic: 'آدَم',
      english: 'Adam',
      turkish: 'Âdem',
      example: {
        arabic: 'فَتَلَقَّىٰٓ ءَادَمُ مِن رَّبِّهِۦ كَلِمَٰتٍۢ فَتَابَ عَلَيْهِ ۚ إِنَّهُۥ هُوَ ٱلتَّوَّابُ ٱلرَّحِيمُ',
        english: 'Then Adam received words from his Lord, and He accepted his repentance. Indeed, He is the Accepting of repentance, the Merciful.',
        turkish: 'Âdem, Rabbinden birtakım kelimeler aldı; böylece Allah onun tövbesini kabul etti. Şüphesiz O, tövbeleri çok kabul edendir, çok merhametlidir.',
        source: 'Qur\'an 2:37',
        highlight: { english: 'Adam', turkish: 'Âdem' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أدم',
        occurrences: 25,
        occurringForm: 'ءَادَمُ',
      },
    },
    {
      id: 'bas',
      arabic: 'بَأْس',
      english: 'might, force; hardship, adversity',
      turkish: 'güç, savaş gücü; sıkıntı, şiddet',
      example: {
        arabic: 'قَالُوا۟ نَحْنُ أُو۟لُوا۟ قُوَّةٍۢ وَأُو۟لُوا۟ بَأْسٍۢ شَدِيدٍۢ وَٱلْأَمْرُ إِلَيْكِ فَٱنظُرِى مَاذَا تَأْمُرِينَ',
        english: 'They said: We are men of strength and men of great might, but the command is yours, so see what you will command.',
        turkish: 'Dediler ki: Biz güç sahibiyiz ve çetin savaş gücüne sahibiz; emir senindir, artık ne buyuracağına bak.',
        source: 'Qur\'an 27:33',
        highlight: { english: 'great might', turkish: 'çetin savaş gücüne' },
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بأس',
        occurrences: 25,
        occurringForm: 'بَأْسٍ',
      },
    },
  ],
}
