import type { DeckDef } from '../types'

// Quran Vocabulary, level 2: the next 50 most frequent words after level 1.
// See GitHub issue #8.
//
// Scaffolded by scripts/generateVocab.ts and then authored by hand, exactly as
// level 1 was. Three ayat were chosen by hand where the generator's pick showed
// the word in the wrong sense (sala, dhakara, akh).
//
// DRAFT: verify every English meaning before memorizing it. Turkish is
// generated convenience text and stays draft - correct it on sight while
// studying. Note banun: the corpus lemmatizes the construct plural here, so the
// headword is the "children of" form rather than the singular ibn.
//
// Locked until level 1 is mostly graduated; see quranVocabTrack.ts.

export const quranVocab2: DeckDef = {
  id: 'quran-vocab-2',
  name: 'Quran Vocabulary 2',
  nameArabic: 'مُفْرَدَاتُ الْقُرْآنِ ٢',
  description:
    'The next 50 most frequent Quranic words, each with an ayah where it occurs.',
  directions: ['ar-to-meaning'],
  newPerDay: 10,
  burySiblings: true,
  notes: [
    {
      id: 'diyn',
      arabic: 'دِين',
      english: 'religion, way of life; judgement',
      turkish: 'din; hüküm',
      example: {
        arabic: 'وَرَأَيْتَ ٱلنَّاسَ يَدْخُلُونَ فِى دِينِ ٱللَّهِ أَفْوَاجًۭا',
        english: 'and you see the people entering into the religion of Allah in crowds,',
        turkish: 've insanların dalga dalga Allah’ın dinine girdiklerini gördüğünde,',
        source: 'Qur\'an 110:2',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'دين',
        forms: [
          { label: 'plural', arabic: 'أَدْيَان' },
        ],
        occurrences: 92,
        occurringForm: 'دِينِ',
      },
    },
    {
      id: 'qawl',
      arabic: 'قَوْل',
      english: 'word, speech, saying',
      turkish: 'söz',
      example: {
        arabic: 'إِنَّكُمْ لَفِى قَوْلٍۢ مُّخْتَلِفٍۢ',
        english: 'Indeed, you are in differing speech.',
        turkish: 'Şüphesiz siz çelişkili bir söz içindesiniz.',
        source: 'Qur\'an 51:8',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قول',
        forms: [
          { label: 'plural', arabic: 'أَقْوَال' },
        ],
        occurrences: 92,
        occurringForm: 'قَوْلٍ',
      },
    },
    {
      id: 'ghafuwr',
      arabic: 'غَفُور',
      english: 'most forgiving',
      turkish: 'çok bağışlayan, gafûr',
      example: {
        arabic: 'نُزُلًۭا مِّنْ غَفُورٍۢ رَّحِيمٍۢ',
        english: 'as accommodation from a Forgiving, Merciful one.',
        turkish: 'Bağışlayan ve merhamet eden Allah’tan bir ikram olarak.',
        source: 'Qur\'an 41:32',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'غفر',
        occurrences: 91,
        occurringForm: 'غَفُورٍ',
      },
    },
    {
      id: 'laysa',
      arabic: 'لَيْسَ',
      english: 'is not',
      turkish: 'değildir',
      example: {
        arabic: 'لَيْسَ لِوَقْعَتِهَا كَاذِبَةٌ',
        english: 'There is no denying its occurrence.',
        turkish: 'Onun oluşunu yalanlayacak hiçbir şey yoktur.',
        source: 'Qur\'an 56:2',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ليس',
        occurrences: 89,
        occurringForm: 'لَيْسَ',
      },
    },
    {
      id: 'shaytan',
      arabic: 'شَيْطان',
      english: 'devil, satan',
      turkish: 'şeytan',
      example: {
        arabic: 'وَمَا هُوَ بِقَوْلِ شَيْطَٰنٍۢ رَّجِيمٍۢ',
        english: 'And it is not the word of an outcast devil.',
        turkish: 'O, kovulmuş bir şeytanın sözü de değildir.',
        source: 'Qur\'an 81:25',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شطن',
        forms: [
          { label: 'plural', arabic: 'شَيَاطِين' },
        ],
        occurrences: 88,
        occurringForm: 'شَيْطَٰنٍ',
      },
    },
    {
      id: 'faala',
      arabic: 'فَعَلَ',
      english: 'to do',
      turkish: 'yapmak, işlemek',
      example: {
        arabic: 'كَذَٰلِكَ نَفْعَلُ بِٱلْمُجْرِمِينَ',
        english: 'Thus do We deal with the criminals.',
        turkish: 'Biz suçlulara işte böyle yaparız.',
        source: 'Qur\'an 77:18',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'فعل',
        forms: [
          { label: 'mudari', arabic: 'يَفْعَلُ' },
          { label: 'masdar', arabic: 'فِعْل' },
        ],
        occurrences: 88,
        occurringForm: 'نَفْعَلُ',
      },
    },
    {
      id: 'mathal',
      arabic: 'مَثَل',
      english: 'example, likeness, parable',
      turkish: 'misal, örnek',
      example: {
        arabic: 'فَأَهْلَكْنَآ أَشَدَّ مِنْهُم بَطْشًۭا وَمَضَىٰ مَثَلُ ٱلْأَوَّلِينَ',
        english: 'and the example of the former peoples has passed on.',
        turkish: 've öncekilerin örneği geçti.',
        source: 'Qur\'an 43:8',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'مثل',
        forms: [
          { label: 'plural', arabic: 'أَمْثَال' },
        ],
        occurrences: 88,
        occurringForm: 'مَثَلُ',
      },
    },
    {
      id: 'malak',
      arabic: 'مَلَك',
      english: 'angel',
      turkish: 'melek',
      example: {
        arabic: 'وَلَوْ نَشَآءُ لَجَعَلْنَا مِنكُم مَّلَٰٓئِكَةًۭ فِى ٱلْأَرْضِ يَخْلُفُونَ',
        english: 'And if We willed, We could make among you angels succeeding one another on the earth.',
        turkish: 'Dileseydik, içinizden yeryüzünde birbirinin yerine geçen melekler yapardık.',
        source: 'Qur\'an 43:60',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ملك',
        forms: [
          { label: 'plural', arabic: 'مَلَائِكَة' },
        ],
        occurrences: 88,
        occurringForm: 'مَّلَٰٓئِكَةً',
      },
    },
    {
      id: 'nazara',
      arabic: 'نَظَرَ',
      english: 'to look, to consider',
      turkish: 'bakmak, düşünmek',
      example: {
        arabic: 'ثُمَّ نَظَرَ',
        english: 'Then he considered.',
        turkish: 'Sonra düşündü.',
        source: 'Qur\'an 74:21',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نظر',
        forms: [
          { label: 'mudari', arabic: 'يَنْظُرُ' },
          { label: 'masdar', arabic: 'نَظَر' },
        ],
        occurrences: 87,
        occurringForm: 'نَظَرَ',
      },
    },
    {
      id: 'mal',
      arabic: 'مال',
      english: 'wealth, property',
      turkish: 'mal, servet',
      example: {
        arabic: 'يَقُولُ أَهْلَكْتُ مَالًۭا لُّبَدًا',
        english: 'He says: I have squandered abundant wealth.',
        turkish: 'Yığınla mal harcadım, diyor.',
        source: 'Qur\'an 90:6',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'مول',
        forms: [
          { label: 'plural', arabic: 'أَمْوَال' },
        ],
        occurrences: 86,
        occurringForm: 'مَالًا',
      },
    },
    {
      id: 'waliyy',
      arabic: 'وَلِيّ',
      english: 'ally, protector, guardian',
      turkish: 'dost, veli, koruyucu',
      example: {
        arabic: 'خَٰلِدِينَ فِيهَآ أَبَدًۭا ۖ لَّا يَجِدُونَ وَلِيًّۭا وَلَا نَصِيرًۭا',
        english: 'abiding therein forever; they will find no protector and no helper.',
        turkish: 'Orada ebedi kalıcıdırlar; ne bir dost ne de bir yardımcı bulurlar.',
        source: 'Qur\'an 33:65',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ولي',
        forms: [
          { label: 'plural', arabic: 'أَوْلِيَاء' },
        ],
        occurrences: 86,
        occurringForm: 'وَلِيًّا',
      },
    },
    {
      id: 'hudan',
      arabic: 'هُدًى',
      english: 'guidance',
      turkish: 'hidayet, doğru yol',
      example: {
        arabic: 'هُدًۭى وَبُشْرَىٰ لِلْمُؤْمِنِينَ',
        english: 'as guidance and good tidings for the believers,',
        turkish: 'Müminler için bir hidayet ve müjdedir,',
        source: 'Qur\'an 27:2',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'هدي',
        occurrences: 85,
        occurringForm: 'هُدًى',
      },
    },
    {
      id: 'dhakara',
      arabic: 'ذَكَرَ',
      english: 'to remember, to mention',
      turkish: 'anmak, hatırlamak, zikretmek',
      example: {
        arabic: 'وَذَكَرَ ٱسْمَ رَبِّهِۦ فَصَلَّىٰ',
        english: 'and mentions the name of his Lord and prays.',
        turkish: 'Rabbinin adını anıp namaz kılan.',
        source: 'Qur\'an 87:15',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ذكر',
        forms: [
          { label: 'mudari', arabic: 'يَذْكُرُ' },
          { label: 'masdar', arabic: 'ذِكْر' },
        ],
        occurrences: 84,
        occurringForm: 'وَذَكَرَ',
      },
    },
    {
      id: 'fadl',
      arabic: 'فَضْل',
      english: 'bounty, favour, grace',
      turkish: 'lütuf, fazl, ihsan',
      example: {
        arabic: 'فَضْلًۭا مِّن رَّبِّكَ ۚ ذَٰلِكَ هُوَ ٱلْفَوْزُ ٱلْعَظِيمُ',
        english: 'as bounty from your Lord. That is the great attainment.',
        turkish: 'Rabbinden bir lütuf olarak. İşte büyük kurtuluş budur.',
        source: 'Qur\'an 44:57',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'فضل',
        occurrences: 84,
        occurringForm: 'فَضْلًا',
      },
    },
    {
      id: 'layl',
      arabic: 'لَيْل',
      english: 'night',
      turkish: 'gece',
      example: {
        arabic: 'فَأَسْرِ بِعِبَادِى لَيْلًا إِنَّكُم مُّتَّبَعُونَ',
        english: 'So travel with My servants by night; indeed, you will be pursued.',
        turkish: 'Kullarımı geceleyin yürüt; şüphesiz takip edileceksiniz.',
        source: 'Qur\'an 44:23',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ليل',
        occurrences: 84,
        occurringForm: 'لَيْلًا',
      },
    },
    {
      id: 'khafa',
      arabic: 'خافَ',
      english: 'to fear',
      turkish: 'korkmak',
      example: {
        arabic: 'وَلَا يَخَافُ عُقْبَٰهَا',
        english: 'And He does not fear its consequence.',
        turkish: 'O, bunun sonucundan korkmaz.',
        source: 'Qur\'an 91:15',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'خوف',
        forms: [
          { label: 'mudari', arabic: 'يَخَافُ' },
          { label: 'masdar', arabic: 'خَوْف' },
        ],
        occurrences: 83,
        occurringForm: 'يَخَافُ',
      },
    },
    {
      id: 'sala',
      arabic: 'صَلاة',
      english: 'prayer, salah',
      turkish: 'namaz',
      example: {
        arabic: 'ٱلَّذِينَ هُمْ عَن صَلَاتِهِمْ سَاهُونَ',
        english: 'those who are heedless of their prayer,',
        turkish: 'Onlar namazlarından gafildirler,',
        source: 'Qur\'an 107:5',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صلو',
        forms: [
          { label: 'plural', arabic: 'صَلَوَات' },
        ],
        occurrences: 83,
        occurringForm: 'صَلَاتِهِمْ',
      },
    },
    {
      id: 'qatala',
      arabic: 'قَتَلَ',
      english: 'to kill, to slay',
      turkish: 'öldürmek',
      example: {
        arabic: 'قُتِلَ ٱلْخَرَّٰصُونَ',
        english: 'Cursed are the falsifiers,',
        turkish: 'Kahrolsun o yalancılar,',
        source: 'Qur\'an 51:10',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'قتل',
        forms: [
          { label: 'mudari', arabic: 'يَقْتُلُ' },
          { label: 'masdar', arabic: 'قَتْل' },
        ],
        occurrences: 83,
        occurringForm: 'قُتِلَ',
      },
    },
    {
      id: 'kayf',
      arabic: 'كَيْف',
      english: 'how',
      turkish: 'nasıl',
      example: {
        arabic: 'فَقُتِلَ كَيْفَ قَدَّرَ',
        english: 'Destroyed is he — how he plotted!',
        turkish: 'Kahrolası, nasıl da ölçüp biçti!',
        source: 'Qur\'an 74:19',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كيف',
        occurrences: 83,
        occurringForm: 'كَيْفَ',
      },
    },
    {
      id: 'awwal',
      arabic: 'أَوَّل',
      english: 'first',
      turkish: 'ilk, birinci',
      example: {
        arabic: 'وَأُمِرْتُ لِأَنْ أَكُونَ أَوَّلَ ٱلْمُسْلِمِينَ',
        english: 'and I have been commanded to be the first of the Muslims.',
        turkish: 'Ve bana müslümanların ilki olmam emredildi.',
        source: 'Qur\'an 39:12',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أول',
        forms: [
          { label: 'plural', arabic: 'أَوَّلُون' },
        ],
        occurrences: 82,
        occurringForm: 'أَوَّلَ',
      },
    },
    {
      id: 'akthar',
      arabic: 'أَكْثَر',
      english: 'most, more numerous',
      turkish: 'çoğu, daha çok',
      example: {
        arabic: 'وَلَقَدْ ضَلَّ قَبْلَهُمْ أَكْثَرُ ٱلْأَوَّلِينَ',
        english: 'And most of the former peoples had gone astray before them,',
        turkish: 'Andolsun, onlardan önce evvelkilerin çoğu sapmıştı,',
        source: 'Qur\'an 37:71',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كثر',
        occurrences: 80,
        occurringForm: 'أَكْثَرُ',
      },
    },
    {
      id: 'banun',
      arabic: 'بُنَىّ',
      english: 'son; (in construct) children of',
      turkish: 'oğul; (izafetle) oğulları',
      example: {
        arabic: 'كَذَٰلِكَ وَأَوْرَثْنَٰهَا بَنِىٓ إِسْرَٰٓءِيلَ',
        english: 'Thus. And We caused the Children of Israel to inherit it.',
        turkish: 'İşte böyle. Onu İsrailoğulları’na miras bıraktık.',
        source: 'Qur\'an 26:59',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بني',
        forms: [
          { label: 'singular', arabic: 'ٱبْن' },
        ],
        occurrences: 80,
        occurringForm: 'بَنِىٓ',
      },
    },
    {
      id: 'rajaa',
      arabic: 'رَجَعَ',
      english: 'to return, to come back',
      turkish: 'dönmek',
      example: {
        arabic: 'وَإِنِّى مُرْسِلَةٌ إِلَيْهِم بِهَدِيَّةٍۢ فَنَاظِرَةٌۢ بِمَ يَرْجِعُ ٱلْمُرْسَلُونَ',
        english: 'and I am going to send them a gift and see with what the messengers return.',
        turkish: 'Ben onlara bir hediye göndereyim de elçilerin ne ile döneceğine bakayım.',
        source: 'Qur\'an 27:35',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'رجع',
        forms: [
          { label: 'mudari', arabic: 'يَرْجِعُ' },
          { label: 'masdar', arabic: 'رُجُوع' },
        ],
        occurrences: 79,
        occurringForm: 'يَرْجِعُ',
      },
    },
    {
      id: 'ashab',
      arabic: 'أَصْحاب',
      english: 'companions, people of',
      turkish: 'ashab, arkadaşlar, ehli',
      example: {
        arabic: 'قُتِلَ أَصْحَٰبُ ٱلْأُخْدُودِ',
        english: 'Destroyed were the companions of the trench,',
        turkish: 'Kahrolsun o hendeğin adamları,',
        source: 'Qur\'an 85:4',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صحب',
        forms: [
          { label: 'singular', arabic: 'صَاحِب' },
        ],
        occurrences: 78,
        occurringForm: 'أَصْحَٰبُ',
      },
    },
    {
      id: 'tawallaa',
      arabic: 'تَوَلَّى',
      english: 'to turn away',
      turkish: 'yüz çevirmek, sırt dönmek',
      example: {
        arabic: 'أَفَرَءَيْتَ ٱلَّذِى تَوَلَّىٰ',
        english: 'Have you seen the one who turned away,',
        turkish: 'Gördün mü o yüz çevireni?',
        source: 'Qur\'an 53:33',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ولي',
        forms: [
          { label: 'mudari', arabic: 'يَتَوَلَّى' },
        ],
        occurrences: 78,
        occurringForm: 'تَوَلَّىٰ',
      },
    },
    {
      id: 'samia',
      arabic: 'سَمِعَ',
      english: 'to hear',
      turkish: 'işitmek, duymak',
      example: {
        arabic: 'لَّا تَسْمَعُ فِيهَا لَٰغِيَةًۭ',
        english: 'Wherein they will hear no unsuitable speech.',
        turkish: 'Orada boş bir söz işitmezler.',
        source: 'Qur\'an 88:11',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سمع',
        forms: [
          { label: 'mudari', arabic: 'يَسْمَعُ' },
          { label: 'masdar', arabic: 'سَمْع' },
        ],
        occurrences: 78,
        occurringForm: 'تَسْمَعُ',
      },
    },
    {
      id: 'amara',
      arabic: 'أَمَرَ',
      english: 'to command, to order',
      turkish: 'emretmek',
      example: {
        arabic: 'أَوْ أَمَرَ بِٱلتَّقْوَىٰٓ',
        english: 'or enjoined righteousness?',
        turkish: 'yahut takvayı emrettiyse?',
        source: 'Qur\'an 96:12',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'أمر',
        forms: [
          { label: 'mudari', arabic: 'يَأْمُرُ' },
          { label: 'masdar', arabic: 'أَمْر' },
        ],
        occurrences: 77,
        occurringForm: 'أَمَرَ',
      },
    },
    {
      id: 'jahannam',
      arabic: 'جَهَنَّم',
      english: 'Hell, Jahannam',
      turkish: 'cehennem',
      example: {
        arabic: 'إِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًۭا',
        english: 'Indeed, Hell has been lying in wait,',
        turkish: 'Şüphesiz cehennem bir gözetleme yeridir,',
        source: 'Qur\'an 78:21',
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 77,
        occurringForm: 'جَهَنَّمَ',
      },
    },
    {
      id: 'haya',
      arabic: 'حَياة',
      english: 'life',
      turkish: 'hayat, yaşam',
      example: {
        arabic: 'وَلَكُمْ فِى ٱلْقِصَاصِ حَيَوٰةٌۭ يَٰٓأُو۟لِى ٱلْأَلْبَٰبِ لَعَلَّكُمْ تَتَّقُونَ',
        english: 'And there is for you in legal retribution life, O people of understanding,',
        turkish: 'Ey akıl sahipleri, kısasta sizin için hayat vardır,',
        source: 'Qur\'an 2:179',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حيي',
        occurrences: 76,
        occurringForm: 'حَيَوٰةٌ',
      },
    },
    {
      id: 'dakhala',
      arabic: 'دَخَلَ',
      english: 'to enter',
      turkish: 'girmek',
      example: {
        arabic: 'قِيلَ ٱدْخُلِ ٱلْجَنَّةَ ۖ قَالَ يَٰلَيْتَ قَوْمِى يَعْلَمُونَ',
        english: 'It was said: Enter Paradise. He said: I wish my people could know,',
        turkish: 'Ona: Cennete gir, denildi. Dedi ki: Keşke kavmim bilseydi,',
        source: 'Qur\'an 36:26',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'دخل',
        forms: [
          { label: 'mudari', arabic: 'يَدْخُلُ' },
          { label: 'masdar', arabic: 'دُخُول' },
        ],
        occurrences: 76,
        occurringForm: 'ٱدْخُلِ',
      },
    },
    {
      id: 'dhikr',
      arabic: 'ذِكْر',
      english: 'remembrance, reminder',
      turkish: 'zikir, anma, öğüt',
      example: {
        arabic: 'فَٱلتَّٰلِيَٰتِ ذِكْرًا',
        english: 'and those who recite a reminder,',
        turkish: 'Bir zikir okuyanlara andolsun,',
        source: 'Qur\'an 37:3',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ذكر',
        occurrences: 76,
        occurringForm: 'ذِكْرًا',
      },
    },
    {
      id: 'zawj',
      arabic: 'زَوْج',
      english: 'spouse, pair, kind',
      turkish: 'eş, çift',
      example: {
        arabic: 'وَخَلَقْنَٰكُمْ أَزْوَٰجًۭا',
        english: 'And We created you in pairs,',
        turkish: 'Sizi çift çift yarattık,',
        source: 'Qur\'an 78:8',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'زوج',
        forms: [
          { label: 'plural', arabic: 'أَزْوَاج' },
        ],
        occurrences: 76,
        occurringForm: 'أَزْوَٰجًا',
      },
    },
    {
      id: 'akh',
      arabic: 'أَخ',
      english: 'brother',
      turkish: 'kardeş',
      example: {
        arabic: 'إِذْ قَالَ لَهُمْ أَخُوهُمْ نُوحٌ أَلَا تَتَّقُونَ',
        english: 'when their brother Noah said to them: Will you not fear Allah?',
        turkish: 'Kardeşleri Nuh onlara demişti ki: Sakınmaz mısınız?',
        source: 'Qur\'an 26:106',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أخو',
        forms: [
          { label: 'plural', arabic: 'إِخْوَة' },
        ],
        occurrences: 75,
        occurringForm: 'أَخُوهُمْ',
      },
    },
    {
      id: 'lawla',
      arabic: 'لَوْلا',
      english: 'if only, why not',
      turkish: 'keşke, olmasaydı, neden',
      example: {
        arabic: 'قَالَ أَوْسَطُهُمْ أَلَمْ أَقُل لَّكُمْ لَوْلَا تُسَبِّحُونَ',
        english: 'The most moderate of them said: Did I not say to you, why do you not glorify Allah?',
        turkish: 'İçlerinden en insaflısı dedi ki: Ben size, tesbih etseydiniz ya, demedim mi?',
        source: 'Qur\'an 68:28',
      },
      vocab: {
        partOfSpeech: 'harf',
        occurrences: 75,
        occurringForm: 'لَوْلَا',
      },
    },
    {
      id: 'mithl',
      arabic: 'مِثْل',
      english: 'like, similar to',
      turkish: 'gibi, benzeri',
      example: {
        arabic: 'بَلْ قَالُوا۟ مِثْلَ مَا قَالَ ٱلْأَوَّلُونَ',
        english: 'Rather, they say the like of what the former peoples said.',
        turkish: 'Aksine, öncekilerin dediği gibi dediler.',
        source: 'Qur\'an 23:81',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'مثل',
        occurrences: 75,
        occurringForm: 'مِثْلَ',
      },
    },
    {
      id: 'nabiyy',
      arabic: 'نَبِيّ',
      english: 'prophet',
      turkish: 'peygamber, nebi',
      example: {
        arabic: 'وَبَشَّرْنَٰهُ بِإِسْحَٰقَ نَبِيًّۭا مِّنَ ٱلصَّٰلِحِينَ',
        english: 'And We gave him good tidings of Isaac, a prophet from among the righteous.',
        turkish: 'Ona salihlerden bir peygamber olarak İshak’ı müjdeledik.',
        source: 'Qur\'an 37:112',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نبأ',
        forms: [
          { label: 'plural', arabic: 'أَنْبِيَاء' },
        ],
        occurrences: 75,
        occurringForm: 'نَبِيًّا',
      },
    },
    {
      id: 'ahad',
      arabic: 'أَحَد',
      english: 'one, anyone',
      turkish: 'bir, biri, hiç kimse',
      example: {
        arabic: 'وَلَا يُوثِقُ وَثَاقَهُۥٓ أَحَدٌۭ',
        english: 'And none will bind as He binds.',
        turkish: 'Onun bağladığı gibi kimse bağlayamaz.',
        source: 'Qur\'an 89:26',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أحد',
        occurrences: 74,
        occurringForm: 'أَحَدٌ',
      },
    },
    {
      id: 'khalid',
      arabic: 'خالِد',
      english: 'abiding, eternal',
      turkish: 'ebedi kalan, kalıcı',
      example: {
        arabic: 'خَٰلِدِينَ فِيهَا ۚ حَسُنَتْ مُسْتَقَرًّۭا وَمُقَامًۭا',
        english: 'abiding therein eternally. It is good as a settlement and residence.',
        turkish: 'Orada ebedi kalıcıdırlar. Ne güzel bir karargâh ve makamdır.',
        source: 'Qur\'an 25:76',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'خلد',
        forms: [
          { label: 'plural', arabic: 'خَالِدُون' },
        ],
        occurrences: 74,
        occurringForm: 'خَٰلِدِينَ',
      },
    },
    {
      id: 'salih',
      arabic: 'صالِح',
      english: 'righteous, sound; Salih',
      turkish: 'salih, iyi; Salih',
      example: {
        arabic: 'إِذْ قَالَ لَهُمْ أَخُوهُمْ صَٰلِحٌ أَلَا تَتَّقُونَ',
        english: 'when their brother Salih said to them: Will you not fear Allah?',
        turkish: 'Kardeşleri Salih onlara demişti ki: Sakınmaz mısınız?',
        source: 'Qur\'an 26:142',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'صلح',
        forms: [
          { label: 'plural', arabic: 'صَالِحُون' },
        ],
        occurrences: 74,
        occurringForm: 'صَٰلِحٌ',
      },
    },
    {
      id: 'firawn',
      arabic: 'فِرْعَوْن',
      english: 'Pharaoh',
      turkish: 'Firavun',
      example: {
        arabic: 'فِرْعَوْنَ وَثَمُودَ',
        english: 'Pharaoh and Thamud?',
        turkish: 'Firavun ve Semud’un?',
        source: 'Qur\'an 85:18',
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 74,
        occurringForm: 'فِرْعَوْنَ',
      },
    },
    {
      id: 'jazaa',
      arabic: 'جَزَى',
      english: 'to recompense, to repay',
      turkish: 'karşılık vermek, mükâfatlandırmak',
      example: {
        arabic: 'كَذَٰلِكَ نَجْزِى ٱلْمُحْسِنِينَ',
        english: 'Indeed, We thus reward the doers of good.',
        turkish: 'İşte biz iyilik yapanları böyle mükâfatlandırırız.',
        source: 'Qur\'an 37:110',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'جزي',
        forms: [
          { label: 'mudari', arabic: 'يَجْزِي' },
          { label: 'masdar', arabic: 'جَزَاء' },
        ],
        occurrences: 73,
        occurringForm: 'نَجْزِى',
      },
    },
    {
      id: 'alam',
      arabic: 'عالَم',
      english: 'world; (pl.) all creation',
      turkish: 'âlem, dünya; âlemler',
      example: {
        arabic: 'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ',
        english: 'All praise is due to Allah, Lord of the worlds,',
        turkish: 'Hamd, âlemlerin Rabbi Allah’a mahsustur,',
        source: 'Qur\'an 1:2',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'علم',
        forms: [
          { label: 'plural', arabic: 'عَالَمُون' },
        ],
        occurrences: 73,
        occurringForm: 'ٱلْعَٰلَمِينَ',
      },
    },
    {
      id: 'ataa-2',
      arabic: 'أَطاعَ',
      english: 'to obey',
      turkish: 'itaat etmek',
      example: {
        arabic: 'فَلَا تُطِعِ ٱلْمُكَذِّبِينَ',
        english: 'So do not obey the deniers.',
        turkish: 'Yalanlayanlara itaat etme.',
        source: 'Qur\'an 68:8',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'طوع',
        forms: [
          { label: 'mudari', arabic: 'يُطِيعُ' },
          { label: 'masdar', arabic: 'طَاعَة' },
        ],
        occurrences: 72,
        occurringForm: 'تُطِعِ',
      },
    },
    {
      id: 'aliym',
      arabic: 'أَلِيم',
      english: 'painful',
      turkish: 'acıklı, elem verici',
      example: {
        arabic: 'فَبَشِّرْهُم بِعَذَابٍ أَلِيمٍ',
        english: 'So give them tidings of a painful punishment,',
        turkish: 'Onlara acıklı bir azabı müjdele,',
        source: 'Qur\'an 84:24',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ألم',
        occurrences: 72,
        occurringForm: 'أَلِيمٍ',
      },
    },
    {
      id: 'awhaa',
      arabic: 'أَوْحَى',
      english: 'to reveal, to inspire',
      turkish: 'vahyetmek, ilham etmek',
      example: {
        arabic: 'بِأَنَّ رَبَّكَ أَوْحَىٰ لَهَا',
        english: 'because your Lord has inspired it.',
        turkish: 'Çünkü Rabbin ona vahyetmiştir.',
        source: 'Qur\'an 99:5',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'وحي',
        forms: [
          { label: 'mudari', arabic: 'يُوحِي' },
          { label: 'masdar', arabic: 'وَحْي' },
        ],
        occurrences: 72,
        occurringForm: 'أَوْحَىٰ',
      },
    },
    {
      id: 'wajh',
      arabic: 'وَجْه',
      english: 'face',
      turkish: 'yüz',
      example: {
        arabic: 'وُجُوهٌۭ يَوْمَئِذٍۢ مُّسْفِرَةٌۭ',
        english: 'Some faces, that Day, will be bright,',
        turkish: 'O gün birtakım yüzler parıldar,',
        source: 'Qur\'an 80:38',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'وجه',
        forms: [
          { label: 'plural', arabic: 'وُجُوه' },
        ],
        occurrences: 72,
        occurringForm: 'وُجُوهٌ',
      },
    },
    {
      id: 'ashraka',
      arabic: 'أَشْرَكَ',
      english: 'to associate partners (with Allah)',
      turkish: 'ortak koşmak, şirk koşmak',
      example: {
        arabic: 'لَّٰكِنَّا۠ هُوَ ٱللَّهُ رَبِّى وَلَآ أُشْرِكُ بِرَبِّىٓ أَحَدًۭا',
        english: 'But as for me, He is Allah, my Lord, and I do not associate anyone with my Lord.',
        turkish: 'Fakat O, benim Rabbim olan Allah’tır ve ben Rabbime hiç kimseyi ortak koşmam.',
        source: 'Qur\'an 18:38',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'شرك',
        forms: [
          { label: 'mudari', arabic: 'يُشْرِكُ' },
          { label: 'masdar', arabic: 'إِشْرَاك' },
        ],
        occurrences: 71,
        occurringForm: 'أُشْرِكُ',
      },
    },
    {
      id: 'alqaa',
      arabic: 'أَلْقَى',
      english: 'to cast, to throw, to present',
      turkish: 'atmak, bırakmak, ortaya koymak',
      example: {
        arabic: 'وَلَوْ أَلْقَىٰ مَعَاذِيرَهُۥ',
        english: 'even if he presents his excuses.',
        turkish: 'Mazeretlerini ortaya koysa da.',
        source: 'Qur\'an 75:15',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'لقي',
        forms: [
          { label: 'mudari', arabic: 'يُلْقِي' },
          { label: 'masdar', arabic: 'إِلْقَاء' },
        ],
        occurrences: 71,
        occurringForm: 'أَلْقَىٰ',
      },
    },
    {
      id: 'insan',
      arabic: 'إِنسان',
      english: 'human being, man',
      turkish: 'insan',
      example: {
        arabic: 'خَلَقَ ٱلْإِنسَٰنَ',
        english: 'He created man,',
        turkish: 'İnsanı yarattı,',
        source: 'Qur\'an 55:3',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أنس',
        occurrences: 71,
        occurringForm: 'ٱلْإِنسَٰنَ',
      },
    },
    {
      id: 'bayyina',
      arabic: 'بَيِّنَة',
      english: 'clear proof, evidence',
      turkish: 'apaçık delil, beyyine',
      example: {
        arabic: 'وَلَقَد تَّرَكْنَا مِنْهَآ ءَايَةًۢ بَيِّنَةًۭ لِّقَوْمٍۢ يَعْقِلُونَ',
        english: 'And We have left of it a clear sign for a people who use reason.',
        turkish: 'Andolsun ki ondan, akleden bir topluluk için apaçık bir delil bıraktık.',
        source: 'Qur\'an 29:35',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بين',
        forms: [
          { label: 'plural', arabic: 'بَيِّنَات' },
        ],
        occurrences: 71,
        occurringForm: 'بَيِّنَةً',
      },
    },
  ],
}
