import type { DeckDef } from '../types'

// Quran Vocabulary, level 4. See GitHub issue #8.
//
// Scaffolded by scripts/generateVocab.ts and then authored by hand, as the
// earlier levels were.
//
// Same lemma-form renames as level 3: araa, tawakkala, bashshara, asaa,
// hazina, dhaqa.
//
// DRAFT: verify every English meaning before memorizing it. Turkish is
// generated convenience text and stays draft - correct it on sight while
// studying.
//
// Locked until the previous level is mostly graduated; see quranVocabTrack.ts.

export const quranVocab4: DeckDef = {
  id: 'quran-vocab-4',
  name: 'Quran Vocabulary 4',
  nameArabic: 'مُفْرَدَاتُ الْقُرْآنِ ٤',
  description:
    'Frequency band 4 of the Quran vocabulary track, each word with an ayah where it occurs.',
  directions: ['ar-to-meaning'],
  newPerDay: 10,
  burySiblings: true,
  notes: [
    {
      id: 'kalima',
      arabic: 'كَلِمَة',
      english: 'word',
      turkish: 'kelime, söz',
      example: {
        arabic: 'وَجَعَلَهَا كَلِمَةًۢ بَاقِيَةًۭ فِى عَقِبِهِۦ لَعَلَّهُمْ يَرْجِعُونَ',
        english: 'And he made it a word remaining among his descendants that they might return.',
        turkish: 'Onu, dönsünler diye ardından gelenler arasında kalıcı bir söz yaptı.',
        source: 'Qur\'an 43:28',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كلم',
        forms: [
          { label: 'plural', arabic: 'كَلِمَات' },
        ],
        occurrences: 42,
        occurringForm: 'كَلِمَةًۢ',
      },
    },
    {
      id: 'bahr',
      arabic: 'بَحْر',
      english: 'sea',
      turkish: 'deniz',
      example: {
        arabic: 'وَإِذَا ٱلْبِحَارُ سُجِّرَتْ',
        english: 'And when the seas are filled with flame,',
        turkish: 'Denizler kaynatıldığı zaman,',
        source: 'Qur\'an 81:6',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بحر',
        forms: [
          { label: 'plural', arabic: 'بِحَار' },
        ],
        occurrences: 41,
        occurringForm: 'ٱلْبِحَارُ',
      },
    },
    {
      id: 'hamala',
      arabic: 'حَمَلَ',
      english: 'to carry, to bear',
      turkish: 'taşımak, yüklenmek',
      example: {
        arabic: 'مَّنْ أَعْرَضَ عَنْهُ فَإِنَّهُۥ يَحْمِلُ يَوْمَ ٱلْقِيَٰمَةِ وِزْرًا',
        english: 'Whoever turns away from it — indeed, he will bear a burden on the Day of Resurrection.',
        turkish: 'Kim ondan yüz çevirirse, kıyamet günü bir günah yükü taşır.',
        source: 'Qur\'an 20:100',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حمل',
        forms: [
          { label: 'mudari', arabic: 'يَحْمِلُ' },
          { label: 'masdar', arabic: 'حَمْل' },
        ],
        occurrences: 41,
        occurringForm: 'يَحْمِلُ',
      },
    },
    {
      id: 'subhan',
      arabic: 'سُبْحان',
      english: 'glory be to, exalted is',
      turkish: 'tesbih, münezzeh olma',
      example: {
        arabic: 'سُبْحَٰنَ ٱللَّهِ عَمَّا يَصِفُونَ',
        english: 'Exalted is Allah above what they describe,',
        turkish: 'Allah, onların nitelemelerinden münezzehtir,',
        source: 'Qur\'an 37:159',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سبح',
        occurrences: 41,
        occurringForm: 'سُبْحَٰنَ',
      },
    },
    {
      id: 'adhdhaba',
      arabic: 'عَذَّبَ',
      english: 'to punish, to torment',
      turkish: 'azap etmek',
      example: {
        arabic: 'فَيَوْمَئِذٍۢ لَّا يُعَذِّبُ عَذَابَهُۥٓ أَحَدٌۭ',
        english: 'So on that Day, none will punish as He punishes,',
        turkish: 'O gün hiç kimse O’nun azabı gibi azap edemez,',
        source: 'Qur\'an 89:25',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عذب',
        forms: [
          { label: 'mudari', arabic: 'يُعَذِّبُ' },
          { label: 'masdar', arabic: 'تَعْذِيب' },
        ],
        occurrences: 41,
        occurringForm: 'يُعَذِّبُ',
      },
    },
    {
      id: 'fawq',
      arabic: 'فَوْق',
      english: 'above, over',
      turkish: 'üstünde, üzerinde',
      example: {
        arabic: 'وَهُوَ ٱلْقَاهِرُ فَوْقَ عِبَادِهِۦ ۚ وَهُوَ ٱلْحَكِيمُ ٱلْخَبِيرُ',
        english: 'And He is the subjugator over His servants, and He is the Wise, the Aware.',
        turkish: 'O, kullarının üstünde mutlak hâkimdir; hikmet sahibidir, her şeyden haberdardır.',
        source: 'Qur\'an 6:18',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'فوق',
        occurrences: 41,
        occurringForm: 'فَوْقَ',
      },
    },
    {
      id: 'araa',
      arabic: 'أَرَيْ',
      english: 'to show',
      turkish: 'göstermek',
      example: {
        arabic: 'وَكَذَٰلِكَ نُرِىٓ إِبْرَٰهِيمَ مَلَكُوتَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ وَلِيَكُونَ مِنَ ٱلْمُوقِنِينَ',
        english: 'And thus did We show Abraham the realm of the heavens and the earth, that he would be among the certain in faith.',
        turkish: 'Böylece İbrahim’e göklerin ve yerin melekûtunu gösterdik ki kesin inananlardan olsun.',
        source: 'Qur\'an 6:75',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'رأي',
        forms: [
          { label: 'mudari', arabic: 'يُرِي' },
        ],
        occurrences: 40,
        occurringForm: 'نُرِىٓ',
      },
    },
    {
      id: 'astaghfara',
      arabic: 'اسْتَغْفَرَ',
      english: 'to seek forgiveness',
      turkish: 'bağışlanma dilemek, istiğfar etmek',
      example: {
        arabic: 'قَالُوا۟ يَٰٓأَبَانَا ٱسْتَغْفِرْ لَنَا ذُنُوبَنَآ إِنَّا كُنَّا خَٰطِـِٔينَ',
        english: 'They said: O our father, ask forgiveness for us of our sins; indeed, we have been sinners.',
        turkish: 'Dediler ki: Ey babamız, günahlarımız için bağışlanma dile; biz gerçekten hata edenlerdik.',
        source: 'Qur\'an 12:97',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'غفر',
        forms: [
          { label: 'mudari', arabic: 'يَسْتَغْفِرُ' },
          { label: 'masdar', arabic: 'اِسْتِغْفَار' },
        ],
        occurrences: 40,
        occurringForm: 'ٱسْتَغْفِرْ',
      },
    },
    {
      id: 'astakbara',
      arabic: 'اسْتَكْبَرَ',
      english: 'to be arrogant, to scorn',
      turkish: 'büyüklenmek, kibirlenmek',
      example: {
        arabic: 'إِلَّآ إِبْلِيسَ ٱسْتَكْبَرَ وَكَانَ مِنَ ٱلْكَٰفِرِينَ',
        english: 'except Iblis; he was arrogant and became among the disbelievers.',
        turkish: 'İblis hariç; büyüklendi ve kâfirlerden oldu.',
        source: 'Qur\'an 38:74',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'كبر',
        forms: [
          { label: 'mudari', arabic: 'يَسْتَكْبِرُ' },
          { label: 'masdar', arabic: 'اِسْتِكْبَار' },
        ],
        occurrences: 40,
        occurringForm: 'ٱسْتَكْبَرَ',
      },
    },
    {
      id: 'ahtadaa',
      arabic: 'اهْتَدَى',
      english: 'to be guided, to find the way',
      turkish: 'hidayete ermek, doğru yolu bulmak',
      example: {
        arabic: 'وَإِنِّى لَغَفَّارٌۭ لِّمَن تَابَ وَءَامَنَ وَعَمِلَ صَٰلِحًۭا ثُمَّ ٱهْتَدَىٰ',
        english: 'But indeed, I am the Perpetual Forgiver of whoever repents and believes and does righteousness and then continues in guidance.',
        turkish: 'Şüphesiz ben, tövbe eden, iman edip salih amel işleyen, sonra doğru yolda devam edeni çokça bağışlarım.',
        source: 'Qur\'an 20:82',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'هدي',
        forms: [
          { label: 'mudari', arabic: 'يَهْتَدِي' },
        ],
        occurrences: 40,
        occurringForm: 'ٱهْتَدَىٰ',
      },
    },
    {
      id: 'bisa',
      arabic: 'بِئْسَ',
      english: 'wretched is, evil is',
      turkish: 'ne kötü',
      example: {
        arabic: 'وَأُتْبِعُوا۟ فِى هَٰذِهِۦ لَعْنَةًۭ وَيَوْمَ ٱلْقِيَٰمَةِ ۚ بِئْسَ ٱلرِّفْدُ ٱلْمَرْفُودُ',
        english: 'And they were followed in this world with a curse and on the Day of Resurrection. Wretched is the gift which is given.',
        turkish: 'Bu dünyada da kıyamet gününde de lanete uğratıldılar. Verilen bu bağış ne kötüdür.',
        source: 'Qur\'an 11:99',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بأس',
        occurrences: 40,
        occurringForm: 'بِئْسَ',
      },
    },
    {
      id: 'balagha',
      arabic: 'بَلَغَ',
      english: 'to reach, to attain',
      turkish: 'ulaşmak, erişmek',
      example: {
        arabic: 'فَلَوْلَآ إِذَا بَلَغَتِ ٱلْحُلْقُومَ',
        english: 'Then why, when the soul at death reaches the throat,',
        turkish: 'Can boğaza geldiğinde,',
        source: 'Qur\'an 56:83',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بلغ',
        forms: [
          { label: 'mudari', arabic: 'يَبْلُغُ' },
          { label: 'masdar', arabic: 'بُلُوغ' },
        ],
        occurrences: 40,
        occurringForm: 'بَلَغَتِ',
      },
    },
    {
      id: 'taraka',
      arabic: 'تَرَكَ',
      english: 'to leave, to abandon',
      turkish: 'bırakmak, terk etmek',
      example: {
        arabic: 'أَيَحْسَبُ ٱلْإِنسَٰنُ أَن يُتْرَكَ سُدًى',
        english: 'Does man think that he will be left neglected?',
        turkish: 'İnsan başıboş bırakılacağını mı sanıyor?',
        source: 'Qur\'an 75:36',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ترك',
        forms: [
          { label: 'mudari', arabic: 'يَتْرُكُ' },
          { label: 'masdar', arabic: 'تَرْك' },
        ],
        occurrences: 40,
        occurringForm: 'يُتْرَكَ',
      },
    },
    {
      id: 'tawakkala',
      arabic: 'تَوَكَّلْ',
      english: 'to put one’s trust in',
      turkish: 'tevekkül etmek, güvenmek',
      example: {
        arabic: 'وَتَوَكَّلْ عَلَى ٱلْعَزِيزِ ٱلرَّحِيمِ',
        english: 'And rely upon the Exalted in Might, the Merciful,',
        turkish: 'Üstün ve merhametli olana güvenip dayan,',
        source: 'Qur\'an 26:217',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'وكل',
        forms: [
          { label: 'mudari', arabic: 'يَتَوَكَّلُ' },
          { label: 'masdar', arabic: 'تَوَكُّل' },
        ],
        occurrences: 40,
        occurringForm: 'وَتَوَكَّلْ',
      },
    },
    {
      id: 'khashiya',
      arabic: 'خَشِيَ',
      english: 'to fear, to stand in awe',
      turkish: 'korkmak, haşyet duymak',
      example: {
        arabic: 'وَهُوَ يَخْشَىٰ',
        english: 'while he fears Allah,',
        turkish: 've o korkarak gelmişken,',
        source: 'Qur\'an 80:9',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'خشي',
        forms: [
          { label: 'mudari', arabic: 'يَخْشَى' },
          { label: 'masdar', arabic: 'خَشْيَة' },
        ],
        occurrences: 40,
        occurringForm: 'يَخْشَىٰ',
      },
    },
    {
      id: 'shariyk',
      arabic: 'شَرِيك',
      english: 'partner, associate',
      turkish: 'ortak, şerik',
      example: {
        arabic: 'لَا شَرِيكَ لَهُۥ ۖ وَبِذَٰلِكَ أُمِرْتُ وَأَنَا۠ أَوَّلُ ٱلْمُسْلِمِينَ',
        english: 'He has no partner. And this I have been commanded, and I am the first of the Muslims.',
        turkish: 'O’nun ortağı yoktur. Bana bu emredildi ve ben müslümanların ilkiyim.',
        source: 'Qur\'an 6:163',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'شرك',
        forms: [
          { label: 'plural', arabic: 'شُرَكَاء' },
        ],
        occurrences: 40,
        occurringForm: 'شَرِيكَ',
      },
    },
    {
      id: 'kabiyr',
      arabic: 'كَبِير',
      english: 'great, big',
      turkish: 'büyük',
      example: {
        arabic: 'سُبْحَٰنَهُۥ وَتَعَٰلَىٰ عَمَّا يَقُولُونَ عُلُوًّۭا كَبِيرًۭا',
        english: 'Exalted is He and high above what they say by great sublimity.',
        turkish: 'O, onların söylediklerinden münezzeh ve çok yücedir.',
        source: 'Qur\'an 17:43',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'كبر',
        forms: [
          { label: 'plural', arabic: 'كِبَار' },
        ],
        occurrences: 40,
        occurringForm: 'كَبِيرًا',
      },
    },
    {
      id: 'wayl',
      arabic: 'وَيْل',
      english: 'woe',
      turkish: 'vay haline, yazıklar olsun',
      example: {
        arabic: 'وَيْلٌۭ لِّلْمُطَفِّفِينَ',
        english: 'Woe to those who give less than due,',
        turkish: 'Ölçüde ve tartıda hile yapanların vay haline,',
        source: 'Qur\'an 83:1',
      },
      vocab: {
        partOfSpeech: 'ism',
        occurrences: 40,
        occurringForm: 'وَيْلٌ',
      },
    },
    {
      id: 'idhn',
      arabic: 'إِذْن',
      english: 'permission, leave',
      turkish: 'izin',
      example: {
        arabic: 'تَنَزَّلُ ٱلْمَلَٰٓئِكَةُ وَٱلرُّوحُ فِيهَا بِإِذْنِ رَبِّهِم مِّن كُلِّ أَمْرٍۢ',
        english: 'The angels and the Spirit descend therein by permission of their Lord for every matter.',
        turkish: 'Melekler ve Ruh, Rablerinin izniyle her iş için orada iner.',
        source: 'Qur\'an 97:4',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أذن',
        occurrences: 39,
        occurringForm: 'بِإِذْنِ',
      },
    },
    {
      id: 'asm',
      arabic: 'اسْم',
      english: 'name',
      turkish: 'isim, ad',
      example: {
        arabic: 'سَبِّحِ ٱسْمَ رَبِّكَ ٱلْأَعْلَى',
        english: 'Exalt the name of your Lord, the Most High,',
        turkish: 'Yüce Rabbinin adını tesbih et,',
        source: 'Qur\'an 87:1',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سمو',
        forms: [
          { label: 'plural', arabic: 'أَسْمَاء' },
        ],
        occurrences: 39,
        occurringForm: 'ٱسْمَ',
      },
    },
    {
      id: 'jabal',
      arabic: 'جَبَل',
      english: 'mountain',
      turkish: 'dağ',
      example: {
        arabic: 'وَإِذَا ٱلْجِبَالُ سُيِّرَتْ',
        english: 'And when the mountains are removed,',
        turkish: 'Dağlar yürütüldüğü zaman,',
        source: 'Qur\'an 81:3',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'جبل',
        forms: [
          { label: 'plural', arabic: 'جِبَال' },
        ],
        occurrences: 39,
        occurringForm: 'ٱلْجِبَالُ',
      },
    },
    {
      id: 'harrama',
      arabic: 'حَرَّمَ',
      english: 'to forbid, to make unlawful',
      turkish: 'haram kılmak, yasaklamak',
      example: {
        arabic: 'يَٰٓأَيُّهَا ٱلنَّبِىُّ لِمَ تُحَرِّمُ مَآ أَحَلَّ ٱللَّهُ لَكَ ۖ تَبْتَغِى مَرْضَاتَ أَزْوَٰجِكَ ۚ وَٱللَّهُ غَفُورٌۭ رَّحِيمٌۭ',
        english: 'O Prophet, why do you prohibit what Allah has made lawful for you, seeking the approval of your wives? And Allah is Forgiving and Merciful.',
        turkish: 'Ey Peygamber! Eşlerinin rızasını arayarak, Allah’ın sana helâl kıldığını niçin haram kılıyorsun? Allah bağışlayandır, merhamet edendir.',
        source: 'Qur\'an 66:1',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حرم',
        forms: [
          { label: 'mudari', arabic: 'يُحَرِّمُ' },
          { label: 'masdar', arabic: 'تَحْرِيم' },
        ],
        occurrences: 39,
        occurringForm: 'تُحَرِّمُ',
      },
    },
    {
      id: 'hisab',
      arabic: 'حِساب',
      english: 'reckoning, account',
      turkish: 'hesap',
      example: {
        arabic: 'فَسَوْفَ يُحَاسَبُ حِسَابًۭا يَسِيرًۭا',
        english: 'he will be judged with an easy account,',
        turkish: 'kolay bir hesapla sorguya çekilecek,',
        source: 'Qur\'an 84:8',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حسب',
        occurrences: 39,
        occurringForm: 'حِسَابًا',
      },
    },
    {
      id: 'mata',
      arabic: 'ماتَ',
      english: 'to die',
      turkish: 'ölmek',
      example: {
        arabic: 'ثُمَّ لَا يَمُوتُ فِيهَا وَلَا يَحْيَىٰ',
        english: 'Then he will neither die therein nor live.',
        turkish: 'Sonra orada ne ölür ne de yaşar.',
        source: 'Qur\'an 87:13',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'موت',
        forms: [
          { label: 'mudari', arabic: 'يَمُوتُ' },
          { label: 'masdar', arabic: 'مَوْت' },
        ],
        occurrences: 39,
        occurringForm: 'يَمُوتُ',
      },
    },
    {
      id: 'muslim',
      arabic: 'مُسْلِم',
      english: 'one who submits, Muslim',
      turkish: 'müslüman, teslim olan',
      example: {
        arabic: 'أَلَّا تَعْلُوا۟ عَلَىَّ وَأْتُونِى مُسْلِمِينَ',
        english: 'Be not haughty with me but come to me in submission.',
        turkish: 'Bana karşı büyüklük taslamayın ve teslim olarak bana gelin.',
        source: 'Qur\'an 27:31',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سلم',
        forms: [
          { label: 'plural', arabic: 'مُسْلِمُون' },
        ],
        occurrences: 39,
        occurringForm: 'مُسْلِمِينَ',
      },
    },
    {
      id: 'bashshara',
      arabic: 'بُشِّرَ',
      english: 'to give good tidings',
      turkish: 'müjdelemek',
      example: {
        arabic: 'بَشِّرِ ٱلْمُنَٰفِقِينَ بِأَنَّ لَهُمْ عَذَابًا أَلِيمًا',
        english: 'Give tidings to the hypocrites that there is for them a painful punishment,',
        turkish: 'Münafıklara, kendileri için acıklı bir azap olduğunu müjdele,',
        source: 'Qur\'an 4:138',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'بشر',
        forms: [
          { label: 'mudari', arabic: 'يُبَشِّرُ' },
          { label: 'masdar', arabic: 'تَبْشِير' },
        ],
        occurrences: 38,
        occurringForm: 'بَشِّرِ',
      },
    },
    {
      id: 'radiya',
      arabic: 'رَضِيَ',
      english: 'to be pleased, to be content',
      turkish: 'razı olmak, hoşnut olmak',
      example: {
        arabic: 'وَلَسَوْفَ يَرْضَىٰ',
        english: 'And he is going to be satisfied.',
        turkish: 'Ve elbette hoşnut olacaktır.',
        source: 'Qur\'an 92:21',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'رضو',
        forms: [
          { label: 'mudari', arabic: 'يَرْضَى' },
          { label: 'masdar', arabic: 'رِضَا' },
        ],
        occurrences: 38,
        occurringForm: 'يَرْضَىٰ',
      },
    },
    {
      id: 'dalal',
      arabic: 'ضَلال',
      english: 'error, misguidance',
      turkish: 'sapkınlık, dalâlet',
      example: {
        arabic: 'إِنِّىٓ إِذًۭا لَّفِى ضَلَٰلٍۢ مُّبِينٍ',
        english: 'Indeed, I would then be in manifest error.',
        turkish: 'O zaman ben apaçık bir sapıklık içinde olurum.',
        source: 'Qur\'an 36:24',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ضلل',
        occurrences: 38,
        occurringForm: 'ضَلَٰلٍ',
      },
    },
    {
      id: 'muhsin',
      arabic: 'مُحْسِن',
      english: 'doer of good',
      turkish: 'iyilik yapan, muhsin',
      example: {
        arabic: 'إِنَّ ٱللَّهَ مَعَ ٱلَّذِينَ ٱتَّقَوا۟ وَّٱلَّذِينَ هُم مُّحْسِنُونَ',
        english: 'Indeed, Allah is with those who fear Him and those who are doers of good.',
        turkish: 'Şüphesiz Allah, sakınanlarla ve iyilik yapanlarla beraberdir.',
        source: 'Qur\'an 16:128',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حسن',
        forms: [
          { label: 'plural', arabic: 'مُحْسِنُون' },
        ],
        occurrences: 38,
        occurringForm: 'مُّحْسِنُونَ',
      },
    },
    {
      id: 'maruwf',
      arabic: 'مَعْرُوف',
      english: 'what is right, kindness',
      turkish: 'iyilik, maruf',
      example: {
        arabic: '۞ قَوْلٌۭ مَّعْرُوفٌۭ وَمَغْفِرَةٌ خَيْرٌۭ مِّن صَدَقَةٍۢ يَتْبَعُهَآ أَذًۭى ۗ وَٱللَّهُ غَنِىٌّ حَلِيمٌۭ',
        english: 'Kind speech and forgiveness are better than charity followed by injury. And Allah is Free of need and Forbearing.',
        turkish: 'Güzel bir söz ve bağışlama, ardından eziyet gelen bir sadakadan hayırlıdır. Allah zengindir, halîmdir.',
        source: 'Qur\'an 2:263',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'عرف',
        occurrences: 38,
        occurringForm: 'مَّعْرُوفٌ',
      },
    },
    {
      id: 'mayyit',
      arabic: 'مَيِّت',
      english: 'dead, mortal',
      turkish: 'ölü, ölümlü',
      example: {
        arabic: 'إِنَّكَ مَيِّتٌۭ وَإِنَّهُم مَّيِّتُونَ',
        english: 'Indeed, you are to die, and indeed, they are to die.',
        turkish: 'Şüphesiz sen de öleceksin, onlar da ölecekler.',
        source: 'Qur\'an 39:30',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'موت',
        forms: [
          { label: 'plural', arabic: 'مَيِّتُون' },
        ],
        occurrences: 38,
        occurringForm: 'مَيِّتٌ',
      },
    },
    {
      id: 'bashar',
      arabic: 'بَشَر',
      english: 'human being, mortal',
      turkish: 'insan, beşer',
      example: {
        arabic: 'وَلَئِنْ أَطَعْتُم بَشَرًۭا مِّثْلَكُمْ إِنَّكُمْ إِذًۭا لَّخَٰسِرُونَ',
        english: 'And if you obey a human being like yourselves, indeed you would then be losers.',
        turkish: 'Kendiniz gibi bir insana itaat ederseniz, şüphesiz o zaman ziyana uğrarsınız.',
        source: 'Qur\'an 23:34',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'بشر',
        occurrences: 37,
        occurringForm: 'بَشَرًا',
      },
    },
    {
      id: 'hashara',
      arabic: 'حَشَرَ',
      english: 'to gather, to assemble',
      turkish: 'toplamak, haşretmek',
      example: {
        arabic: 'وَإِذَا ٱلْوُحُوشُ حُشِرَتْ',
        english: 'And when the wild beasts are gathered,',
        turkish: 'Vahşi hayvanlar toplandığı zaman,',
        source: 'Qur\'an 81:5',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حشر',
        forms: [
          { label: 'mudari', arabic: 'يَحْشُرُ' },
          { label: 'masdar', arabic: 'حَشْر' },
        ],
        occurrences: 37,
        occurringForm: 'حُشِرَتْ',
      },
    },
    {
      id: 'dhanb',
      arabic: 'ذَنب',
      english: 'sin, offence',
      turkish: 'günah, suç',
      example: {
        arabic: 'بِأَىِّ ذَنۢبٍۢ قُتِلَتْ',
        english: 'For what sin she was killed?',
        turkish: 'Hangi günah sebebiyle öldürüldü diye?',
        source: 'Qur\'an 81:9',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'ذنب',
        forms: [
          { label: 'plural', arabic: 'ذُنُوب' },
        ],
        occurrences: 37,
        occurringForm: 'ذَنۢبٍ',
      },
    },
    {
      id: 'sultan',
      arabic: 'سُلْطان',
      english: 'authority, clear proof',
      turkish: 'delil, yetki, sultan',
      example: {
        arabic: 'أَمْ لَكُمْ سُلْطَٰنٌۭ مُّبِينٌۭ',
        english: 'Or do you have a clear authority?',
        turkish: 'Yoksa sizin apaçık bir deliliniz mi var?',
        source: 'Qur\'an 37:156',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'سلط',
        occurrences: 37,
        occurringForm: 'سُلْطَٰنٌ',
      },
    },
    {
      id: 'sadda',
      arabic: 'صَدَّ',
      english: 'to turn away, to bar',
      turkish: 'yüz çevirmek, engellemek',
      example: {
        arabic: 'فَمِنْهُم مَّنْ ءَامَنَ بِهِۦ وَمِنْهُم مَّن صَدَّ عَنْهُ ۚ وَكَفَىٰ بِجَهَنَّمَ سَعِيرًا',
        english: 'And some among them believed in it, and some among them turned away from it. And sufficient is Hell as a blaze.',
        turkish: 'Onlardan kimi ona inandı, kimi de ondan yüz çevirdi. Çılgın ateş olarak cehennem yeter.',
        source: 'Qur\'an 4:55',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'صدد',
        forms: [
          { label: 'mudari', arabic: 'يَصُدُّ' },
          { label: 'masdar', arabic: 'صَدّ' },
        ],
        occurrences: 37,
        occurringForm: 'صَدَّ',
      },
    },
    {
      id: 'asaa',
      arabic: 'عَصا',
      english: 'to disobey',
      turkish: 'isyan etmek, karşı gelmek',
      example: {
        arabic: 'قَالَ سَتَجِدُنِىٓ إِن شَآءَ ٱللَّهُ صَابِرًۭا وَلَآ أَعْصِى لَكَ أَمْرًۭا',
        english: 'He said: You will find me, if Allah wills, patient, and I will not disobey you in any order.',
        turkish: 'Dedi ki: İnşallah beni sabırlı bulacaksın ve senin hiçbir işine karşı gelmeyeceğim.',
        source: 'Qur\'an 18:69',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'عصو',
        forms: [
          { label: 'mudari', arabic: 'يَعْصِي' },
          { label: 'masdar', arabic: 'مَعْصِيَة' },
        ],
        occurrences: 37,
        occurringForm: 'أَعْصِى',
      },
    },
    {
      id: 'fasiq',
      arabic: 'فاسِق',
      english: 'defiantly disobedient, rebellious',
      turkish: 'fâsık, yoldan çıkmış',
      example: {
        arabic: 'فَٱسْتَخَفَّ قَوْمَهُۥ فَأَطَاعُوهُ ۚ إِنَّهُمْ كَانُوا۟ قَوْمًۭا فَٰسِقِينَ',
        english: 'So he bluffed his people, and they obeyed him. Indeed, they were a people defiantly disobedient.',
        turkish: 'Kavmini küçümsedi, onlar da ona itaat ettiler. Şüphesiz onlar yoldan çıkmış bir kavimdi.',
        source: 'Qur\'an 43:54',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'فسق',
        forms: [
          { label: 'plural', arabic: 'فَاسِقُون' },
        ],
        occurrences: 37,
        occurringForm: 'فَٰسِقِينَ',
      },
    },
    {
      id: 'mustaqiym',
      arabic: 'مُسْتَقِيم',
      english: 'straight',
      turkish: 'dosdoğru, düz',
      example: {
        arabic: 'وَلَهَدَيْنَٰهُمْ صِرَٰطًۭا مُّسْتَقِيمًۭا',
        english: 'and We would have guided them to a straight path.',
        turkish: 've onları dosdoğru bir yola iletirdik.',
        source: 'Qur\'an 4:68',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'قوم',
        occurrences: 37,
        occurringForm: 'مُّسْتَقِيمًا',
      },
    },
    {
      id: 'najjaa',
      arabic: 'نَجَّى',
      english: 'to save, to deliver',
      turkish: 'kurtarmak',
      example: {
        arabic: 'ثُمَّ نُنَجِّى ٱلَّذِينَ ٱتَّقَوا۟ وَّنَذَرُ ٱلظَّٰلِمِينَ فِيهَا جِثِيًّۭا',
        english: 'Then We will save those who feared Allah and leave the wrongdoers within it, on their knees.',
        turkish: 'Sonra sakınanları kurtarırız ve zalimleri orada diz üstü çökmüş halde bırakırız.',
        source: 'Qur\'an 19:72',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'نجو',
        forms: [
          { label: 'mudari', arabic: 'يُنَجِّي' },
          { label: 'masdar', arabic: 'تَنْجِيَة' },
        ],
        occurrences: 37,
        occurringForm: 'نُنَجِّى',
      },
    },
    {
      id: 'naam',
      arabic: 'نَعَم',
      english: 'yes',
      turkish: 'evet',
      example: {
        arabic: 'قُلْ نَعَمْ وَأَنتُمْ دَٰخِرُونَ',
        english: 'Say: Yes, and you will be humbled.',
        turkish: 'De ki: Evet, hem de siz aşağılanmış olarak.',
        source: 'Qur\'an 37:18',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'نعم',
        occurrences: 37,
        occurringForm: 'نَعَمْ',
      },
    },
    {
      id: 'hazina',
      arabic: 'يَحْزُن',
      english: 'to grieve, to be sad',
      turkish: 'üzülmek, hüzünlenmek',
      example: {
        arabic: 'وَلَا تَحْزَنْ عَلَيْهِمْ وَلَا تَكُن فِى ضَيْقٍۢ مِّمَّا يَمْكُرُونَ',
        english: 'And grieve not over them, and be not distressed by what they conspire.',
        turkish: 'Onlara üzülme ve kurdukları tuzaklardan dolayı sıkıntıya düşme.',
        source: 'Qur\'an 27:70',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'حزن',
        forms: [
          { label: 'mudari', arabic: 'يَحْزَنُ' },
          { label: 'masdar', arabic: 'حُزْن' },
        ],
        occurrences: 37,
        occurringForm: 'تَحْزَنْ',
      },
    },
    {
      id: 'ahsan',
      arabic: 'أَحْسَن',
      english: 'best, finest',
      turkish: 'en güzel, en iyi',
      example: {
        arabic: 'أَتَدْعُونَ بَعْلًۭا وَتَذَرُونَ أَحْسَنَ ٱلْخَٰلِقِينَ',
        english: 'Do you call upon Baal and leave the best of creators,',
        turkish: 'Ba’l’e mi yalvarıyorsunuz ve yaratıcıların en güzelini bırakıyor musunuz,',
        source: 'Qur\'an 37:125',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حسن',
        occurrences: 36,
        occurringForm: 'أَحْسَنَ',
      },
    },
    {
      id: 'dhaqa',
      arabic: 'ذاقُ',
      english: 'to taste',
      turkish: 'tatmak',
      example: {
        arabic: 'ذُقْ إِنَّكَ أَنتَ ٱلْعَزِيزُ ٱلْكَرِيمُ',
        english: 'Taste! Indeed, you are the mighty, the noble!',
        turkish: 'Tat! Sen güya üstündün, değerliydin!',
        source: 'Qur\'an 44:49',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ذوق',
        forms: [
          { label: 'mudari', arabic: 'يَذُوقُ' },
          { label: 'masdar', arabic: 'ذَوْق' },
        ],
        occurrences: 36,
        occurringForm: 'ذُقْ',
      },
    },
    {
      id: 'radda',
      arabic: 'رَدَّ',
      english: 'to return, to give back',
      turkish: 'geri çevirmek, iade etmek',
      example: {
        arabic: 'ثُمَّ رَدَدْنَا لَكُمُ ٱلْكَرَّةَ عَلَيْهِمْ وَأَمْدَدْنَٰكُم بِأَمْوَٰلٍۢ وَبَنِينَ وَجَعَلْنَٰكُمْ أَكْثَرَ نَفِيرًا',
        english: 'Then We gave back to you a return victory over them. And We reinforced you with wealth and sons and made you more numerous in manpower.',
        turkish: 'Sonra size onlara karşı tekrar üstünlük verdik; mallar ve oğullarla sizi destekledik ve sayınızı çoğalttık.',
        source: 'Qur\'an 17:6',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'ردد',
        forms: [
          { label: 'mudari', arabic: 'يَرُدُّ' },
          { label: 'masdar', arabic: 'رَدّ' },
        ],
        occurrences: 36,
        occurringForm: 'رَدَدْنَا',
      },
    },
    {
      id: 'umm',
      arabic: 'أُمّ',
      english: 'mother; source',
      turkish: 'anne; asıl, kaynak',
      example: {
        arabic: 'وَإِنَّهُۥ فِىٓ أُمِّ ٱلْكِتَٰبِ لَدَيْنَا لَعَلِىٌّ حَكِيمٌ',
        english: 'And indeed it is, in the Mother of the Book with Us, exalted and full of wisdom.',
        turkish: 'Şüphesiz o, katımızdaki Ana Kitap’ta pek yücedir, hikmet doludur.',
        source: 'Qur\'an 43:4',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أمم',
        forms: [
          { label: 'plural', arabic: 'أُمَّهَات' },
        ],
        occurrences: 35,
        occurringForm: 'أُمِّ',
      },
    },
    {
      id: 'ithm',
      arabic: 'إِثْم',
      english: 'sin',
      turkish: 'günah',
      example: {
        arabic: 'ٱنظُرْ كَيْفَ يَفْتَرُونَ عَلَى ٱللَّهِ ٱلْكَذِبَ ۖ وَكَفَىٰ بِهِۦٓ إِثْمًۭا مُّبِينًا',
        english: 'Look how they invent about Allah untruth, and sufficient is that as a manifest sin.',
        turkish: 'Bak, Allah’a karşı nasıl yalan uyduruyorlar! Apaçık bir günah olarak bu yeter.',
        source: 'Qur\'an 4:50',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'أثم',
        occurrences: 35,
        occurringForm: 'إِثْمًا',
      },
    },
    {
      id: 'akhtalafa',
      arabic: 'اخْتَلَفَ',
      english: 'to differ, to disagree',
      turkish: 'ihtilafa düşmek, ayrılığa düşmek',
      example: {
        arabic: 'ٱللَّهُ يَحْكُمُ بَيْنَكُمْ يَوْمَ ٱلْقِيَٰمَةِ فِيمَا كُنتُمْ فِيهِ تَخْتَلِفُونَ',
        english: 'Allah will judge between you on the Day of Resurrection concerning that over which you used to differ.',
        turkish: 'Allah, ayrılığa düştüğünüz konularda kıyamet günü aranızda hükmedecektir.',
        source: 'Qur\'an 22:69',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'خلف',
        forms: [
          { label: 'mudari', arabic: 'يَخْتَلِفُ' },
          { label: 'masdar', arabic: 'اِخْتِلَاف' },
        ],
        occurrences: 35,
        occurringForm: 'تَخْتَلِفُونَ',
      },
    },
    {
      id: 'astawaa',
      arabic: 'اسْتَوَى',
      english: 'to rise over, to be established',
      turkish: 'istiva etmek, yerleşmek',
      example: {
        arabic: 'ٱلرَّحْمَٰنُ عَلَى ٱلْعَرْشِ ٱسْتَوَىٰ',
        english: 'The Most Merciful rose over the Throne.',
        turkish: 'Rahman, Arş’a istiva etti.',
        source: 'Qur\'an 20:5',
      },
      vocab: {
        partOfSpeech: 'fil',
        root: 'سوي',
        forms: [
          { label: 'mudari', arabic: 'يَسْتَوِي' },
          { label: 'masdar', arabic: 'اِسْتِوَاء' },
        ],
        occurrences: 35,
        occurringForm: 'ٱسْتَوَىٰ',
      },
    },
    {
      id: 'hiyn',
      arabic: 'حِين',
      english: 'time, while',
      turkish: 'vakit, an',
      example: {
        arabic: 'وَأَنتُمْ حِينَئِذٍۢ تَنظُرُونَ',
        english: 'And you, at that time, are looking on,',
        turkish: 'Siz de o anda bakıp durursunuz,',
        source: 'Qur\'an 56:84',
      },
      vocab: {
        partOfSpeech: 'ism',
        root: 'حين',
        occurrences: 35,
        occurringForm: 'حِينَئِذٍ',
      },
    },
  ],
}
